import life.genny.rules.QRules;
import life.genny.qwanda.entity.BaseEntity;
import life.genny.qwanda.message.QEventBtnClickMessage;
import life.genny.rules.RulesUtils;
import life.genny.utils.PaymentUtils;
import life.genny.qwandautils.MergeUtil;
import io.vertx.core.json.JsonObject;
import java.util.List;
import java.util.Set;
import life.genny.qwanda.PaymentsResponse;
import java.util.HashSet;
import java.util.HashMap;
import life.genny.qwanda.Link;
import life.genny.qwanda.Answer;
import io.vertx.core.json.JsonObject;
import java.io.IOException;

rule "Job Confirm Delivery - Owner and Release Payment"
  when
      $m : QEventBtnClickMessage( event_type == "BTN_CLICK" && data.code == "BTN_CONFIRM_DELIVERY_OWNER")
      rules: QRules( !isState("CONFIRMED_DELIVERY_OWNER") && !isState("PAYMENT_RELEASED") )
  then
      rules.header();

      rules.setState("PAYMENT_RELEASED");
      rules.println("Release Payment process started");

      String assemblyAuthKey = PaymentUtils.getAssemblyAuthKey();
      String assemblyId = MergeUtil.getAttrValue(rules.getUser().getCode(), "PRI_ASSEMBLY_USER_ID", rules.getToken());

      BaseEntity user = rules.getUser();
      String ownerCode = user.getCode();
      String driverCode = null;
      BaseEntity begBe = null;
      BaseEntity driverBe = null;

      /* list of users for status-change */
      List<String> userCodesForStatusColourChange = new ArrayList<>();

      String dataFromFE = $m.getData().getValue();
      JsonObject dataJson = new JsonObject(dataFromFE);

      String begCode = dataJson.getString("itemCode");
      RulesUtils.println("Beg code in release payment ::"+begCode);

      if(begCode != null) {

        begBe = rules.baseEntity.getBaseEntityByCode(begCode);

        /* getting driver code from links */
        List<Link> linkList = rules.baseEntity.getLinks(begCode,"LNK_BEG");

        if(linkList != null) {

          for(Link link : linkList) {
            if(link.getLinkValue().equals("DRIVER")) {
              driverCode = link.getTargetCode();
              driverBe = rules.baseEntity.getBaseEntityByCode(driverCode);
            }
          }
        }

        rules.sendRating(dataFromFE);

        /* adding users for status change */
        userCodesForStatusColourChange.add(ownerCode);
        if(driverCode != null) {
          userCodesForStatusColourChange.add(driverCode);
        }

        Boolean isRealeasePaymentDone = begBe.getLoopValue("PRI_IS_RELEASE_PAYMENT_DONE", false);
        String paymentStatus = rules.baseEntity.getBaseEntityValueAsString(begCode, "PRI_ITEM_STATUS");

        if(paymentStatus != null && paymentStatus.contains("ITEM_PAYMENT_COMPLETED")) {

        		/*    Adding Release Payment Done status  */
            Answer paymentDoneAns = new Answer(rules.getUser().getCode(), begCode, "PRI_IS_RELEASE_PAYMENT_DONE", "TRUE" );
            rules.baseEntity.saveAnswer(paymentDoneAns);

            /* change status colour to both driver and owner to Orange (warning) :  Funds Cleared disbursement processing */
            rules.baseEntity.updateBaseEntityStatus(begBe, userCodesForStatusColourChange, "success");

            /* we mark the job as paid once the confirm-delivery button is clicked and release-payment is success */
            rules.baseEntity.moveBaseEntitySetLinkValue(begBe.getCode(), "GRP_COMPLETED", "GRP_PAID", "LNK_CORE", "BEG");

            rules.setState("CONFIRMED_DELIVERY_OWNER");

            /* reload cache */
      		rules.reloadCache();

         } else {

         	/* if payment is already released and is successful, set success states */
        		rules.println(isRealeasePaymentDone);

        		if(isRealeasePaymentDone) {

         		 /* change status colour to both driver and owner to Orange :  Funds Cleared disbursement processing */
          		rules.baseEntity.updateBaseEntityStatus(begBe, userCodesForStatusColourChange, "warning");

          		/* we move the job to PAID */
          		rules.baseEntity.moveBaseEntitySetLinkValue(begBe.getCode(), "GRP_COMPLETED", "GRP_PAID", "LNK_CORE", "BEG");

          		rules.setState("CONFIRMED_DELIVERY_OWNER");

          		/* reload cache */
          		rules.reloadCache();

        		} else {

          		/* when payment release process is flowing first time for an item */

          		if(ownerCode != null && driverCode != null) {

        			/* hitting release payment API */
            		Boolean isPaymentReleased = rules.releasePayment(begBe, user, driverBe, assemblyAuthKey);

                if(isPaymentReleased) {

                  /* we move the job to GRP_PAID */
                  rules.baseEntity.moveBaseEntitySetLinkValue(begBe.getCode(), "GRP_COMPLETED", "GRP_PAID", "LNK_CORE", "BEG");

                  /* change status colour to both driver and owner to Orange (warning) :  Funds Cleared disbursement processing */
                  rules.baseEntity.updateBaseEntityStatus(begBe, userCodesForStatusColourChange, "warning");

                  rules.setState("CONFIRMED_DELIVERY_OWNER");

                  /* reload cache */
                  rules.reloadCache();
                }
           	  }
       	 	}
      	 }
      }

      rules.footer();
end
