package life.genny.rules;

import life.genny.rules.QRules;
import life.genny.qwanda.entity.BaseEntity;
import life.genny.qwandautils.KeycloakUtils;
import life.genny.qwanda.message.QEventMessage;
import io.vertx.core.json.JsonObject;

rule "Locate driver in job"

    when
	    $m : QEventMessage( event_type == "BTN_CLICK" && data.code == "BTN_LOCATE_DRIVER" )
	    rules: QRules(!isState("LOCATE_DRIVER"))
     then     
     	
     	rules.header();
	    	rules.setState("LOCATE_DRIVER");
	    	
	    	String dataString = $m.getData().getValue();
	    	if(dataString != null) {
	    		
	    		JsonObject data = new JsonObject(dataString);
	    		if(data != null) {
	    			
	    			String begCode = data.getString("itemCode");
	    			if(begCode != null) {
	    				
	    				/* we ask FE to display a map showing live data of BE */
	    				rules.sendPopupCmd("MAP_VIEW", begCode);
	    			}
	    		}
	    	}
	    	    	
	    	rules.footer();       		      
end
