package life.genny.rules;

import life.genny.rules.RulesUtils;
import life.genny.rules.QRules;

rule "Send Layout To Frontend - memberhub"
    when
        rules: QRules( isState("SEND_LAYOUT") && !isState("HAS_SENT_MEMBERHUB_LAYOUT") )
     then
     	rules.header();

        rules.setState("HAS_SENT_MEMBERHUB_LAYOUT");

        rules.sendLayout("LAY_DEFAULT", "dashboard.json");
        rules.setState("SEND_INITIAL_QUESTIONS");
        
	    rules.footer();
end
