package life.genny.rules;

import life.genny.rules.QRules;

rule "Setup Products"
    when
        rules: QRules( isState("SENT_INITIAL_QUESTIONS") && !isState("SETUP_PRODUCTS") )
     then
     	rules.header();

     	rules.setState("SETUP_PRODUCTS");

		  rules.setState("APPLICATION_READY");
		  rules.setState("TRIGGER_APPLICATION");

      String homeLoanCode = "PRD_HOME_LOAN";
        String holidayCode = "PRD_HOLIDAY";
        String linkCode= "LNK_SCORE";

        String linkHomeloan = "LOAN";
        String linkHoliday = "HOLIDAY";

        /* Check if link exists between USER & PRD_HOME_LOAN */
        Boolean isHomeloan = QwandaUtils.checkIfLinkExistsForTarget(rules.getUser().getCode(), linkCode , homeLoanCode, rules.getToken());
        rules.println("Link Exists ?   ::   "+ isHomeloan);

        /* Creating a link between USER & PRD_HOLIDAY */
        if(!isHomeloan){
            rules.baseEntityUtils.createLink(rules.getUser().getCode(), homeLoanCode, linkCode, linkHomeloan, 1.0);
        }

        /* Check if link exists between USER & PRD_HOME_LOAN */
        Boolean isHoilday = QwandaUtils.checkIfLinkExistsForTarget(rules.getUser().getCode(), linkCode , holidayCode, rules.getToken());
        rules.println("Link Exists ?   ::   "+ isHoilday);

        /* Creating a link between USER & PRD_HOME_LOAN */
        if(!isHoilday){
            rules.baseEntityUtils.createLink(rules.getUser().getCode(), holidayCode, linkCode, linkHoliday, 1.0);
        }

        /* Send begs */
        rules.publishBaseEntityByCode(homeLoanCode);
        rules.publishBaseEntityByCode(holidayCode);

	    rules.footer();
end
