package life.genny.rules;

import life.genny.qwanda.message.QEventMessage;
import life.genny.qwanda.message.QCmdMessage;

import life.genny.rules.QRules;



rule "Accounts"
    when
        m : QEventMessage( event_type == "ACCOUNTS" && data.code == "ACCOUNTS" )
        rules : QRules()
    then
        rules.header();	
        QCmdMessage cmd = new QCmdMessage("CMD_ACCOUNTS","ACCOUNTS");
        rules.publishCmd(cmd);
		rules.footer();
		
end
