package life.genny.rules;

import life.genny.utils.RulesUtils;
import life.genny.rules.QRules;
import life.genny.qwanda.message.QEventMessage;
import java.util.List;
import life.genny.qwanda.entity.BaseEntity;

rule "User-Default-Profile"
   
    when
       m : QEventMessage( event_type == "PROFILE" && data.code == "PROFILE")
       rules: QRules( isState("STARTED") && !isState("PROFILE_RULE_EXECUTED"))
    then
        rules.header();

        rules.setState("PROFILE_RULE_EXECUTED");

        BaseEntity project = rules.getProject();
        if (project != null) {

            String profileQuestionGroup = project.getValue(rules.loadUserRole() + "_PROFILE_GRP", "QUE_DEFAULT_PROFILE_GRP");
            rules.askQuestions(rules.getUser().getCode(), rules.getUser().getCode(), profileQuestionGroup, true);
        }
        
        rules.footer();
end