package life.genny.rules;

import life.genny.rules.QRules;
import life.genny.qwanda.message.QEventMessage;
    

rule "Cache Miss"

    when
        m : QEventMessage( getEvent_type().equals("EVT_CACHE_MISS") )
        rules : QRules( isState("STARTED") )
     then
 		rules.header();
 		
 		rules.println("CACHE MISS CODE:"+m.getData().getCode());
 		        
		rules.footer();
       		      
end



