package com.sample;

import life.genny.rules.RulesUtils;
import life.genny.rules.QRules;

import life.genny.qwanda.message.QEventMessage;
import life.genny.qwanda.message.QMessage.MessageData;
import life.genny.qwanda.message.QCmdMessage;
import life.genny.qwanda.message.QDataBaseEntityMessage;
import io.vertx.core.buffer.Buffer;
import com.google.gson.Gson;
import life.genny.qwanda.Answer;
import life.genny.qwanda.message.QDataAnswerMessage;
import life.genny.qwandautils.KeycloakUtils;
import life.genny.qwandautils.QwandaUtils;
import life.genny.qwandautils.MergeUtil;

import life.genny.qwanda.message.QDataAskMessage;
import life.genny.qwanda.message.QCmdMessage;
import life.genny.qwanda.Ask;
import life.genny.qwanda.entity.BaseEntity;

import java.lang.reflect.Type;
import java.util.Map;
import java.util.Set;
import java.util.ArrayList;
import java.util.List;

import java.time.LocalDateTime;
import java.time.ZonedDateTime;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonParseException;
import com.google.gson.JsonPrimitive;
import com.google.gson.JsonSerializationContext;
import com.google.gson.FieldNamingPolicy;
import io.vertx.core.json.JsonObject;
import io.vertx.core.json.JsonArray;
import java.time.format.DateTimeFormatter;
import life.genny.qwanda.DateTimeDeserializer;
import life.genny.qwanda.entity.User;

rule "Clear User Attributessssss"
	when
		$m : QEventMessage( event_type == "BTN_CLICK" && data.code == "QUE_CLEAR" )
		rules : QRules()
	then		
		rules.header();
		//Prepare Token & qwandaServiceUrl
		String qwandaServiceUrl = rules.getQwandaServiceUrl();
		String tokenString = rules.getToken();
		String userCode = rules.getUser().getCode();
		System.out.println("userCode   ::   "+ userCode);

		/* GET USER BE */
		BaseEntity user = MergeUtil.getBaseEntityForAttr(userCode, tokenString);
		System.out.println("user   ::   "+ user.toString());

		System.out.println("BE Attr   ::   "+ user.getBaseEntityAttributes().toString());

		// Initialize lists
        List<Answer> userList = new ArrayList<Answer>();
        List<Answer> primaryList = new ArrayList<Answer>();
		rules.footer();
end