package com.sample;

import life.genny.rules.RulesUtils;
import life.genny.rules.QRules;
import life.genny.qwanda.message.QEventMessage;
import life.genny.qwandautils.MergeUtil;

rule "Clear User Attribute"
	when
		$m : QEventMessage( event_type == "BTN_CLICK" && data.code == "QUE_CLEAR" )
		rules : QRules()
	then		
		rules.header();
		String userCode = rules.getUser().getCode();
		rules.clearBaseEntityAttr(userCode);
		rules.footer();
end