package life.genny.rules;

import life.genny.rules.QRules;
import life.genny.qwanda.entity.BaseEntity;

rule "Application Ready - send data"
    when
        rules: QRules( isState("APPLICATION_READY_SEND_DATA") && !isState("LOOP_APP_READY_SEND_DATA") )
    then
        rules.header();

		    rules.setState("LOOP_APP_READY_SEND_DATA");
        rules.setState("SEND_TREE_DATA");

        /* we push the user roles */
        rules.clearState("LOOP_SEND_USER_ROLES");
        rules.setState("LOOP_SEND_SUB_LAYOUTS");
        rules.setState("SEND_USER_ROLES");

        rules.footer();
end
