package life.genny.rules;

import life.genny.rules.QRules;
import life.genny.qwanda.entity.BaseEntity;
import life.genny.utils.DateUtils;

rule "Setup New User"
    when
        rules: QRules( isState("DID_CREATE_NEW_USER") && isState("APPLICATION_NOT_READY") &&
                    !isState("LOOP_SETUP_NEW_USER") )
    then
        rules.header();
        rules.setState("LOOP_SETUP_NEW_USER");

        BaseEntity user = rules.getUser();

        /*  saving the default profile image   */
        rules.baseEntity.saveAnswer( new Answer (user.getCode(),
                          user.getCode(),
                          "PRI_IMAGE_URL", "https://s3.ap-southeast-2.amazonaws.com/channel40-images/jtaQozJT5HSpn3bX6P4EXSqQj3NDalkQ") );
        /*  saving user registration date time  */
	    rules.baseEntity.saveAnswer( new Answer(user.getCode(),
	   							    user.getCode(),
	   							    "PRI_REGISTRATION_DATETIME", DateUtils.getCurrentUTCDateTime())
	   				    );

        /* send notification for new registration */
        String message = "New registration: " + user.getValue("PRI_FIRSTNAME", "") + " " + user.getValue("PRI_LASTNAME") + ". Email: " + user.getValue("PRI_EMAIL", "");
  			rules.sendSlackNotification(message);

        rules.setState("DID_SETUP_NEW_USER");

        rules.clearState("PROFILE_CHECK_COMPLETED");
        rules.footer();
end
