package life.genny.rules;
import life.genny.rules.QRules;

/* Create Internship BaseEntity */
rule "Add Self Sourced Internship - Step 2"
	when
		rules: QRules(  isState("BTN_CREATE_SELF_SOURCE_INTERNSHIP") &&
						isState("CREATE_INT") && 
						isState("CREATED_BASE_ENTITY") && 
						isState("BEG") && 
						isState("CREATED_BEG") && 
						!isState("LOOP_ADD_SS_INTERNSHIP_STEP2") ) 
	 then
	    rules.header();
		rules.setState("LOOP_ADD_SS_INTERNSHIP_STEP2");

		/* GET newly created BEG BaseEntity */
		BaseEntity beg = rules.getAsBaseEntity("baseEntity");
		
		/* BEG is required to have atleast one attribute */
		rules.saveAnswer(new Answer(beg.getCode(), beg.getCode(), "PRI_CREATED_DATE", rules.getCurrentLocalDateTime()));

		/* SET BEG BaseEntity to state */
		rules.set("begBe", beg);	

        /* Create Internship BaseEntity*/
		rules.set("beCode", rules.getUser().getCode());
		rules.set("bePrefix", "INT");
		rules.set("beName", "INTERNSHIP");
		rules.setState("CREATE_BASE_ENTITY");	

		rules.setState("CREATED_INT");			
        rules.setState("LINK_BEG_TO_SS_INT");
	    rules.footer();     		      
end