package life.genny.rules;
import life.genny.rules.QRules;

rule "Add Self Sourced Internship - Step 8"
	when
        rules: QRules(  isState("BTN_CREATE_SELF_SOURCE_INTERNSHIP") &&
        					isState("SENT_QUESTION") && 
						isState("QUE_SELF_SOURCED_INTERNSHIP_GRP") && 
                        !isState("LOOP_ADD_SS_INTERNSHIP_STEP8")  )
     then 
 		rules.header();
		rules.setState("LOOP_ADD_SS_INTERNSHIP_STEP8");

		BaseEntity internship = rules.getAsBaseEntity("companyBe");
		rules.set("questionSourceCode", rules.getUser().getCode());
		rules.set("questionTargetCode", internship.getCode());
		rules.set("questionGroupCode", "QUE_SELF_SOURCED_HOST_COMPANY_GRP");
		rules.set("questionIsPopup", false);

		rules.setState("SEND_QUESTION");
		
 		rules.footer();
end
