package life.genny.rules;

import life.genny.rules.QRules;

rule "Check If Education Provider Profile Completion"
     when
        rules: QRules(  isState("CHECK_INTERNMATCH_PROFILE") && !isState("LOOP_EDU_ROLE_CHECK") && isState("PRI_IS_EDU_PROVIDER")) 
     then
        
        rules.header();
        
		rules.setState("LOOP_EDU_ROLE_CHECK");
     	rules.set("registration_question_grp", "QUE_EDU_PROVIDER_GRP");
     	
     	rules.sendSelections("GRP_UNI_SELECTION", "LNK_CORE", 10);
     	rules.sendSelections("GRP_DEGREE_SELECTION", "LNK_CORE", 10);
     	
     	rules.setState("CHECK_USER_PROFILE_COMPLETED");

	    rules.footer();     		      
end
     	