package life.genny.rules;

import life.genny.rules.QRules;
import life.genny.qwanda.message.QDataAskMessage;
import life.genny.qwanda.QuestionSourceTarget;
import life.genny.qwanda.message.QDataQSTMessage;

import java.util.ArrayList;
import java.util.Arrays;
import life.genny.qwandautils.MergeUtil;

rule "Check if Profile Completed - Intermatch"
    no-loop true
    when
		
        rules: QRules( ( isState("USER_FOUND") || isState("STARTED") ) && isState("CHECK_USER_PROFILE_COMPLETED") && !isState("PROFILE_CHECK_COMPLETED") )
     then
     	rules.header();
     	
     	rules.setState("PROFILE_CHECK_COMPLETED");
     	
		Boolean isProfileCompleted = rules.getUser().getLoopValue("PRI_IS_PROFILE_COMPLETED", false);
		
		if(isProfileCompleted == null || isProfileCompleted == false) {
   		 	rules.setState("PROFILE_NOT_COMPLETED");
   		}
   		else {
   		   	rules.setState("PROFILE_IS_COMPLETED");
   		}

    	rules.footer();
end
