package life.genny.rules;
import life.genny.rules.QRules;

rule "Ask Registration"
    when
        rules: QRules(  isState("PROFILE_NOT_COMPLETED") && 
						!isState("PRI_IS_HOST_COMPANY") && 
						!isState("LOOP_ASK_REGISTRATION") )
     then 
 		rules.header();
		rules.setState("LOOP_ASK_REGISTRATION");

		String sourceCode = rules.getUser().getCode();
		String targetCode = rules.getUser().getCode();
 		String questionGroupCode = rules.getAsString("registration_question_grp");
		Boolean isPopup = false;

		rules.set("sourceCode", sourceCode);
		rules.set("targetCode", targetCode);
		rules.set("questionGroup", questionGroupCode);
		rules.set("isPopup", isPopup);
		
		rules.setState("ASK_QUESTION");
		
 		rules.footer();
end
