package life.genny.rules;
import life.genny.rules.QRules;

rule "Ask Registration - Host Company - STEP 2"
    when
        rules: QRules(  isState("CREATED_BASE_ENTITY") && 
						isState("CPY") &&
						!isState("LOOP_ASK_REGISTRATION_HOST_COMPANY_STEP2") ) 
     then 
 		rules.header();
		rules.setState("LOOP_ASK_REGISTRATION_HOST_COMPANY_STEP2");

		String userCode = rules.getUser().getCode();
		BaseEntity company = rules.getAsBaseEntity("baseEntity");
		String companyCode = company.getCode();
		rules.set("companyBe", company);

		/* link COMPANY to GRP_COMPANY */
		rules.set("linkSourceCode", "GRP_COMPANYS");
		rules.set("linkTargetCode", companyCode);
		rules.set("linkCode", "LNK_CORE");
		rules.set("linkValue", "COMPANY");
		rules.set("linkWeight", 1.0);
		rules.setState("CREATE_LINK");

		/* link USER to COMPANY */
		rules.set("linkSourceCode", companyCode);
		rules.set("linkTargetCode", userCode);
		rules.set("linkCode", "LNK_STAFF");
		rules.set("linkValue", "STAFF");
		rules.set("linkWeight", 1.0);
		rules.setState("CREATE_LINK");
		
 		rules.footer();
end
