package life.genny.rules;
import life.genny.rules.QRules;

rule "Ask Registration - Host Company - STEP 2"
    when
        rules: QRules(  isState("BASE_ENTITY_CREATED") && 
						isState("CPY") &&
						!isState("LOOP_ASK_REGISTRATION_HOST_COMPANY_STEP2") ) 
     then 
 		rules.header();
		String userCode = rules.getUser().getCode();
		BaseEntity company = rules.getAsBaseEntity("baseEntity");
		String companyCode = company.getCode();
		rules.setState("LOOP_ASK_REGISTRATION_HOST_COMPANY_STEP2");

		/* link COMPANY to GRP_COMPANY */
		rules.set("sourceCode", "GRP_COMPANYS");
		rules.set("targetCode", companyCode);
		rules.set("linkCode", "LNK_CORE");
		rules.set("linkValue", "COMPANY");
		rules.set("weight", 1.0);

		rules.setState("CREATE_LINK");

		/* link USER to COMPANY */
		rules.set("sourceCode", companyCode);
		rules.set("targetCode", userCode);
		rules.set("linkCode", "LNK_STAFF");
		rules.set("linkValue", "STAFF");
		rules.set("weight", 1.0);

		rules.setState("CREATE_LINK");
		
 		rules.footer();
end
