package life.genny.rules;
import life.genny.rules.QRules;

rule "Ask Registration - Host Company - STEP 3"
    when
        rules: QRules(  isState("PROFILE_NOT_COMPLETED") &&
						isState("CREATED_LINK") && 
						isState("STAFF") &&
						!isState("LOOP_ASK_REGISTRATION_HOST_COMPANY_STEP3") ) 
     then 
 		rules.header();		
		rules.setState("LOOP_ASK_REGISTRATION_HOST_COMPANY_STEP3");
 		
 		String questionSourceCode = rules.getUser().getCode();
		String questionTargetCode = rules.getUser().getCode();

		/* send question group for user */
		rules.set("questionSourceCode", questionSourceCode);
		rules.set("questionTargetCode", questionTargetCode);
		rules.set("questionGroupCode", "QUE_NEW_USER_DETAILS_GRP");
		rules.setState("SEND_QUESTION");	
		
 		rules.footer();
end
