package life.genny.rules;
import life.genny.rules.QRules;

rule "Ask Registration - Host Company - STEP 4"
    when
        rules: QRules(  isState("QUESTION_SENT") && 
						isState("QUE_NEW_USER_COMPANY_GRP") &&
						!isState("LOOP_ASK_REGISTRATION_HOST_COMPANY_STEP4") ) 
     then 
 		rules.header();		
		rules.setState("LOOP_ASK_REGISTRATION_HOST_COMPANY_STEP4");
 		
 		String sourceCode = rules.getUser().getCode();
		String targetCode = rules.getUser().getCode();

		/* send question group for host company */
		rules.set("sourceCode", sourceCode);
		rules.set("targetCode", targetCode);	
		rules.set("questionGroup", "QUE_NEW_USER_COMPANY_GRP");
		rules.setState("SEND_QUESTION");
		
		/* we send the layout */
		rules.sendSublayout("LAY_HOST_COMPANY", "registration/hostcompany.json", null, false);
		
 		rules.footer();
end
