package life.genny.rules;
import life.genny.rules.QRules;

rule "Ask Registration - Host Company - STEP 4"
    when
        rules: QRules(  isState("SENT_QUESTION") && 
						isState("QUE_NEW_USER_DETAILS_GRP") &&
						!isState("LOOP_ASK_REGISTRATION_HOST_COMPANY_STEP4") ) 
     then 
 		rules.header();		
		rules.setState("LOOP_ASK_REGISTRATION_HOST_COMPANY_STEP4");
 		
 		String questionSourceCode = rules.getUser().getCode();
		String questionTargetCode = rules.getUser().getCode();

		/* send question group for host company */
		rules.set("questionSourceCode", questionSourceCode);
		rules.set("questionTargetCode", questionTargetCode);	
		rules.set("questionGroupCode", "QUE_NEW_USER_COMPANY_GRP");
		
		rules.setState("SEND_QUESTION");
		
		/* we send the layout */
		rules.sendSublayout("LAY_HOST_COMPANY", "registration/hostcompany.json", null, false);
		
 		rules.footer();
end
