package life.genny.rules;
import life.genny.rules.QRules;

/* Send GRP_AVAILABLE begKids - INTERN */
/* Sending INTERNSHIP \ CREATOR \ HOSTCOMPANY \ APPLICATION >> APPLICANT */
rule "Send GRP_AVAILABLE BEG KIDS - INTERN" 
    when    
        rules: QRules(  isState("SEND_GRP_AVAILABLE_BEG_KIDS_INTERN") && 
                        isState("SENT_GRP_AVAILABLE_BEGS_INTERN") && 
                        isState("PRI_IS_INTERN") && 
                        !isState("LOOP_SEND_GRP_AVAILABLE_BEG_KIDS_INTERN") )
     then
     	rules.header();
        rules.setState("LOOP_SEND_GRP_AVAILABLE_BEG_KIDS_INTERN");
		
        /* 	get all the begs of GRP_AVAILABLE */
        List<BaseEntity> availableBegs = rules.getBaseEntitysByParentAndLinkCode("GRP_AVAILABLE", "LNK_CORE", 0, 500, false);

        /* Recipent Array */
        String[] recipient = {rules.getUser().getCode()};

        if (availableBegs != null) {
            for (BaseEntity beg : availableBegs) {
                /* get all the begKids */
                List<BaseEntity> begKids = rules.getBaseEntitysByParentAndLinkCode(beg.getCode(), "LNK_BEG", 0, 500, false);
                rules.println("Beg Code   ::   " + beg.getCode());
                rules.printList("Beg Kids", begKids);

                if(begKids != null){

                    for (BaseEntity begKid : begKids) {

                        /* if begKid == APPLICATION */
                        if (begKid.getName().equals("APPLICATION")) {
                            BaseEntity applicant = rules.getChildren(begKid.getCode(), "LNK_APP", "APPLICANT");

                            if (applicant != null) {
                                
                                /* if  current INTERN == APPLICANT of this applicantion BE */
                                if (rules.getUser().getCode().equals(applicant.getCode())) {

                                    /* subscribe to APPLICATION  */
                                    rules.subscribeUserToBaseEntity(rules.getUser().getCode(), begKid.getCode());
                                    rules.subscribeUserToBaseEntity(rules.getUser().getCode(), applicant.getCode());

                                    rules.publishBaseEntityByCode(begKid.getCode(), beg.getCode(), "LNK_BEG", recipient);
                                    rules.publishBaseEntityByCode(applicant.getCode(), begKid.getCode(), "LNK_APP", recipient);
                                }
                            }else{
                                rules.println("applicant is null");
                            }
                        }
                        rules.publishBaseEntityByCode(begKid.getCode(), beg.getCode(), "LNK_BEG", recipient);
                    }  
                }
            }
        }else{
            rules.println("available begs is null");
        }
        rules.setState("SENT_GRP_AVAILABLE_BEG_KIDS_INTERN");
        rules.setState("SEND_BUCKETS_INTERN");
	    rules.footer();      		      
end