package life.genny.rules;

import life.genny.rules.RulesUtils;
import life.genny.rules.QRules;

import life.genny.qwandautils.QwandaUtils;
import life.genny.qwanda.message.QCmdMessage;
import life.genny.qwanda.message.QCmdLayoutMessage;

import io.vertx.core.json.JsonObject;
import io.vertx.core.json.JsonArray;



rule "Send Sub Layouts To Frontend"

     salience 680
    agenda-group "SendLayoutsAndData"
    when
        rules: QRules( isState("LAYOUT_CHANGE_READY") && (!isState("SUBLAYOUT_CHANGE_READY"))  ) 
     then

        rules.header();
  
  		String subLayoutMap = RulesUtils.getLayout("sublayouts");
 		if(subLayoutMap != null) {
		
			JsonArray subLayouts = new JsonArray(subLayoutMap);
			if(subLayouts != null) {
				
				for(int i = 0; i < subLayouts.size(); i++) {
					
					JsonObject sublayoutData = subLayouts.getJsonObject(i);
					String url = sublayoutData.getString("download_url");
					String name = sublayoutData.getString("name");
					name = name.replace(".json", "");
					name = name.replaceAll("\"", "");
					
					if(url != null) {
						
						/*    grab sublayout from github   */

						rules.println(url);
						
						String subLayoutString = QwandaUtils.apiGet(url, null);
						if(subLayoutString != null) {
							
							try {
								
								/*    send sublayout to FE    */
								QDataSubLayoutMessage msg = new QDataSubLayoutMessage(name,subLayoutString,rules.getToken());								
						        rules.publishCmd(msg);
						        
							}
							catch(Exception e) {
							} 
						}
					}
				}
			}
		}
		
		rules.setState("SUBLAYOUT_CHANGE_READY");
		
	    rules.footer();     		      
end
