package life.genny.rules;

import life.genny.rules.QRules;
import life.genny.qwanda.entity.BaseEntity;
import java.util.List;
import java.util.ArrayList;


rule "Send Ch40 BucketData To Frontend"
    no-loop true
    salience 7
    agenda-group "SendLayoutsAndData"
    when
        rules: QRules( !isState("SEND_BUCKET_DATA")  && isState("SUBLAYOUT_CHANGE_READY") ) 
     then
     	rules.header();
	
		/* Show loading indicator */
		  rules.showLoading("Loading your interface..."); 
     	
     	BaseEntity user = rules.getUser();
      		
     	 List<BaseEntity> root = rules.getBaseEntitysByParentAndLinkCode("GRP_ROOT","LNK_CORE", 0, 20, false) ;
    	 	 rules.publishCmd(root,"GRP_ROOT","LNK_CORE");
 		 rules.println(root);
 		 
     	 List<BaseEntity> buckets = rules.getBaseEntitysByParentAndLinkCode("GRP_DASHBOARD","LNK_CORE", 0, 20, false) ;
     	 rules.publishCmd(buckets,"GRP_DASHBOARD","LNK_CORE");
  		 rules.println(buckets);
     	 
     	for (BaseEntity bucket : buckets ) 
     	{
     		rules.println(bucket);
     		List<BaseEntity> begs = new ArrayList<BaseEntity>();
     		if (user.is("PRI_DRIVER") && bucket.getCode().equals("GRP_NEW_ITEMS")) {
     			List<BaseEntity> driverbegs = rules.getBaseEntitysByParentAndLinkCode(bucket.getCode(),"LNK_CORE", 0, 500, false) ;
     			begs.addAll(driverbegs);
     		} else {
     			List<BaseEntity> driverbegs = rules.getBaseEntitysByParentAndLinkCode(bucket.getCode(),"LNK_CORE", 0, 500, false, user.getCode()) ;
     		    begs.addAll(driverbegs);
    		
     		}
 
    			if (user.is("PRI_OWNER")) {
     			List<BaseEntity> ownerbegs = rules.getBaseEntitysByParentAndLinkCode(bucket.getCode(),"LNK_CORE", 0, 500, false, user.getCode()) ;
     		    begs.addAll(ownerbegs);
     		}
 
     		 rules.publishCmd(begs,bucket.getCode(),"LNK_CORE");
     		 
     		 
     		for (BaseEntity beg : begs) {
     			List<BaseEntity> begKids = rules.getBaseEntitysByParentAndLinkCode(beg.getCode(),"LNK_BEG", 0, 20, false) ;
     			rules.publishCmd(begKids,beg.getCode(),"LNK_BEG");
     			for (BaseEntity begKid : begKids) {   	 			
     	 			rules.println(bucket.getCode()+":"+begKid.getCode());
     	 		}
     		}
     	}
     	
     	 rules.setState("SEND_BUCKET_DATA");
       	   		
	    rules.footer();       		      
end
