package life.genny.rules;

import life.genny.rules.RulesUtils;
import life.genny.rules.QRules;

import life.genny.qwandautils.QwandaUtils;
import life.genny.qwanda.message.QCmdMessage;
import life.genny.qwanda.message.QCmdLayoutMessage;

import io.vertx.core.json.JsonObject;

rule "Send Bucket Layout To Frontend"
    salience 660
    agenda-group "SendLayoutsAndData"
    when
        rules: QRules( isState("SEND_BUCKET_DATA") && (!isState("SEND_BUCKET_LAYOUT"))  ) 
     then
     	rules.header();
     	
     	String layout = RulesUtils.getLayout("card.json");
     	
     	/* sending cmd BUCKET_VIEW */
        rules.sendSublayout("bucket-dashboard", "dashboard_channel40.json");
           
		rules.setState("SEND_BUCKET_LAYOUT");
		
	    rules.footer();     		      
end
