package life.genny.rules;

import life.genny.rules.QRules;


rule "Ask Registration"
    	no-loop true
		ruleflow-group 'Registration'
    when
        rules: QRules( isState("NEW_USER_CREATED") &&
                        isState("TRIGGER_REGISTRATION") &&
                        (!isState("ASKED_REGISTRATION"))  )
     then
     	rules.header();
   	    String userCode = rules.getUser().getCode();
   		rules.sendSelections("GRP_USER_ROLE", "LNK_CORE", 10);



  		rules.sendQuestions(userCode,userCode,"QUE_NEW_USER_PROFILE_GRP", true);

  	  /*  Check if user is already added to the company   */
        BaseEntity company = rules.getParent(userCode, "LNK_STAFF");
        String companyCode = "";
        if(company != null)
        {
           rules.println("Company Found");
           rules.println("Company BE is  :: "+company.toString());
            companyCode = company.getCode();
         /*   rules.askQuestions(userCode, companyCode, "QUE_USER_COMPANY_GRP"); */

        }
        if(company == null)
        {
           rules.println("Company Not Found, Creating New Company");
          /*  Creating new base-entity Company    */
           BaseEntity newCompany = QwandaUtils.createBaseEntityByCode(QwandaUtils.getUniqueId(userCode, null, "CPY", rules.getToken()), "COMPANY", rules.getQwandaServiceUrl(), rules.getToken());
           companyCode = newCompany.getCode();
           /* Set PRI_GST attribute to FALSE by default */
           rules.updateBaseEntityAttribute(userCode, companyCode, "PRI_GST", "FALSE");
           rules.println("The New Company is   :: "+newCompany);
         /*  link new Company to the GRP_COMPANYS    */
            Link companyGRPCompanyLink =  QwandaUtils.createLink("GRP_COMPANYS", companyCode , "LNK_CORE", null, (double) 1, rules.getToken());

            /* bad stuff */
            if(rules.isRealm("channel40")) {
                /*  link GRP_LOADS to new Company    */
                Link companyGRPLoadLink =  QwandaUtils.createLink(companyCode, "GRP_LOADS" , "LNK_CORE", null, (double) 1, rules.getToken());
            }

         /*  link new person to the Company    */
           Link userCompanyLink =  QwandaUtils.createLink(companyCode, userCode, "LNK_STAFF", null, (double) 1, rules.getToken());

        }

        rules.println("The Users Company code is   ::  "+companyCode);
        rules.sendQuestions(userCode, companyCode, "QUE_NEW_USER_COMPANY_GRP", true);
        rules.sendSublayout("REGISTER", "create_user.json", "TEST");

		    rules.setState("ASKED_REGISTRATION");
	      rules.footer();
end
