package life.genny.rules;

import life.genny.qwanda.message.QCmdMessage;
import life.genny.qwanda.message.QEventMessage;
import life.genny.qwanda.Layout;
import life.genny.rules.QRules;
import io.vertx.core.json.JsonObject;
import java.util.List;
import java.util.ArrayList;
import life.genny.qwanda.entity.BaseEntity;

rule "TV_SELECT Event - Generate Report"
     when
       $m : QEventMessage( event_type == "TV_SELECT" && ( data.value =="GRP_REPORTS" || data.value.startsWith("GRP_REPORTS_")) )
       rules: QRules(!isState("REPORTS_LAYOUT_SENT"))
     then

     rules.header();
        rules.setState("REPORTS_LAYOUT_SENT");
        /* TODO: refactor this. */
       	String grpCode = $m.getData().getValue();
       	rules.println("The Group Id is :: "+grpCode );

    /*   	JsonObject buttonsLayout = rules.generateLayout(grpCode);
       	Layout[] layoutArray = new Layout[1];
       	layoutArray[0] = new Layout(grpCode, buttonsLayout.toString());
        QCmdMessage cmdJobSublayout = new QCmdMessage("CMD_SUBLAYOUT", "ADMIN_REPORTS");
		JsonObject cmdJobSublayoutJson = JsonObject.mapFrom(cmdJobSublayout);
		rules.println("Loading url: " + rules.realm() );
		rules.println("the Layout array string is :: "+ layoutArray[0].getData());
		cmdJobSublayoutJson.put("items", layoutArray[0].getData());
		rules.println("The CMD_SUBLAYOUT cmd is :: "+cmdJobSublayoutJson);
		rules.publishCmd(cmdJobSublayoutJson);   */

		rules.publishSearhBE(grpCode);
		BaseEntity user = rules.getUser();
		String viewGrpCode = "";
	    if ( user.is("PRI_IS_SELLER") || user.getValue("PRI_IS_SELLER").equals("TRUE") ) {
	        viewGrpCode = "GRP_REPORTS_DRIVER";
	    }
	    else if ( user.is("PRI_IS_BUYER") || user.getValue("PRI_IS_BUYER").equals("TRUE") ) {
	        viewGrpCode = "GRP_REPORTS_OWNER";
	    }
	    	if ( rules.hasRole("admin") ) {
	    	    viewGrpCode = "GRP_REPORTS_ADMIN";
	    	}
		rules.sendCmdReportsSplitView("GRP_REPORTS", viewGrpCode);

     rules.footer();
end
