package life.genny.rules;

import life.genny.qwanda.message.QCmdMessage;
import life.genny.qwanda.message.QEventMessage;
import life.genny.rules.QRules;
import io.vertx.core.json.JsonObject;
import java.util.List;
import java.util.ArrayList;
import life.genny.qwanda.entity.BaseEntity;

rule "TV_SELECT Event - Generate Report"
     when
       $m : QEventMessage( event_type == "TV_SELECT" && data.value matches "GRP_REPORTS.*" )
       rules: QRules()
     then

     rules.header();

        /* TODO: refactor this. */
       	String grpCode = $m.getData().getValue();
       	rules.println("The Group Id is :: "+grpCode );
       	
       	JsonObject buttonsLayout = rules.generateLayout(grpCode); 
       	Layout[] layoutArray = new Layout[1];
       	layoutArray[0] = new Layout(grpCode, buttonsLayout.toString());
       	QDataSubLayoutMessage msg = new QDataSubLayoutMessage(layoutArray, rules.getToken());
		rules.publishCmd(msg);
       	rules.println(msg);
        	
    

     rules.footer();
end
