package life.genny.rules;

import life.genny.rules.QRules;


rule "Report: Send Result Data"
    no-loop true
    salience 580
    ruleflow-group 'ButtonClick'
    
    when
        m : QEventMessage( event_type == "BTN_CLICK"  && data.getCode().startsWith("SBE_") )
        rules: QRules( !isState("REPORT_SENT") )
     then
         rules.header();
         
         rules.setState("REPORT_SENT");
         //rules.sendAllUsers("SBE_GET_ALL_USERS");
         rules.sendReport(m.getData().getCode());
         
		 rules.footer();
	      		      
end
