package life.genny.rules;

import life.genny.rules.QRules;
import life.genny.qwanda.message.QDataAnswerMessage;
import life.genny.qwanda.Answer;

import life.genny.qwandautils.PaymentUtils;

rule "Make Payment"
	when 
		m : QDataAnswerMessage( QDataAnswerMessage.getData_type().equals(Answer.class.getSimpleName()) )
	    rules: QRules()
	then
		rules.header();
		
		if(PaymentUtils.checkIfAnswerContainsPaymentAttribute(m) == true) {
		
			rules.println("Make Payment started"); 
			
			/* Save Payment-related answers as user/BEG attributes */
			String begCode = PaymentUtils.processPaymentAnswers(rules.getQwandaServiceUrl(), m, rules.getToken());
		
       		String assemblyAuthKey = PaymentUtils.getAssemblyAuthKey();
       		String assemblyId = MergeUtil.getAttrValue(rules.getUser().getCode(), "PRI_ASSEMBLY_USER_ID", rules.getToken());
         	
  
			if(begCode != null && assemblyId != null) {
		
				/* Make payment */
				PaymentUtils.makePayment(begCode, assemblyAuthKey, rules.getToken());	      
				rules.println("Make Payment process ended");  
			}
		
		}
		
		rules.footer();	
end