package life.genny.rules;

import life.genny.rules.QRules;

import life.genny.qwanda.message.QEventMessage;
import life.genny.qwandautils.PaymentUtils;
import life.genny.qwandautils.MergeUtil;

import io.vertx.core.json.JsonObject;

rule "Release Payment"
	agenda-group "FormSubmit"
	when 
		$m : QEventMessage( event_type == "FORM_SUBMIT" && data.code == "QUE_USER_RATING_GRP" )
      	rules: QRules( isState("RELEASE_PAYMENT") )
	then
	
	 	rules.header();
		rules.println("Release Payment process started"); 
		rules.clearState("RELEASE_PAYMENT");
		
		String assemblyAuthKey = PaymentUtils.getAssemblyAuthKey();
       	String assemblyId = MergeUtil.getAttrValue(rules.getUser().getCode(), "PRI_ASSEMBLY_USER_ID", rules.getToken());
       	
       	String begCode = rules.getBaseEntityValueAsString(rules.getUser().getCode(), "STT_JOB_IS_RATING");
      	RulesUtils.println("Beg code in release payment ::"+begCode);
		
  		if(begCode != null && assemblyId != null) {
	    
		     PaymentUtils.releasePayment(begCode, assemblyAuthKey, rules.getToken());
		     rules.println("Payment is released!"); 
	
		}
	rules.footer();	
end