package life.genny.rules;
import life.genny.rules.QRules;

/* Sends ROOT for EDU_PROVIDER */
rule "Send Root Kids - EDU_PROVIDER" 
    when    
        rules: QRules(  isState("SEND_ROOT_KIDS_EDU_PROVIDER") && 
                        isState("SENT_ROOT_EDU_PROVIDER") && 
                        isState("PRI_IS_EDU_PROVIDER") && 
                        !isState("LOOP_SEND_ROOT_KIDS_EDU_PROVIDER") )
     then
     	rules.header();
        rules.setState("LOOP_SEND_ROOT_KIDS_EDU_PROVIDER");
		
		List<BaseEntity> rootKids = rules.getBaseEntitysByParentAndLinkCode("GRP_ROOT", "LNK_CORE", 0, 20, false);
		List<BaseEntity> toRemove = new ArrayList<BaseEntity>();

		/* Remove  GRP_DASHBOARD from GRP_ROOT */
		if(rootKids != null){
			for (BaseEntity rootKid : rootKids) {
				if (rootKid.getCode().equalsIgnoreCase("GRP_DASHBOARD")){
					toRemove.add(rootKid);
				}
                if (rootKid.getCode().equalsIgnoreCase("GRP_BIN")) {
					toRemove.add(rootKid);
				}
			}
			rootKids.removeAll(toRemove);

	        /* SEND ROOT Kids */
			rules.publishCmd(rootKids, "GRP_ROOT", "LNK_CORE");		
			
			 /* SET rootKids in MAP */
			rules.set("rootKidsList", rootKids);
        	rules.setState("SENT_ROOT_KIDS_EDU_PROVIDER");

        	rules.setState("SEND_GRP_AVAILABLE_EDU_PROVIDER");
		}
	    rules.footer();      		      
end