package life.genny.rules;

import life.genny.rules.QRules;


rule "Trigger Send Chat"
    no-loop true
    salience 570
    ruleflow-group 'ButtonClick'
    
    when
        m : QEventMessage( event_type == "BTN_CLICK"  && data.code == "BTN_SEND_MESSAGE" )
        rules: QRules( !isState("SEND_CHAT"))
     then
     	rules.println("TRIGGER SEND_CHAT");
     	rules.setState("SEND_CHAT");
   		drools.setFocus("Chat");
		
	      		      
end
