package life.genny.rules;
import life.genny.rules.QRules;

/* Add BEG, INT, CPY to map */
rule "Submit Internship - Step 1"
	when
		rules: QRules( 	isState("QUE_INTERNSHIP_GRP") && 
						isState("EVENT_FORM_SUBMIT") && 
						isState("SUBMIT") && 
						!isState("LOOP_SUBMIT_INTERNSHIP_STEP1")) 
	 then
	 	rules.header();
        rules.setState("LOOP_SUBMIT_INTERNSHIP_STEP1");

		String internshipCode = rules.getAsString("quesTargetCode");

		if(internshipCode != null){

			BaseEntity internship = rules.getBaseEntityByCode(internshipCode);
			rules.set("internshipBe", internship);

			BaseEntity beg = rules.getParent(internshipCode, "LNK_BEG");
			rules.set("begBe", beg);

			BaseEntity company = rules.getParent(rules.getUser().getCode(), "LNK_STAFF");
			rules.set("companyBe", company);

			rules.setState("BEG_INTERNSHIP_COMPANY_READY");            
            
        }else{
            rules.println("internship is null");
        }
end