package life.genny.rules;
import life.genny.rules.QRules;

/* LINK GRP_INTERNSHIPS + BEG || INTERNSHIPS */
rule "Submit Internship - Step 2"
     when
        rules: QRules( 	isState("BEG_INTERNSHIP_COMPANY_READY") && 
                     	isState("QUE_INTERNSHIP_GRP") && 
						isState("EVENT_FORM_SUBMIT") && 
						isState("SUBMIT") && 
						!isState("LOOP_SUBMIT_INTERNSHIP_STEP2")) 
     then
        rules.header();
		rules.setState("LOOP_SUBMIT_INTERNSHIP_STEP2");
     	
        BaseEntity beg = rules.getAsBaseEntity("begBe");
        
        if(beg != null){
            /* link GRP_INTERNSHIPS to BEG  */
            rules.set("linkSourceCode",  "GRP_INTERNSHIPS");
            rules.set("linkTargetCode", beg.getCode());
            rules.set("linkCode", "LNK_CORE");
            rules.set("linkValue", "INTERNSHIP");
            rules.set("linkWeight", 1.0);
            rules.setState("CREATE_LINK");

			rules.setState("LINKED_GRP_INTERNSHIPS_TO_BEG");            
        }else{
            rules.println("beg is null");            
        }
	    rules.footer();     		      
end
     	