package life.genny.rules;
import life.genny.rules.QRules;

/* LINK BEG + CPY || COMPANY */
rule "Submit Internship - Step 4"
	when
	    rules: QRules( 	isState("LINKED_BEG_TO_USER") && 
						isState("CREATED_LINK") && 	
						isState("CREATOR") && 	
						isState("QUE_INTERNSHIP_GRP") && 
						isState("EVENT_FORM_SUBMIT") && 
						isState("SUBMIT") && 
						!isState("LOOP_SUBMIT_INTERNSHIP_STEP4")) 
	 then
	 	rules.header();
        rules.setState("LOOP_SUBMIT_INTERNSHIP_STEP4");

		BaseEntity beg = rules.getAsBaseEntity("begBe");
		BaseEntity company = rules.getAsBaseEntity("companyBe");

		if(beg == null){
			rules.println("beg not found");			
		}
		else if(company == null){
			rules.println("Company not found");
		}
		else{
			/* link BEG to CPY */
			rules.set("linkSourceCode", beg.getCode());
			rules.set("linkTargetCode", company.getCode());
			rules.set("linkCode", "LNK_BEG");
			rules.set("linkValue", "COMPANY");
			rules.set("linkWeight", 1.0);
			rules.setState("CREATE_LINK");

			rules.setState("LINKED_BEG_TO_COMPANY");
		}
end
