package life.genny.rules;
import life.genny.rules.QRules;
import life.genny.qwanda.Link;
import life.genny.qwandautils.JsonUtils;
import life.genny.qwandautils.QwandaUtils;
import java.io.IOException;



/* Move BEG from GRP_DRAFTS >>> GRP_AVAILABLE  */
rule "Submit Internship - Step 4"
	when
		rules: QRules( 	isState("SUBSCRIBED_TO_BEG") && 
						isState("EVENT_FORM_SUBMIT") && 	
						!isState("LOOP_SUBMIT_INTERNSHIP_STEP4")) 
	 then
	 	rules.header();
        rules.setState("LOOP_SUBMIT_INTERNSHIP_STEP4");

		BaseEntity beg = rules.getAsBaseEntity("begBe");
        if(beg!=null){
        	rules.moveBaseEntity(beg.getCode(), "GRP_DRAFTS", "GRP_AVAILABLE", "LNK_CORE");
		}
        rules.setState("MOVED_BEG_TO_AVAILABLE");
        rules.setState("PUBLISH_BEG");
	 	rules.footer();      
end
