gpackage life.genny.rules;
import life.genny.rules.QRules;
import life.genny.utils.VertxUtils;

/* Subscribe COMPANY (user's Host Company) to BEG */
rule "Submit Internship - Step 5.1"
	when
		rules: QRules( 	isState("SUBSCRIBED_CREATOR_TO_BEG") &&
						isState("SUBSCRIBE_COMPANY_TO_BEG") &&
						isState("QUE_INTERNSHIP_GRP") &&
						isState("EVENT_FORM_SUBMIT") &&
						isState("SUBMIT") &&
						!isState("LOOP_SUBMIT_INTERNSHIP_STEP5_1"))

	 then
	 	rules.header();
        rules.setState("LOOP_SUBMIT_INTERNSHIP_STEP5_1");

		BaseEntity beg = rules.getAsBaseEntity("begBe");
		BaseEntity company = rules.getAsBaseEntity("companyBe");

		rules.subscribeUserToBaseEntity(company.getCode(), beg);

 		rules.setState("SUBSCRIBED_COMPANY_TO_BEG");
 		rules.setState("SUBSCRIBE_ALL_INTERNS_TO_NEW_BEG");
	 	rules.footer();
end
