package life.genny.rules;
import life.genny.rules.QRules;
import life.genny.utils.VertxUtils;

/* Publish BEG TO bucket */
rule "Submit Internship - Step 7"	
	when
		rules: QRules( 	isState("MOVED_BEG_TO_AVAILABLE") && 
						isState("EVENT_FORM_SUBMIT") && 
						isState("SUBMIT") && 
						!isState("LOOP_SUBMIT_INTERNSHIP_STEP7") ) 
	 then
	 	rules.header();
        rules.setState("LOOP_SUBMIT_INTERNSHIP_STEP7");

		BaseEntity beg = rules.getAsBaseEntity("begBe");
		BaseEntity internship = rules.getAsBaseEntity("internshipBe");
		BaseEntity company = rules.getAsBaseEntity("companyBe");
		
		String[] begRecipients = VertxUtils.getSubscribers(rules.realm(), beg.getCode());
		
		rules.publishBaseEntityByCode(rules.getUser().getCode(), beg.getCode(), "LNK_BEG", begRecipients);
		rules.publishBaseEntityByCode(company.getCode(), beg.getCode(), "LNK_BEG", begRecipients);
		rules.publishBaseEntityByCode(internship.getCode(), beg.getCode(), "LNK_BEG", begRecipients);
		rules.publishBaseEntityByCode(beg.getCode(), "GRP_AVAILABLE", "LNK_CORE", begRecipients);
		
		rules.setState("PUBLISHED_BEG_AND_KIDS");
	 	rules.footer();      
end
