package life.genny.rules;
import life.genny.rules.QRules;
import life.genny.utils.VertxUtils;

/* Redirect to HOMEPAGE */
rule "Submit Internship - Step 8"	
	when
		rules: QRules( 	isState("PUBLISHED_BEG_AND_KIDS") && 
						isState("EVENT_FORM_SUBMIT") && 
						isState("SUBMIT") && 
						!isState("LOOP_SUBMIT_INTERNSHIP_STEP8") ) 
	 then
	 	rules.header();
        rules.setState("LOOP_SUBMIT_INTERNSHIP_STEP8");
		
		rules.setState("TRIGGER_HOME_PAGE");
 
	 	rules.footer();      
end
