package life.genny.rules;
import life.genny.rules.QRules;

/* Intern Accepts Offer */
rule "Accept Offer - Edu Provider"
	when
		rules: QRules( 	isState("BTN_ACCEPT_OFFER") && 
						isState("EVENT_BTN_CLICK") && 
						isState("PRI_IS_EDU_PROVIDER") && 
						isState("QUE_EDU_PROVIDER_AGREEMENT_GRP") && 
						isState("SUBMIT") && 
						!isState("LOOP_EDU_PROVIDER_ACCEPT_OFFER") ) 
	 then
	 	rules.header();
        rules.setState("LOOP_EDU_PROVIDER_ACCEPT_OFFER");

		String begCode = rules.getAsString("quesTargetCode");
 		
		if(begCode != null){
		    rules.updateBaseEntityAttribute(rules.getUser().getCode(), begCode, "PRI_EDU_PROVIDER_ACCEPTED", "TRUE");
            rules.setState("EDU_PROVIDER_ACCEPTED_OFFER");

            rules.setState("CHECK_OFFER_ACCEPTED");
        }
	 	rules.footer();      
end
