package life.genny.rules;

import life.genny.rules.QRules;

rule "Apply internship"
    no-loop true
    when
        m : QEventBtnClickMessage( event_type == "BTN_CLICK" && data.code == "BTN_APPLY_INTERNSHIP")
        rules: QRules( !isState("APPLY_INTERNSHIP") )
     then

     	rules.header();
        rules.setState("APPLY_INTERNSHIP");

        /* TODO: create new application BE */

        rules.sendSublayout("internship-application", "internships/apply.json", "", true);
	    rules.footer();
end
