package life.genny.rules;

import life.genny.rules.QRules;

rule "Show Details of internships"
    no-loop true
    when
        m : QEventBtnClickMessage( event_type == "BTN_CLICK" && data.code == "BTN_SHOW_INTERNSHIP")
        rules: QRules( !isState("SHOW_INTERNSHIP") )
     then

     	rules.header();
        rules.setState("SHOW_INTERNSHIP");
        rules.showInternship(m);
	    rules.footer();
end
