package life.genny.rules;
import life.genny.rules.QRules;

/* Show Offer Document - Edu Provider */
rule "Show Offer Document - Edu Provider"
	when
		rules: QRules( 	isState("REDIRECT_EVENT") && 
						isState("REDIRECT_SHOW_OFFER") && 
						isState("PRI_IS_EDU_PROVIDER") && 
						isState("EXIT_HOME_PAGE") &&
						!isState("LOOP_SHOW_OFFER_DOCUMENT_EDU_PROVIDER") ) 
	 then
	 	rules.header();
        rules.setState("LOOP_SHOW_OFFER_DOCUMENT_EDU_PROVIDER");

		String begCode = rules.getAsString("valueCode");

        if(begCode != null){
		   	String questionSourceCode = rules.getUser().getCode();
			String questionTargetCode = begCode;
			String questionGroupCode = "QUE_EDU_PROVIDER_AGREEMENT_GRP";
			Boolean questionIsPopup = false;

			rules.set("questionSourceCode", questionSourceCode);
			rules.set("questionTargetCode", questionTargetCode);
			rules.set("questionGroupCode", questionGroupCode);
			rules.set("questionIsPopup", questionIsPopup);
			rules.setState("ASK_QUESTION");

			rules.setState("SHOWN_OFFER_DOCUMENT_EDU_PROVIDER");

        }else{
			rules.println("begCode is null");
		}
	 	rules.footer();      
end
