package life.genny.rules;
import life.genny.rules.QRules;

/* Update  PRI_IS_PROFILE_COMPLETED = TRUE */
rule "Intern Registration Form Submit - Step 2"
	when
	    rules: QRules( 	isState("SET_PROFILE_IS_COMPLETED") && 
	    				isState("LINKED_EDU_PROVIDER_TO_INTERN") && 
	    				isState("QUE_INTERN_GRP") && 
						isState("EVENT_FORM_SUBMIT") && 						
						isState("CREATED_LINK") && 						
						isState("STUDENT") && 						
						!isState("PRI_IS_PROFILE_COMPLETED") && 
						!isState("LOOP_INTERN_REGISTRATION_FORM_SUBMIT_STEP2")) 
	 then
	 	rules.header();
        rules.setState("LOOP_INTERN_REGISTRATION_FORM_SUBMIT_STEP2");

		String sourceCode = rules.getUser().getCode();
		String targetCode = rules.getUser().getCode();
		String attributeCode = "PRI_IS_PROFILE_COMPLETED";
		String value = "TRUE";

/* 		rules.updateBaseEntityAttribute(sourceCode, targetCode, attributeCode, value);
 */
		rules.saveAnswer(
			new Answer(	sourceCode, 
						targetCode, 
						attributeCode,
						value )
		);
	 	rules.footer();      
end
