package life.genny.rules;

import life.genny.rules.QRules;
import life.genny.qwanda.entity.BaseEntity;

rule "Application is ready role is found - {{REALM}}"
    when
         rules: QRules( isState("APPLICATION_READY") &&
                        isState("ROLE_FOUND") &&
                        !isState("LOOP_APPLICATION_READY_{{REALM}}") )
     then
     	rules.header();

        rules.setState("LOOP_APPLICATION_READY_{{REALM}}");
        rules.setState("TRIGGER_PROFILE_CHECK");

	    rules.footer();
end
