package life.genny.rules;

import life.genny.rules.QRules;
import life.genny.qwanda.message.QEventCronMessage;
import io.vertx.core.json.JsonObject;

rule "Reload Cache - Cron"
    when
  		rules: QRules( isState("CRON_EVENT") && isState("CRON_RELOAD_CACHE") && !isState("RELOADED_CACHE") )
     then

        rules.header();

        rules.setState("RELOADED_CACHE");
        rules.reloadCache();
        rules.footer();
end
