package life.genny.rules;
import life.genny.rules.QRules;

/* Send Sub Layout */
rule "View Application Details - Send Application Details Layout"
	when
		rules: QRules(  isState("VIEW_APPLICATION_DETAILS") && 
                    	!isState("LOOP_VIEW_APPLICATION_DETAILS") ) 
	 then
	 	rules.header();
    	rules.setState("LOOP_VIEW_APPLICATION_DETAILS");

		/* get applicationBe from state */
		BaseEntity application = rules.getAsBaseEntity("applicationBe");
		if(application != null){
			rules.set("subLayoutCode", "APP_DETAILS");
			rules.set("subLayoutPath", "application/view-application.json");
			rules.set("subLayoutRootCode", application.getCode());
			rules.set("subLayoutIsPopup", false);

			rules.setState("SEND_SUBLAYOUT"); 
      		rules.setState("VIEWED_APPLICATION_DETAILS");	
				
		}else{
			rules.println("applicationCode is null");
		}
	 	rules.footer();      
end

        
