package life.genny.rules;
import life.genny.rules.QRules;

/* Set BEG \ APP \ INTERN To Map */
rule "IN_PROGRESS Internship - Step 0"
	when
		rules: QRules( 	isState("BTN_IN_PROGRESS_INTERN") && 
						isState("EVENT_BTN_CLICK") && 
						!isState("LOOP_IN_PROGRESS_INTERN_STEP0")) 
	 then
	 	rules.header();
        rules.setState("LOOP_IN_PROGRESS_INTERN_STEP0");

		String begCode = rules.getAsString("itemCode");

		if(begCode == null){
            rules.println("begCode is null");
        }else{
			BaseEntity beg = rules.getBaseEntityByCode(begCode);
			rules.set("begBe", beg);

			BaseEntity creator = rules.getChildren(beg.getCode(), "LNK_BEG", "CREATOR");
			BaseEntity hostCompany = rules.getChildren(beg.getCode(), "LNK_BEG", "HOSTCOMPANY");
			BaseEntity internship = rules.getChildren(beg.getCode(), "LNK_BEG", "INTERNSHIP");

			if (creator == null) {
            	rules.println("Creator of beg is null");
				return;
			} 
			if (hostCompany == null) {
            	rules.println("Host Company of beg is null");
				return;
			} 
			if (internship == null) {
            	rules.println("Internship is null");
				return;
			} 

            rules.println("beg  ::   " + beg);
            rules.println("creator   ::   " + creator);
            rules.println("hostCompany   ::   " + hostCompany);
            rules.println("internship   ::   " + internship);
			
			rules.set("creatorBe", creator);
			rules.set("companyBe", hostCompany);
			rules.set("internshipBe", internship);
			
			rules.setState("IN_PROGRESS_INTERN_READY");            
			rules.setState("MOVE_BEG_TO_IN_PROGRESS");
        }
	 	rules.footer();      
end
