package life.genny.rules;
import life.genny.rules.QRules;

/* MOVE BEG from GRP_AVAILABLE >>> GRP_IN_PROGRESS */
rule "IN_PROGRESS Internship - Step 3"
	when
		rules: QRules(  isState("BTN_IN_PROGRESS_INTERN") && 
						isState("EVENT_BTN_CLICK") && 
						isState("PRI_IS_EDU_PROVIDER") && 
						!isState("LOOP_MOVE_BEG_TO_IN_PROGRESS")) 
	 then
	 	rules.header();
        rules.setState("LOOP_MOVE_BEG_TO_IN_PROGRESS");

		String begCode = rules.getAsString("itemCode");
		
        if(begCode != null){
			rules.moveBaseEntity(begCode, "GRP_APPROVED", "GRP_IN_PROGRESS", "LNK_CORE");
        	rules.setState("MOVED_BEG_TO_IN_PROGRESS");
		}else{
			rules.println("beg is null");
		}
	 	rules.footer();      
end