package life.genny.rules;

import life.genny.rules.RulesUtils;
import life.genny.rules.QRules;

import life.genny.qwanda.message.QEventMessage;


rule "Send Chat Message"
   /* no-loop true
    salience 999
    ruleflow-group 'chat' */
    when
	    m : QEventMessage( event_type == "BTN_CLICK" && data.code == "BTN_SEND_MESSAGE" )
        rules: QRules( isState("STARTED") && !isState("SENT_CHAT_MESSAGE")) 
     then
     	
     	rules.header();
     		
	    String data = m.getData().getValue();
		
  		if(data != null) {
  			
  			rules.processChat(m);
  			rules.setState("SENT_CHAT_MESSAGE");
  		}
     	
     	rules.footer();
end
