package life.genny.rules;

import life.genny.rules.QRules;
import java.util.List;

rule "Send Intern Profile Dropdown Data"
    when
        rules: QRules(isState("SEND_BUYER_DROPDOWN_SELECTIONS") &&
						          !isState("LOOP_INTERN_ROLE_CHECK")	)
    then
      rules.header();
      rules.setState("LOOP_INTERN_ROLE_CHECK");

     	rules.sendSelections("GRP_UNI_SELECTION", "LNK_CORE", 10);
     	rules.sendSelections("GRP_FIELD_OF_WORK", "LNK_CORE", 10);
     	rules.sendSelections("GRP_DEGREE_SELECTION", "LNK_CORE", 10);
     	rules.sendSelections("GRP_GENDERS", "LNK_CORE", 10);
     	rules.sendSelections("GRP_RESIDENTIAL_STATUS", "LNK_CORE", 10);

			rules.setState("SEND_FACULTY_DROPDOWN");

     	rules.setState("SENT_REGISTRATION_DATA");
	  	rules.footer();
end

