package life.genny.rules;

import life.genny.rules.RulesUtils;
import life.genny.rules.QRules;
import life.genny.qwandautils.QwandaUtils;
import io.vertx.core.json.JsonObject;


import io.vertx.core.json.JsonObject;

import life.genny.qwanda.message.QEventMessage;

rule "Expand TreeView Item"

    when
        m : QEventMessage( QEventMessage.getData().getCode().equals("LAYOUT_CHANGE_READY") )
        rules: QRules( ) 
     then
     	RulesUtils.header(drools.getRule().getName());

       JsonObject obj = new JsonObject(QwandaUtils.apiGet(rules.getQwandaServiceUrl()+"/qwanda/baseentitys/"+m.getData().getValue()+"/linkcodes/LNK_CORE", rules.getToken()));
		obj.put("token", rules.getToken());
	rules.publish("cmds", obj);

    
  		
	    RulesUtils.footer(drools.getRule().getName());       		      
end
