package life.genny.rules;
 
import life.genny.qwanda.message.QEventMessage;
import life.genny.qwanda.message.QCmdMessage;
import io.vertx.rxjava.core.eventbus.EventBus;
import io.vertx.core.buffer.Buffer;
import com.google.gson.Gson;
import life.genny.qwanda.Answer;
import life.genny.qwanda.message.QDataAnswerMessage;
import life.genny.qwandautils.KeycloakUtils;
import life.genny.qwandautils.QwandaUtils;
import life.genny.qwanda.message.QDataAskMessage;
import life.genny.qwanda.Ask;

import java.lang.reflect.Type;
import java.util.Map;
import org.apache.commons.lang3.StringUtils;
import java.time.LocalDateTime;
import java.time.ZonedDateTime;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonParseException;
import com.google.gson.JsonPrimitive;
import com.google.gson.JsonParser;
import com.google.gson.JsonSerializationContext;
import com.google.gson.FieldNamingPolicy;
import io.vertx.core.json.JsonObject;
import java.time.format.DateTimeFormatter;
import life.genny.qwanda.DateTimeDeserializer;

global java.lang.String REACT_APP_QWANDA_API_URL;
global java.lang.String REACT_APP_VERTX_URL;
global java.lang.String KEYCLOAKIP;
 
  


/*Rules to Send CMD_VIEW with value based on the GRP_VALUE */
rule "Send CMD_VIEW:GRP_DASHBOARD"
     agenda-group "CMD_VIEW"
     when
       $m : QEventMessage( event_type == "TV_SELECT" && data.code == "TV1" && (data.value == "GRP_DASHBOARD" || data.value == "GRP_DRIVER_VIEW" ))
       bus: EventBus()
       $map : Map($value: this["token"] != null)
     then
       System.out.println("------- Rule: Send CMD_VIEW :- "+$m.data.getValue()+ " --------");
       /*sending cmd BUCKET_VIEW */
       QCmdMessage cmdBucketView = new QCmdMessage("CMD_VIEW","BUCKET_VIEW");
        /*Convert cmd to JSON Obj */
       JsonObject bucketViewJson = new JsonObject().mapFrom(cmdBucketView);
       
       bucketViewJson.put("token", $value);
       
       bucketViewJson.put("root","GRP_DRIVER_VIEW");
       System.out.println(" ##################### ");
       System.out.println("Layout Data ="+bucketViewJson.toString()); 
       System.out.println(" #################### ");
        /*Publish it to the EventBus */
       bus.publish("cmds", bucketViewJson); 
       System.out.println("-------------------------------------------------");    
end