package life.genny.rules;

import life.genny.rules.QRules;

rule "Pre Init Auth Init"
	no-loop true
	ruleflow-group 'Init'
    when
        m : QEventMessage( "AUTH_INIT" == data.code  )
        rules: QRules(!isState("STARTED")) 
     then    
        rules.setDrools(drools);
        rules.println("RULE INIT AUTH_INIT: "+m);
 
        rules.setState("STARTED");
        rules.footer();
      		      
end
