package life.genny.rules;

import life.genny.rules.QRules;

rule "Add New payment method - payment submit"
	no-loop true
	ruleflow-group 'Init'
    when
          m : QEventMessage( event_type == "PAYMENT_SUBMIT" )
          rules: QRules(!isState("STARTED")) 
     then    
        rules.setDrools(drools);
        		rules.println("RULE INIT PAYMENT_SUBMIT: "+m.getData().getValue());
        		rules.setState("STARTED");
        		
        		String paymentMethodSubmitCode =  m.getData().getCode();
        		String paymentMethodDataString = m.getData().getValue();
        		
        		if(paymentMethodSubmitCode != null && paymentMethodDataString != null){
        			rules.setState(paymentMethodSubmitCode);
        			rules.set("paymentMethodDataString", paymentMethodDataString);       		
        		}
        
       rules.footer();       
end
