package life.genny.rules;

import life.genny.rules.QRules;

rule "Pre Init Answer"
    when
        m : QDataAnswerMessage( QDataAnswerMessage.getData_type().equals(Answer.class.getSimpleName()) )
        rules: QRules(!isState("STARTED"))
     then
        rules.setDrools(drools);
        rules.println("RULE INIT ANSWER: "+ m + " - " + m.getItems());
		
		/* we grab the data associated to the answers */
		 Answer[] answers = m.getItems();
		 if(answers.length > 0) {
		 	
		 	/* TODO: update to handle multiple answers */
		 	Answer firstAnswer = answers[0];
		 	String answerSourceCode = firstAnswer.getSourceCode();
		 	String answerTargetCode = firstAnswer.getTargetCode();
		 	String answerAttributeCode = firstAnswer.getAttributeCode();
		 	String answerValue = firstAnswer.getValue();
		 	
		 	if(answerSourceCode != null && answerTargetCode != null && answerAttributeCode != null && answerValue != null ){
		 	    rules.set("answerSourceCode", answerSourceCode);
		 		rules.set("answerTargetCode", answerTargetCode);
		 	    rules.set("answerAttributeCode", answerAttributeCode);
		 	    rules.set("answerValue", answerValue);
		 	    
		 	    rules.setState(answerAttributeCode);
		 	    rules.set(answerAttributeCode, firstAnswer);
		 	}	 	
		 }
       
        rules.setState("EVENT_ANSWER"); /* other rules listening for thos state */
        rules.setState("DATA_ANSWER");
        rules.setState("STARTED");
        rules.setState("ANSWER");
        drools.setFocus("Answer");
end
