package life.genny.rules;

import life.genny.rules.QRules;
import life.genny.qwanda.message.QEventMessage;
import io.vertx.core.json.JsonObject;

rule "Pre Init De-Select Event"
	no-loop true
	ruleflow-group 'Init'
    when
	  m : QEventMessage( event_type == "BTN_CLICK" && getData() != null && getData().getCode().equals("DESELECT_EVENT") )
	  rules: QRules(!isState("STARTED"))
     then
        rules.setDrools(drools);
        rules.println("RULE INIT BTN_CLICK: "+m);

        String dataString = m.getData().getValue();

        try {

          JsonObject dataJson = new JsonObject(dataString);

          String itemCode = dataJson.getString("itemCode");
          if(itemCode != null) {
            rules.set("itemCode", itemCode);
          }

          rules.popContext();
        }
        catch( Exception e) {
            rules.println("button click event   ::   " +  m.getData());
        }

        rules.setState("STARTED");
        rules.setState("DESELECT_EVENT");

end
