package life.genny.rules;

import life.genny.rules.QRules;

rule "Pre Init Menu Profile"
    no-loop true
	ruleflow-group 'Init'
    when
          m : QEventMessage( event_type == "PROFILE" && data.code == "PROFILE" )
          rules: QRules(!isState("STARTED")) 
     then    
        rules.setDrools(drools);
        rules.println("RULE INIT MENU_PROFILE: "+m);
 
        rules.setState("EVENT_MENU_PROFILE");
        rules.setState("STARTED");
end
