package life.genny.rules;

import life.genny.rules.QRules;
import life.genny.qwanda.message.QEventMessage;
import io.vertx.core.json.JsonObject;

rule "Pre Init Route Change"
	no-loop true
	ruleflow-group 'Init'
    when
	  m : QEventMessage( event_type == "ROUTE_CHANGE" )
	  rules: QRules(!isState("STARTED"))
     then
        rules.setDrools(drools);
        rules.println("RULE INIT ROUTE_CHANGE: "+m);

        String route = m.getData().getCode();
        String selectedItem = m.getData().getValue();
        

        if(route != null) {
          rules.setState(route);
        }
        if(selectedItem != null) {
            rules.setState(selectedItem);
            rules.set("selectedItem", selectedItem);
        }

        rules.setState("STARTED");
        rules.setState("EVENT_ROUTE_CHANGE");

end
