package life.genny.rules;

import life.genny.rules.QRules;
import life.genny.qwanda.message.QEventMessage;
import io.vertx.core.json.JsonObject;

rule "Pre Init Select Event"
	no-loop true
	ruleflow-group 'Init'
    when
	  m : QEventMessage( event_type == "BTN_CLICK" && getData() != null && getData().getCode().equals("SELECT_EVENT") )
	  rules: QRules(!isState("STARTED"))
     then
        rules.setDrools(drools);
        rules.println("RULE INIT BTN_CLICK: "+m);

        String btnCode = m.getData().getCode(); /* TODO : remove this if unused */
        String quesCode = m.getData().getCode(); /* TODO: use this, don't remove. */

        String dataString = m.getData().getValue();

        try {

          JsonObject dataJson = new JsonObject(dataString);

          String itemCode = dataJson.getString("itemCode");
          if(itemCode != null) {
            rules.set("itemCode", itemCode);
          }

          rules.setContext(itemCode);
        }
        catch( Exception e) {
            rules.println("button click event   ::   " +  m.getData());
        }

        rules.setState("STARTED");
        rules.setState("SELECT_EVENT");

end
