package life.genny.rules;

import life.genny.rules.QRules;

rule "Pre Init Attribute Change"
	no-loop true
	salience 10000
/*	ruleflow-group 'Init' */
    when
          m : QEventMessage( event_type == "EVT_ATTRIBUTE_VALUE_CHANGE" )
          rules: QRules(!isState("STARTED")) 
     then    
        rules.setDrools(drools);
        rules.println("RULE INIT ATTRIBUTE_CHANGE: "+m);
 
        rules.setState("EVT_ATTRIBUTE_VALUE_CHANGE");
        rules.setState("STARTED");
		
        drools.setFocus("AttributeChange");
       		      
end
