package life.genny.rules;

import life.genny.rules.QRules;
import life.genny.qwanda.entity.BaseEntity;

import life.genny.qwanda.message.QEventMessage;

rule "Pre Init"
	no-loop true
    ruleflow-group 'Init'

    when
        m : QEventMessage( "AUTH_INIT" == data.code  )
        rules: QRules(  !isState("LOOP_PRE_INIT_EVT") &&
                        !isState("STARTED") )
     then   
        rules.setDrools(drools);
     	rules.header();
        rules.setState("STARTED");
        rules.setState("LOOP_PRE_INIT_EVT");
	    rules.footer();
end
