package life.genny.rules;

import life.genny.rules.QRules;
import life.genny.qwanda.message.QEventMessage;
import io.vertx.core.json.JsonObject;

rule "Pre Init Redirect Event"
	no-loop true
	ruleflow-group 'Init'
    when
		m : QEventMessage( event_type == "REDIRECT_EVENT" )
		rules: QRules(!isState("STARTED")) 
     then   
        rules.setDrools(drools);
        rules.println("RULE INIT REDIRECT_EVT: "+m);
        rules.setState("REDIRECT_EVENT");
        rules.setState("STARTED");

        String dataCode = m.getData().getCode();
        String valueCode = m.getData().getValue();

		if(dataCode != null) {
 	 		rules.setState(dataCode);
		}
		if(valueCode != null) {
			rules.set("valueCode", valueCode);
		}
end
