package life.genny.rules;

import life.genny.rules.QRules;

rule "Pre Init Attribute Change"
	no-loop true
	salience 10000
/*	ruleflow-group 'Init' */
    when
        m : QEventAttributeValueChangeMessage( event_type == "EVT_ATTRIBUTE_VALUE_CHANGE" )
        rules: QRules(!isState("STARTED")) 
     then    
        rules.setDrools(drools);
        rules.println("RULE INIT ATTRIBUTE_CHANGE: "+m);

        String answerSourceCode = m.getAnswer().getSourceCode();
        rules.println("answerSourceCode   ::   " + answerSourceCode);

        String answerTargetCode = m.getAnswer().getTargetCode();
        rules.println("answerTargetCode   ::   " + answerTargetCode);

        String answerAttributeCode = m.getAnswer().getAttributeCode();
        rules.println("answerAttributeCode   ::   " + answerAttributeCode);

        String answerValue = m.getAnswer().getValue();
        rules.println("answerValue   ::   " + answerValue);

        /* Boolean answerInferredValue = m.getAnswer().getInferred();
        Boolean answerExpiredValue = m.getAnswer().getExpired();
        Boolean answerRefusedValue = m.getAnswer().getRefused();
        Boolean answerWeightValue = m.getAnswer().getWeight(); */

        if(answerSourceCode != null) {
            rules.set("answerSourceCode", answerSourceCode);
		}
        if(answerTargetCode != null) {
            rules.set("answerTargetCode", answerTargetCode);
		}
		if(answerAttributeCode != null) {
			rules.set("answerAttributeCode", answerAttributeCode);
			rules.setState(answerAttributeCode);
		}
		if(answerValue != null) {
			rules.set("answerValue", answerValue);
		}

        rules.setState("EVT_ATTRIBUTE_VALUE_CHANGE");
        rules.setState("STARTED");
        drools.setFocus("AttributeChange");
end