package life.genny.rules;

import life.genny.rules.QRules;


rule "Pre Init System Event"
	no-loop true
	salience 10000
/*	ruleflow-group 'Init' */
    when
          m : QEventMessage( event_type == "EVT_SYSTEM" )
          rules: QRules(!isState("STARTED")) 
     then    
        rules.setDrools(drools);
        rules.println("RULE INIT SYSTEM_EVENT: "+m);
 
        rules.setState("EVT_SYSTEM");
        rules.setState("STARTED");
		
        	drools.setFocus("SystemEvent");
       		      
end