package life.genny.rules;

import life.genny.rules.QRules;

rule "Pre Init FORM Submit"
	no-loop true
	ruleflow-group 'Init'
    when
          m : QEventMessage( event_type == "FORM_SUBMIT" )
          rules: QRules(!isState("STARTED")) 
     then    
        rules.setDrools(drools);
        rules.println("RULE INIT FORM_SUBMIT: "+m);
        rules.setState("EVENT_FORM_SUBMIT");
        rules.setState("STARTED");

  		drools.setFocus("FormSubmit");
        
      		      
end
