package life.genny.rules;

import life.genny.rules.QRules;
import life.genny.qwanda.message.QEventMessage;
import io.vertx.core.json.JsonObject;

rule "Pre Init FORM Submit"
	no-loop true
	ruleflow-group 'Init'
    when
        m : QEventMessage( event_type == "FORM_SUBMIT" )
        rules: QRules(!isState("STARTED")) 
     then    
        rules.setDrools(drools);
        rules.println("RULE INIT FORM_SUBMIT: "+m);
        rules.setState("EVENT_FORM_SUBMIT");
        rules.setState("STARTED");

        String quesCode = m.getData().getCode();
        
        String dataString = m.getData().getValue();
		JsonObject dataJson = new JsonObject(dataString);
		String targetCode = dataJson.getString("targetCode");
		rules.println("targetCode   ::   " + targetCode);

        if(quesCode != null) {
	 		rules.setState(quesCode);
	 		rules.set("quesTargetCode", targetCode);
		}

  		drools.setFocus("FormSubmit");
        
      		      
end
