package life.genny.rules;

import life.genny.rules.QRules;


rule "Pre Init Focus Rule Group"
	no-loop true
	salience 10000
/*	ruleflow-group 'Init' */
    when
          m : QEventMessage( event_type == "FOCUS_RULE_GROUP" )
          rules: QRules(!isState("FOCUS_RULE_GROUP")  && (hasRole("dev") == true) ) 
     then    
        rules.setDrools(drools);
        rules.println("RULE INIT FOCUS RULE GROUP: "+m);
 
        rules.setState("FOCUS_RULE_GROUP");

		
       String ruleGroup = m.getData().getCode();
		drools.setFocus(ruleGroup);
       		      
end