package life.genny.rules;

import life.genny.rules.QRules;
import life.genny.qwanda.entity.BaseEntity;
import java.util.List;

/* Sends BEGs */
rule "Send Buckets"
    when
        rules: QRules(  isState("SENT_DASHBOARD") && 
                        isState("SEND_BUCKETS") && 
                        isState("PUBLISHED_BASE_ENTITY_LIST") && 
                        !isState("LOOP_SEND_DASHBOARD_BEGS") )
     then
     	rules.header();
     	rules.setState("LOOP_SEND_DASHBOARD_BEGS");
        
        /* Get BUCKETS from map */
        List<BaseEntity> bucketList = rules.getAsBaseEntitys("beList");

        List<BaseEntity> begs = null;
        List<BaseEntity> begKids = new ArrayList<BaseEntity>();
        
        for(BaseEntity bucket: bucketList) {  
            begs = rules.getBaseEntitysByParentAndLinkCode(bucket.getCode(), "LNK_CORE", 0, 500, false);
            
            /* send BEGS */
            rules.publishCmd(begs, bucket.getCode(), "LNK_CORE");

            for(BaseEntity beg: begs) {  
                begKids = rules.getBaseEntitysByParentAndLinkCode(beg.getCode(), "LNK_BEG", 0, 500, false);
                
                /* send INTERNSHIP | COMPANY | CREATOR */
                rules.publishCmd(begKids, beg.getCode(), "LNK_BEG");
            }
        }
        
        
         
        rules.setState("SENT_BUCKETS");		
        rules.setState("SEND_CONTACTS");		
	    rules.footer();     		      
end


       
