package life.genny.rules;
import life.genny.rules.QRules;
import life.genny.qwanda.Answer;


rule "Attribute Change - Set Title value to the BE's name"
    when
        rules : QRules( isState("EVENT_ANSWER")  && 
						(isState("PRI_TITLE") ||
						isState("PRI_NAME") ||
						isState("PRI_CPY_NAME") ) &&
                        !isState("LOOP_BASEENTITY_NAME_UPDATED") )
     then    
      	rules.header();
		rules.setState("LOOP_BASEENTITY_NAME_UPDATED");
		String attributeCode = rules.getAsString("attributeCode");
		String targetBeCode = rules.getAsString("targetCode");
		String newValue = rules.getAsString("value");
		
		if(attributeCode != null && targetBeCode != null && newValue != null ){
			BaseEntity targetBe = rules.baseEntity.getBaseEntityByCode(targetBeCode);
			targetBe.setName(newValue);
			rules.println("The updated baseEntity name after setting "+targetBe.getName());
			/* Update Load BaseEntity   */
			rules.baseEntity.updateBaseEntity(targetBe);
			
			/* Answer baseEntityNameAnswer = new Answer(rules.getUser().getCode(), targetBeCode, "PRI_NAME", newValue); */
			/* rules.baseEntity.saveAnswer(baseEntityNameAnswer); */
			
			rules.setState("BASEENTITY_NAME_UPDATED");
		}
			
   	    rules.footer();
  
end