package life.genny.rules;

import life.genny.rules.QRules;
import life.genny.qwanda.Answer;


rule "Attribute Change - Set Title value to the BE's name"
    when
        rules : QRules( isState("STARTED")  && 
                        isState("EVT_ATTRIBUTE_VALUE_CHANGE") &&
                        isState("PRI_TITLE") &&
                        !isState("LOOP_BASEENTITY_NAME_UPDATED") )
     then    
      	rules.header();
      		rules.setState("LOOP_BASEENTITY_NAME_UPDATED");
			String attributeCode = rules.getAsString("newAnsAttributeCode");
			String targetBeCode = rules.getAsString("newAnsTargetCode");
			String newValue = rules.getAsString("newAnsValue");
			
			if(attributeCode != null && targetBeCode != null && newValue != null ){
				BaseEntity targetBe = rules.baseEntity.getBaseEntityByCode(targetBeCode);
			    targetBe.setName(newValue);
			    rules.println("The updated baseEntity name after setting "+targetBe.getName());
			    /* Update Load BaseEntity   */
         		rules.baseEntity.updateBaseEntity(targetBe);
         		
         		//Answer baseEntityNameAnswer = new Answer(rules.getUser().getCode(), targetBeCode, "PRI_NAME", newValue);
         		//rules.baseEntity.saveAnswer(baseEntityNameAnswer);
         		
         		rules.setState("LOOP_BASEENTITY_NAME_UPDATED");
			}
			
   	    rules.footer();
  
end