package life.genny.rules;
import life.genny.rules.QRules;

rule "Trigger Subscription - Internmatch"
     when
        rules: QRules(  isState("TRIGGER_SUBSCRIPTION") && 
                        !isState("LOOP_TRIGGER_SUBSCRIPTION") ) 
     then      
        rules.header();
		rules.setState("LOOP_TRIGGER_SUBSCRIPTION");
        
		rules.setState("TRIGGER_SUBSCRIPTION_AFTER_REGISTRATION");
		rules.footer();     		      
end
     	