package life.genny.rules;
import life.genny.rules.QRules;

rule "Select Dashboard"
    when
      rules: QRules(  isState("EVENT_TV_SELECT") &&
                      isState("TV1") &&
                      isState("GRP_DASHBOARD") &&
                      !isState("LOOP_SELECT_DASHBOARD") )
    then
      rules.header();
      rules.setState("LOOP_SELECT_DASHBOARD");

      String tvSelectValue = rules.getAsString("tvSelectValue");
      
      if(tvSelectValue.equals("GRP_DASHBOARD")){
        rules.setState("TRIGGER_INTERNMATCH_HOMEPAGE");

        rules.clearState("GRP_DASHBOARD");
        rules.setState("SELECTED_DASHBOARD");
      }
      rules.footer();
end