package life.genny.rules;
import life.genny.rules.QRules;
import life.genny.qwanda.message.QEventMessage;

/* Show Offer Document - Host Company */
rule "Show Offer Document - Host Company"
	when
		rules: QRules( 	isState("REDIRECT_EVENT") &&
						isState("REDIRECT_SHOW_OFFER") &&
						isState("PRI_IS_HOST_COMPANY") && 
						isState("EXIT_HOME_PAGE") &&
						!isState("LOOP_SHOW_OFFER_DOCUMENT_HOST_COMPANY") ) 
	 then
	 	rules.header();
        rules.setState("LOOP_SHOW_OFFER_DOCUMENT_HOST_COMPANY");

        String begCode = rules.getAsString("valueCode");

        if(begCode != null){
		   	String questionSourceCode = rules.getUser().getCode();
			String questionTargetCode = begCode;
			String questionGroupCode = "QUE_HOST_COMPANY_AGREEMENT_GRP";
			Boolean questionIsPopup = false;

			rules.set("questionSourceCode", questionSourceCode);
			rules.set("questionTargetCode", questionTargetCode);
			rules.set("questionGroupCode", questionGroupCode);
			rules.set("questionIsPopup", questionIsPopup);
			rules.setState("ASK_QUESTION");

			rules.setState("SHOWN_OFFER_DOCUMENT_HOST_COMPANY");

        }else{
			rules.println("begCode is null");
		}
	 	rules.footer();      
end