package life.genny.rules;

import life.genny.rules.QRules;
import life.genny.qwanda.entity.BaseEntity;
import life.genny.utils.VertxUtils;
import life.genny.qwandautils.JsonUtils;
import life.genny.qwanda.message.QDataBaseEntityMessage;

rule "Send Capabilities"
    when
         rules: QRules( isState("SEND_CAPABILITIES") && !isState("SENT_CAPABILITIES") )
     then
     	rules.header();

        rules.setState("SENT_CAPABILITIES");

        /* we grab GRP_CAPABILITIES which contains all the capabilities of the system */
		List<BaseEntity> capabilities = rules.getAvailableCapabilities(rules.getUser());
		if(capabilities != null) {
			
			/* we publish the filtered capabilities */
			rules.publishCmd(capabilities, "GRP_CAPABILITIES", "LNK_CORE");
		}
        
        rules.setState("SEND_PROJECT");

	    rules.footer();      		      
end
