package life.genny.rules;

import life.genny.rules.QRules;
import life.genny.qwanda.entity.BaseEntity;
import life.genny.utils.VertxUtils;
import life.genny.qwandautils.JsonUtils;
import life.genny.qwanda.message.QDataBaseEntityMessage;

rule "Send Capabilities"
    when
         rules: QRules( isState("SEND_CAPABILITIES") && !isState("SENT_CAPABILITIES") )
     then
     	rules.header();

        rules.setState("SENT_CAPABILITIES");

     	QDataBaseEntityMessage capabilitiesMsg = VertxUtils.getObject(rules.realm(), "CAPABILITIES", rules.realm(), QDataBaseEntityMessage.class);

        if(capabilitiesMsg != null) {
            rules.println("Sending "+capabilitiesMsg.getItems().length +" Capabilities  ");
            rules.publishCmd(capabilitiesMsg);
        }
        
        rules.setState("SEND_ROLES");

	    rules.footer();      		      
end
