package life.genny.rules;
import life.genny.rules.QRules;

rule "Exit Send System Data"

    when
         rules: QRules( isState("SENT_SUB_LAYOUTS") && !isState("LOOP_EXIT_SEND_SYSTEM_DATA") )
     then
     	rules.header();
        rules.setState("LOOP_EXIT_SEND_SYSTEM_DATA");
    
        rules.setState("EXIT_SEND_SYSTEM_DATA");
        rules.setState("TRIGGER_SEND_SYSTEM_LAYOUTS");

	    rules.footer();      		      
end
