package life.genny.rules;

import life.genny.rules.QRules;


rule "Send User Company"
    when
        rules: QRules( isState("SEND_USER_COMPANY")  && !isState("LOOP_SEND_USER_COMPANY") )
     then
     	rules.header();
     	rules.setState("LOOP_SEND_USER_COMPANY");

     	/*  Get Company Code of the current user   */
        BaseEntity company = rules.getUserCompany();
        if(company != null)
        {
            String companyCode = company.getCode();
            rules.publishCmd(company, "USER_COMPANY");
        }

        rules.setState("SEND_COMPANY_ROLES");
        rules.setState("SENT_USER_COMPANY");
	    rules.footer();
end
