package life.genny.rules;

import life.genny.rules.QRules;

rule "Send Company Roles"
    when
        rules: QRules( isState("SEND_COMPANY_ROLES")  && !isState("LOOP_SEND_COMPANY_ROLES") )
     then
     	rules.header();
     	rules.setState("LOOP_SEND_COMPANY_ROLES");

     	/* we grab the current user's company */
     	BaseEntity company = rules.getUserCompany();

      if(company != null && rules.hasCapability(rules.getUser(), "CAP_UPDATE_ROLES")) {

        /* we grab all the linked roles */
        List<BaseEntity> roles = rules.baseEntity.getLinkedBaseEntities(company.getCode(), "LNK_ROLE");
        if(roles != null && roles.size() > 0) {

          /* we publish them */
          rules.publishCmd(roles, "GRP_ROLES", "LNK_CORE");
        }
      }

      rules.setState("SEND_USER_ROLES");
	    rules.footer();
end
