package life.genny.rules;

import life.genny.rules.QRules;

rule "Send User Roles"
    when
        rules: QRules( isState("SEND_USER_ROLES")  && !isState("LOOP_SEND_USER_ROLES") )
     then
     	rules.header();
     	rules.setState("LOOP_SEND_USER_ROLES");

     	/* we grab the current user */
     	BaseEntity user = rules.getUser();
     	
     	/* we grab all the linked roles */
		SearchEntity roles = new SearchEntity("SBE_ROLES", "User Roles").setSourceCode(user.getCode())
			.addFilter("PRI_CODE", SearchEntity.StringFilter.LIKE, "ROL_%")
			.setPageStart(0)
			.setPageSize(10000);
	
	    try {
	    		rules.sendSearchResults(roles, "GRP_ROLES", "ROLE");
	    }
	    catch(Exception e) {}

        rules.setState("SEND_SUBLAYOUTS");
	    rules.footer();
end
