package life.genny.rules;

import life.genny.qwanda.entity.SearchEntity;
import life.genny.rules.QRules;

rule "Send Company Staff"
    when
        rules: QRules( isState("SEND_COMPANY_STAFF")  && !isState("LOOP_SEND_COMPANY_STAFF") )
     then
     	rules.header();
     	rules.setState("LOOP_SEND_COMPANY_STAFF");

     	/* we grab the current user's company */
     	BaseEntity company = rules.getUserCompany();

	    if(company != null) {
	
	    		/* we grab all the linked staff members */
	    		SearchEntity staffEntity = new SearchEntity("SBE_STAFF", "Company Staff").setSourceCode(company.getCode())
					.addFilter("PRI_CODE", SearchEntity.StringFilter.LIKE, "PER_%")
					.setPageStart(0)
					.setPageSize(10000);
	    	
	        try {
	        		rules.sendSearchResults(staffEntity, "GRP_STAFFS", "STAFF");
	        }
	        catch(Exception e) {}
	    }
	
	    rules.setState("SEND_USER_ROLES");
	    rules.footer();
end
