package life.genny.rules;

import life.genny.rules.QRules;

rule "Send Company Roles"
    when
        rules: QRules( isState("SEND_COMPANY_ROLES")  && !isState("LOOP_SEND_COMPANY_ROLES") )
     then
     	rules.header();
     	rules.setState("LOOP_SEND_COMPANY_ROLES");

     	/* we grab the current user's company */
     	BaseEntity company = rules.getUserCompany();

      if(company != null && rules.hasCapability(rules.getUser(), "CAP_UPDATE_ROLES")) {

    	  /* we grab all the linked roles */
  		SearchEntity roles = new SearchEntity("SBE_CPY_ROLES", "Company Roles").setSourceCode(company.getCode())
  			.addFilter("PRI_CODE", SearchEntity.StringFilter.LIKE, "ROL_%")
  			.setPageStart(0)
  			.setPageSize(10000);
  	
  	    try {
  	    		rules.sendSearchResults(roles, "GRP_ROLES", "ROLE");
  	    }
  	    catch(Exception e) {}
  	    
      }

      rules.setState("SEND_COMPANY_STAFF");
	  rules.footer();
end
