package life.genny.rules;

import life.genny.qwanda.message.QCmdMessage;
import life.genny.qwanda.message.QBulkMessage;
import life.genny.qwanda.message.QDataBaseEntityMessage;
import life.genny.qwanda.message.QEventMessage;
import life.genny.rules.QRules;
import io.vertx.core.json.JsonObject;
import java.util.List;
import java.util.ArrayList;
import life.genny.qwanda.entity.BaseEntity;
import life.genny.utils.VertxUtils;

rule "Generate Layouts"

    ruleflow-group 'GenerateLayouts'
    salience 700

     when
       rules: QRules(isState("GENERATE_STARTUP") && !isState("GENERATE_LAYOUTS"))
     then

    rules.header();

        rules.setState("GENERATE_LAYOUTS");
		rules.println("Generating layouts");
		rules.layoutUtils.getAllLayouts();

    rules.footer();

end
