package life.genny.rules;

import life.genny.rules.QRules;


rule "Ask First User Profile"
    no-loop true
	salience 5
    agenda-group "NewUserProfile"
    when
        rules: QRules( !isNewUserProfileCompleted() ) 
     then
     	rules.header();
     	rules.debug();   		
   	
   		rules.sendSelections("GRP_USER_ROLE", "LNK_CORE", 10);
   	
  		rules.askQuestions(rules.getUser().getCode(),rules.getUser().getCode(),"QUE_NEW_USER_PROFILE_GRP");
  		/*  Creating new base-entity Company    */
        BaseEntity company = QwandaUtils.createBaseEntityByCode(QwandaUtils.getUniqueId(rules.getUser().getCode(), null, "CPY", rules.getToken()), "COMPANY", rules.getQwandaServiceUrl(), rules.getToken());
        String companyCode = company.getCode();
  		rules.askQuestions(rules.getUser().getCode(), companyCode, "QUE_NEW_USER_COMPANY_GRP");

	    rules.footer();     		      
end
