package life.genny.rules;
import life.genny.rules.QRules;

rule "Exit Welcome Page"
    when
        rules: QRules( isState("WELCOME_PAGE_SENT_LAYOUT") && 
                    !isState("LOOP_EXIT_WELCOME_PAGE") ) 
     then           
        rules.header();  

        rules.setState("LOOP_EXIT_WELCOME_PAGE"); 
        rules.setState("EXIT_WELCOME_PAGE");  

        rules.footer();
      		      
end
