package life.genny.rules;
import life.genny.rules.QRules;

rule "Trigger Welcome Page"
    when
        rules: QRules(  isState("TRIGGER_WELCOME_PAGE") && 
                        isState("ROLE_CHECKED") && 
                        !isState("LOOP_TRIGGER_WELCOME_PAGE")) 
     then       
        rules.header();
        rules.setState("LOOP_TRIGGER_WELCOME_PAGE");
        
        rules.clearState("WELCOME_PAGE_SENT_LAYOUT");   
        rules.setState("WELCOME_PAGE_SEND_LAYOUT");

        rules.footer(); 		      
end
