package life.genny.rules;

import life.genny.rules.QRules;

rule "Select Seller Default Values"

	when
		 rules: QRules( isState("ROLE_SELECTION") && isState("SELLER_SELECTED") && 
						isState("PRI_IS_SELLER")  && isState("ROLE_SET") && !isState("DEFAULT_VALUES_SET") )   
	 then
	    rules.header();
	
		rules.setState("DEFAULT_VALUES_SET");
		String defaultTag = rules.getAllChildCodes("GRP_LOAD_CATEGORY", "LNK_CORE");
		Long defaultBitMaskedTag = rules.getDefaultBitMaskedTag("GRP_LOAD_CATEGORY", "LNK_CORE");
		if(defaultTag != null && defaultBitMaskedTag != null ) {
			rules.updateBaseEntityAttribute(rules.getUser().getCode(), rules.getUser().getCode(), "LNK_PRODUCT_CATEGORY_LIST_TAG", defaultTag);
			rules.updateBaseEntityAttribute(rules.getUser().getCode(), rules.getUser().getCode(), "PRI_PRODUCT_CATEGORY_TAG_BITMASKED", String.valueOf(defaultBitMaskedTag));
	    }
	    
	    rules.footer();	         		      
end