package life.genny.rules;
import life.genny.rules.QRules;

rule "Add Note - STEP 1"
	when
		rules: QRules(  isState("CREATE_NOTE_BASEENTITY") &&
						!isState("LOOP_CREATE_NOTE_BASEENTITY")) 
	 then
	 	rules.header();
		rules.setState("LOOP_CREATE_NOTE_BASEENTITY");
		
        /* Create BEG BaseEntity*/
		rules.set("beCode", rules.getUser().getCode());
		rules.set("bePrefix", "NOT");
		rules.set("beName", "NOTE");		
		rules.setState("CREATE_BASE_ENTITY");	

		rules.setState("SAVE_APPLICATION_CODE_AS_ATTRIBUTE");
	 	rules.footer();      
end
