package life.genny.rules;

import life.genny.rules.QRules;


rule "Re-send Mobile Verification Passcode"
   no-loop true
   salience 560
   ruleflow-group 'ButtonClick'
    when
        $m : QEventMessage( event_type == "BTN_CLICK" && data.code == "BTN_RESEND_VERIFICATION_SMS" )
        rules: QRules( isState("STARTED") && !isState("RESEND_MOBILE_VERIFICATION") ) 
     then
     	rules.header();  		
   	    String userCode = rules.getUser().getCode();
   	
  	    rules.sendMobileVerificationPasscode(userCode);
         
		rules.setState("RESEND_MOBILE_VERIFICATION");
	    rules.footer();     		      
end
