package life.genny.rules;

import life.genny.qwandautils.MergeUtil;
import life.genny.rules.RulesUtils;
import life.genny.rules.QRules;
import life.genny.qwanda.entity.BaseEntity;


rule "Set Is Owner"

    when
        rules: QRules(isState("IS_LOGGED_IN") && !isState("IS_DRIVER") && !isState("IS_OWNER") )  
     then
        rules.header();
        /* GET token AND userCode */
        String tokenString = rules.getToken();  
        String userCode =  rules.getUser().getCode();    

     	String owner = MergeUtil.getAttrValue(userCode, "PRI_OWNER", tokenString);
        System.out.println("Owner    ::   "+ owner);
        
        if( owner != null && owner.equals("TRUE")){
            rules.setState("IS_OWNER");
            System.out.println("State   ::   IS_OWNER");
        }	
	    rules.footer();     		      
end
