package life.genny.rules;

import life.genny.rules.QRules;
import life.genny.qwanda.entity.BaseEntity;
import io.vertx.core.json.JsonObject;

import life.genny.qwanda.Answer;

rule "Create New User"
	no-loop true
	salience 899
	ruleflow-group 'Registration'
    when
        rules: QRules( isState("NEW_REGISTRATION") && (isState("TRIGGER_REGISTRATION")) && (!isState("NEW_USER_CREATED")))
      then
     	rules.header();

     	rules.println("Creating User  ");
     	BaseEntity be = rules.createUser();
     	be = rules.getUser();

		BaseEntity project = rules.getProject();

		if(project != null) {

			String webhookURL = project.getLoopValue("PRI_SLACK_SIGNUP_WEBHOOK", null);
			if(webhookURL != null) {

				rules.println(be.getName());

				if(be.getName() != null) {

					String message = be.getName() + " just signed up";
					JsonObject payload = new JsonObject();
					payload.put("text", message);
					
					rules.sendSlackNotification(webhookURL, payload);
				}
			}
		}
		
		List<Answer> answers = new ArrayList<Answer>();
		
	   /*  saving user registration date time  */
		answers.add(new Answer(be.getCode(), be.getCode(), "PRI_REGISTRATION_DATETIME", QwandaUtils.getZonedCurrentLocalDateTime()) );

      /*  saving the default profile image   */
        answers.add( new Answer(be.getCode(), be.getCode(), "PRI_IMAGE_URL", "https://s3.ap-southeast-2.amazonaws.com/channel40-images/jtaQozJT5HSpn3bX6P4EXSqQj3NDalkQ") );

      /*  saving the attribute PRI_IS_PROFILE_COMPLETED as FALSE for the new user */
        rules.println("Updating User attribute PRI_IS_PROFILE_COMPLETED");
        answers.add(new Answer(be.getCode(), be.getCode(), "PRI_IS_PROFILE_COMPLETED", "FALSE") );
        rules.saveAnswers(answers);
        
     	rules.setState("NEW_USER_CREATED");
        rules.println("The user created is  ::  " + be.toString() );

     	rules.clearState("NEW_REGISTRATION");
         rules.setState("NEW_USER_CREATED");
         rules.clearState("PROFILE_CHECK_COMPLETED");

  	  /* Calling the rule agenda group : NewUser   You're an agenda group! */
  	    drools.setFocus("SendAliases");

        drools.setFocus("Registration");
	    rules.footer();
end
