package life.genny.rules;

import life.genny.rules.QRules;
import life.genny.qwanda.entity.BaseEntity;


rule "Create New User"
	no-loop true

	salience 899
	ruleflow-group 'Registration'
    when
        rules: QRules( isState("NEW_REGISTRATION") && (isState("TRIGGER_REGISTRATION")) && (!isState("NEW_USER_CREATED"))) 
      then
     	rules.header();
     	
     	rules.println("Creating User  ");
     	BaseEntity be = rules.createUser();
     	be = rules.getUser();
     	
      /*  saving the attribute PRI_IS_PROFILE_COMPLETED as FALSE for the new user */
        rules.println("Updating User attribute PRI_IS_PROFILE_COMPLETED");
     	rules.updateBaseEntityAttribute(be.getCode(), be.getCode(), "PRI_IS_PROFILE_COMPLETED", "FALSE");
     	
     	rules.setState("NEW_USER_CREATED");
        rules.println("The user created is  ::  "+be.toString() );
 
     	rules.clearState("NEW_REGISTRATION");
         rules.setState("NEW_USER_CREATED");
         rules.clearState("PROFILE_CHECK_COMPLETED");
  
  	  /* Calling the rule agenda group : NewUser   You're an agenda group! */
        drools.setFocus("Registration");
  		
	    rules.footer();   		      
end
