package life.genny.rules;

import life.genny.rules.QRules;
import life.genny.qwanda.entity.BaseEntity;
import life.genny.qwanda.message.QEventMessage;


rule "Ask Registration - Profile Submit"
	no-loop true
	salience 570
    ruleflow-group 'FormSubmit'
    when
        $m : QEventMessage( event_type == "FORM_SUBMIT" && data.code == "QUE_NEW_USER_COMPANY_GRP" )
        rules: QRules( isState("EVENT_FORM_SUBMIT") && isState("STARTED") )
      then

		rules.header();

     	/*  saving the attribute PRI_IS_PROFILE_COMPLETED as FALSE for the new user */
        rules.println("Updating User attribute PRI_IS_PROFILE_COMPLETED");
     	rules.updateBaseEntityAttribute(rules.getUser().getCode(), rules.getUser().getCode(), "PRI_IS_PROFILE_COMPLETED", "TRUE");

        /*  Send Layouts and Bucket Datas    */
        drools.setFocus("SendLayoutsAndData");

	    rules.footer();
end
