package life.genny.rules;

import life.genny.rules.QRules;


rule "Send Mobile Verification Passcode"
   no-loop true
   salience 560
   ruleflow-group 'FormSubmit'
    when
        $m : QEventMessage( event_type == "FORM_SUBMIT" && data.code == "QUE_NEW_USER_COMPANY_GRP" )
        rules: QRules( isState("EVENT_FORM_SUBMIT") && isState("STARTED") && !isState("ASKED_MOBILE_VERIFICATION") ) 
     then
     	rules.header();  		
   	    String userCode = rules.getUser().getCode();
   	
  		rules.sendMobileVerificationPasscode(userCode);
  		
  		/*  TODO: Send Account Verification Layout  */
  		

		rules.setState("ASKED_MOBILE_VERIFICATION");
	    rules.footer();     		      
end
