package life.genny.rules;

import life.genny.rules.QRules;


rule "Ask Terms and Conditions On Form Submit"
   no-loop true
   salience 560
   ruleflow-group 'FormSubmit'
    when
        $m : QEventMessage( event_type == "FORM_SUBMIT" && data.code == "QUE_NEW_USER_COMPANY_GRP" )
        rules: QRules( isState("EVENT_FORM_SUBMIT") && isState("STARTED") && !isState("ASKED_TC") ) 
     then
     	rules.header();  		
   	    String userCode = rules.getUser().getCode();
   	
  		rules.askQuestions(userCode,userCode,"QUE_NEW_USER_TC_GRP"); 

		rules.setState("ASKED_TC");
	    rules.footer();     		      
end
