package life.genny.rules;

import life.genny.rules.QRules;


rule " Verify Passcode"
   no-loop true
   salience 560
   ruleflow-group 'FormSubmit'
    when
        $m : QEventMessage( event_type == "EVT_PASSCODE_VALIDATION" ) 
        rules: QRules( isState("ASKED_MOBILE_VERIFICATION")  && !isState("PASSCODE_VERIFIED") ) 
     then
     	rules.header();  		
   	    String userCode = rules.getUser().getCode();
   	

		rules.setState("ASKED_MOBILE_VERIFICATION");
	    rules.footer();     		      
end
