package life.genny.rules;
import life.genny.rules.QRules;

/* MOVE BEG from GRP_AVAILABLE >>> GRP_IN_PROGRESS */
rule "IN_PROGRESS Internship - Step 2"
	when
		rules: QRules( 	isState("BTN_INTERVIEW_COMPLETED") && 
						isState("EVENT_BTN_CLICK") && 
						isState("PRI_IS_HOST_COMPANY") && 
						!isState("LOOP_MOVE_BEG_TO_IN_PROGRESS_STEP2")) 
	 then
	 	rules.header();
        rules.setState("LOOP_MOVE_BEG_TO_IN_PROGRESS_STEP2");

        String begCode = rules.getAsString("itemCode");
        
        if(begCode != null){
			rules.saveAnswer( new Answer(rules.getUser().getCode(), begCode, "PRI_HOST_COMPANY_INTERVIEW_COMPLETED", "TRUE") );
		}else{
			rules.println("beg is null");
		}
	 	rules.footer();      
end