package life.genny.rules;
import life.genny.rules.QRules;
import life.genny.qwanda.message.QEventBtnClickMessage;

rule "Create Internship"

	when
		rules: QRules(  isState("BTN_CREATE_INTERSHIP") && 
						!isState("LOOP_CREATE_INTERNSHIP") ) 
	 then
	    rules.header();
		rules.setState("LOOP_CREATE_INTERNSHIP");

        /* Create Internship BaseEntity*/
		rules.set("beCode", rules.getUser().getCode());
		rules.set("bePrefix", "INT");
		rules.set("beName", "INTERNSHIP");
		rules.setState("CREATE_BASE_ENTITY");	

        rules.setState("LINK_TO_DRAFT");

	    rules.footer();     		      
end