package life.genny.rules;

import life.genny.rules.QRules;
import life.genny.qwanda.entity.BaseEntity;


rule "Create New User"
	no-loop true
    when
        rules: QRules( isState("NO_USER") &&  (!isState("NEW_USER")) ) 
      then
     	rules.header();
     	rules.setState("NEW_USER");
     	rules.clearState("NO_USER");
     	
     	rules.println("Creating User  ");
     	BaseEntity be = rules.createUser();
     	be = rules.getUser();
     	
     	
     	rules.clearState("NO_USER");
        rules.setState("NEW_USER");
        
        rules.println("The user created is  ::  "+be.toString() );

  		/* Calling the rule agenda group : NewUser   */
        drools.setFocus("CheckIfProfileCompleted");
  		
	    rules.footer();   		      
end
