package life.genny.rules;
import life.genny.rules.QRules;

/* Check If Current User has applied for a BEG */
rule "Check If Current User has applied for a BEG"
	when
	    rules: QRules(  isState("CHECK_IF_USER_HAS_APPLIED") && 
	                    isState("BTN_APPLY_INTERNSHIP") && 
						isState("EVENT_BTN_CLICK") && 
						!isState("LOOP_CHECK_IF_USER_HAS_APPLIED_STEP1")) 
	 then
	 	rules.header();
        rules.setState("LOOP_CHECK_IF_USER_HAS_APPLIED_STEP1");
        
        BaseEntity beg = rules.getAsBaseEntity("begBe");
        if(beg != null){
            Boolean applied = false;
			
            List<BaseEntity> applications = rules.getChildrens(beg.getCode(), "LNK_BEG", "APPLICATION");
            if(applications != null){

                for(BaseEntity application : applications){
                    
                    Boolean linked = rules.checkIfLinkExistsAndAvailable(beg.getCode(), "LNK_BEG", "APPLICATION", application.getCode());
                    rules.println("linked" +linked);
                    
                    /* BEG + APPLICATION || wt = 1 */
                    if(linked == true){
                        BaseEntity applicant = rules.getChildren(application.getCode(), "LNK_APP", "APPLICANT");
                        if(applicant !=null){
                            if( rules.getUser().getCode().equals(applicant.getCode()) ){
                                applied = true;
                            }
                        }   
                    }
                }
            }else{
                rules.println("application is null");
            }

            if(applied == true){
                rules.setState("USER_HAS_APPLIED");
            }else{
                rules.setState("USER_HAS_NOT_APPLIED");
            }
            rules.println("User applied   ::   " + applied);
        }else{
            rules.println("beg is null");
        }
	 	rules.footer();      
end