package life.genny.rules;

import life.genny.rules.QRules;
import life.genny.qwanda.entity.BaseEntity;


rule "Create New User"
	no-loop true
	lock-on-active true
	salience 899
	ruleflow-group 'Registration'
    when
        rules: QRules( isState("NEW_REGISTRATION") && (isState("TRIGGER_REGISTRATION")) && (!isState("NEW_USER_CREATED"))) 
      then
     	rules.header();
     	
     	rules.println("Creating User  ");
     	BaseEntity be = rules.createUser();
     	be = rules.getUser();
     	
     	rules.setState("NEW_USER_CREATED");
       rules.println("The user created is  ::  "+be.toString() );
 
     	rules.clearState("NEW_REGISTRATION");
         rules.setState("NEW_USER_CREATED");
  
  		/* Calling the rule agenda group : NewUser   You're an agenda group! */
        drools.setFocus("SendAliases");
  		
	    rules.footer();   		      
end
