package life.genny.rules;

import life.genny.rules.QRules;
import life.genny.qwanda.entity.BaseEntity;
import life.genny.qwanda.message.QEventMessage;


rule "Ask Registration - Profile Submit"
	no-loop true
	salience 570
    ruleflow-group 'FormSubmit'
    when
        $m : QEventMessage( event_type == "FORM_SUBMIT" && data.code == "QUE_NEW_USER_COMPANY_GRP" )
        rules: QRules( isState("EVENT_FORM_SUBMIT") && isState("STARTED") ) 
      then
     	rules.header();
     	
        /*  Send Layouts and Bucket Datas    */
        drools.setFocus("SendLayoutsAndData");
        
	    rules.footer();   		      
end
