package life.genny.rules;

import life.genny.rules.QRules;
import life.genny.qwanda.entity.BaseEntity;

rule "Terms and conditions have been accepted"
    when
        rules: QRules( isState("TERMS_AND_CONDITIONS_ACCEPTED") && !isState("LOOP_SUBMIT_ACCEPTED_T_C") )
    then
        rules.header();

		    rules.setState("LOOP_SUBMIT_ACCEPTED_T_C");
		    rules.setState("APPLICATION_READY_SEND_DATA");
        
        rules.footer();
end
