package life.genny.rules;

import life.genny.qwanda.message.QCmdMessage;
import life.genny.qwanda.message.QBulkMessage;
import life.genny.qwanda.message.QDataBaseEntityMessage;
import life.genny.qwanda.message.QEventMessage;
import life.genny.rules.QRules;
import io.vertx.core.json.JsonObject;
import java.util.List;
import java.util.ArrayList;
import life.genny.qwanda.entity.BaseEntity;
import life.genny.qwanda.entity.SearchEntity;
import life.genny.utils.VertxUtils;

rule "Generate Archive caches"

    ruleflow-group 'GenerateArchiveCaches'
     when
       rules: QRules( !isState("GENERATE_ARCHIVE_CACHES"))
     then
	 rules.setDrools(drools);
     rules.header();
        rules.setState("GENERATE_ARCHIVE_CACHES");
		rules.println("Generating Archive Caches for "+rules.realm());

		rules.reloadCache();


     rules.footer();
end
