// package com.sample;

// import org.apache.commons.lang3.StringUtils;

// import life.genny.qwanda.message.QEventMessage;
// import life.genny.qwanda.message.QMessage.MessageData;
// import life.genny.qwanda.message.QCmdMessage;
// import life.genny.qwanda.message.QDataBaseEntityMessage;
// import io.vertx.rxjava.core.eventbus.EventBus;
// import io.vertx.core.buffer.Buffer;
// import com.google.gson.Gson;
// import life.genny.qwanda.Answer;
// import life.genny.qwanda.message.QDataAnswerMessage;
// import life.genny.qwandautils.KeycloakUtils;
// import life.genny.qwandautils.QwandaUtils;
// import life.genny.qwanda.message.QDataAskMessage;
// import life.genny.qwanda.message.QCmdMessage;
// import life.genny.qwanda.Ask;
// import life.genny.qwanda.entity.BaseEntity;

// import java.lang.reflect.Type;
// import java.util.Map;
// import java.util.Set;
// import java.time.LocalDateTime;
// import java.time.ZonedDateTime;
// import com.google.gson.GsonBuilder;
// import com.google.gson.JsonDeserializationContext;
// import com.google.gson.JsonDeserializer;
// import com.google.gson.JsonElement;
// import com.google.gson.JsonParseException;
// import com.google.gson.JsonPrimitive;
// import com.google.gson.JsonSerializationContext;
// import com.google.gson.FieldNamingPolicy;
// import io.vertx.core.json.JsonObject;
// import io.vertx.core.json.JsonArray;
// import java.time.format.DateTimeFormatter;
// import life.genny.qwanda.DateTimeDeserializer;
// import life.genny.qwanda.entity.User;
// import life.genny.qwanda.Link;

// // global java.lang.String REACT_APP_QWANDA_API_URL;
// // global java.lang.String REACT_APP_VERTX_URL;
// // global java.lang.String KEYCLOAKIP;

// // global variables for color logs
// global java.lang.String LOG_RESET;
// global java.lang.String LOG_RED;
// global java.lang.String LOG_GREEN;
// global java.lang.String LOG_YELLOW;
// global java.lang.String LOG_BLUE;
// global java.lang.String LOG_PURPLE;
// global java.lang.String LOG_CYAN;
// global java.lang.String LOG_WHITE;
// global java.lang.String LOG_BOLD;

    
// rule "Send ALIAS when first login"
//    salience 18
//    agenda-group "UserRegistration"
//     when
//        bus: EventBus()
//        $user: User(realm != null )
//        $map : Map($value: this["token"] != null)
//      then
//         System.out.println(LOG_YELLOW + "================================================================================================================================================" + LOG_RESET);
//         System.out.println(LOG_GREEN + "RULE EXECUTED      ::   Send ALIAS2" + LOG_RESET);
//         //Prepare Token & qwandaServiceUrl
//         String qwandaServiceUrl = System.getenv("REACT_APP_QWANDA_API_URL");
//         String tokenString = (String)$map.get("token");  
//         //Getting the User BE and sending it as ALIAS
//         //Get User BE for USER ALIAS based on the user's username
//         JsonObject userObj = new JsonObject(QwandaUtils.apiGet(qwandaServiceUrl+"/qwanda/baseentitys/GRP_PEOPLE/linkcodes/LNK_CORE/attributes?PRI_USERNAME="+ $user.getUname(), tokenString));
//         userObj.put("aliasCode", "USER"); 
//         userObj.put("token", $value);      
//         bus.publish("cmds", userObj);
        
//         //Getting the Project BE and sending it as ALIAS
//         //Get Project BaseEntity for PROJECT ALIAS based on the user's keycloak realm name
//         JsonObject prjObj = new JsonObject(QwandaUtils.apiGet(qwandaServiceUrl+"/qwanda/baseentitys/GRP_PROJECTS/linkcodes/LNK_CORE/attributes?PRI_REALM="+$user.getRealm(), tokenString));
//         prjObj.put("aliasCode", "PROJECT");   
//         prjObj.put("token", $value);    
//         bus.publish("cmds", prjObj);
//         System.out.println("Sent Project Alias: ["+prjObj+"]");
        
//         System.out.println( "\n" + LOG_RED + "RULE TERMINATED    ::   Send ALIAS" + LOG_RESET);
//         System.out.println(LOG_YELLOW + "------------------------------------------------------------------------------------------------------------------------------------------------" + LOG_RESET);
// end

