package life.genny.rules;

import life.genny.rules.QRules;
import life.genny.qwanda.message.QEventBtnClickMessage;

rule "Select Company Role"
	when
	    rules: QRules( 	isState("BTN_SELECT_ROLE_COMPANY") &&  isState("ROLE_SELECTION") &&
						!isState("COMPANY_SELECTED") ) 	    
	 then
	    
		rules.header();
		
		/* PRI_IS_DRIVER and PRI_IS_OWNER */
		/* COMPANY representatives are freight owners */
		rules.updateBaseEntityAttribute(rules.getUser().getCode(), rules.getUser().getCode(), "PRI_IS_OWNER", "TRUE");
		rules.updateBaseEntityAttribute(rules.getUser().getCode(), rules.getUser().getCode(), "PRI_IS_DRIVER", "FALSE");

		rules.setState("COMPANY_SELECTED");
	    rules.footer();     		      
end
