package life.genny.rules;
import life.genny.rules.QRules;

/* Send ROOT */
rule "Send Root - INTERN" 
    when    
        rules: QRules(  isState("SEND_ROOT_INTERN") && 
                        isState("PRI_IS_INTERN") && 
                        !isState("LOOP_SEND_ROOT_INTERN") )
     then
     	rules.header();
        rules.setState("LOOP_SEND_ROOT_INTERN");
		
        String[] recipient = {rules.getUser().getCode()};

        /* SEND ROOT BaseEntity */
        rules.publishBaseEntityByCode("GRP_ROOT", null, null, recipient);			
        rules.setState("SENT_ROOT_INTERN");

        rules.setState("SEND_ROOT_KIDS_INTERN");
	    rules.footer();      		      
end


