package life.genny.rules;

import life.genny.rules.QRules;


rule "Ask First User Profile"
    no-loop true
	salience 5
    agenda-group "NewUserProfile"
    when
        rules: QRules( !isNewUserProfileCompleted() ) 
     then
     	rules.header();
     	rules.debug();   		
   	    String userCode = rules.getUser().getCode();
   		rules.sendSelections("GRP_USER_ROLE", "LNK_CORE", 10);
   	
  		rules.askQuestions(userCode,userCode,"QUE_NEW_USER_PROFILE_GRP");
  	  /*  Check if user is already added to the company   */
        BaseEntity company = rules.getParent(userCode, "LNK_STAFF");
        String companyCode = "";
        if(company != null)
        {
           rules.println("Company Found");
           rules.println("Company BE is  :: "+company.toString());
            companyCode = company.getCode();
         /*   rules.askQuestions(userCode, companyCode, "QUE_USER_COMPANY_GRP"); */
            
        }
        if(company == null)
        {
           rules.println("Company Not Found, Creating New Company");
           /*  Creating new base-entity Company    */
           BaseEntity newCompany = QwandaUtils.createBaseEntityByCode(QwandaUtils.getUniqueId(userCode, null, "CPY", rules.getToken()), "COMPANY", rules.getQwandaServiceUrl(), rules.getToken());
           companyCode = newCompany.getCode();
           /*  link new person to the Company    */
           Link userCompanyLink =  QwandaUtils.createLink(companyCode, userCode, "LNK_STAFF", null, (double) 1, rules.getToken());
      
        }
         rules.askQuestions(userCode, companyCode, "QUE_NEW_USER_COMPANY_GRP");

	    rules.footer();     		      
end
