package life.genny.rules;
import life.genny.rules.QRules;

/* Sends Grp / BEGS / BEG kids */
rule "Send Internmatch Application Data - EDU PROVIDER "
    when    
         rules: QRules( isState("SEND_INTERNMATCH_APPLICATION_DATA") && 
                        isState("PRI_IS_EDU_PROVIDER") && 
                        !isState("LOOP_SEND_INTERNMATCH_APPLICATION_DATA_EDU_PROVIDER") )
     then
     	rules.header();
        rules.setState("LOOP_SEND_INTERNMATCH_APPLICATION_DATA_EDU_PROVIDER");
        
        BaseEntity eduProvider = rules.getParent(rules.getUser().getCode(), "LNK_EDU");
		
		if (eduProvider == null) {
			rules.println("Edu Provider of the current user is null");
		}else{
            rules.sendEduProviderData();
            rules.setState("SENT_INTERNMATCH_APPLICATION_DATA");
        }
	    rules.footer();      		      
end
