package life.genny.rules;
import life.genny.rules.QRules;

/* Move BEG from GRP_SHORTLISTED >>> GRP_IN_PROGRESS  */
rule "In Progress Intern - Step 1"
	when
		rules: QRules( 	isState("MOVE_BEG_TO_IN_PROGRESS") && 
						isState("IN_PROGRESS_INTERN_READY") && 
						isState("BTN_IN_PROGRESS_INTERN") && 
						isState("EVENT_BTN_CLICK") && 
						!isState("LOOP_IN_PROGRESS_INTERN_STEP1")) 
	 then
	 	rules.header();
        rules.setState("LOOP_IN_PROGRESS_INTERN_STEP1");

		BaseEntity beg = rules.getAsBaseEntity("begBe");
        if(beg != null){
        	rules.moveBaseEntity(beg.getCode(), "GRP_PLACED", "GRP_IN_PROGRESS", "LNK_CORE");
        	rules.setState("MOVED_BEG_TO_IN_PROGRESS");

		}else{
			rules.println("beg is null");
		}
	 	rules.footer();      
end
