package life.genny.rules;
import life.genny.rules.QRules;

/* Move APP from GRP_SHORTLISTED >>> GRP_INTERVIEWS  */
rule "Trigger Interview Application"
	when
		rules: QRules( 	isState("BTN_INTERVIEW_APPLICATION") && 
						isState("EVENT_BTN_CLICK") && 
						!isState("LOOP_INTERVIEW_APPLICATION_STEP0")) 
	 then
	 	rules.header();
        rules.setState("LOOP_INTERVIEW_APPLICATION_STEP0");

        String applicationCode = rules.getAsString("itemCode");
		String bucketCode = rules.getAsString("hintCode");

        if(applicationCode == null){
			rules.println("applicationCode is null");
		}else if(bucketCode == null){
			rules.println("bucketCode is null");
		}else{
            rules.moveBaseEntity(applicationCode, bucketCode, "GRP_INTERVIEWS", "LNK_CORE");
        }
	 	rules.footer();      
end
