package life.genny.rules;

import life.genny.qwanda.message.QCmdMessage;
import life.genny.qwanda.message.QBulkMessage;
import life.genny.qwanda.message.QDataBaseEntityMessage;
import life.genny.qwanda.message.QEventMessage;
import life.genny.rules.QRules;
import io.vertx.core.json.JsonObject;
import java.util.List;
import java.util.ArrayList;
import life.genny.qwanda.Answer;
import life.genny.qwanda.entity.BaseEntity;
import life.genny.qwanda.entity.SearchEntity;
import life.genny.utils.VertxUtils;

rule "ProductCategoryTags"

    ruleflow-group 'ProductCategoryTags'
     when
       rules: QRules( !isState("PRODUCT_CATEGORY_TAGS"))
     then
	 rules.setDrools(drools);
     rules.header();
        rules.setState("PRODUCT_CATEGORY_TAGS");
		rules.println("Processing PRODUCT_CATEGORY_TAGS for "+rules.realm());

        SearchEntity searchBE = new SearchEntity("SBE_GET_ALL_DRIVERS","All Drivers")
  	     .addSort("PRI_CREATED","Created",SearchEntity.Sort.DESC)
  	     .addFilter("PRI_IS_SELLER",true)
  	     .setPageStart(0)
  	     .setPageSize(10000);


		QDataBaseEntityMessage msg = rules.getSearchResults(searchBE);

		Integer count = 0;
		
		for (BaseEntity be : msg.getItems()) {
			rules.println("Processing "+count+" of "+msg.getItems().length+" "+be.getCode()+" ");
			Answer ans1 = new Answer(be.getCode(),be.getCode(),"PRI_PRODUCT_CATEGORY_TAG_BITMASKED","524287");
			Answer ans2 = new Answer(be.getCode(),be.getCode(),"LNK_PRODUCT_CATEGORY_LIST_TAG",
			"[\"SEL_BDL\", \"SEL_PAR\", \"SEL_MAC2\", \"SEL_TRA1\", \"SEL_BOT\", \"SEL_TRA2\", \"SEL_VEC\", \"SEL_GEN\", \"SEL_LSK\", \"SEL_BTR\", \"SEL_TRC\", \"SEL_CRV\", \"SEL_BPT\", \"SEL_GENL\", \"SEL_PAL\", \"SEL_SCT\", \"SEL_MAC3\", \"SEL_MAC1\", \"SEL_TRA3\"]");		
			
			List<Answer> answers = new ArrayList<Answer>();
			answers.add(ans1);
			answers.add(ans2);
			rules.baseEntity.saveAnswers(answers);
			count++;
		}

     rules.footer();
end
