package life.genny.rules;

import life.genny.qwanda.message.QCmdMessage;
import life.genny.qwanda.message.QBulkMessage;
import life.genny.qwanda.message.QDataBaseEntityMessage;
import life.genny.qwanda.message.QEventMessage;
import life.genny.rules.QRules;
import io.vertx.core.json.JsonObject;
import java.util.List;
import java.util.ArrayList;
import life.genny.qwanda.entity.BaseEntity;
import life.genny.qwanda.entity.SearchEntity;
import life.genny.utils.VertxUtils;

rule "Refresh Addresses"

    ruleflow-group 'RefreshAddresses'
     when
       rules: QRules( !isState("REFRESH_ADDRESSES"))
     then
	 rules.setDrools(drools);
     rules.header();
        rules.setState("REFRESH_ADDRESSES");
		rules.println("Refreshing Person Addresses for "+rules.realm());

		rules.processAddresses(rules.realm());


     rules.footer();
end
