package life.genny.rules;

import life.genny.rules.QRules;

rule "Send Edu Provider Registration Data"
     when
        rules: QRules(  isState("PROFILE_NOT_COMPLETED") && 
						isState("PRI_IS_EDU_PROVIDER") &&
						!isState("LOOP_EDU_ROLE_CHECK") )
     then
        
        rules.header();
        
		rules.setState("LOOP_EDU_ROLE_CHECK");
     	rules.set("registration_question_grp", "QUE_EDU_PROVIDER_GRP");
     	
     	rules.sendSelections("GRP_UNI_SELECTION", "LNK_CORE", 10);
     	rules.sendSelections("GRP_DEGREE_SELECTION", "LNK_CORE", 10);
     	
     	rules.setState("SENT_REGISTRATION_DATA");
	    rules.footer();     		      
end
     	