package life.genny.rules;

import life.genny.rules.QRules;
import java.util.List;

rule "Send Host Company Registration Data"
      when
        rules: QRules( 	isState("PROFILE_NOT_COMPLETED") && 
						isState("PRI_IS_HOST_COMPANY") &&
						!isState("LOOP_HOST_COMPANY_ROLE_CHECK")  ) 
     then
        
        rules.header();
        
		rules.setState("LOOP_HOST_COMPANY_ROLE_CHECK");
     	rules.set("registration_question_grp", "QUE_HOST_COMPANY_GRP");
     	
     	rules.sendSelections("GRP_COMPANY_SELECTION", "LNK_CORE", 10);
     	
     	rules.setState("SENT_REGISTRATION_DATA");
	    rules.footer();     		      
end
     	