package life.genny.rules;

import life.genny.rules.QRules;
import life.genny.qwanda.message.QEventMessage;
import java.util.HashMap;
import java.util.Map;

rule "AuthInit"
    salience 60000
	no-loop true
    when
         m : QEventMessage( QEventMessage.getData().getCode().equals("AUTH_INIT") )
         rules: QRules(!isState("AUTHINIT") && isState("STARTED") ) 
     then    
     Map<String,Object> parms = new HashMap<String, Object>();
     parms.put("qrules",rules);
     parms.put("qevent",m);
     
        rules.startWorkflow("defaultPackage.AdamTest",parms);
        rules.setState("AUTHINIT"); 
        
         		      
end