package life.genny.rules;
import life.genny.rules.QRules;

/* Sends Grp / BEGS / BEG kids */
rule "Send Application Data - INTERN" 
    when    
         rules : QRules( isState("SEND_APPLICATION_DATA") && 
                        isState("PRI_IS_INTERN") && 
                        (isState("PROFILE_IS_COMPLETED") || isState("PRI_IS_PROFILE_COMPLETED")) && 
                        !isState("LOOP_SEND_APPLICATION_DATA_INTERN") )
     then
     	rules.header();
        rules.setState("LOOP_SEND_APPLICATION_DATA_INTERN");
        rules.sendInternApplicationData();
        
        rules.setState("SENT_APPLICATION_DATA");
	    rules.footer();      		      
end