package life.genny.rules;
import life.genny.rules.QRules;

/* Move APP from GRP_PLACED >>> GRP_IN_PROGRESS   */
rule "Trigger In Progress Application"
	when
		rules: QRules( 	isState("BTN_IN_PROGRESS_APPLICATION") && 
						isState("EVENT_BTN_CLICK") && 
						!isState("LOOP_IN_PROGRESS_APPLICATION_STEP0")) 
	 then
	 	rules.header();
        rules.setState("LOOP_IN_PROGRESS_APPLICATION_STEP0");

        String applicationCode = rules.getAsString("itemCode");
		String bucketCode = rules.getAsString("hintCode");

        if(applicationCode == null){
			rules.println("applicationCode is null");
		}else if(bucketCode == null){
			rules.println("bucketCode is null");
		}else{
            rules.moveBaseEntity(applicationCode, bucketCode, "GRP_IN_PROGRESS ", "LNK_CORE");
        }
	 	rules.footer();      
end
