package life.genny.rules;
import life.genny.rules.QRules;

rule "Trigger Internmatch Homepage Layout"
    when
        rules: QRules(  isState("TRIGGER_INTERNMATCH_HOMEPAGE_LAYOUT") && 
                        !isState("LOOP_TRIGGER_INTERNMATCH_HOMEPAGE_LAYOUT")) 
     then       
        rules.header();
        rules.setState("LOOP_TRIGGER_INTERNMATCH_HOMEPAGE_LAYOUT");

        rules.clearState("SEND_INTERNMATCH_HOMEPAGE_LAYOUT");   
        rules.setState("SEND_INTERNMATCH_HOMEPAGE_LAYOUT");
        rules.footer(); 		      
end
