package life.genny.rules;

import life.genny.rules.QRules;
import life.genny.qwanda.entity.BaseEntity;
import life.genny.utils.DateUtils;
import life.genny.utils.VertxUtils;

rule "Trigger User Is Ready"
    when
        rules: QRules(	isState("USER_IS_READY") &&
						isUserPresent() == true &&
						!isState("LOOP_USER_LOGGED_IN"))
      then
		rules.header();
		rules.setState("LOOP_USER_LOGGED_IN");
		
		rules.setState("USER_DID_LOGIN");

		rules.footer();
end
