package life.genny.rules;

import life.genny.rules.QRules;
import life.genny.qwanda.entity.BaseEntity;
import life.genny.utils.DateUtils;
import life.genny.utils.VertxUtils;

rule "User logged in"
    when
        rules: QRules(	isState("USER_DID_LOGIN") &&
						!isState("LOOP_USER_DID_LOG_IN"))
      then
		rules.header();
		rules.setState("LOOP_USER_DID_LOG_IN");
		
		BaseEntity user = rules.getUser();
		if(user != null) {

		   /* TODO: to delete once pagination is in place. NOT BEFORE */
		    VertxUtils.putObject(rules.realm(), "", "PRODUCT_HISTORY_WAS_SENT", null);


	      /*  saving user logged in date time  */
	      rules.baseEntity.saveAnswer( new Answer(user.getCode(),
	   							      user.getCode(),
	   							      "PRI_LAST_LOGIN_DATETIME", DateUtils.getCurrentUTCDateTime())
	   					  );
	   	}

		rules.setState("TRIGGER_APPLICATION_SETUP");

		rules.footer();
end
