package life.genny.rules;

import life.genny.rules.RulesUtils;
import life.genny.rules.QRules;
import life.genny.utils.VertxUtils;
import life.genny.qwanda.entity.BaseEntity;


rule "Is Logged In"

    when

        rules: QRules( isUserPresent() == true  && (!isState("IS_LOGGED_IN")) && isState("USER_CHECKED")) 

     then
        rules.header();
     	
     	
        BaseEntity user = rules.getUser();
        rules.println("user exists");
        rules.println("User "+user+" LOGGED IN"); 

  		rules.clearState("NO_USER");
  		
  		/* we mark the user as logged in */
        rules.setState("IS_LOGGED_IN");
        
        if (rules.hasRole("admin")) {
        		VertxUtils.subscribeAdmin(rules.realm(),rules.getUser().getCode());
        }
        
        rules.println("Decoded Token:"+rules.getDecodedTokenMap());
        	drools.setFocus("SendAliases");
        
		drools.setFocus("payments"); 
		
		
	    rules.footer();     		      
end
