package life.genny.rules;
import life.genny.rules.QRules;
import life.genny.qwanda.message.QEventMessage;

rule "View Host Company Profile"
    when
        m : QEventMessage(  event_type == "PROFILE" && 
                            data.code == "PROFILE")
                            
	    rules: QRules(  isState("ROLE_FOUND") &&
                        isState("PRI_IS_HOST_COMPANY") &&	
                        isState("PRI_IS_PROFILE_COMPLETED") &&	
                        !isState("LOOP_VIEW_HOST_COMPANY_PROFILE")) 	
     then
        rules.header();    
        rules.setState("LOOP_VIEW_HOST_COMPANY_PROFILE");
        
        /* send question group for USER */
		rules.set("questionSourceCode", rules.getUser().getCode());
		rules.set("questionTargetCode", rules.getUser().getCode());
		rules.set("questionGroupCode", "QUE_NEW_USER_DETAILS_GRP");
		rules.setState("SEND_QUESTION");	

        /*  Get Company Code of the current user   */
        BaseEntity company = rules.getParent(rules.getUser().getCode(), "LNK_STAFF");     

        if(company != null){
            /* send question group for COMPANY */
            rules.set("questionSourceCode", rules.getUser().getCode());
            rules.set("questionTargetCode", company.getCode());	
            rules.set("questionGroupCode", "QUE_NEW_USER_COMPANY_GRP");
            
            rules.setState("SEND_QUESTION");

            /* we send the layout */
            rules.sendSublayout("LAY_HOST_COMPANY", "registration/hostcompany.json", null, false);
            rules.footer(); 
        }else{
            rules.println("Company of the user was not found");
        }
		
		    		      
end
