package life.genny.rules;
import life.genny.rules.QRules;
import life.genny.qwanda.message.QEventMessage;

/* Send Company Details Question */
rule "View Host Company Profile Step - 2"    
    when                            
	    rules: QRules(  isState("ROLE_FOUND") &&
                        isState("PRI_IS_HOST_COMPANY") &&	
                        isState("PRI_IS_PROFILE_COMPLETED") &&	
                        isState("SENT_QUESTION") &&	
                        isState("QUE_NEW_USER_DETAILS_GRP") &&	
                        !isState("LOOP_VIEW_HOST_COMPANY_PROFILE_STEP2")) 	
     then
        rules.header();  
        rules.setState("LOOP_VIEW_HOST_COMPANY_PROFILE_STEP2");
          
         /*  Get Company Code of the current user   */
        BaseEntity company = rules.getParent(rules.getUser().getCode(), "LNK_STAFF");     

        if(company != null){
            /* send question group for COMPANY */
            rules.set("questionSourceCode", rules.getUser().getCode());
            rules.set("questionTargetCode", company.getCode());	
            rules.set("questionGroupCode", "QUE_NEW_USER_COMPANY_GRP");
            rules.setState("SEND_QUESTION");

            /* we send the layout */
            rules.set("subLayoutCode", "LAY_HOST_COMPANY");
            rules.set("subLayoutPath", "registration/hostcompany.json");	
            rules.set("subLayoutRootCode", null);
            rules.set("subLayoutIsPopup", false);
            rules.setState("SEND_SUBLAYOUT");

        }else{
            rules.println("Company of the user was not found");
        }
        rules.footer(); 
		
		    		      
end
