package life.genny.rules;

import life.genny.rules.QRules;

rule "Delete BEG - Step 2 - Channel40"
	when
		rules: QRules( isState("MOVE_BEG_TO_BIN") && !isState("DID_MOVE_JOB_TO_BIN") )
	then
	
		rules.header();

		rules.setState("DID_MOVE_JOB_TO_BIN");
		
		String begCode = rules.getAsString("itemCode");
		String groupCode = rules.getAsString("parentCode");

         if(begCode != null && begCode != null) {
        	 
	        /* if the deleted BEG was sitting in "GRP_NEW_ITEMS" we need to warn the drivers */
	        if(groupCode.equalsIgnoreCase("GRP_NEW_ITEMS") ){
		        rules.setState("SEND_MESSAGE_TO_DRIVERS");
	        }
         }  

	    rules.footer();
end
