package life.genny.rules;

import life.genny.rules.QRules;

rule "Delete BEG - Step 3 - Channel40"
	when
		rules: QRules( isState("SEND_MESSAGE_TO_DRIVERS") && !isState("DID_SEND_MESSAGE_TO_DRIVER") )
	then
	
		rules.header();

		rules.setState("DID_SEND_MESSAGE_TO_DRIVER");

		String begCode = rules.getAsString("itemCode");
		String groupCode = rules.getAsString("parentCode");

         if(begCode != null && begCode != null ){
        	 	
        	 		/* we get the current subscribers of the job */
             	String[] allBegRecipients = VertxUtils.getSubscribers(rules.realm(), begCode);
             
			   	/* we send a message to drivers saying the job was deleted */
		        HashMap<String,String> contextMap = new HashMap<String, String>();
		        contextMap.put("JOB", begCode);
		        contextMap.put("OWNER", rules.getUser().getCode());
				
		        /* Sending toast message to all the beg frontends */
		        rules.sendMessage("", allBegRecipients, contextMap, "MSG_CH40_NEW_JOB_DELETED", "TOAST");
         }     

	    rules.footer();
end
