package life.genny.rules;


import life.genny.rules.QRules;
import life.genny.qwanda.entity.BaseEntity;


rule "Send PROJECT To Frontend"
    no-loop true
    salience 770
    ruleflow-group 'SendProject'
    when
         rules: QRules( isState("ALL_ATTRIBUTES_SENT")  && (!isState("PROJECT_SENT")) )
     then
     	rules.header();
     	String projectCode = "PRJ_"+rules.getAsString("realm").toUpperCase();
     	BaseEntity project = rules.getBaseEntityByCode(projectCode);
     	rules.println("Project "+project);
     	  
        rules.publishCmd(project,"PROJECT");
   
        rules.println("PROJECT SENT TO FRONTEND");
        rules.setState("PROJECT_SENT");

		
	    rules.footer();      		      
end
