package life.genny.rules;


import life.genny.rules.QRules;
import life.genny.qwanda.entity.BaseEntity;


rule "Send PROJECT To Frontend"
    no-loop true
    salience 770
    ruleflow-group 'SendAliases'
    when
         rules: QRules( isState("IS_LOGGED_IN")  && (!isState("PROJECT_SENT")) )
     then
     	rules.header();
     	
     	BaseEntity project = rules.getBaseEntityByAttributeAndValue("PRI_REALM", rules.getAsString("realm"));
     	rules.println("Project "+project);
     	  
        rules.publishCmd(project,"PROJECT");
   
        rules.println("PROJECT SENT TO FRONTEND");
        rules.setState("PROJECT_SENT");

		
	    rules.footer();      		      
end
