package life.genny.rules;

import life.genny.rules.QRules;


rule "Send User To Frontend"
    no-loop true
    salience 780
        ruleflow-group 'SendAliases'
    when
        rules: QRules( isState("PROJECT_SENT")  && (!isState("USER_SENT")) )
     then
     	rules.header();
     	
        rules.publishCmd(rules.getUser(),"USER");
   
        rules.println("USER "+rules.getUser().getCode()+" SENT TO FRONTEND");
        rules.setState("USER_SENT");
		
	    rules.footer();     		      
end
