package life.genny.rules;

import life.genny.rules.QRules;


rule "Send User Company To Frontend"
    no-loop true
    salience 760
        ruleflow-group 'SendAliases'
    when
        rules: QRules( isState("USER_SENT")  && (!isState("USER_COMPANY_SENT")) )
     then
     	rules.header();
     	
     	String userCode = rules.getUser().getCode();
     	
     	/*  Get Company Code of the current user   */
        BaseEntity company = rules.getParent(userCode, "LNK_STAFF");
        
        if(company != null)
        {
            rules.println("Company BE is  :: "+company.toString());
            String companyCode = company.getCode();
            rules.println("The Company Code is :: "+companyCode);
            
            rules.publishCmd(company,"USER_COMPANY");
            
            rules.println("Company "+companyCode+" SENT TO FRONTEND");
        }      
		
		rules.setState("USER_COMPANY_SENT");
		
	    rules.footer();     		      
end
