package life.genny.rules;

import life.genny.rules.QRules;
import java.util.List;

rule "Selected Company Role"
     when
        $m: QEventAttributeValueChangeMessage( QEventAttributeValueChangeMessage.getData().getCode().equals("PRI_IS_OWNER") )
        rules: QRules( isState("STARTED") && !isState("HAS_SELECTED_PROFILE_COMPANY") && isState("BTN_SELECT_ROLE_COMPANY"))
     then

        rules.header();
		
        rules.setState("HAS_SELECTED_PROFILE_COMPANY");
        
        /* we create the company */
        /*BaseEntity newCompany = QwandaUtils.createBaseEntityByCode(QwandaUtils.getUniqueId(userCode, null, "CPY", rules.getToken()), "COMPANY", rules.getQwandaServiceUrl(), rules.getToken());        
        rules.createLink(companyCode, userCode, "LNK_STAFF", "REPRESENTATIVE", 1.0); */
        
     	rules.setState("TRIGGER_PROFILE_CHECK");

		rules.footer();
end
