package life.genny.rules;
import life.genny.rules.QRules;

rule "Update Education Provider Profile"
	when
	    rules: QRules( 	isState("QUE_EDU_PROVIDER_GRP") && 
						isState("EVENT_FORM_SUBMIT") && 		
						isState("PRI_IS_PROFILE_COMPLETED") && 
						!isState("LOOP_UPDATE_EDU_PROVIDER_PROFILE")) 
	 then
	 	rules.header();
        rules.setState("LOOP_UPDATE_EDU_PROVIDER_PROFILE");

		rules.setState("TRIGGER_PROFILE_CHECK");
	 	rules.footer();      
end