package life.genny.rules;
import life.genny.rules.QRules;

rule "Trigger Submit Add BEG"
	when
		rules: QRules(  isState("EVENT_FORM_SUBMIT") &&
						isState("QUE_ADD_BEG_GRP") &&
						isState("SUBMIT") &&
						!isState("LOOP_TRIGGER_SUBMIT_ADD_BEG") )
	 then
	 	rules.header();
        rules.setState("LOOP_TRIGGER_SUBMIT_ADD_BEG");
		
		rules.showLoading("Loading", true);
		
		String begCode = rules.getAsString("targetCode");
		if(begCode == null) {
			rules.setState("FAILED_CREATE_BEG");
			return;
		}
		
		BaseEntity beg = rules.baseEntity.getBaseEntityByCode(begCode);			
		if(beg == null) {
			rules.setState("FAILED_CREATE_BEG");
			return;
		}
		
		rules.set("begBe", beg);
		
		Boolean productTemplateRequired = rules.getProject().getValue("PRI_HAS_PRODUCT_TEMPLATE", false);
		if(productTemplateRequired){
			
			BaseEntity product = rules.baseEntity.getLinkedBaseEntity(beg.getCode(), "LNK_BEG", "PRODUCT"); 
			if(product == null) {
				rules.setState("FAILED_CREATE_BEG");
				return;
			}
			rules.set("productBe", product);
		}
		
		BaseEntity company = rules.baseEntity.getParent(rules.getUser().getCode(), "LNK_STAFF");
		rules.println("company in trigger submit ::"+company);
		if(company != null) {
			rules.set("companyBe", company);
		}
		
        rules.setState("LINK_BEG_AND_CREATOR");
		rules.footer();      
end