package life.genny.rules;
import life.genny.rules.QRules;

rule "Trigger Submit Add BEG"
	when
		rules: QRules(  isState("EVENT_FORM_SUBMIT") &&
						isState("QUE_ADD_BEG_GRP") &&
						isState("SUBMIT") &&
						!isState("LOOP_TRIGGER_SUBMIT_ADD_BEG") )
	 then
	 	rules.header();
        rules.setState("LOOP_TRIGGER_SUBMIT_ADD_BEG");
		
		rules.showLoading("", true);
		
		String begCode = rules.getAsString("quesTargetCode");
		if(begCode == null) {
			rules.setState("FAILED_CREATE_BEG");
			return;
		}
		
		
		BaseEntity beg = rules.baseEntity.getBaseEntityByCode(begCode);			
		if(beg == null) {
			rules.setState("FAILED_CREATE_BEG");
			return;
		}
		
		rules.set("begBe", beg);

        //BaseEntity product = rules.baseEntity.getLinkedBaseEntity(beg.getCode(), "LNK_BEG", "PRODUCT"); 
       // if(product == null) {
        //		rules.setState("FAILED_CREATE_BEG");
        //		return;
       // }
        
      //  rules.set("productBe", product);
		
		BaseEntity company = rules.baseEntity.getLinkedBaseEntity(rules.getUser().getCode(), "LNK_STAFF", "STAFF");
		if(company != null) {
			rules.set("companyBe", company);
		}
		
      //  rules.setState("COPY_PRODUCT_ATTRIBUTES_TO_BEG");
        rules.setState("LINK_BEG_AND_CREATOR"); 
		rules.footer();      
end
		
		