package life.genny.rules;
import life.genny.rules.QRules;

/* LINK BEG + USER || CREATOR */
rule "Submit Add BEG - Step 1"
	when
		rules: QRules( 	isState("LINK_BEG_AND_CREATOR") && 
						!isState("LOOP_SUBMIT_ADD_BEG_STEP1")) 
	 then
	 	rules.header();
        rules.setState("LOOP_SUBMIT_ADD_BEG_STEP1");

        BaseEntity beg = rules.getAsBaseEntity("begBe");
		if(beg == null){
			rules.setState("FAILED_CREATE_BEG");
			rules.println("beg is not in the state");
			return;
		}
        /* link BEG to USER */
		rules.set("linkSourceCode",  beg.getCode());
		rules.set("linkTargetCode", rules.getUser().getCode());
		rules.set("linkCode", "LNK_BEG");
		rules.set("linkValue", "CREATOR");
		rules.set("linkWeight", 1.0);
		rules.setState("CREATE_LINK");
		if(rules.getUserCompany() != null){
			rules.setState("LINK_BEG_AND_COMPANY");
		}else{
			rules.setState("MOVE_BEG_TO_GRP_NEW_ITEMS");
		}
		
	 	rules.footer();      
end
