package life.genny.rules;
import life.genny.rules.QRules;

/* Move BEG from GRP_DRAFTS >>> GRP_NEW_ITEMS  */
rule "Submit Add BEG - Step 3"
	when
		rules: QRules( 	isState("MOVE_BEG_TO_GRP_NEW_ITEMS") && 
						!isState("LOOP_SUBMIT_ADD_BEG_STEP3")) 
	 then
	 	rules.header();
        rules.setState("LOOP_SUBMIT_ADD_BEG_STEP3");

		BaseEntity beg = rules.getAsBaseEntity("begBe");
		rules.println("begCode is ::"+beg.getCode());
		rules.baseEntity.moveBaseEntity(beg.getCode(), "GRP_DRAFTS", "GRP_NEW_ITEMS", "LNK_CORE", "BEG");
		
		rules.setState("PUBLISH_BEG_AND_KIDS");
	 	rules.footer();      
end
