package life.genny.rules;
import life.genny.rules.QRules;
import life.genny.utils.VertxUtils;

/* Publish BEG AND KIDS */
rule "Submit Add BEG - Step 4"
	when
		rules: QRules( 	isState("PUBLISH_BEG_AND_KIDS") && 
						!isState("LOOP_SUBMIT_ADD_BEG_STEP4") ) 
	 then
	 	rules.header();
        rules.setState("LOOP_SUBMIT_ADD_BEG_STEP4");
        
        rules.setState("RELOAD_CACHE_BEG");

		/* rules.setState("EXIT_ADD_BEG_SUCCESS");  */
		
	 	rules.footer();      
end
