BEG_PE9564FF3098514C28B5D6CEACB2239AA50package life.genny.rules;
import life.genny.rules.QRules;
import life.genny.utils.VertxUtils;

/* Publish BEG AND KIDS */
rule "Submit Add BEG - Step 5 - Exit"
	when
		rules: QRules( 	isState("EXIT_ADD_BEG_SUCCESS") && 
						!isState("LOOP_EXIT_ADD_BEG_SUCCESS") ) 
	 then
	 	rules.header();
       
		rules.setState("LOOP_EXIT_ADD_BEG_SUCCESS");
		
		/* Go To Homepage */
		rules.setState("TRIGGER_HOMEPAGE");
		
	 	rules.footer();      
end
