package life.genny.rules;
import life.genny.rules.QRules;

/* Subscribe Intern to APPLICATION */
rule "Submit Apply Internship - Step 3"
	when
		rules: QRules( 	isState("SUBSCRIBE_INTERN_TO_APPLICATION") && 
						isState("LINKED_APPLICATION_TO_INTERN") && 
						isState("CREATED_LINK") && 
						isState("APPLICANT") && 
						isState("QUE_INTERNSHIP_ADDITIONAL_GRP") && 
						isState("EVENT_FORM_SUBMIT") && 
						isState("SUBMIT") && 
						!isState("LOOP_SUBMIT_APPLY_INTERNSHIP_STEP3")) 

	 then
	 	rules.header();
        rules.setState("LOOP_SUBMIT_APPLY_INTERNSHIP_STEP3");

		/* get application from state map */
        BaseEntity application = rules.getAsBaseEntity("applicationBe");

		if(application != null){
			rules.subscribeUserToBaseEntity(rules.getUser().getCode(), application.getCode());
			rules.setState("SUBSCRIBED_INTERN_TO_APPLICATION");

			rules.setState("SUBSCRIBE_HOST_COMPANY_TO_APPLICATION");
		}else{
            rules.println("application BaseEntity is null");			
		}
	 	rules.footer();      
end
