package life.genny.rules;
import life.genny.rules.QRules;

/* LINK BEG + APPLICATION || APPLICATION */
rule "Submit Apply Internship - Step 3.1"
	when
		rules: QRules(  isState("LINK_GRP_APPLIED_TO_BEG") && 
		            	isState("SUBSCRIBED_HOST_COMPANY_STAFF_TO_APPLICATION") && 
		                isState("QUE_INTERNSHIP_ADDITIONAL_GRP") && 
						isState("EVENT_FORM_SUBMIT") && 
						isState("SUBMIT") && 
						!isState("LOOP_SUBMIT_APPLY_INTERNSHIP_STEP3.1")) 
	 then
	 	rules.header();
        rules.setState("LOOP_SUBMIT_APPLY_INTERNSHIP_STEP3.1");

        BaseEntity beg = rules.getAsBaseEntity("begBe");
        
        if(beg == null){   
            rules.println("beg is null");
        }else{
            /* link GRP_APPLIED to BEG || APPLIED */
            rules.set("linkSourceCode",  "GRP_APPLIED");
            rules.set("linkTargetCode", beg.getCode());
            rules.set("linkCode", "LNK_CORE");
            rules.set("linkValue", "APPLIED");
            rules.set("linkWeight", 1.0);
            rules.setState("CREATE_LINK");

            rules.setState("LINKED_GRP_APPLIED_TO_BEG");
            rules.setState("LINK_BEG_TO_APPLICATION");
            
        }
end