package life.genny.rules;
import life.genny.rules.QRules;

/* LINK BEG + APPLICATION || APPLICATION */
rule "Submit Apply Internship - Step 4"
	when
		rules: QRules(  isState("LINK_BEG_TO_APPLICATION") && 
		            	isState("SUBSCRIBED_HOST_COMPANY_STAFF_TO_APPLICATION") && 
		                isState("QUE_INTERNSHIP_ADDITIONAL_GRP") && 
						isState("EVENT_FORM_SUBMIT") && 
						isState("SUBMIT") && 
						!isState("LOOP_SUBMIT_APPLY_INTERNSHIP_STEP4")) 
	 then
	 	rules.header();
        rules.setState("LOOP_SUBMIT_APPLY_INTERNSHIP_STEP4");

        BaseEntity application = rules.getAsBaseEntity("applicationBe");
        BaseEntity beg = rules.getAsBaseEntity("begBe");
        
        if(beg == null){   
            rules.println("beg is null");
        }else if(application == null){
            rules.println("application is null");    
        }else{

            /* link BEG to APPLICATION || APPLICATION */
            rules.set("linkSourceCode",  beg.getCode());
            rules.set("linkTargetCode", application.getCode());
            rules.set("linkCode", "LNK_BEG");
            rules.set("linkValue", "APPLICATION");
            rules.set("linkWeight", 4.0);
            rules.setState("CREATE_LINK");

            rules.setState("LINKED_BEG_TO_APPLICATION");
            rules.setState("LINK_APPLICATION_TO_INTERN");
            
        }
end