package life.genny.rules;
import life.genny.rules.QRules;

/* Subscribe Host Company to APPLICATION */
rule "Submit Apply Internship - Step 4"
	when
		rules: QRules( 	isState("SUBSCRIBE_HOST_COMPANY_TO_APPLICATION") && 
						isState("SUBSCRIBED_INTERN_TO_APPLICATION") && 
						isState("QUE_INTERNSHIP_ADDITIONAL_GRP") && 
						isState("EVENT_FORM_SUBMIT") && 
						isState("SUBMIT") && 
						!isState("LOOP_SUBMIT_APPLY_INTERNSHIP_STEP4")) 
	 then
	 	rules.header();
        rules.setState("LOOP_SUBMIT_APPLY_INTERNSHIP_STEP4");

		/* get application from state map */
        BaseEntity application = rules.getAsBaseEntity("applicationBe");

		/* Get HostCompany BaseEntity */
		BaseEntity company = rules.getAsBaseEntity("companyBe");
		
		if(application == null){
			rules.println("application BaseEntity is null");
		}else if(company == null){
			rules.println("company BaseEntity is null");
		}else{
			rules.subscribeUserToBaseEntity(company.getCode(), application.getCode());
			rules.setState("SUBSCRIBED_HOST_COMPANY_TO_APPLICATION");

			rules.setState("SUBSCRIBE_HOST_COMPANY_STAFF_TO_APPLICATION");
		}
	 	rules.footer();      
end
