// package life.genny.rules;
// import life.genny.rules.QRules;

// /* Subscribe All Staffs of Host Company to APPLICATION */
// rule "Apply Internship - Step 3.5"
// 	when
// 		rules: QRules( 	isState("SUBSCRIBE_INTERN_TO_BEG") && 
// 						isState("LINKED_BEG_TO_INTERN") && 
// 						isState("CREATED_LINK") && 
// 						isState("INTERN") && 
// 						isState("QUE_INTERNSHIP_ADDITIONAL_GRP") && 
// 						isState("EVENT_FORM_SUBMIT") && 
// 						isState("SUBMIT") && 
// 						!isState("LOOP_APPLY_INTERNSHIP_STEP3_5")) 

// 	 then
// 	 	rules.header();
//         rules.setState("LOOP_APPLY_INTERNSHIP_STEP3_5");

// 		/* Get beg BaseEntity */
// 		BaseEntity beg = rules.getAsBaseEntity("targetCode");

// 		if(beg != null){
// 			rules.subscribeUserToBaseEntity(rules.getUser().getCode(), beg.getCode());
// 			rules.setState("SUBSCRIBED_INTERN_TO_BEG");
// 			rules.setState("GO_TO_HOMEPAGE");
// 		}
// 	 	rules.footer();      
// end
