package life.genny.rules;
import life.genny.rules.QRules;

/* Subscribe STAFF of Host Company to APPLICATION */
rule "Submit Apply Internship - Step 5"
	when
		rules: QRules( 	isState("SUBSCRIBE_HOST_COMPANY_STAFF_TO_APPLICATION") && 
						isState("SUBSCRIBED_HOST_COMPANY_TO_APPLICATION") && 
						isState("QUE_INTERNSHIP_ADDITIONAL_GRP") && 
						isState("EVENT_FORM_SUBMIT") && 
						isState("SUBMIT") && 
						!isState("LOOP_SUBMIT_APPLY_INTERNSHIP_STEP5")) 
	 then
	 	rules.header();
        rules.setState("LOOP_SUBMIT_APPLY_INTERNSHIP_STEP5");

		/* Get company & application BaseEntity */
		BaseEntity company = rules.getAsBaseEntity("companyBe");
		BaseEntity application = rules.getAsBaseEntity("applicationBe");

        if(company != null){
		    BaseEntity companyStaff = rules.getChildren(company.getCode(), "LNK_STAFF", "STAFF");
            if(companyStaff != null){
                rules.subscribeUserToBaseEntity(companyStaff.getCode(), application.getCode());
                rules.setState("SUBSCRIBED_HOST_COMPANY_STAFF_TO_APPLICATION");
                
                rules.setState("PUBLISH_APPLICATION");
            }else{
                rules.println("No staff found for company");
            }
        }else{
            rules.println("company is null");
        }
	 	rules.footer();      
end
