package life.genny.rules;
import life.genny.rules.QRules;

/* Subscribe Intern to BEG */
rule "Submit Apply Internship - Step 6"
	when
		rules: QRules( 	isState("GO_TO_HOMEPAGE") && 
						isState("QUE_INTERNSHIP_ADDITIONAL_GRP") && 
						isState("EVENT_FORM_SUBMIT") && 
						isState("SUBMIT") && 
						!isState("LOOP_SUBMIT_APPLY_INTERNSHIP_STEP6")) 

	 then
	 	rules.header();
        rules.setState("LOOP_SUBMIT_APPLY_INTERNSHIP_STEP6");

        rules.setState("TRIGGER_HOME_PAGE");

 		rules.setState("SUBMITTED_APPLICATION_FOR_INTERNSHIP");
	 	rules.footer();      
end
