package life.genny.rules;
import life.genny.rules.QRules;

rule "Submit BEG Data"
	when
	    rules: QRules( 	isState("QUE_EDIT_BEG_GRP") && 
						isState("EVENT_FORM_SUBMIT") && 		
						!isState("LOOP_UPDATE_BEG_DATA")) 
	 then
	 	rules.header();
    rules.setState("LOOP_UPDATE_BEG_DATA");

    String begCode = rules.getAsString("targetCode");

    if(begCode != null){
      BaseEntity beg = rules.baseEntity.getBaseEntityByCode(begCode);
      rules.set("begBe", beg);
    }else{
      rules.println("beg is null");
    }

		rules.setState("TRIGGER_VIEW_BEG");
	 	rules.footer();      
end
