package life.genny.rules;

import life.genny.rules.QRules;
import life.genny.qwanda.entity.BaseEntity;

import io.vertx.core.json.JsonObject;

rule "Send DropDown Datas"
   agenda-group "CreateLoad"
   no-loop true
   when
     rules: QRules()
   then
    rules.header();
     
     String userCode =  rules.getUser().getCode();
     System.out.println("The user Code is  ::  " +userCode);

   /* Get the users Company Code  */
    BaseEntity company =  rules.getParent(userCode,"LNK_STAFF");
    System.out.println("The users company code is  ::   " +company.getCode());
   
   /*      Getting list of loads      */
    rules.sendSelections("GRP_LOADS", "LNK_"+company.getCode(), 100);

   /*   Getting list of the load category   */
    rules.sendSelections("GRP_LOAD_CATEGORY", "LNK_CORE", 20);
     
 	rules.footer();
  
end
