package life.genny.rules;

import life.genny.rules.RulesUtils;
import life.genny.rules.QRules;
import life.genny.qwandautils.QwandaUtils;
import life.genny.qwandautils.MergeUtil;
import life.genny.qwanda.Answer;
import life.genny.qwanda.message.QEventAttributeValueChangeMessage;
import life.genny.qwanda.entity.BaseEntity;
import java.lang.Double;
import java.lang.String;
import java.math.BigDecimal;

import org.javamoney.moneta.Money;
import javax.money.CurrencyUnit;
import javax.money.Monetary;

function Double calculate(String price) {

	Double ownerOriginalPrice = Double.parseDouble(price);
    return ownerOriginalPrice;
}

/*  Calculate Load Price adding service fee  */
rule "Calculate Load Price"
	no-loop true
    when
    	$m: QEventAttributeValueChangeMessage(  QEventAttributeValueChangeMessage.getData().getCode().equals("PRI_PRICE")  && getAnswer().getTargetCode().startsWith("BEG_") || 
												QEventAttributeValueChangeMessage.getData().getCode().equals("PRI_OFFER_PRICE")  && getAnswer().getTargetCode().startsWith("OFR_") )
    	rules : QRules()
    then    
		rules.header();

		Answer newAnswer = $m.getAnswer();
		
		/* BaseEntity Code */
			String beCode = newAnswer.getTargetCode();
		
		/* Price recieved as an answer */
					
			
			CurrencyUnit DEFAULT_CURRENCY_AUD = Monetary.getCurrency("AUD");		
			Money answerPrice = Money.of(Integer.parseInt(newAnswer.getValue()), DEFAULT_CURRENCY_AUD);


		/* Price attributeCode and Other price atrributeCode generation */
			String priceCode = $m.getData().getCode();			
			String ownerPriceIncGstCode = priceCode.replace("_PRICE", "_OWNER_PRICE_INC_GST");
			String ownerPriceExcGstCode = priceCode.replace("_PRICE", "_OWNER_PRICE_EXC_GST");
			String driverPriceIncGstCode = priceCode.replace("_PRICE", "_DRIVER_PRICE_INC_GST");
			String driverPriceExcGstCode = priceCode.replace("_PRICE", "_DRIVER_PRICE_EXC_GST");
			String feePriceIncGstCode = priceCode.replace("_PRICE", "_FEE_INC_GST");
			String feePriceExcGstCode = priceCode.replace("_PRICE", "_FEE_EXC_GST");
		
			Money ownerPriceExcGST = Money.of(0, DEFAULT_CURRENCY_AUD);
			Money ownerPriceIncGST = Money.of(0, DEFAULT_CURRENCY_AUD);
			Money driverPriceExcGST = Money.of(0, DEFAULT_CURRENCY_AUD);
			Money driverPriceIncGST = Money.of(0, DEFAULT_CURRENCY_AUD);

			Money fees = Money.of(0, DEFAULT_CURRENCY_AUD);
			Money feePriceExcGST = Money.of(0, DEFAULT_CURRENCY_AUD);
			Money feePriceIncGST = Money.of(0, DEFAULT_CURRENCY_AUD);

		/* Get userRole */
			String userRole = null;
			if(newAnswer.getTargetCode().startsWith("OFR_")) {			
				String offerCode = newAnswer.getTargetCode();
				userRole = rules.getBaseEntityValueAsString(offerCode, "PRI_NEXT_ACTION");
			}

			System.out.println(" targetCode " + newAnswer.getTargetCode() );
			System.out.println(" userRole " + userRole );

		if( newAnswer.getTargetCode().startsWith("BEG_") || ( newAnswer.getTargetCode().startsWith("OFR_") && userRole != null && userRole.equals("OWNER")) ) {

			/* Owner Fees */
			fees = rules.calcOwnerFeeInMoney( answerPrice );		
			feePriceExcGST = fees;
			feePriceIncGST = rules.includeGSTMoney(fees);

			System.out.println("=======================================================================================================");
			System.out.println("OWNER countering   ::   ");
			System.out.println(" targetCode" +newAnswer.getTargetCode() );
			ownerPriceExcGST = answerPrice;
			ownerPriceIncGST = rules.includeGSTMoney(answerPrice);
			driverPriceIncGST = ownerPriceIncGST.subtract(feePriceIncGST);
			driverPriceExcGST = ownerPriceExcGST.subtract(feePriceExcGST);
			System.out.println("ownerPriceExcGST   ::   " + ownerPriceExcGST);
			System.out.println("ownerPriceIncGST   ::   " + ownerPriceIncGST);
			System.out.println("driverPriceIncGST   ::   " + driverPriceIncGST);
			System.out.println("driverPriceExcGST   ::   " + driverPriceExcGST);
			System.out.println("=======================================================================================================");
		}
		else if(newAnswer.getTargetCode().startsWith("OFR_") && (userRole == null || userRole.equals("QUOTER"))) {

			/* Driver Fees */
			fees = rules.calcDriverFeeInMoney( answerPrice );		
			feePriceExcGST = fees;
			feePriceIncGST = rules.includeGSTMoney(fees);

			System.out.println("=======================================================================================================");
			System.out.println("QUOTER countering   ::   ");
			driverPriceExcGST = answerPrice;
			driverPriceIncGST = rules.includeGSTMoney(answerPrice);
			ownerPriceExcGST = driverPriceExcGST.add(feePriceExcGST);
			ownerPriceIncGST = rules.includeGSTMoney(ownerPriceExcGST);

			System.out.println("ownerPriceExcGST   ::   " + ownerPriceExcGST);
			System.out.println("ownerPriceIncGST   ::   " + ownerPriceIncGST);
			System.out.println("driverPriceIncGST   ::   " + driverPriceIncGST);
			System.out.println("driverPriceExcGST   ::   " + driverPriceExcGST);
			System.out.println("=======================================================================================================");
		}


		/* Saving  OWNER_PRICE_INC_GST */
			Answer ownerPriceIncGSTAnswer = new Answer(rules.getUser().getCode(), beCode, ownerPriceIncGstCode, String.valueOf(ownerPriceIncGST));          
			rules.publishData(ownerPriceIncGSTAnswer);   

		/* Saving  OWNER_PRICE_EXC_GST */
			Answer ownerPriceExcGSTAnswer = new Answer(rules.getUser().getCode(), beCode, ownerPriceExcGstCode, String.valueOf(ownerPriceExcGST));          
			rules.publishData(ownerPriceExcGSTAnswer); 

		/* Saving  DRIVER_PRICE_INC_GST */
			Answer driverPriceIncGSTAnswer = new Answer(rules.getUser().getCode(), beCode, driverPriceIncGstCode, String.valueOf(driverPriceIncGST));          
			rules.publishData(driverPriceIncGSTAnswer);   

		/* Saving  DRIVER_PRICE_EXC_GST */
			Answer driverPriceExcGSTAnswer = new Answer(rules.getUser().getCode(), beCode, driverPriceExcGstCode, String.valueOf(driverPriceExcGST));          
			rules.publishData(driverPriceExcGSTAnswer); 

		/* Saving  FEE_INC_GST */
			Answer feePriceIncGstCodeAnswer = new Answer(rules.getUser().getCode(), beCode, feePriceIncGstCode, String.valueOf(feePriceIncGST));          
			rules.publishData(feePriceIncGstCodeAnswer);   
			
		/* Saving  FEE_EXC_GST */
			Answer feePriceExcGstCodeAnswer = new Answer(rules.getUser().getCode(), beCode, feePriceExcGstCode, String.valueOf(feePriceExcGST));          
			rules.publishData(feePriceExcGstCodeAnswer); 

		rules.footer();
end