package life.genny.rules;

import life.genny.rules.QRules;
import life.genny.qwanda.entity.BaseEntity;
import life.genny.qwandautils.KeycloakUtils;
import life.genny.qwanda.message.QEventMessage;
import io.vertx.core.json.JsonObject;

rule "Locate driver in job"

    when
	    $m : QEventMessage( event_type == "BTN_CLICK" && data.code == "BTN_LOCATE_DRIVER" )
	    rules: QRules(!isState("LOCATE_DRIVER"))
     then     
     	
     	rules.header();
	    	rules.setState("LOCATE_DRIVER");
	    	
	  
	    	    	
	    	rules.footer();       		      
end
