package life.genny.rules;

import life.genny.rules.QRules;
import life.genny.qwanda.entity.BaseEntity;
import java.util.List;

/* Sends BEGs */
rule "Send Groups"
    when
        rules: QRules(  isState("SEND_GROUPS") &&  
                        !isState("LOOP_SEND_CONTACT_GROUPS") )
     then
     	rules.header();
     	rules.setState("LOOP_SEND_CONTACT_GROUPS");
        
        /* Get GROUPS from map */
        List<String> groupList = (List<String>)(List<?>)rules.getAsList("beList");
        List<BaseEntity> members = null;
        
        for(String group: groupList) {  
        	
        		rules.println("PUSHING : " + group);
            
        		List<BaseEntity> newMembers = rules.getBaseEntitysByParentAndLinkCode(group, "LNK_CORE", 0, 500, false);
            members.addAll(newMembers);
            
            /* send members of a particular group */
            rules.publishCmd(members, group, "LNK_CORE");

        }
        rules.setState("SENT_GROUPS");		
	    rules.footer();     		      
end


       
