package life.genny.rules;

import life.genny.rules.QRules;
import life.genny.qwanda.entity.BaseEntity;
import java.util.List;

/* Sends Contacts */
rule "Send Contacts"
    when
        rules: QRules(  isState("SENT_ROOT") && 
                        isState("SEND_CONTACTS") && 
                        isState("SENT_BUCKETS") && 
                        !isState("LOOP_SEND_CONTACTS") )
     then
     	rules.header();
     	rules.setState("LOOP_SEND_CONTACTS");
     	rules.clearState("PUBLISHED_BASE_ENTITY_LIST");
        
        rules.set("beParentCode", "GRP_CONTACTS");                    
        rules.set("beLinkCode", "LNK_CORE");
        rules.set("bePageStart", 0);
        rules.set("bePageSize", 20);
        rules.set("beCache", false);
        
        rules.clearState("LOOP_PUBLISH_BASE_ENTITY_LIST");
        rules.setState("PUBLISH_BASE_ENTITY_LIST");
        
        rules.setState("SENT_CONTACTS");		
        rules.setState("SEND_GROUPS");		
	    rules.footer();     		      
end

       


       