package life.genny.rules;
import life.genny.rules.QRules;

rule "Check If Mandatory Questions are Answered - BUYER"
    when
	    rules: QRules( isState("CHECK_USER_PROFILE_COMPLETED") && 
				   	   isState("PRI_IS_BUYER") && 
	    			   !isState("LOOP_CHECK_USER_PROFILE_COMPLETED") )
     then
     	rules.header();
		rules.setState("LOOP_CHECK_USER_PROFILE_COMPLETED");
		
		/* we check if the user has answered the mandatory questions */
		Boolean hasAnsweredProfileQuestions = rules.isMandatoryFieldsEntered(rules.getUser().getCode(), "QUE_BUYER_GRP");
		if(hasAnsweredProfileQuestions) {
			rules.setState("USER_PROFILE_ANSWERED");
		}
		else {
			rules.setState("USER_DID_NOT_COMPLETE_PROFILE");
			rules.setState("PROFILE_NOT_COMPLETED");
		}
	    rules.footer();
end
