package life.genny.rules;

import life.genny.qwanda.message.QEventMessage;
import life.genny.qwanda.message.QCmdMessage;
import life.genny.rules.QRules;


rule "TV_SELECT Individual Chat Message"
	   no-loop true
       ruleflow-group 'TV_SELECT'
       salience 6
     when
       rules: QRules( isState("STARTED") && isState("EVENT_TV_SELECT") && 
                       get("tvSelectValue").toString().startsWith("CHT_") && !isState("TV_CHAT_ITEM_DATA_SENT") ) 
     then

     rules.header();
     
	     rules.setState("TV_CHAT_ITEM_DATA_SENT");
         rules.setState("TV_SELECT_RULE_EXECUTED"); /* Need to set this state compulsarily as the default rule
         												 executes based on this state */
         String grpCode = rules.get("tvSelectValue").toString();
         rules.println("The chat code is :: "+grpCode);
         rules.sendChatMessages(grpCode, 0, 10000);
  		 rules.sendCmdSplitView("GRP_MESSAGES", grpCode);

     rules.footer();
end
