package life.genny.rules;

import life.genny.qwanda.message.QEventMessage;
import life.genny.qwanda.message.QCmdMessage;
import life.genny.rules.QRules;


rule "TV_SELECT Chat Messages"
	   no-loop true
       ruleflow-group 'TV_SELECT'
       salience 4
     when
       rules: QRules( isState("STARTED") && isState("EVENT_TV_SELECT") && 
                       isState("GRP_MESSAGES") && !isState("TV_ITEM_MESSAGES_DATA_SENT")) 
     then

     rules.header();
     
	     rules.setState("TV_ITEM_MESSAGES_DATA_SENT");
         rules.setState("TV_SELECT_RULE_EXECUTED");  /* Need to set this state compulsarily as the default rule
         												 executes based on this state */
	     rules.sendAllChats(0,1000);
	     rules.sendCmdSplitView(rules.get("tvSelectValue").toString(), null);

     rules.footer();
end
