package life.genny.rules;

import life.genny.qwanda.message.QEventMessage;
import life.genny.rules.QRules;


import life.genny.qwanda.message.QEventMessage;

rule "Expand TreeView Item"

    when
        $m : QEventMessage( event_type == "EVT_MSG" && data.code == "TV_EXPAND")
        rules: QRules( ) 
     then
     	
    rules.header();
     
       /*      Getting list of loads      */
    rules.sendSelections($m.getData().getValue(), "LNK_CORE", 100);
     

	  rules.footer();       		      
end
