package life.genny.rules;

import life.genny.qwanda.message.QEventMessage;
import life.genny.rules.QRules;


rule "TV_SELECT Messages Event"
     when
       $m : QEventMessage( event_type == "TV_SELECT" && data.value == "GRP_MESSAGES")
       rules: QRules()
     then

     rules.header();

     rules.sendSublayout("messages-layout", "messages-layout.json");
     rules.sendSelections($m.getData().getValue(), "LNK_CORE", rules.getUser().getCode(), 200);

     rules.footer();
end
