package life.genny.rules;

import life.genny.qwanda.message.QEventMessage;
import life.genny.rules.QRules;


rule "TV_SELECT event handling"
     when
       $m : QEventMessage( event_type == "TV_SELECT" && !getData().getValue().equals("GRP_DASHBOARD") 
                                                     && !getData().getValue().equals("GRP_REPORTS") 
                                                     && data.value != "GRP_MESSAGES"
                                                     && !data.value.startsWith("GRP_REPORTS_"))
       rules: QRules( !isState("TV_SELECT_HANDLED") )
     then

     rules.header();

     rules.setState("TV_SELECT_HANDLED");

     String code = $m.getData().getValue();
     if(code != null) {
        rules.sendViewCmd("LIST_VIEW", code);
        rules.setLastLayout( "LIST_VIEW", code );
     }

     rules.footer();
end
