package life.genny.rules;

import life.genny.qwanda.message.QCmdMessage;
import life.genny.qwanda.message.QEventMessage;
import life.genny.rules.QRules;
import io.vertx.core.json.JsonObject;

rule "TV_SELECT Event Default"
     no-loop true
     ruleflow-group 'TV_SELECT'
     salience 1
     when
       rules: QRules(isState("STARTED") && isState("EVENT_TV_SELECT") && !isState("TV_SELECT_RULE_EXECUTED") 
                       && !isState("TV_SELECT_DEFAULT"))
     then
     
       rules.header();
       
         rules.setState("TV_SELECT_DEFAULT");
       	 //String grpCode = $m.getData().getValue();
       	 String grpCode = rules.get("tvSelectValue").toString();
       	 rules.println("The group code is :: "+grpCode);
       	 if(grpCode != null){         
	        	/* sending cmd LIST_VIEW */
	        	 rules.publishViewCmdMessage("LIST_VIEW", grpCode);
	     }
        else{
            rules.println("Error!! The group code is null");
        }

     rules.footer();
end
