package life.genny.rules;

import life.genny.rules.QRules;

rule "TV_SELECT Event Default"
     no-loop true
     ruleflow-group 'TV_SELECT'
     salience 1
     when
       rules: QRules(isState("STARTED") && isState("EVENT_TV_SELECT") && !isState("TV_SELECT_RULE_EXECUTED") 
                       && !isState("TV_SELECT_DEFAULT"))
     then
     
       rules.header();
       
         rules.setState("TV_SELECT_DEFAULT");
       	 Object grpCodeObj = rules.get("tvSelectValue");
       	 
       	 if(grpCodeObj != null){  
       	     String grpCode = grpCodeObj.toString();
       	     if(grpCode != null && !grpCode.isEmpty()){     
		        	 /* sending cmd LIST_VIEW */
		        	 rules.publishViewCmdMessage("LIST_VIEW", grpCode);
	        	 }
	     }
        else{
            rules.println("Error!! The group code is null");
        }

     rules.footer();
end
