package life.genny.rules;

import life.genny.qwanda.message.QCmdMessage;
import life.genny.qwanda.message.QEventMessage;
import life.genny.qwanda.message.QDataBaseEntityMessage;
import life.genny.qwanda.Layout;
import life.genny.rules.QRules;
import io.vertx.core.json.JsonObject;
import java.util.List;
import java.util.ArrayList;
import life.genny.qwanda.entity.BaseEntity;

rule "TV_SELECT Event - Generate Report"
	   no-loop true
       ruleflow-group 'TV_SELECT'
       salience 5
     when
       rules: QRules( isState("STARTED") && isState("EVENT_TV_SELECT") && 
                       ( isState("GRP_REPORTS") || get("tvSelectValue").toString().startsWith("GRP_REPORTS") ) && 
                       !isState("REPORTS_LAYOUT_SENT") ) 
     then

     rules.header();
     
        rules.setState("TV_SELECT_RULE_EXECUTED"); /* Need to set this state compulsarily as the default rule
         												 executes based on this state */
        rules.setState("REPORTS_LAYOUT_SENT");
   	    rules.generateReport(rules.get("tvSelectValue").toString());

     rules.footer();
end
