package life.genny.rules;


import java.util.Arrays;

import io.vertx.core.json.JsonObject;
import life.genny.rules.QRules;

rule "TV_SELECT Event - Select Company"
	   no-loop true
       ruleflow-group 'TV_SELECT'
       salience 6
     when
       rules: QRules( isState("STARTED") && isState("EVENT_TV_SELECT") &&
                       ( isState("GRP_COMPANY_SETTINGS")) &&
                       !isState("COMPANY_SETTINGS_LAYOUT") )
     then

      rules.header();

        rules.setState("TV_SELECT_RULE_EXECUTED"); /* Need to set this state compulsarily as the default rule
         												 executes based on this state */
        rules.setState("COMPANY_SETTINGS_LAYOUT");

        /* WE DO NOTHING FOR NOW */
		

     rules.footer();
end
