package life.genny.rules;
import life.genny.rules.QRules;

rule "Trigger Activate Application"
	when
		rules: QRules(  isState("EVENT_BTN_CLICK") &&
						isState("BTN_ACTIVATE_APPLICATION") && 
						!isState("LOOP_TRIGGER_ACTIVATE_APPLICATION")) 
	 then
	 	rules.header();
		rules.setState("LOOP_TRIGGER_ACTIVATE_APPLICATION");
		
	   	String applicationCode = rules.getAsString("itemCode");
		if(applicationCode != null){
			rules.baseEntity.saveAnswer( new Answer( rules.getUser().getCode(), applicationCode, "PRI_IS_DEACTIVATED", "FALSE" ) );
            rules.baseEntity.updateBaseEntityStatus(applicationCode, rules.getUser().getCode(), "orange");            

			rules.setState("APPLICATION_IS_ACTIVATED");
		}else{
			rules.println("applicationCode is null");
		}
	 	rules.footer();      
end
