package life.genny.rules;
import life.genny.rules.QRules;

rule "Add Note - STEP 3"
	when
		rules: QRules(  isState("ASK_NOTE_QUESTION") &&
						!isState("LOOP_ASK_NOTE_QUESTION")) 
	 then
	 	rules.header();
		rules.setState("LOOP_ASK_NOTE_QUESTION");
		
		BaseEntity note = rules.getAsBaseEntity("noteBe");
		if(note != null){
			rules.set("questionSourceCode", rules.getUser().getCode());
            rules.set("questionTargetCode", note.getCode());
            rules.set("questionGroupCode", "QUE_ADD_NOTE_GRP");
            rules.set("questionIsPopup", true);
            rules.setState("ASK_QUESTION");
		}else{
			rules.println("note is null");
		}
	 	rules.footer();      
end
