
import life.genny.rules.QRules;
import life.genny.qwanda.entity.BaseEntity;
import life.genny.qwanda.message.QEventMessage;
import life.genny.rules.RulesUtils;
import java.util.HashMap;
import life.genny.qwandautils.QwandaUtils;

rule "Geofence Exit Pickup Point"
	when
	  $m : QEventMessage( event_type == "GEOFENCE_EXIT" && data.code.contains("PICKUP"))
	  rules: QRules()
	then
    
		RulesUtils.header(drools.getRule().getName());
  
		String begCode = $m.data.getCode();
		String action = $m.data.getValue();
		
		RulesUtils.println("---- ACTION ----");
		RulesUtils.println("EXITED PICKUP POINT");
		
		rules.moveBaseEntity(begCode, "GRP_APPROVED", "GRP_IN_TRANSIT", "LNK_CORE");
		
		RulesUtils.footer(drools.getRule().getName());

end
