package life.genny.rules;

import life.genny.rules.QRules;


rule "Is Mobile Verification Completed"
    when
        rules: QRules( isState("IS_LOGGED_IN") && isState("NEW_USER_PROFILE_COMPLETION_CHECKED") && !isState("MOBILE_VERIFICATION_COMPLETED") &&  !isState("NEW_USER_CREATED") ) 
     then
     	rules.header();
   	    String userCode = rules.getUser().getCode();
   	    rules.println("The isMobileVerificationCompleted status is:: "+rules.isMobileVerificationCompleted() );
   	    if( rules.isMobileVerificationCompleted() ){
   	       rules.setState("MOBILE_VERIFICATION_COMPLETED");
   	    }else{
  		 /* Send Account Verification Layout  */
  		  rules.println("Sending Passcode View");
  		  if(rules.isState("EVENT_AUTH_INIT")){
  		       rules.sendLayout("LAY_FULL_SCREEN", "initial-profile-update.json");
  		  }
  	      rules.sendSublayout("SUB_LAY_PASSCODE_VERIFICATION", "confirm-mobile-code.json");
  		  rules.println("Passcode View Sent");
   	    }
	    
  		
	    rules.footer();
end
