import life.genny.qwanda.message.QEventMessage;
import life.genny.qwanda.message.QCmdMessage;
import io.vertx.rxjava.core.eventbus.EventBus;
import com.google.gson.Gson;



rule "Layout 3"
    when
       m : QEventMessage (data.code == "layout3")
       bus: EventBus()
    then
        QCmdMessage cmd = new QCmdMessage("CMD_LAYOUT","layout3");
        Gson gson = new Gson();
        String json = gson.toJson(cmd);
        System.out.println(json);
        bus.publish("cmds", json);        
        System.out.println(m.getData().getCode());
end

