package life.genny.rules;
import life.genny.rules.RulesUtils;
import life.genny.rules.QRules;
import life.genny.qwandautils.QwandaUtils;
import life.genny.qwandautils.MergeUtil;
import life.genny.qwanda.Answer;
import life.genny.qwanda.message.QEventAttributeValueChangeMessage;
import life.genny.qwanda.entity.BaseEntity;
import java.lang.Double;
import java.lang.String;
import java.math.BigDecimal;
import org.javamoney.moneta.Money;
import javax.money.CurrencyUnit;
import javax.money.Monetary;
import org.json.simple.JSONObject;
import java.util.ArrayList;

rule "Calculate Price for Driver"
    no-loop true
    when
        $m: QEventAttributeValueChangeMessage( QEventAttributeValueChangeMessage.getData().getCode().equals("PRI_OFFER_DRIVER_PRICE_EXC_GST")  && getAnswer().getTargetCode().startsWith("OFR_") )
        rules : QRules( isState("STARTED") && !isState("CALCULATE_DRIVER_PRICE") )
    then    
    
        rules.header();
        rules.setState("CALCULATE_DRIVER_PRICE");
        
        if(rules.getUser() != null && rules.getUser().is("PRI_DRIVER")) {
        		
        		String tokenString = rules.getToken();
            Answer newAnswer = $m.getAnswer();
            /* BaseEntity Code */
                String begCode = newAnswer.getTargetCode();
            /* Get JSON */
                JSONObject moneyJson = JsonUtils.fromJson(newAnswer.getValue(), JSONObject.class);
            /* Get amount and currency */
                String amount = QwandaUtils.getAmountAsString(newAnswer.getValue());
                String currency = QwandaUtils.getCurrencyAsString(newAnswer.getValue());    
            /* Generate CURRENCY and amount in Double */
                Double amountValue = Double.parseDouble(amount);
                CurrencyUnit DEFAULT_CURRENCY = Monetary.getCurrency(currency);     
            /* Generate price in Money Type */      
                Money answerPrice = Money.of(amountValue, DEFAULT_CURRENCY);
            /* check if target is an OFFER  */
                Boolean isOffer = newAnswer.getTargetCode().startsWith("OFR_");
            /* Price attributeCodes */  
                String ownerPriceIncGstCode = "PRI_OFFER_OWNER_PRICE_INC_GST";
                String ownerPriceExcGstCode = "PRI_OFFER_OWNER_PRICE_EXC_GST";
                String driverPriceIncGstCode = "PRI_OFFER_DRIVER_PRICE_INC_GST";
                String driverPriceExcGstCode = "PRI_OFFER_DRIVER_PRICE_EXC_GST";
                String feePriceIncGstCode = "PRI_OFFER_FEE_INC_GST";
                String feePriceExcGstCode = "PRI_OFFER_FEE_EXC_GST";
            
                Money ownerPriceExcGST = Money.of(0, DEFAULT_CURRENCY);
                Money ownerPriceIncGST = Money.of(0, DEFAULT_CURRENCY);
                Money driverPriceExcGST = Money.of(0, DEFAULT_CURRENCY);
                Money driverPriceIncGST = Money.of(0, DEFAULT_CURRENCY);
                Money fees = Money.of(0, DEFAULT_CURRENCY);
                Money feePriceExcGST = Money.of(0, DEFAULT_CURRENCY);
                Money feePriceIncGST = Money.of(0, DEFAULT_CURRENCY);
            /* Get userRole */
                String userRole = null;
                if(isOffer) {           
                    String offerCode = newAnswer.getTargetCode();
                    System.out.println(" offerCode BE "+ offerCode);
                    userRole = MergeUtil.getAttrValue(offerCode, "PRI_NEXT_ACTION", tokenString);
                }
                System.out.println("targetCode   ::   " + newAnswer.getTargetCode() );
                System.out.println("userRole     ::    " + userRole );
            
            /* Check if the amount is  not null or not negative */  
                if( amountValue != null && amountValue >= 0){
                    if( newAnswer.getTargetCode().startsWith("OFR_") && (userRole == null || userRole.equals("QUOTER"))) {
                         
                         /* Driver Fees */
					   	fees = rules.calcDriverFee( answerPrice );       
			   			if(answerPrice.compareTo(Money.of(300, DEFAULT_CURRENCY)) > 0) {
							if(fees.compareTo(Money.of(100, DEFAULT_CURRENCY)) < 0) {
						     	fees = Money.of(100, DEFAULT_CURRENCY);
						     }
			  			}
			
			            feePriceExcGST = fees;
			            feePriceIncGST = rules.includeGSTMoney(feePriceExcGST);
            
                        driverPriceExcGST = answerPrice;
                        driverPriceIncGST = rules.includeGSTMoney(answerPrice);
                        ownerPriceExcGST = driverPriceExcGST.add(feePriceExcGST);
                        ownerPriceIncGST = rules.includeGSTMoney(ownerPriceExcGST);
                        System.out.println("=======================================================================================================");
                        System.out.println("QUOTER quoting     ::   ");
                        System.out.println("targetCode         ::   " +newAnswer.getTargetCode() );
                        System.out.println("ownerPriceExcGST   ::   " + ownerPriceExcGST);
                        System.out.println("ownerPriceIncGST   ::   " + ownerPriceIncGST);
                        System.out.println("driverPriceIncGST  ::   " + driverPriceIncGST);
                        System.out.println("driverPriceExcGST  ::   " + driverPriceExcGST);
                        System.out.println("=======================================================================================================");
                        /* Get amount values in String */
                            String ownerPriceIncGSTString = QwandaUtils.getMoneyString(ownerPriceIncGST);
                            String ownerPriceExcGSTString = QwandaUtils.getMoneyString(ownerPriceExcGST);
                            String driverPriceIncGSTString = QwandaUtils.getMoneyString(driverPriceIncGST);
                            String driverPriceExcGSTString = QwandaUtils.getMoneyString(driverPriceExcGST);
                            String feePriceIncGSTString = QwandaUtils.getMoneyString(feePriceIncGST);
                            String feePriceExcGSTString = QwandaUtils.getMoneyString(feePriceExcGST);
                            
                            /* Save PRICES as Answer */
                            List<Answer> answers = new ArrayList<Answer>();
                            answers.add(new Answer(rules.getUser().getCode(), begCode, ownerPriceIncGstCode, ownerPriceIncGSTString));
                            answers.add(new Answer(rules.getUser().getCode(), begCode, ownerPriceExcGstCode, ownerPriceExcGSTString));
                            answers.add(new Answer(rules.getUser().getCode(), begCode, driverPriceIncGstCode, driverPriceIncGSTString));
                            answers.add(new Answer(rules.getUser().getCode(), begCode, driverPriceExcGstCode, driverPriceExcGSTString));
                            answers.add(new Answer(rules.getUser().getCode(), begCode, feePriceIncGstCode, feePriceIncGSTString));
                            answers.add(new Answer(rules.getUser().getCode(), begCode, feePriceExcGstCode, feePriceExcGSTString));
                            rules.saveAnswers(answers);
                    }
                }
        }

        rules.footer();
end