package life.genny.rules;

import life.genny.rules.RulesUtils;
import life.genny.rules.QRules;

import life.genny.qwanda.Answer;
import life.genny.qwanda.message.QEventAttributeValueChangeMessage;

import life.genny.qwanda.entity.BaseEntity;
 

rule "Load Description Attribute Change"
/*  Update Jobs description based on Loadss desc value change  */

    when
      $m: QEventAttributeValueChangeMessage( QEventAttributeValueChangeMessage.getData().getCode().equals("PRI_DESCRIPTION") && getAnswer().getTargetCode().startsWith("LOD_") )
      rules : QRules( isState("STARTED") &&  !isState("LD_DESC_CHG"))
    then    
	     rules.header();  
	    rules.setState("LD_DESC_CHG");
	    
        /*     Collect load code from answer    */
         Answer newAnswer = $m.getAnswer();
         
         RulesUtils.println("The created value  ::  "+newAnswer.getCreatedDate());
         RulesUtils.println("Answer from QEventAttributeValueChangeMessage  ::  "+newAnswer.toString());
  
         String loadDescription = newAnswer.getValue();
           
       /* Get the sourceCode(Job code) for this LOAD */
       BaseEntity job = rules.getParent(newAnswer.getTargetCode(), "LNK_BEG");
       
       Answer jobDescriptionAnswer = new Answer(rules.getUser().getCode() ,job.getCode(), newAnswer.getAttributeCode() ,loadDescription);          	    
       //rules.publishData(jobDescriptionAnswer);
       rules.saveAnswer(jobDescriptionAnswer);
        
       rules.footer();
end

