package life.genny.rules;

import life.genny.rules.QRules;
import life.genny.qwanda.entity.BaseEntity;
import life.genny.qwanda.message.QEventMessage;
import life.genny.rules.RulesUtils;
import io.vertx.core.json.JsonObject;

import life.genny.qwanda.message.QCmdMessage;

rule "Delete job"
	when
		$m: QEventMessage( event_type == "BTN_CLICK" && data.code == "BTN_DELETE_BEG")
		rules: QRules(!isState("JOB_MOVED_TO_BIN"))
	then
		
		rules.header();
		
		String begCode = $m.getData().getValue();
	   /*     Moving the BEG      */
          Link link = new Link("GRP_NEW_ITEMS", begCode, "LNK_CORE");
 	      String output = QwandaUtils.apiPostEntity(rules.getQwandaServiceUrl()+"/qwanda/baseentitys/move/GRP_BIN", JsonUtils.toJson(link), rules.getToken()); 
		rules.setState("JOB_MOVED_TO_BIN");
		
		drools.setFocus("SendLayoutsAndData"); 
		
	    rules.footer();
end
