package life.genny.rules;

import life.genny.rules.QRules;
import life.genny.qwanda.entity.BaseEntity;
import life.genny.qwanda.message.QEventMessage;
import life.genny.rules.RulesUtils;
import io.vertx.core.json.JsonObject;

import life.genny.qwanda.message.QCmdMessage;

rule "Delete job"
	when
		$m: QEventMessage( event_type == "BTN_CLICK" && data.code == "BTN_DELETE_BEG")
		rules: QRules(!isState("JOB_MOVED_TO_BIN"))
	then
		
		rules.header();
		
		String begCode = $m.getData().getValue();
	   /*     Moving the BEG      */
          Link link = new Link("GRP_NEW_ITEMS", begCode, "LNK_CORE");
          rules.moveBaseEntity(begCode, "GRP_NEW_ITEMS", "GRP_BIN", "LNK_CORE");
          
          String[] recipients = VertxUtils.getSubscribers(rules.realm(), "GRP_NEW_ITEMS");
        
       /* SEND JOB BE */
          rules.publishBaseEntityByCode(begCode, "GRP_BIN","LNK_CORE", recipients);  
          List<String> driverList = new ArrayList<String>();
            
          for (String s: recipients) { 
          BaseEntity user = rules.getBaseEntityByCode(s);
             if (user.is("PRI_DRIVER")){
                   rules.println("This is the driver BE ::"+s);
                   driverList.add(s); 
               }
           }
           String [] driverRecipients = driverList.toArray(new String[driverList.size()]);
           BaseEntity load = rules.getChildren(begCode, "LNK_BEG", "LOAD");
           rules.clearBaseEntity(load.getCode(), driverRecipients);
           rules.clearBaseEntity(begCode, driverRecipients);
           
           /* Sending Messages */
                HashMap<String,String> contextMap = new HashMap<String, String>();
                contextMap.put("JOB", begCode);
                contextMap.put("OWNER", rules.getUser().getCode()); 
        
               /* rules.println("The String Array is ::"+Arrays.toString(driverRecipients));*/
                
             /* Sending toast message to owner frontend */
                rules.sendMessage("", driverRecipients, contextMap, "MSG_CH40_NEW_JOB_DELETED", "TOAST");
          
		rules.setState("JOB_MOVED_TO_BIN");
		
		drools.setFocus("SendLayoutsAndData"); 
		
	    rules.footer();
end
