package life.genny.rules;

import life.genny.rules.QRules;

import life.genny.qwanda.Answer;
import life.genny.qwanda.message.QDataAnswerMessage;
import life.genny.qwanda.message.QEventAttributeValueChangeMessage;
import life.genny.qwandautils.QwandaUtils;
import life.genny.qwandautils.MergeUtil;
import life.genny.qwanda.entity.BaseEntity;




/*   Rule to handle load category selection   */
rule "Handle Load Category Selection"
    when
        $m: QEventAttributeValueChangeMessage( event_type == "EVT_ATTRIBUTE_VALUE_CHANGE" && QEventAttributeValueChangeMessage.getData().getCode().equals("LNK_LOAD_CATEGORY_LISTS") )
        rules: QRules(isState("STARTED") &&  !isState("LD_CAT_SEL_CHG"))
     then
        rules.header();
        rules.setState("LD_CAT_SEL_CHG");
        
          rules.println("Print QEventAttributeValueChangeMessage ::  "+$m.toString());
 
 		rules.processLoadTypeAnswer($m);
 		
         rules.footer();

end
