package life.genny.rules;

import life.genny.rules.QRules;
import life.genny.qwanda.message.QEventMessage;

rule "Edu Provider Registration Form Submit - Step 0"
	when
	    rules: QRules( 	isState("QUE_EDU_PROVIDER_GRP") && 
						isState("EVENT_FORM_SUBMIT") && 						
						!isState("PRI_IS_PROFILE_COMPLETED") && 
						!isState("LOOP_EDU_PROVIDER_REGISTRATION_FORM_SUBMIT_STEP0")) 
	 then
	 	rules.header();
        rules.setState("LOOP_EDU_PROVIDER_REGISTRATION_FORM_SUBMIT_STEP0");
		
		BaseEntity user = rules.getBaseEntityByCode(rules.getUser().getCode());
		String eduProviderCode = user.getLoopValue("LNK_UNI", null);
		
		if(eduProviderCode != null){
			BaseEntity eduProvider = rules.getBaseEntityByCode(eduProviderCode);
			rules.println("eduProvider is   ::   " + eduProvider.getCode());
			
			rules.set("eduProviderBe", eduProvider);
			
			rules.setState("EDU_PROVIDER_REGISTRATION_FORM_SUBMIT_READY");  
			rules.setState("LINK_EDU_PROVIDER_TO_STUDENT");  
		}else{
			rules.println("eduProviderCode is null");
		}
	 	rules.footer();      
end