package life.genny.rules;
import life.genny.rules.QRules;

/* Update  PRI_IS_PROFILE_COMPLETED = TRUE */
rule "Edu Provider Registration Form Submit - Step 2"
	when
	    rules: QRules( 	isState("SET_PROFILE_IS_COMPLETED") && 
	    				isState("LINKED_EDU_PROVIDER_TO_STAFF") && 
	    				isState("QUE_EDU_PROVIDER_GRP") && 
						isState("EVENT_FORM_SUBMIT") && 						
						isState("CREATED_LINK") && 						
						isState("STAFF") && 						
						!isState("PRI_IS_PROFILE_COMPLETED") && 
						!isState("LOOP_EDU_PROVIDER_REGISTRATION_FORM_SUBMIT_STEP2")) 
	 then
	 	rules.header();
        rules.setState("LOOP_EDU_PROVIDER_REGISTRATION_FORM_SUBMIT_STEP2");

		String sourceCode = rules.getUser().getCode();
		String targetCode = rules.getUser().getCode();
		String attributeCode = "PRI_IS_PROFILE_COMPLETED";
		String value = "TRUE";

		rules.updateBaseEntityAttribute(sourceCode, targetCode, attributeCode, value);

	 	rules.footer();      
end
