package life.genny.rules;

import life.genny.qwandautils.RulesUtils;
import life.genny.rules.QRules;

import life.genny.qwanda.message.QEventMessage;

rule "Main Init"

    when
        m : QEventMessage( QEventMessage.getData().getCode().equals("AUTH_INIT") )
        rules: QRules() 
     then
     	RulesUtils.header("Main Init");
     	
        
  
		
	    RulesUtils.footer("Main Init");       		      
end
