package life.genny.rules;

import life.genny.qwandautils.RulesUtils;
import life.genny.rules.QRules;
import life.genny.qwanda.entity.BaseEntity;

import life.genny.qwanda.message.QEventMessage;

rule "Main Init"

    when
        m : QEventMessage( QEventMessage.getData().getCode().equals("AUTH_INIT") )
        rules: QRules( isUserPresent() == false ) 
     then
     	RulesUtils.header(drools.getRule().getName());
     	    	
        BaseEntity user = rules.getUser();
        if (user == null) {
        		RulesUtils.println("user ("+ rules.getAsString("preferred_username")+") is not present");
  		}
        rules.setState("USER_CHECKED");
        update(rules); 
  
  		
	    RulesUtils.footer(drools.getRule().getName());       		      
end
