package life.genny.rules;

import life.genny.rules.QRules;
import life.genny.qwanda.entity.BaseEntity;

import life.genny.qwanda.message.QEventMessage;

rule "Main Init"

    when
        m : QEventMessage( QEventMessage.getData().getCode().equals("AUTH_INIT") )
        rules: QRules( isUserPresent() == false && (!isState("USER_CHECKED"))) 
     then
     
     	rules.setDrools(drools);
         
     	rules.header();
     	    	
        rules.getUser();
        rules.setState("USER_CHECKED");
		
	    rules.footer();       		      
end
