package life.genny.rules;

import life.genny.qwandautils.RulesUtils;
import life.genny.rules.QRules;
import life.genny.qwanda.entity.BaseEntity;

import life.genny.qwanda.message.QEventMessage;

rule "No User"

    when
        m : QEventMessage( QEventMessage.getData().getCode().equals("AUTH_INIT") )
        rules: QRules( is("USER") == true    && isNull("USER") ) 
     then
     	RulesUtils.header(drools.getRule().getName());
     	
     	BaseEntity be = rules.createUser();
		RulesUtils.println("New User Created "+be);
		
	    RulesUtils.footer(drools.getRule().getName());       		      
end
