package life.genny.rules;

import life.genny.rules.QRules;


import life.genny.qwanda.message.QEventMessage;

rule "No User"

    when
        m : QEventMessage( QEventMessage.getData().getCode().equals("AUTH_INIT") )
        rules: QRules( isUserPresent() == false  && isState("USER_CHECKED")  && (!isState("NO_USER"))) 
      then
     	rules.header();
     	
        	rules.println("user ("+ rules.getAsString("preferred_username")+") is not present");
 
		rules.setState("NO_USER");
 
		rules.footer();     		      
end
