package life.genny.rules;

import life.genny.rules.RulesUtils;
import life.genny.rules.QRules;
import life.genny.qwanda.entity.BaseEntity;

import life.genny.qwanda.message.QEventMessage;

rule "No User"

    when
        m : QEventMessage( QEventMessage.getData().getCode().equals("AUTH_INIT") )
        rules: QRules( isUserPresent() == false  && isState("USER_CHECKED")) 
      then
     	RulesUtils.header(drools.getRule().getName());
     	
     	BaseEntity be = rules.createUser();
     	update(rules);
     	
		RulesUtils.println("New User Created "+be);
		
		rules.setState("NEW_USER");
        update(rules); 
 
		
	    RulesUtils.footer(drools.getRule().getName());       		      
end
