package life.genny.rules;

import life.genny.qwandautils.RulesUtils;
import life.genny.rules.QRules;
import life.genny.qwanda.entity.BaseEntity;

import life.genny.qwanda.message.QEventMessage;

rule "User Exists"

    when
        m : QEventMessage( QEventMessage.getData().getCode().equals("AUTH_INIT") )
        rules: QRules(( isUserPresent() == true)  && isState("USER_CHECKED")) 
     then
     	RulesUtils.header(drools.getRule().getName());
     	
     	
        BaseEntity user = rules.getUser();
        RulesUtils.println("user exists");
        RulesUtils.println("User "+user);
  
        rules.setState("IS_LOGGED_IN");
        update(rules); 
		
	    RulesUtils.footer(drools.getRule().getName());       		      
end
