package life.genny.rules;

import life.genny.qwandautils.RulesUtils;
import life.genny.rules.QRules;
import life.genny.qwanda.entity.BaseEntity;

import life.genny.qwanda.message.QEventMessage;

rule "Is Logged In"
    when
        rules: QRules( isState("IS_LOGGED_IN")) 
     then
     	RulesUtils.header(drools.getRule().getName());
     	
   
        RulesUtils.println("CONFIRM IS_LOGGED_IN");

		
	    RulesUtils.footer(drools.getRule().getName());       		      
end
