package life.genny.rules;

import life.genny.qwandautils.RulesUtils;
import life.genny.rules.QRules;
import life.genny.qwanda.entity.BaseEntity;

import life.genny.qwanda.message.QEventMessage;

rule "Is Logged In"
	no-loop true
    when
        rules: QRules( isState("IS_LOGGED_IN") == true) 
     then
     	RulesUtils.header(drools.getRule().getName());
     	
   
        rules.setState("IS_LOGGED_IN");
        update(rules); 
		
	    RulesUtils.footer(drools.getRule().getName());       		      
end
