package life.genny.rules;

import life.genny.rules.RulesUtils;
import life.genny.rules.QRules;

import life.genny.qwandautils.QwandaUtils;
import life.genny.qwanda.message.QCmdMessage;
import life.genny.qwanda.message.QCmdLayoutMessage;



rule "Send Layout Change To Frontend"
    no-loop true
    when
        rules: QRules( isState("IS_LOGGED_IN")) 
     then
     	RulesUtils.header(drools.getRule().getName());
     	
     	/*  String layout = QwandaUtils.apiGet(RulesUtils.getLayoutCacheURL("layouts/layout1.json"), null); */
     	String layout = RulesUtils.getLayout("layouts/layout1.json");
     	
  		RulesUtils.println(layout);
  		QCmdMessage layoutCmd = new QCmdLayoutMessage("layout1",layout);
  		
        rules.publishCmd(layoutCmd);
        RulesUtils.println("DEFAULT LAYOUT SENT TO FRONTEND");
        rules.clearState("IS_LOGGED_IN");
        rules.setState("LAYOUT_CHANGE_READY");
        update(rules); 
 
		
	    RulesUtils.footer(drools.getRule().getName());       		      
end
