package life.genny.rules;

import life.genny.rules.QRules;


rule "Send Layout Change To Frontend"
    no-loop true
    when
        rules: QRules( isState("IS_LOGGED_IN") && (!isState("LAYOUT_CHANGE_READY"))) 
     then
     	rules.header();
     	
        rules.sendLayout("LAY_DEFAULT","layouts/layout1.json");
           
        rules.setState("LAYOUT_CHANGE_READY");
 
		
	    rules.footer();    		      
end
