package life.genny.rules;

import life.genny.rules.RulesUtils;
import life.genny.rules.QRules;
import life.genny.qwanda.entity.BaseEntity;

import life.genny.qwanda.message.QEventMessage;

rule "User Exists : Send Asks if profile not completed"
    no-loop true
    when
        rules: QRules( isState("IS_LOGGED_IN") && (!isState("INITIAL_PROFILE_LAYOUT_SENT")) && isNewUserProfileCompleted() == false ) 
     then
        rules.header();
     	
        drools.setFocus("NewUserProfile");
	    rules.setState("INITIAL_PROFILE_LAYOUT_SENT");
	    
	    rules.footer();     		      
end
