package life.genny.rules;

import life.genny.rules.RulesUtils;
import life.genny.rules.QRules;
import life.genny.qwanda.entity.BaseEntity;
import java.util.List;


rule "Send Ch40 BucketData To Frontend"
    no-loop true
    when
        rules: QRules( isState("LAYOUT_CHANGE_READY")) 
     then
     	RulesUtils.header(drools.getRule().getName());
     	
     	BaseEntity user = rules.getUser();
     	
     	 List<BaseEntity> views = rules.getBaseEntitysByParentAndLinkCode("GRP_DASHBOARD","LNK_CORE", 0, 20, false) ;
     	 rules.publishCmd(views,"GRP_DASHBOARD","LNK_CORE");
  		RulesUtils.println(views);
     	
     	 List<BaseEntity> buckets = rules.getBaseEntitysByParentAndLinkCode("GRP_DRIVER_VIEW","LNK_CORE", 0, 20, false) ;
     	 rules.publishCmd(buckets,"GRP_DRIVER_VIEW","LNK_CORE");
     	 
     	for (BaseEntity bucket : buckets ) 
     	{
     		RulesUtils.println(bucket);
     		List<BaseEntity> begs = new ArrayList<BaseEntity>();
     		if (user.is("PRI_DRIVER")) {
     			List<BaseEntity> driverbegs = rules.getBaseEntitysByParentAndLinkCode(bucket.getCode(),"LNK_CORE", 0, 500, false, rules.getUser().getCode()) ;
     			begs.addAll(driverbegs);
     		}
 
    			if (user.is("PRI_OWNER")) {
     			List<BaseEntity> ownerbegs = rules.getBaseEntitysByParentAndLinkCode(bucket.getCode(),"LNK_CORE", 0, 500, false, rules.getUser().getCode()) ;
     		    begs.addAll(ownerbegs);
     		}
 
     		 rules.publishCmd(begs,bucket.getCode(),"LNK_CORE");
     		 
     		 
     		for (BaseEntity beg : begs) {
     			List<BaseEntity> begKids = rules.getBaseEntitysByParentAndLinkCode(beg.getCode(),"LNK_BEG", 0, 20, false) ;
     			rules.publishCmd(begKids,beg.getCode(),"LNK_BEG");
     			for (BaseEntity begKid : begKids) {   	 			
     	 			RulesUtils.println(bucket.getCode()+":"+begKid.getCode());
     	 		}
     		}
     	}
       	   		
	    RulesUtils.footer(drools.getRule().getName());       		      
end
