package life.genny.rules;

import life.genny.rules.QRules;


rule "Send Treeview To Frontend"
    no-loop true
    agenda-group "SendLayoutsAndData"
    when
        rules: QRules( isState("LAYOUT_CHANGE_READY") && (!isState("SEND_TREEVIEW"))) 
     then
     	rules.header();
     	
      	rules.publishBaseEntitysByParentAndLinkCode("GRP_ROOT","LNK_CORE", 0, 10, true); /* Send tree view */
      	rules.publishBaseEntitysByParentAndLinkCodeWithAttributes("GRP_MESSAGES","LNK_CHAT", 0, 100, true); /* Send messages */
   	    rules.println("Root Group is "+"GRP_ROOT");
   	    
   	    rules.setState("SEND_TREEVIEW");
     		
	    rules.footer();     		      
end
