package life.genny.rules;

import life.genny.qwandautils.RulesUtils;
import life.genny.rules.QRules;

import life.genny.entity.BaseEntity;


rule "Send Project To Frontend"
    no-loop true
    when
        rules: QRules( isState("IS_LOGGED_IN")) 
     then
     	RulesUtils.header(drools.getRule().getName());
     	
     	BaseEntity project = rules.getBaseEntityByAttributeAndValue("PRI_REALM",rules.getAsString("realm"));
     	RulesUtils.println("Project "+project);
     	  
        rules.publishCmd(project,"PROJECT");
   
        RulesUtils.println("PROJECT SENT TO FRONTEND");
		
	    RulesUtils.footer(drools.getRule().getName());       		      
end
