package life.genny.rules;

import life.genny.qwandautils.RulesUtils;
import life.genny.rules.QRules;


rule "Send User To Frontend"
    no-loop true
    when
        rules: QRules( isState("LAYOUT_CHANGE_READY")) 
     then
     	RulesUtils.header(drools.getRule().getName());
     	
        rules.publishCmd(rules.getUser(),"USER");
   
        RulesUtils.println("USER SENT TO FRONTEND");
		
	    RulesUtils.footer(drools.getRule().getName());       		      
end
