package life.genny.rules;

import life.genny.rules.RulesUtils;
import life.genny.rules.QRules;
import life.genny.qwanda.entity.BaseEntity;
import java.util.List;


rule "Send Treeview To Frontend"
    no-loop true
    when
        rules: QRules( isState("LAYOUT_CHANGE_READY")) 
     then
     	RulesUtils.header(drools.getRule().getName());
     	
      	rules.publishBaseEntitysByParentAndLinkCode("GRP_ROOT","LNK_CORE",0,10,true);
   	    RulesUtils.println("Root Group is "+"GRP_ROOT");
     		
	    RulesUtils.footer(drools.getRule().getName());       		      
end
