package life.genny.rules;

import life.genny.rules.RulesUtils;
import life.genny.rules.QRules;
import life.genny.qwanda.entity.BaseEntity;


rule "Send Project To Frontend"
    no-loop true
    when
        rules: QRules( isState("IS_LOGGED_IN")  && (!isState("PROJECT_SENT")) )
     then
     	RulesUtils.header(drools.getRule().getName());
     	
     	BaseEntity project = rules.getBaseEntityByAttributeAndValue("PRI_REALM",rules.getAsString("realm"));
     	RulesUtils.println("Project "+project);
     	  
        rules.publishCmd(project,"PROJECT");
   
        RulesUtils.println("PROJECT SENT TO FRONTEND");
        rules.setState("PROJECT_SENT");
        update(rules); 
		
	    RulesUtils.footer(drools.getRule().getName());       		      
end
