 package life.genny.rules;

 import life.genny.rules.RulesUtils;
 import life.genny.rules.QRules;
 import life.genny.qwanda.entity.BaseEntity;

 import life.genny.qwanda.message.QEventMessage;

 rule "Send GPS Region"
     when
         rules: QRules( isState("LAYOUT_CHANGE_READY"))
      then
      	
      	 RulesUtils.header(drools.getRule().getName()); 
    		
 		List<BaseEntity> jobsInTransit = rules.getBaseEntitysByAttributeAndValue("STT_IN_TRANSIT", rules.getUser().getCode());
 		for(BaseEntity be: jobsInTransit) {
 			
 			String begCode = be.getCode();	
 			rules.geofenceJob(begCode, rules.getUser().getCode(), 30.0);
 		}
 		        
 	    RulesUtils.footer(drools.getRule().getName());       		      
 end
