package life.genny.rules;

import life.genny.qwandautils.RulesUtils;
import life.genny.rules.QRules;

import life.genny.qwandautils.QwandaUtils;
import life.genny.qwanda.message.QCmdMessage;
import life.genny.qwanda.message.QCmdLayoutMessage;



rule "Send Default Layout To Frontend"
    no-loop true
    when
        rules: QRules( isState("IS_LOGGED_IN")) 
     then
     	RulesUtils.header(drools.getRule().getName());
     	
     	String layout = QwandaUtils.apiGet("https://raw.githubusercontent.com/genny-project/layouts/master/layouts/layout1.json", null);
  		RulesUtils.println(layout);
  		QCmdMessage layoutCmd = new QCmdLayoutMessage("layout1",layout);
  		
        rules.publishCmd(layoutCmd);
           
        RulesUtils.println("DEFAULT LAYOUT SENT TO FRONTEND");
		
	    RulesUtils.footer(drools.getRule().getName());       		      
end
