package life.genny.rules;

import life.genny.rules.RulesUtils;
import life.genny.rules.QRules;

import life.genny.qwandautils.QwandaUtils;
import life.genny.qwanda.message.QCmdMessage;
import life.genny.qwanda.message.QCmdLayoutMessage;

import io.vertx.core.json.JsonObject;
import io.vertx.core.json.JsonArray;
import com.google.gson.Gson;


rule "Send Sub Layouts To Frontend"
    no-loop true
    agenda-group "SendLayoutsAndData"
    when
        rules: QRules( isState("USER_SENT")) 
     then

        rules.header();
  
  		String subLayoutMap = RulesUtils.getLayout("sublayouts");
 		if(subLayoutMap != null) {
		
			JsonArray subLayouts = new JsonArray(subLayoutMap);
			if(subLayouts != null) {
				
				for(int i = 0; i < subLayouts.size(); i++) {
					
					JsonObject sublayoutData = subLayouts.getJsonObject(i);
					String url = sublayoutData.getString("download_url");
					String name = sublayoutData.getString("name");
					name = name.replace(".json", "");
					name = name.replaceAll("\"", "");
					
					if(url != null) {
						
						/*  grab sublayout from github */

						rules.println(url);
						
						String subLayoutString = QwandaUtils.apiGet(url, null);
						if(subLayoutString != null) {
							
							try {
								
								/* send sublayout to FE  */
								JsonObject subLayoutObj = new JsonObject();
						        subLayoutObj.put("msg_type", "DATA_MSG");
						        subLayoutObj.put("data_type", "SUB_LAYOUT");
						        subLayoutObj.put("code", name);
						        subLayoutObj.put("items", subLayoutString);      
								subLayoutObj.put("token", rules.getToken());
								
						        rules.publish("cmds", subLayoutObj);
						        
							}
							catch(Exception e) {
							} 
						}
					}
				}
			}
		}
		
	    rules.footer();     		      
end
