package life.genny.rules;

import life.genny.qwandautils.RulesUtils;
import life.genny.rules.QRules;

import life.genny.qwandautils.QwandaUtils;
import life.genny.qwanda.message.QCmdMessage;
import life.genny.qwanda.message.QCmdLayoutMessage;

import io.vertx.core.json.JsonObject;
import io.vertx.core.json.JsonArray;


rule "Send Sub Layouts To Frontend"
    no-loop true
    when
        rules: QRules( isState("LAYOUT_CHANGE_READY")) 
     then
     	RulesUtils.header(drools.getRule().getName());
     	
       	/*  Send all sublayouts for entities  */
  		RulesUtils.header( "Send initial sublayouts");  
  
  		String subLayoutMap = RulesUtils.getLayout("sublayouts");
 		if(subLayoutMap != null) {
		
			JsonArray subLayouts = new JsonArray(subLayoutMap);
			if(subLayouts != null) {
				
				for(int i = 0; i < subLayouts.size(); i++) {
					
					JsonObject sublayoutData = subLayouts.getJsonObject(i);
					String url = sublayoutData.getString("download_url");
					String name = sublayoutData.getString("name");
					name = name.replace(".json", "");
					name = name.replaceAll("\"", "");
					
					if(url != null) {
						
						/*  grab sublayout from github */

						RulesUtils.println(url);
						
						String subLayoutString = QwandaUtils.apiGet(url, null);
						if(subLayoutString != null) {
							
							try {
								
								/* send sublayout to FE  */
								JsonObject subLayoutObj = new JsonObject();
						        subLayoutObj.put("msg_type", "DATA_MSG");
						        subLayoutObj.put("data_type", "SUB_LAYOUT");
						        subLayoutObj.put("code", name);
						        subLayoutObj.put("items", subLayoutString);      
								subLayoutObj.put("token", rules.getToken());
								
						        rules.publish("cmds", subLayoutObj);
						        
							}
							catch(Exception e) {
							} 
						}
					}
				}
			}
		}
		
	    RulesUtils.footer(drools.getRule().getName());       		      
end
