package life.genny.rules;

import life.genny.qwandautils.RulesUtils;
import life.genny.rules.QRules;

import life.genny.qwandautils.QwandaUtils;
import life.genny.qwanda.message.QCmdMessage;
import life.genny.qwanda.message.QCmdLayoutMessage;

import life.genny.qwanda.Answer;
import life.genny.qwanda.message.QDataAnswerMessage;
import life.genny.qwanda.message.QEventAttributeValueChangeMessage;

import io.vertx.core.json.JsonObject;


rule "Listen Attribute Change"
    when
        $m: QEventAttributeValueChangeMessage( event_type == "EVT_ATTRIBUTE_VALUE_CHANGE" )
        rules : QRules()
     then
     
      	RulesUtils.header(drools.getRule().getName());
        
        Answer newAnswer = $m.getAnswer();
        
        rules.publish("data",new QDataAnswerMessage(newAnswer));
  
   
  
   	RulesUtils.footer(drools.getRule().getName());
  
end