// package life.genny.rules;
// import life.genny.rules.QRules;

// /* Unsubscribe INTERN from OLD_BEG */
// rule "Shortlist Internship - Step 9"	
// 	when
// 		rules: QRules( 	isState("UNSUBSCRIBE_INTERN_FROM_OLD_BEG") && 
// 						isState("BTN_SHORTLIST_INTERN") && 
// 						isState("EVENT_BTN_CLICK") && 
// 						!isState("LOOP_SHORTLIST_INTERN_STEP9") ) 

// 	 then
// 	 	rules.header();
//         rules.setState("LOOP_SHORTLIST_INTERN_STEP9");

//         BaseEntity intern = rules.getAsBaseEntity("internBe");
//         BaseEntity oldBeg = rules.getAsBaseEntity("begBe");
		
// 		if(intern != null && oldBeg != null){
//             rules.unsubscribeUserToBaseEntity(intern.getCode() , oldBeg.getCode());

// 	 		rules.setState("UNSUBSCRIBED_INTERN_FROM_OLD_BEG");
// 	 		rules.setState("DELETE_OLD_BEG_FROM_INTERN");
// 		}
// 	 	rules.footer();      
// end