package life.genny.rules;

import life.genny.rules.QRules;


rule "Send Layout Change To Frontend - Memberhub"

    salience 697
    no-loop true
    ruleflow-group "SendLayoutsAndData"
    when
        rules: QRules( !isState("LAYOUT_CHANGE_READY") && isRealm("memberhub"))
     then
     	rules.header();

     	String userCode = rules.getUser().getCode();
        rules.sendLayout("LAY_DEFAULT", "layout.json");

        rules.sendQuestions(userCode, userCode, "QUE_MEMBERHUB_GRP", false); /* false for form_view*/
        rules.setState("MEMBERHUB_QUESTIONS_READY");

        String homeLoanCode = "PRD_HOME_LOAN";
        String holidayCode = "PRD_HOLIDAY";
        String linkCode= "LNK_SCORE";

        String linkHomeloan = "LOAN";
        String linkHoliday = "HOLIDAY";

        /* Check if link exists between USER & PRD_HOME_LOAN */
        Boolean isHomeloan = QwandaUtils.checkIfLinkExistsForTarget(userCode, linkCode , homeLoanCode, rules.getToken());
        System.out.println("Link Exists ?   ::   "+ isHomeloan);

        /* Creating a link between USER & PRD_HOLIDAY */
        if(!isHomeloan){
            rules.createLink(userCode, homeLoanCode, linkCode, linkHomeloan, 1.0);
        }

        /* Check if link exists between USER & PRD_HOME_LOAN */
        Boolean isHoilday = QwandaUtils.checkIfLinkExistsForTarget(userCode, linkCode , holidayCode, rules.getToken());
        System.out.println("Link Exists ?   ::   "+ isHoilday);

        /* Creating a link between USER & PRD_HOME_LOAN */
        if(!isHoilday){
            rules.createLink(userCode, holidayCode, linkCode, linkHoliday, 1.0);
        }

        /* Send begs */
        rules.publishBaseEntityByCode(homeLoanCode);
        rules.publishBaseEntityByCode(holidayCode);

	    rules.footer();
end
