package life.genny.rules;
import life.genny.rules.QRules;

rule "Trigger Check Role - Auth Init"

    when
         rules: QRules( isState("TRIGGER_CHECK_USER_ROLE") &&
                        !isState("LOOP_TRIGGER_CHECK_USER_ROLE") )
     then
     	rules.header();
        rules.setState("LOOP_TRIGGER_CHECK_USER_ROLE");

        rules.setState("CHECK_IF_PROJECT_REQUIRES_ROLE");

	    rules.footer();
end
