package life.genny.rules;
import life.genny.rules.QRules;

rule "Check if project requires role - User Role Not Found"

    when
         rules: QRules( isState("IS_USER_ROLE_SET") &&
                        isState("ROLE_NOT_FOUND") &&
                        !isState("LOOP_IS_USER_ROLE_SET") )
     then
     	rules.header();
        rules.setState("LOOP_IS_USER_ROLE_SET");

        rules.setState("TRIGGER_ASK_USER_ROLE");

	    rules.footer();
end
