package life.genny.rules;

import life.genny.rules.QRules;
import java.util.List;

rule "Exit Role Selection - channel40"
     when
        rules: QRules( 	isState("EXIT_ROLE_SELECTION") &&
						!isState("EXITED_ROLE_SELECTION") ) 
     then      
        rules.header();     
		
		rules.setState("EXITED_ROLE_SELECTION");
		rules.setState("TRIGGER_PROFILE_CHECK");

		rules.footer();     		      
end
     	