package life.genny.rules;
import life.genny.rules.QRules;

rule "Submit Invite Intern - Step 0"
	when
        rules: QRules(  isState("EVENT_FORM_SUBMIT") && 
						isState("QUE_INVITE_INTERNS_GRP") && 
						isState("SUBMIT") && 
                        !isState("LOOP_SUBMIT_INVITE_INTERN")  )
     then 
 		rules.header();
		rules.setState("LOOP_SUBMIT_INVITE_INTERN");
        
        /* Trigger HomePage */
        rules.setState("TRIGGER_INTERNMATCH_HOMEPAGE");
        
        String internCode = rules.getAsString("quesTargetCode");
        rules.println("internCode    ::   " + internCode);
        if(internCode != null){
            BaseEntity intern = rules.getBaseEntityByCode(internCode);
            if(intern !=null){
                rules.set("internBe", intern);
	    	    rules.setState("SUBMIT_INVITE_INTERN_READY");

	    	    rules.setState("ADD_TO_GRP_INVITED_INTERNS");
            }
        }
 		rules.footer();
end
