package life.genny.rules;
import life.genny.rules.QRules;

rule "Submit Invite Intern - Step 1"
	when
        rules: QRules(  isState("EVENT_FORM_SUBMIT") && 
						isState("QUE_INVITE_INTERNS_GRP") && 
						isState("SUBMIT") && 
                        !isState("LOOP_SUBMIT_INVITE_INTERN")  )
     then 
 		rules.header();
		rules.setState("LOOP_SUBMIT_INVITE_INTERN");

        String internCode = rules.getAsString("quesTargetCode");
        rules.println("internCode    ::   " + internCode);
        if(internCode != null){
            BaseEntity intern = rules.getBaseEntityByCode(internCode);
            if(intern !=null){
                rules.set("internBe", intern);
		        /* Trigger Messages */
	    	    rules.setState("SEND_INVITATION_MESSAGE_TO_INTERN");
            }
        }
 		rules.footer();
end
