package life.genny.rules;
import life.genny.rules.QRules;

rule "Trigger Role check"
    when
        rules: QRules(  isState("TRIGGER_ASK_USER_ROLE") &&
                        !isState("LOOP_TRIGGER_ASK_USER_ROLE") )
     then
        rules.clearState("ASKED_USER_ROLE");
        rules.setState("LOOP_TRIGGER_ASK_USER_ROLE");

        rules.setState("ASK_USER_ROLE");
        rules.setState("IS_REGISTRATION");
        rules.footer();

end
