package life.genny.rules;

import life.genny.rules.QRules;

rule "Application Not Ready"
    when
        rules: QRules(	isState("AUTH_INIT") &&
						isUserPresent() == false &&
						!isState("LOOP_APPLICATION_NOT_READY"))
      then
		rules.header();
		rules.setState("LOOP_APPLICATION_NOT_READY");
		
		BaseEntity be = rules.createUser();
		rules.setState("APPLICATION_NOT_READY");

		rules.footer();
end
