package life.genny.rules;
import life.genny.rules.QRules;

/* COPY attributes from PRODUCT TO BEG */
rule "Submit Add BEG - Step 0"
	when
		rules: QRules( 	isState("COPY_PRODUCT_ATTRIBUTES_TO_BEG") && 
						!isState("LOOP_SUBMIT_ADD_BEG_STEP0")) 
	 then
	 	rules.header();
        rules.setState("LOOP_SUBMIT_ADD_BEG_STEP0");

        BaseEntity beg = rules.getAsBaseEntity("begBe");
        BaseEntity product = rules.getAsBaseEntity("productBe");

		rules.baseEntity.copyAttributes(product, beg);
		rules.setState("COPIED_ALL_ATTRIBUTES_FROM_PRODUCT_TO_BEG");
		rules.setState("LINK_BEG_AND_CREATOR");
		
	 	rules.footer();      
end
