package life.genny.rules;
import life.genny.rules.QRules;

/* LINK BEG + CPY || COMPANY */
rule "Submit Add BEG - Step 3"
	when
	    rules: QRules( 	isState("LINK_BEG_AND_COMPANY") && 
						isState("CREATED_LINK") && 	
						isState("CREATOR") && 	
						!isState("LOOP_SUBMIT_ADD_BEG_STEP3")) 
	 then
	 	rules.header();
        rules.setState("LOOP_SUBMIT_ADD_BEG_STEP3");

		BaseEntity beg = rules.getAsBaseEntity("begBe");
		BaseEntity company = rules.getAsBaseEntity("companyBe");

		if(beg == null){
			rules.println("beg not found");			
		}
		else if(company == null){
			rules.println("Company not found");
		}
		else{
			/* link BEG to CPY */
			rules.set("linkSourceCode", beg.getCode());
			rules.set("linkTargetCode", company.getCode());
			rules.set("linkCode", "LNK_BEG");
			rules.set("linkValue", "COMPANY");
			rules.set("linkWeight", 1.0);
			rules.setState("CREATE_LINK");
			
			/* project specific state to link beg with host-company representative */
			rules.setState("LINK_BEG_AND_COMPANY_REP");
			
			// rules.setState("MOVE_BEG_TO_GRP_NEW_ITEMS");
		}
		rules.footer();
end
