package life.genny.rules;
import life.genny.rules.QRules;

/* Move BEG from GRP_DRAFTS >>> GRP_NEW_ITEMS  */
rule "Submit Add BEG - Step 4"
	when
		rules: QRules( 	isState("MOVE_BEG_TO_GRP_NEW_ITEMS") && 
						isState("CREATED_LINK") && 
						isState("HOST_COMPANY_REPRESENTATIVE") && 
						!isState("LOOP_SUBMIT_ADD_BEG_STEP4")) 
	 then
	 	rules.header();
        rules.setState("LOOP_SUBMIT_ADD_BEG_STEP4");

		BaseEntity beg = rules.getAsBaseEntity("begBe");
        if(beg != null){
        	rules.moveBaseEntitySetLinkValue(beg.getCode(), "GRP_DRAFTS", "GRP_NEW_ITEMS", "LNK_CORE", "BEG");
			
        	rules.setState("PUBLISH_BEG_AND_KIDS");
		}else{
			rules.println("beg is null");
		}
	 	rules.footer();      
end
