package life.genny.rules;
import life.genny.rules.QRules;
import life.genny.utils.VertxUtils;

/* Publish BEG AND KIDS */
rule "Submit Add BEG - Step 4"
	when
		rules: QRules( 	isState("PUBLISH_BEG_AND_KIDS") && 
						!isState("LOOP_SUBMIT_ADD_BEG_STEP4") ) 
	 then
	 	rules.header();
        rules.setState("LOOP_SUBMIT_ADD_BEG_STEP4");

		BaseEntity beg = rules.getAsBaseEntity("begBe");
		BaseEntity product = rules.getAsBaseEntity("productBe");
		BaseEntity company = rules.getAsBaseEntity("companyBe");

		String[] recipients = VertxUtils.getSubscribers(rules.realm(), "GRP_NEW_ITEMS");
		
		List<BaseEntity> begKids = rules.baseEntity.getBaseEntitysByParentAndLinkCode(beg.getCode(), "LNK_BEG", 0, 400, false);
		if(begKids != null){
			
			rules.printList("begKids", begKids);
			
			/* Send BEG BE */
			rules.publishBaseEntityByCode(beg.getCode(), "GRP_NEW_ITEMS", "LNK_CORE", recipients);
			
			/* Send BEG KIDS */
			rules.publishCmd(begKids, beg.getCode(), "LNK_BEG", recipients);
		}
		
		/* Go To Homepage */
		rules.setState("TRIGGER_HOMEPAGE");
		
	 	rules.footer();      
end
