// package life.genny.rules;
// import life.genny.rules.QRules;

// /* LINK BEG + HOST COMPANY REPRESENTATIVE */
// rule "Submit Add BEG - Step 3.5"
// 	when
// 		rules: QRules( 	isState("LINK_BEG_AND_COMPANY_REP") && 
// 						isState("CREATED_LINK") &&
// 						isState("COMPANY") &&
// 						!isState("LOOP_SUBMIT_ADD_BEG_STEP3.5")) 
// 	 then
// 	 	rules.header();
//         rules.setState("LOOP_SUBMIT_ADD_BEG_STEP3.5");

//         BaseEntity beg = rules.getAsBaseEntity("begBe");
//         String hostCompanyRepresentative = beg.getValue("LNK_SELECT_REPRESENTATIVE", null);
        
//         rules.println("beg ::"+beg.getCode());
//         rules.println("host Company Representative ::"+hostCompanyRepresentative);

// 		if(beg != null){
// 			/* link BEG to USER */
// 			rules.set("linkSourceCode",  beg.getCode());
// 			rules.set("linkTargetCode", hostCompanyRepresentative);
// 			rules.set("linkCode", "LNK_BEG");
// 			rules.set("linkValue", "HOST_COMPANY_REPRESENTATIVE");
// 			rules.set("linkWeight", 1.0);
// 			rules.setState("CREATE_LINK");

// 			rules.setState("MOVE_BEG_TO_GRP_NEW_ITEMS");
// 		}else{
// 			rules.println("beg is null");			
// 		}

// 	 	rules.footer();      
// end
