package life.genny.rules;
import life.genny.rules.QRules;

/* Update BEG Status */
rule "Update BEG Status"
	when
		rules: QRules( 	isState("OFFER_ACCEPTED_BY_ALL") && 
						!isState("LOOP_OFFER_ACCEPTED_BY_ALL") ) 
	 then
	 	rules.header();
        rules.setState("LOOP_OFFER_ACCEPTED_BY_ALL");

		String applicationCode = rules.getAsString("itemCode");
		String begCode = rules.getAsString("hintCode");

		BaseEntity beg = null;

        if(beg != null){
            BaseEntity intern = rules.getChildren(beg.getCode(), "LNK_BEG", "INTERN");
            BaseEntity hostCompany = rules.getChildren(beg.getCode(), "LNK_BEG", "HOSTCOMPANY");
			
			if(intern != null && hostCompany != null){
            	
				BaseEntity eduProvider = rules.getParent(intern.getCode(), "LNK_EDU");
				if(eduProvider.getCode() != null){

					rules.updateBaseEntityAttribute(beg.getCode(), beg.getCode(), "STA_" + intern.getCode() , "TRUE");
					rules.updateBaseEntityAttribute(beg.getCode(), beg.getCode(), "STA_" + hostCompany.getCode(), "TRUE");
					rules.updateBaseEntityAttribute(beg.getCode(), beg.getCode(), "STA_" + eduProvider.getCode(), "TRUE");

        			rules.setState("UPDATED_BEG_STATUS");
					
				}else{
					rules.println("eduProvider is null");
				}

			}else{
				rules.println("hostCompany is null");
				rules.println("intern is null");
			}
        }else{
			rules.println("beg is null");
		}
	 	rules.footer();      
end
