package life.genny.rules;
import life.genny.rules.QRules;

rule "Select Contacts - channel40"
    when
      rules: QRules(  isState("EVENT_TV_SELECT") &&
                      isState("TV1") &&
                      isState("GRP_CONTACTS") &&
                      !isState("LOOP_SELECT_CONTACTS") )
    then
      rules.header();
      rules.setState("LOOP_SELECT_CONTACTS");

      String tvSelectValue = rules.getAsString("tvSelectValue");
      
      if(tvSelectValue.equals("GRP_CONTACTS")){

        rules.set("cmdViewType", "LIST_VIEW");
        rules.set("cmdViewRootCode", tvSelectValue);
        rules.setState("SEND_CMD_VIEW");

        rules.setState("SELECTED_CONTACTS");
        rules.clearState(tvSelectValue);
      }
      rules.footer();
end