package life.genny.rules;
import life.genny.rules.QRules;

rule "Select GRP_HOST_COMPANYS - Contacts"
    when
      rules: QRules(  isState("EVENT_TV_SELECT") &&
                      isState("TV1") &&
                      isState("GRP_HOST_COMPANYS") &&
                      !isState("LOOP_SELECT_HOST_COMPANYS") )
    then
      rules.header();
      rules.setState("LOOP_SELECT_HOST_COMPANYS");

      String tvSelectValue = rules.getAsString("tvSelectValue");
      
      if(tvSelectValue.equals("GRP_HOST_COMPANYS")){

        rules.set("cmdViewType", "LIST_VIEW");
        rules.set("cmdViewRootCode", tvSelectValue);
        rules.setState("SEND_CMD_VIEW");

        rules.setState("SELECTED_HOST_COMPANYS");
        rules.clearState(tvSelectValue);
      }
      rules.footer();
end