package life.genny.rules;
import life.genny.rules.QRules;

rule "Add To Edu Provider Group"
     when
        rules: QRules(  isState("ADD_TO_GROUP") && 
						isState("PRI_IS_EDU_PROVIDER") &&
						!isState("LOOP_ADD_TO_EDU_PROVIDER_GROUP") )
     then
        rules.header();
		rules.setState("LOOP_ADD_TO_EDU_PROVIDER_GROUP");
     	
     	/* link EDU_PROVIDER to GRP_EDU_PROVIDERS */
        rules.set("linkSourceCode",  "GRP_EDU_PROVIDERS");
        rules.set("linkTargetCode", rules.getUser().getCode());
        rules.set("linkCode", "LNK_CORE");
        rules.set("linkValue", "EDU_PROVIDER");
        rules.set("linkWeight", 1.0);
        rules.setState("CREATE_LINK");

     	rules.setState("ADDED_TO_EDU_PROVIDER_GROUP");
        rules.setState("ADDDED_TO_GROUP");         
	    rules.footer();     		      
end
     	