package life.genny.rules;
import life.genny.rules.QRules;

rule "Add To Host Company Group - Step 2"
     when
        rules: QRules(  isState("ADD_TO_GROUP") && 
						isState("CHECKED_COMPANY_EXISTS") &&
						isState("FALSE") &&
						isState("PRI_IS_HOST_COMPANY") &&
						!isState("LOOP_ADD_TO_HOST_COMPANY_GROUP_STEP2") )
     then
        rules.header();
		rules.setState("LOOP_ADD_TO_HOST_COMPANY_GROUP_STEP2");
     	
         /* get company BasEntity FROM state */
        BaseEntity company =rules.getAsBaseEntity("companyBe");

		/* link HOST_COMPANY to GRP_HOST_COMPANYS */
        rules.set("linkSourceCode",  "GRP_HOST_COMPANYS");
        rules.set("linkTargetCode", company.getCode());
        rules.set("linkCode", "LNK_CORE");
        rules.set("linkValue", "HOST_COMPANY");
        rules.set("linkWeight", 1.0);
        rules.setState("CREATE_LINK");

        rules.setState("ADDED_TO_HOST_COMPANY_GROUP");
        rules.setState("ADDDED_TO_GROUP");
	    rules.footer();     		      
end
     	
          