package life.genny.rules;
import life.genny.rules.QRules;

rule "00_Trigger_Deselect_BEG"
	when
		rules: QRules(  isState("EVENT_BTN_CLICK") &&
						isState("DESELECT_EVENT") &&
						(getAsString("itemCode") != null) && (getAsString("itemCode").startsWith("BEG_")) && 
						!isState("LOOP_TRIGGER_DESELECT_BEG")) 
	 then
	 	rules.header();
		rules.setState("LOOP_TRIGGER_DESELECT_BEG");
		
		/* get all the buckets linked to GRP_APPLICATIONS */
		List<BaseEntity> buckets = rules.baseEntity.getLinkedBaseEntities("GRP_APPLICATIONS", "LNK_CORE");
	
		/* set the buckets and trigger next rule to send all applications data */
        if(buckets != null) {
        		rules.println("total number of buckets ::"+buckets.size() );
        		rules.set("buckets", buckets);
        		rules.setState("SEND_DATA_FOR_BEG_DESELECTION");
        }

	 	rules.footer();      
end
