package life.genny.rules;
import life.genny.rules.QRules;
import java.util.List;
import life.genny.qwanda.entity.SearchEntity;
import java.io.IOException;
import life.genny.qwanda.message.QDataBaseEntityMessage;

rule "10_SendData_For_BEG_Deselection"
	when
	   rules: QRules( isState("SEND_DATA_FOR_BEG_DESELECTION") && !isState("LOOP_SEND_DATA_FOR_BEG_DESELECTION") )
	then
	    rules.header();
	   
	    rules.setState("LOOP_SEND_DATA_FOR_BEG_DESELECTION");

		/* publish all applications */
        List<BaseEntity> applications = rules.getAsBaseEntitys("applications");
        rules.publishBaseEntityByCode(applications);
       
		rules.setState("SENT_DATA_FOR_BEG_DESELECTION");
	    rules.footer();
end
