package life.genny.rules;

import life.genny.rules.QRules;
import life.genny.qwanda.entity.BaseEntity;

import life.genny.qwanda.message.QEventMessage;

rule "Main Init"

    when
        m : QEventMessage( getData().getCode().equals("AUTH_INIT") )
        rules: QRules(isState("STARTED") &&  (!isState("USER_CHECKED"))) 
     then     
     	rules.header();
        rules.getUser();
        rules.setState("USER_CHECKED");
		rules.println("Checked User is "+rules.getUser());
	    rules.footer();       		      
end
