package life.genny.rules;

import life.genny.rules.RulesUtils;
import life.genny.rules.QRules;
import life.genny.qwanda.entity.BaseEntity;


rule "Is Logged In"

    when

        rules: QRules( isUserPresent() == true  && (!isState("IS_LOGGED_IN")) && isState("USER_CHECKED")) 

     then
        rules.header();
     	
     	
        BaseEntity user = rules.getUser();
        rules.println("user exists");
        rules.println("User "+user+" LOGGED IN"); 

  		rules.clearState("NO_USER");
  		
  		/* we mark the user as logged in */
        rules.setState("IS_LOGGED_IN");
        
        /*Sending a toast message as soon as a user logs in */
        String[] recipientArr = {rules.getUser().getCode()};
        HashMap<String,String> contextMap = new HashMap<String, String>();
        rules.sendMessage("", recipientArr, contextMap,"MSG_CH40_WELCOME_TOAST", "TOAST");
        
        rules.updateBaseEntityAttribute(rules.getUser().getCode(), rules.getUser().getCode(), "PRI_ONLINE", "TRUE");
        
		drools.setFocus("payments"); 
		
		drools.setFocus("SendAliases");
		
	    rules.footer();     		      
end
