package life.genny.rules;

import life.genny.rules.QRules;


rule "New Registration"

    when

        rules: QRules( isUserPresent() == false  && (!isState("NEW_REGISTRATION")) && isState("USER_CHECKED")) 
      then
     	rules.header();
     	
        	rules.println("user ("+ rules.getAsString("preferred_username")+") is not present -> Need to REGISTER");
 
		rules.setState("NEW_REGISTRATION");
 
		rules.footer();     		      
end
