package life.genny.rules;

import life.genny.rules.RulesUtils;
import life.genny.rules.QRules;
import life.genny.qwanda.entity.BaseEntity;

import life.genny.qwanda.message.QEventMessage;

rule "User Exists"
    no-loop true
    when
        rules: QRules( isUserPresent() == true  && (!isState("IS_LOGGED_IN"))  && isState("USER_CHECKED")) 
     then
        rules.header();
     	
     	
        BaseEntity user = rules.getUser();
        rules.println("user exists");
        rules.println("User "+user+" LOGGED IN");

  		rules.clearState("NO_USER");
        rules.setState("IS_LOGGED_IN");
 
/*		drools.setFocus("payments"); */
		
	    rules.footer();     		      
end
