package life.genny.rules;

import life.genny.rules.RulesUtils;
import life.genny.rules.QRules;
import life.genny.qwanda.entity.BaseEntity;

import life.genny.qwanda.message.QEventMessage;

rule "User Exists"
    no-loop true
    when
        m : QEventMessage( QEventMessage.getData().getCode().equals("AUTH_INIT") )
        rules: QRules( (!isState("IS_LOGGED_IN")) ) 
     then
        rules.header();
     	
     	
        BaseEntity user = rules.getUser();
        rules.println("user exists");
        rules.println("User "+user);

  		rules.clearState("NO_USER");
        rules.setState("IS_LOGGED_IN");
		drools.setFocus("payments");
		
		drools.setFocus("SendLayoutsAndData");
		
	    rules.footer();     		      
end
