package life.genny.rules;


import life.genny.rules.QRules;
import life.genny.qwanda.entity.BaseEntity;


rule "Send PROJECT To Frontend"
    no-loop true
    when
       /* rules: QRules( (isState("LAYOUT_CHANGE_READY") || isState("ASK_FIRST_PROFILE") )  && (!isState("PROJECT_SENT")) )   */
        rules: QRules( isState("IS_LOGGED_IN")  && (!isState("PROJECT_SENT")) )
     then
     	rules.header();
     	
     	BaseEntity project = rules.getBaseEntityByAttributeAndValue("PRI_REALM",rules.getAsString("realm"));
     	rules.println("Project "+project);
     	  
        rules.publishCmd(project,"PROJECT");
   
        rules.println("PROJECT SENT TO FRONTEND");
        rules.setState("PROJECT_SENT");

		
	    rules.footer();      		      
end
