package life.genny.rules;
import life.genny.rules.QRules;

rule "Trigger Reject Application"
	when
		rules: QRules(  isState("EVENT_BTN_CLICK") &&
						isState("BTN_REJECT_APPLICATION") && 
						!isState("LOOP_TRIGGER_REJECT_APPLICATION")) 
	 then
	 	rules.header();
		rules.setState("LOOP_TRIGGER_REJECT_APPLICATION");
	   	String applicationCode = rules.getAsString("itemCode");
		if(applicationCode != null){

			BaseEntity application = rules.baseEntity.getBaseEntityByCode(applicationCode);
			if(application != null){
            	String applicantCode = application.getLoopValue("PRI_APPLICANT_CODE" , null);
				if(applicantCode != null){
					
					List<String> userCodes = new ArrayList<String>();
					userCodes.add(rules.getUser().getCode());
					userCodes.add(applicantCode);
					
					rules.baseEntity.saveAnswer( new Answer( rules.getUser().getCode(), applicationCode, "PRI_IS_REJECTED", "TRUE" ) );
					rules.baseEntity.updateBaseEntityStatus(applicationCode, userCodes, "red");            

					rules.setState("APPLICATION_IS_REJECTED");
				}else{
					rules.println("applicantCode is null");
				}
			}else{
				rules.println("application is null");
			}	
		}else{
			rules.println("applicationCode is null");
		}
	 	rules.footer();      
end
