package life.genny.rules;
import life.genny.rules.QRules;

rule "Select GRP_INTERNS - Contacts"
    when
      rules: QRules(  isState("EVENT_TV_SELECT") &&
                      isState("TV1") &&
                      isState("GRP_INTERNS") &&
                      !isState("LOOP_SELECT_INTERNS") )
    then
      rules.header();
      rules.setState("LOOP_SELECT_INTERNS");

      String tvSelectValue = rules.getAsString("tvSelectValue");
      
      if(tvSelectValue.equals("GRP_INTERNS")){

        rules.set("cmdViewType", "LIST_VIEW");
        rules.set("cmdViewRootCode", tvSelectValue);
        rules.setState("SEND_CMD_VIEW");

        rules.setState("SELECTED_INTERNS");
        rules.clearState(tvSelectValue);
      }
      rules.footer();
end