package life.genny.rules;

import life.genny.rules.RulesUtils;
import life.genny.rules.QRules;
import life.genny.utils.PaymentUtils;

rule "Check if project uses Assembly Payments"
	agenda-group "ispayments"
	no-loop true	
    when
    	rules: QRules( !isState("IS_ASSEMBLY_PAYMENTS") )
    then
     
     RulesUtils.header(drools.getRule().getName());
     
    Boolean isPaymentAssembly = rules.getProject().getValue("PRI_IS_PAYMENTS_ASSEMBLY", false);
    rules.println("isPayments assembly used in the project ::"+isPaymentAssembly);
       rules.setState("IS_ASSEMBLY_PAYMENTS");
    
    if(isPaymentAssembly) {
    		drools.setFocus("payments");
    }


	  rules.footer();      		      
end