package life.genny.rules;
import life.genny.rules.QRules;

/* Create Application BaseEntity */
rule "Apply Internship - Step 1"
	when
	    rules: QRules(  isState("USER_HAS_NOT_APPLIED") && 
						isState("BTN_APPLY_INTERNSHIP") && 
						isState("EVENT_BTN_CLICK") && 
						!isState("LOOP_APPLY_INTERNSHIP_STEP1")) 
	 then
	 	rules.header();
        rules.setState("LOOP_APPLY_INTERNSHIP_STEP1");

        /* Create BEG BaseEntity*/
		rules.set("beCode", rules.getUser().getCode());
		rules.set("bePrefix", "APP");
		rules.set("beName", "APPLICATION");		
		rules.setState("CREATE_BASE_ENTITY");	

		rules.setState("CREATED_APPLICATION");	
		rules.setState("SAVE_BEG_CODE_AS_ATTRIBUTE");
	 	rules.footer();      
end


        
        
