package life.genny.rules;
import life.genny.rules.QRules;

rule "Exit Registration"

    when
         rules: QRules( isState("CREATED_NEW_USER") && !isState("LOOP_EXIT_REGISTRATION") )
     then
     	rules.header();
        rules.setState("LOOP_EXIT_REGISTRATION");
    
        rules.setState("EXIT_REGISTRATION");
        rules.setState("TRIGGER_APPLICATION_SETUP");

	    rules.footer();      		      
end
