package life.genny.rules;
import life.genny.rules.QRules;

/* Add BEG, APPLICATION, CPY to map */
rule "Trigger Submit Apply BEG"
	when
		rules: QRules( 	isState("QUE_APPLY_BEG_GRP") &&
						isState("EVENT_FORM_SUBMIT") &&
						isState("SUBMIT") &&
						!isState("LOOP_SUBMIT_APPLY_BEG_STEP0"))
	then
	 	rules.header();
  		rules.setState("LOOP_SUBMIT_APPLY_BEG_STEP0");

		/* get applicationCode from targetCode */
		String applicationCode = rules.getAsString("quesTargetCode");
		
		if(applicationCode != null){

			BaseEntity application = rules.getBaseEntityByCode(applicationCode);
			rules.set("applicationBe", application);

			/* get begCode(attribute) from application */
			String begCode = application.getLoopValue("PRI_BEG_CODE", null);

			if(begCode != null) {

				BaseEntity beg = rules.getBaseEntityByCode(begCode);
				rules.set("begBe", beg);

				BaseEntity company = rules.getChildren(begCode, "LNK_BEG", "COMPANY");
				BaseEntity creator = rules.getChildren(begCode, "LNK_BEG", "CREATOR");

				if(company == null){
					rules.println("company is null");

				}else if(creator == null) {
					rules.println("creator is null");

				}else{
					rules.set("companyBe", company);
					rules.set("creatorBe", creator);
					rules.set("applicantBe", rules.getUser());

					rules.setState("LINK_BEG_AND_APPLICATION");
					rules.setState("SUBMIT_APPLY_BEG_TRIGGERED");

				}
			}else{
				rules.println("begCode is null");
			}
		}else{
			rules.println("applicationCode is null");
		}
		rules.footer();
end
