package life.genny.rules;

import life.genny.qwanda.message.QEventAttributeValueChangeMessage;
import life.genny.qwanda.Answer;
import io.vertx.core.json.JsonObject;
import life.genny.rules.QRules;

rule "Inference Gender Change"
    when
        $m: QEventAttributeValueChangeMessage( event_type == "EVT_ATTRIBUTE_VALUE_CHANGE" && data.code == "PRI_FIRSTNAME" )
        rules: QRules()
 
     then    
        rules.header();
        String userCode =  rules.getUser().getCode();  
		String firstName=  $m.getAnswer().getValue();
         
        rules.println("QEventAttributeValueChangeMessage   ::    " +$m); 
        rules.println("Attribute Code changed              ::    " +$m.data.getCode()); 
		
        JsonObject genderObj = new JsonObject( QwandaUtils.apiGet("https://api.genderize.io/?name=" +firstName , null));
        String gender = genderObj.getString("gender");    
        Double weight = genderObj.getDouble("probability");  

        rules.println("GENDER OBJECT   ::   "+genderObj.toString());
        rules.println("gender   ::   " + gender);
        rules.println("weight   ::   " + weight);
       
        if(gender !=null ) {            
            Answer genderAnswer = new Answer(userCode, userCode, "PRI_GENDER", gender);
            genderAnswer.setWeight(weight);
            genderAnswer.setInferred(true);
            RulesUtils.println(genderAnswer);
            rules.saveAnswer(genderAnswer);
        }else{
            rules.println("Sorry, No Inferred Rule was executed ");
        }
        rules.footer();
end