package com.sample;

import life.genny.qwanda.message.QEventMessage;
import life.genny.qwanda.message.QCmdMessage;
import life.genny.qwanda.message.QMessage.MessageData;
import io.vertx.rxjava.core.eventbus.EventBus;
import life.genny.qwandautils.QwandaUtils;
import io.vertx.core.json.JsonObject;
import com.google.gson.Gson;
import com.sample.*;
import java.util.Map;
import java.util.HashSet;
import java.util.Set;
import life.genny.qwanda.entity.User;

global java.lang.String REACT_APP_QWANDA_API_URL;



rule "test-realm Name"
   when
      $map : Map($value: this["token"] != null)
      $map1 : Map($value1: this["realm"] == "memberhub")
   then
      System.out.println("-------- Rule:- Test Realm Name --------");	
      System.out.println(" #######    Rule : test-realm name memberhub ###### ");
      System.out.println(" #######    PRJ- memberhub   ###### ");
      System.out.println(" Hello! You belong to project "+ $map1.get("realm")); 

end



