package life.genny.rules;

import life.genny.rules.QRules;
import life.genny.qwanda.message.QEventMessage;
import life.genny.rules.RulesUtils;
import life.genny.qwandautils.PaymentUtils;

rule "User Payments Methods"
    when
        m : QEventMessage( event_type == "PAYMENT_METHODS" && data.code == "PAYMENT_METHODS" )
 		rules: QRules( !isState("USER_PAYMENT_METHOD_CREATED") )

    then

    	rules.header();

    	/* Save token answers */
        String assemblyAuthKey = PaymentUtils.getAssemblyAuthKey();
       	String assemblyId = rules.getBaseEntityValueAsString(rules.getUser().getCode(), "PRI_ASSEMBLY_USER_ID");

       	if(assemblyId != null) {

       		RulesUtils.println("Refreshing tokens");
  			String oneTimeTransactionToken = null;
       		oneTimeTransactionToken = PaymentUtils.fetchOneTimeAssemblyToken(rules.getQwandaServiceUrl(), rules.getUser().getCode(), rules.getToken(), assemblyId, assemblyAuthKey);
						Answer cardTokenAnswer = new Answer(rules.getUser().getCode(), rules.getUser().getCode(), "PRI_ASSEMBLY_CARD_TOKEN", oneTimeTransactionToken);
						rules.publishData(cardTokenAnswer);

						Answer bankTokenAnswer = new Answer(rules.getUser().getCode(), rules.getUser().getCode(), "PRI_ASSEMBLY_BANK_TOKEN", oneTimeTransactionToken);
						rules.publishData(bankTokenAnswer);
       	}
       	
        String userCode = rules.getUser().getCode();
        rules.sendQuestions(userCode, userCode, "QUE_PAYMENT_METHOD_GRP", true);
 		rules.sendSublayout("PAYMENT_METHODS", "user-profile-payment-methods.json");

 		rules.setState("USER_PAYMENT_METHOD_CREATED");

		rules.footer();
end

