package life.genny.rules;

import life.genny.rules.RulesUtils;
import life.genny.rules.QRules;

import life.genny.qwanda.message.QEventMessage;
import life.genny.qwanda.entity.BaseEntity;


rule "User-Profile"
    when
       m : QEventMessage( event_type == "PROFILE" && data.code == "PROFILE"  )
       rules: QRules( isState("STARTED") ) 
    then
         rules.header();
  	    String userCode = rules.getUser().getCode();
  	    
        rules.sendQuestions(userCode,userCode,"QUE_USER_PROFILE_GRP", false);
       /*  Get Company Code of the current user   */
        BaseEntity company = rules.getParent(userCode, "LNK_STAFF");
        if(company != null)
        {
            rules.println("Company BE is  :: "+company.toString());
            String companyCode = company.getCode();
            rules.println("The Company Code is :: "+companyCode);
           /*    Send Company asks   */       
            rules.sendQuestions(userCode, companyCode, "QUE_USER_COMPANY_GRP", false);
            
        }
        
        /*  Send Bank Details asks   */ 
          rules.sendQuestions(userCode, userCode, "QUE_PAYMENT_METHOD_GRP", false);
        /*  Send User Documents asks   */ 
          rules.sendQuestions(userCode, userCode, "QUE_USER_DOCUMENTS_GRP", false);
          
	   /* Send SubLayout  */	
		rules.sendSublayout("SUB_USER_PROFILE", "user-profile.json");
		
		
         
       rules.footer(); 
end

