package life.genny.rules;

import life.genny.rules.QRules;
import life.genny.qwanda.message.QEventMessage;

rule "Payment Methods user"
    when
        m : QEventMessage( event_type == "PAYMENT_METHODS" && data.code == "PAYMENT_METHODS" )
 		rules: QRules() 
    then
       
    		rules.header();
    		
    		/* Save token answers */
    		String assemblyAuthKey = PaymentUtils.getAssemblyAuthKey();
       	String assemblyId = rules.getBaseEntityValueAsString(rules.getUser().getCode(), "PRI_ASSEMBLY_USER_ID");
       	
       	if(assemblyId != null) {
       		PaymentUtils.saveTokenAnswers(rules.getQwandaServiceUrl(), rules.getUser().getCode(), rules.getToken(), assemblyId, assemblyAuthKey);
       	}
    		
        
        String userCode = rules.getUser().getCode();
        rules.sendQuestions(userCode, userCode, "QUE_PAYMENT_METHOD_GRP", true);
 		rules.sendSublayout("PAYMENT_METHODS", "user-profile-payment-methods.json");
        
		rules.footer();      
end 