package life.genny.rules;

import life.genny.rules.QRules;

rule "Pre Init Startup"
	no-loop true
	ruleflow-group 'Init'
    when
       m : QEventMessage( event_type == "EVT_MSG" && "INIT_STARTUP"  == data.code)
          rules: QRules(!isState("STARTED")) 
     then    
        rules.setDrools(drools);
         rules.println("RULE INIT STARTUP: Realms "+rules.realm());
 
        rules.setState("GENERATE_STARTUP");
        rules.setState("STARTED");
		
		/* set up a service user for each realm */
			if (rules.loadRealmData() ) {
		
				drools.setFocus("GenerateReports");
				drools.setFocus("GenerateSearches");
        		drools.setFocus("GenerateTree");
        		drools.setFocus("GenerateCaches");
        	}
       		      
end
