package life.genny.rules;

import life.genny.rules.QRules;

rule "Pre Init Generate Reports"
	no-loop true
	ruleflow-group 'Init'
    when
       m : QEventMessage( event_type == "EVT_MSG" && "GEN_REPORTS"  == data.code)
          rules: QRules(!isState("STARTED")) 
     then    
        rules.setDrools(drools);
         rules.println("RULE INIT GENERATE REPORTS: "+ m );
 
        rules.setState("GENERATE_REPORTS");
        rules.setState("STARTED");
		
        	drools.setFocus("GenerateReports");
       		      
end
