package life.genny.rules;

import life.genny.qwanda.message.QEventMessage;
import life.genny.rules.QRules;
import life.genny.utils.VertxUtils;
import java.time.Duration;
import java.time.LocalDateTime;

rule "Pre Init Auth Init"
	no-loop true
	ruleflow-group 'Init'
    when
          m : QEventMessage( event_type == "AUTH_INIT" && data.code == "AUTH_INIT"  )
          rules: QRules(!isState("STARTED")) 
     then    
        rules.setDrools(drools);
        rules.println("RULE INIT AUTH_INIT: "+m);
 		
 		/* Start init timer */
 		LocalDateTime start = LocalDateTime.now();
 		VertxUtils.putObject(rules.realm(), "TIMING", (String)rules.getDecodedTokenMap().get("session_state"), start);
 		rules.println("GOT TO HERE");
 		
 		/* create startup service token */
 		
         rules.setState("EVENT_AUTH_INIT");
        rules.setState("STARTED");

        
        rules.footer();
      		      
end
