package life.genny.rules;
import life.genny.rules.QRules;

rule "Ask Registration Question - BUYER"
    when
        rules: QRules(  isState("PRI_IS_BUYER") && 
                        isState("ASK_REGISTRATION_QUESTIONS") &&
                        !isState("LOOP_ASK_REGISTRATION_BUYER") )
    then
        rules.header();
        rules.setState("LOOP_ASK_REGISTRATION_BUYER");

        rules.askQuestions(rules.getUser().getCode(), rules.getUser().getCode(), "QUE_BUYER_GRP");
        rules.footer();
end
