package life.genny.rules;
import life.genny.rules.QRules;

rule "Ask Registration Question - SELLER"
    when
        rules: QRules(  isState("PRI_IS_SELLER") && 
                        isState("ASK_REGISTRATION_QUESTIONS") &&
                        !isState("LOOP_ASK_REGISTRATION_SELLER") )
    then
        rules.header();
		rules.setState("LOOP_ASK_REGISTRATION_SELLER");
        
		rules.askQuestions(rules.getUser().getCode(), rules.getUser().getCode(), "QUE_SELLER_GRP");
        rules.footer();
end
