package life.genny.rules;
import life.genny.rules.QRules;

rule "Trigger Registration Form Submit"
	when
	    rules: QRules((	isState("QUE_SELLER_GRP") || 
						isState("QUE_BUYER_GRP")) &&
						isState("EVENT_FORM_SUBMIT") &&
						!isState("LOOP_TRIGGER_REGISTRATION_FORM_SUMIT")) 
	 then
	 	rules.header();
		rules.setState("LOOP_TRIGGER_REGISTRATION_FORM_SUMIT");
		
		rules.setState("CHECK_USER_PHONE_NUMBER");
	 	rules.footer();      
end