package life.genny.rules;

import life.genny.rules.QRules;
import life.genny.qwanda.message.QEventMessage;
import life.genny.utils.VertxUtils;
import life.genny.qwandautils.QwandaMessage;
import life.genny.qwanda.message.QBaseMSGMessageTemplate;

	rule "Email unsubscription redirect"
		no-loop true
		when
			rules: QRules( isState("TRIGGER_APPLICATION") && 
        				   isState("APPLICATION_READY") &&
        				   isState("REDIRECT_EVENT") && 
        				   isState("LOOP_APPLICATION_READY_CHANNEL40") && 
        				   !isState("EMAIL_UNSUBSCRIBE") )
		then
			rules.header();
			rules.setState("EMAIL_UNSUBSCRIBE");
			
			BaseEntity userBe = rules.getUser();
			
			String templateCode = rules.getAsString("valueCode");
			rules.println("email unsubscription :: "+templateCode + ", data code ::"+rules.getAsString("dataCode"));
			
			/* temporary: save the template code into the cache for retrieval later */
			VertxUtils.putObject(rules.realm(), "MSG_TEMPLATE", rules.getUser().getCode(), rules.getAsString("valueCode"));
			
			/* get template */
			QBaseMSGMessageTemplate template = QwandaUtils.getTemplate( templateCode , rules.getToken());
			if(template != null) {
				String customQuestion = "Do you want to unsubscribe from the email with the subject - "+ template.getSubject() + "?";
				
				/* get the question that needs to be edited */
				QwandaMessage questions = rules.getQuestions(userBe.getCode(), userBe.getCode(), "QUE_EMAIL_UNSUBSCRIPTION_GRP");
				
				/* set custom question */
				questions = QwandaUtils.setCustomQuestion(questions, "PRI_IS_EMAIL_UNSUBSCRIBE", customQuestion);
				
				if(questions != null) {
					/* publish the custom question to user */
					rules.publishCmd(questions);
					rules.publishViewCmdMessage("FORM_VIEW", "QUE_EMAIL_UNSUBSCRIPTION_GRP");
				}
				
			}	
			
			rules.footer();
	end
