package life.genny.rules;

import life.genny.rules.QRules;
import life.genny.qwanda.message.QEventMessage;
import life.genny.utils.VertxUtils;


	rule "Email unsubscription redirect"
		no-loop true
		when
			rules: QRules( isState("TRIGGER_APPLICATION") && 
        				   isState("APPLICATION_READY") &&
        				   isState("REDIRECT_EVENT") && 
        				   isState("LOOP_APPLICATION_READY_CHANNEL40") && 
        				   !isState("EMAIL_UNSUBSCRIBE") )
		then
			rules.header();
			rules.setState("EMAIL_UNSUBSCRIBE");
			
			rules.println("email unsubscription :: "+rules.getAsString("valueCode") + ", data code ::"+rules.getAsString("dataCode"));
			
			/* temporary: save the template code into the cache for retrieval later */
			VertxUtils.putObject(rules.realm(), "MSG_TEMPLATE", rules.getUser().getCode(), rules.getAsString("valueCode"));
	
	     	rules.askQuestions(rules.getUser().getCode(), rules.getUser().getCode() , "QUE_EMAIL_UNSUBSCRIPTION_GRP");

			rules.footer();
	end
