package life.genny.rules;

import life.genny.rules.QRules;

rule "Pre Init"
    salience 60000
	no-loop true
    when
         m : QEventMessage( QEventMessage.getData().getCode().equals("AUTH_INIT") )
         rules: QRules(!isState("STARTED")) 
     then    
        rules.setDrools(drools);
        rules.header();
        rules.setState("STARTED");
        
        /* rules.startWorkflow("com.sample.bpmn.hello"); */
        rules.footer();
      		      
end
