package life.genny.rules;
import life.genny.rules.QRules;

rule "Trigger Send Internmatch Application Data"
    when
        rules: QRules(  isState("EXIT_INTERNMATCH_HOMEPAGE_LAYOUT") && 
                        isState("TRIGGER_INTERNMATCH_APPLICATION") && 
                        !isState("LOOP_TRIGGER_SEND_INTERNMATCH_APPLICATION_DATA") ) 
     then       
        rules.header();
        rules.setState("LOOP_TRIGGER_SEND_INTERNMATCH_APPLICATION_DATA");
        
        /* clear the state below: so that App Data is not sent again after Homepage is sent */
/*         rules.clearState("TRIGGER_INTERNMATCH_APPLICATION");
 */        rules.setState("TRIGGER_INTERNMATCH_APPLICATION_DATA");
        rules.footer(); 		      
end

