package life.genny.rules;
import life.genny.rules.QRules;

/* Send Company Questions */
rule "Ask Registration - Host Company - STEP 3"
    when
        rules: QRules(  isState("SEND_HOST_COMPANY_REGISTRATION_LAYOUT") &&
                        isState("SENT_HOST_COMPANY_QUESTION") &&
						isState("HOST_COMPANY_EXISTS") &&
        				isState("PROFILE_NOT_COMPLETED") &&
        				isState("PRI_IS_HOST_COMPANY") &&
        				isState("SENT_REGISTRATION_DATA") &&
						isState("SENT_QUESTION") && 
						isState("QUE_USER_HOST_COMPANY_GRP") &&
						!isState("LOOP_ASK_REGISTRATION_HOST_COMPANY_STEP3") ) 
     then 
 		rules.header();		
		rules.setState("LOOP_ASK_REGISTRATION_HOST_COMPANY_STEP3");
 		
		rules.set("subLayoutCode", "LAY_HOST_COMPANY");
		rules.set("subLayoutPath", "registration/hostcompany.json");
		rules.set("subLayoutRootCode", null);
		rules.set("subLayoutIsPopup", false);
		rules.setState("SEND_SUBLAYOUT");

		rules.setState("SENT_HOST_COMPANY_REGISTRATION_LAYOUT");
 		rules.footer();
end
