package life.genny.rules;


import life.genny.rules.QRules;



import life.genny.qwanda.Answer;
import life.genny.qwanda.message.QDataAnswerMessage;
import life.genny.qwanda.message.QEventAttributeValueChangeMessage;


rule "Timer test"
 /* timer (cron:* 0/1 * * * ?) */
 /* timer (int:5s)  */
/*  timer (int: 30s 10s; start=3-JAN-2010, end=5-JAN-2010) */
 timer ( int: 5s 10s ) 
     
    when
    rules : QRules()
	eval(true)
     then    
 		rules.setDrools(drools);
 		System.out.println("TIMER!!!"+rules.realm());
   
  
end