package life.genny.rules;

import life.genny.rules.RulesUtils;
import life.genny.rules.QRules;
import life.genny.qwanda.message.QDataPaymentsCallbackMessage;


rule "Assembly item callback"
	agenda-group "payment-callback"
	no-loop true
	when 
		m : QDataPaymentsCallbackMessage( QDataPaymentsCallbackMessage.getData_type().equals(QDataPaymentsCallbackMessage.class.getSimpleName()) )
		rules: QRules( isState("STARTED") && !isState("ITEM_CALLBACK") ) 
	then
		RulesUtils.header(drools.getRule().getName());
     	
     	rules.setState("ITEM_CALLBACK");
     			
		RulesUtils.footer(drools.getRule().getName());
end