// package life.genny.rules;
// import life.genny.rules.QRules;

// /* Send ROOT */
// rule "Send Root - INTERN" 
//     when    
//         rules: QRules(  isState("SEND_ROOT_INTERN") && 
//                         isState("PRI_IS_INTERN") && 
//                         (isState("PROFILE_IS_COMPLETED") || isState("PRI_IS_PROFILE_COMPLETED")) && 
//                         !isState("LOOP_SEND_ROOT_INTERN_STEP1") )
//      then
//      	rules.header();
//         rules.setState("LOOP_SEND_ROOT_INTERN_STEP1");
		
//         /* SEND ROOT BaseEntity */
//         rules.publishBaseEntityByCode("GRP_ROOT", null, null, recipient);			
//         rules.setState("SENT_ROOT_INTERN");

//         rules.setState("SEND_ROOT_KIDS_INTERN");
// 	    rules.footer();      		      
// end


