// package life.genny.rules;
// import life.genny.rules.QRules;

// /* Sends ROOT */
// rule "Send Application Data - INTERN" 
//     when    
//         rules: QRules(  isState("SEND_APPLICATION_DATA") && 
//                         isState("PRI_IS_INTERN") && 
//                         (isState("PROFILE_IS_COMPLETED") || isState("PRI_IS_PROFILE_COMPLETED")) && 
//                         !isState("LOOP_SEND_APPLICATION_DATA_INTERN_STEP1") )
//      then
//      	rules.header();
//         rules.setState("LOOP_SEND_APPLICATION_DATA_INTERN_STEP1");
		
//         /* SEND ROOT BaseEntity */
//         rules.publishCmd(rootKids, "GRP_ROOT", "LNK_CORE");
//         rules.publishBaseEntityByCode("GRP_ROOT", null, null, recipient);			
        
//         rules.setState("SENT_ROOT_APPLICATION_DATA_INTERN");

//         rules.setState("SEND_ROOT_KIDS_APPLICATION_DATA_INTERN");
// 	    rules.footer();      		      
// end`


