// package life.genny.rules;
// import life.genny.rules.QRules;

// /* Send GRP_AVAILABLE */
// rule "Send GRP_AVAILABLE - INTERN" 
//     when    
//         rules: QRules(  isState("SEND_GRP_AVAILABLE_INTERN") && 
//                         isState("SENT_ROOT_INTERN") && 
//                         isState("PRI_IS_INTERN") && 
//                         (isState("PROFILE_IS_COMPLETED") || isState("PRI_IS_PROFILE_COMPLETED")) && 
//                         !isState("LOOP_SEND_APPLICATION_DATA_INTERN_STEP1") )
//      then
//      	rules.header();
//         rules.setState("LOOP_SEND_APPLICATION_DATA_INTERN_STEP1");
		
//         /* subscribe to GRP_AVAILABLE  */
//         rules.subscribeUserToBaseEntity(rules.getUser().getCode(), "GRP_AVAILABLE");

//         /* send GRP_AVAILABLE as child of GRP_ROOT for list view */
//         rules.publishBaseEntityByCode("GRP_AVAILABLE", "GRP_ROOT", "LNK_CORE", {rules.getUser().getCode()} );
//         rules.setState("SENT_GRP_AVAILABLE_INTERN");

//         rules.setState("SEND_ROOT_KIDS_INTERN");
// 	    rules.footer();      		      
// end
