package life.genny.rules;

import life.genny.qwanda.message.QCmdMessage;
import life.genny.qwanda.message.QBulkMessage;
import life.genny.qwanda.message.QDataBaseEntityMessage;
import life.genny.qwanda.message.QEventMessage;
import life.genny.rules.QRules;
import io.vertx.core.json.JsonObject;
import java.util.List;
import java.util.ArrayList;
import life.genny.qwanda.entity.BaseEntity;
import life.genny.utils.VertxUtils;

rule "GenerateRoles - shared"

    ruleflow-group 'GenerateRoles'
    salience 200

     when
       rules: QRules(isState("GENERATE_STARTUP") && isState("GENERATE_CAPABILITIES") && !isState("GENERATED_ROLES"))
     then

    rules.header();

    rules.setState("GENERATED_ROLES");
	rules.println("Generating Roles for "+rules.realm());


    rules.footer();

end
