package life.genny.rules;


import life.genny.qwanda.message.QEventMessage;
import life.genny.rules.QRules;

/* TODO: Need to remove this ch40 specific rules to ch40 prj folder later, its kept here in shared folder only because
 * there is issue with startup rules being fired only from shared folder.
 * It will be moved once this issue is solved.
 */
rule "Generate ch40 Capabilities"

    ruleflow-group 'GenerateCapabilities'
    salience 680

     when
       rules: QRules( realm() == "channel40" && !isState("LOOP_GENERATE_CAPABILITIES_RULES") )
     then

        rules.header();
        rules.setState("LOOP_GENERATE_CAPABILITIES_RULES");
		rules.println("Generating specific capabilities for "+rules.realm());
		
		/* This was commented out because capabilities or not baseEntities... to be changed? */
	
		/* Capabilities filtered by role PRI_IS_BUYER */
		/*List<Answer> capabilitiesBuyer = new ArrayList<>();
		capabilitiesBuyer.add(new Answer("CAP_ADD_ITEM", "CAP_ADD_ITEM", "CAP_ADD_ITEM", "PRI_IS_BUYER"));
		capabilitiesBuyer.add(new Answer("CAP_DELETE_ITEM", "CAP_DELETE_ITEM", "CAP_DELETE_ITEM", "PRI_IS_BUYER"));
		capabilitiesBuyer.add(new Answer("CAP_READ_QUOTE", "CAP_READ_QUOTE", "CAP_READ_QUOTE", "PRI_IS_BUYER"));
		rules.baseEntity.saveAnswers(capabilitiesBuyer); */

		/* Capabilities filtered by role PRI_IS_SELLER */
		/* List<Answer> capabilitiesSeller = new ArrayList<>();
		capabilitiesSeller.add(new Answer("CAP_ACCEPT_QUOTE", "CAP_ACCEPT_QUOTE", "CAP_ACCEPT_QUOTE", "PRI_IS_SELLER"));
		capabilitiesSeller.add(new Answer("CAP_ADD_QUOTE", "CAP_ADD_QUOTE", "CAP_ADD_QUOTE", "PRI_IS_SELLER"));
		capabilitiesSeller.add(new Answer("CAP_DELETE_QUOTE", "CAP_DELETE_QUOTE", "CAP_DELETE_QUOTE", "PRI_IS_SELLER"));
		capabilitiesSeller.add(new Answer("CAP_LOCATE_USER", "CAP_LOCATE_USER", "CAP_LOCATE_USER", "PRI_IS_SELLER"));
		capabilitiesSeller.add(new Answer("CAP_MARK_DELIVERY", "CAP_MARK_DELIVERY", "CAP_MARK_DELIVERY", "PRI_IS_SELLER"));
		capabilitiesSeller.add(new Answer("CAP_MARK_PICKUP", "CAP_MARK_PICKUP", "CAP_MARK_PICKUP", "PRI_IS_SELLER"));
		capabilitiesSeller.add(new Answer("CAP_READ_NEW_ITEMS", "CAP_READ_NEW_ITEMS", "CAP_READ_NEW_ITEMS", "PRI_IS_SELLER"));
		capabilitiesSeller.add(new Answer("CAP_UPDATE_QUOTE", "CAP_UPDATE_QUOTE", "CAP_UPDATE_QUOTE", "PRI_IS_SELLER"));
		rules.baseEntity.saveAnswers(capabilitiesSeller); */


     rules.footer();
end
