package life.genny.rules;
import life.genny.rules.QRules;

/* Link HOST_COMPANY >>>> USER  */
rule "Create Host Company - STEP 3"
    when
        rules: QRules(  isState("LINK_HOST_COMPANY_TO_USER") &&
        					isState("LINKED_GRP_HOST_COMPANYS_TO_HOST_OMPANY") &&
        					isState("CREATED_LINK") &&
        					isState("HOSTCOMPANY") &&
						!isState("LOOP_CREATE_HOST_COMPANY_STEP3") ) 
     then 
 		rules.header();
		rules.setState("LOOP_CREATE_HOST_COMPANY_STEP3");

		BaseEntity company = rules.getAsBaseEntity("companyBe");
        if(company != null){
		
			/* link HOST_COMPANY to USER */
			rules.set("linkSourceCode", company.getCode());
			rules.set("linkTargetCode", rules.getUser().getCode());
			rules.set("linkCode", "LNK_STAFF");
			rules.set("linkValue", "STAFF");
			rules.set("linkWeight", 1.0);
			rules.setState("CREATE_LINK");

			rules.setState("LINKED_HOST_COMPANY_TO_USER");
			rules.setState("SEND_USER_QUESTION");
		}
		rules.footer();
end
