package life.genny.rules;


import life.genny.rules.QRules;
import life.genny.qwanda.Answer;
import life.genny.qwanda.message.QDataAnswerMessage;
import life.genny.rules.RulesUtils;

rule "Answer"
ruleflow-group 'Answer'
    when
        $m : QDataAnswerMessage( QDataAnswerMessage.getData_type().equals(Answer.class.getSimpleName()) )
        rules: QRules( isState("STARTED") && !isState("ANSWER_PROCESSED"))
    then    
        rules.header();
        	
        Answer[] answers = $m.getItems();
		if(answers != null && answers.length > 0) {
			
			Answer firstAnswer = answers[0];
			String attributeCode = firstAnswer.getAttributeCode();
			
				
			if(attributeCode.contains("ADDRESS_JSON")) {
				rules.processAddressAnswers($m);
			}
			else if(attributeCode.contains("PRI_RATING")) {
				rules.processAnswerRating($m, "PRI_DRIVER_RATING"); 
			}
			else if(attributeCode.equals("PRI_MESSAGE")) {
				rules.processAnswerMessage($m); 
			}
			else if(attributeCode.contains("PRI_PAYMENT_METHOD") && !rules.isState("PAYMENT_ANSWER")) {
				rules.setState("PAYMENT_ANSWER");
				drools.setFocus("makepayment");
			}
			else {
				rules.processAnswer($m); 
			}	
		}
	   
	   rules.setState("ANSWER_PROCESSED");
       rules.footer();
           
end


   