package life.genny.rules;

import life.genny.rules.QRules;
import life.genny.qwanda.message.QEventBtnClickMessage;

rule "Select New Role - Step 4"

	when
		 rules: QRules( 	isState("ROLE_SELECTION") && isState("COMPANY_EXISTS") &&
						!isState("CHECK_COMPANY_QUESTIONS") )   
	 then
	    rules.header();
		
		rules.setState("CHECK_COMPANY_QUESTIONS");
		
		BaseEntity companyBe = rules.getAsBaseEntity("baseEntity");	
		
		if(companyBe != null && rules.isMandatoryFieldsEntered(companyBe.getCode(), "QUE_USER_COMPANY_GRP")) {
			rules.setState("COMPANY_IS_READY");
		}
		else {
			rules.setState("COMPANY_IS_NOT_READY");
		}
		
	    rules.footer();     		      
end
