package life.genny.rules;

import life.genny.rules.QRules;
import life.genny.qwanda.entity.SearchEntity;
import life.genny.utils.VertxUtils;
import java.util.ArrayList;


rule "SBE_OWNERJOBS"
    no-loop true
    salience 550
    ruleflow-group 'GenerateReports'
    
    when
        rules: QRules( !isState("SBE_OWNERJOBS") )
     then
         rules.setState(drools.getRule().getName());
         
  	     SearchEntity report = new SearchEntity(drools.getRule().getName(),"Loads")
  	     .addColumn("PRI_NAME","Load Name")
  	     .addColumn("PRI_JOB_ID","Job ID")
  	     .addColumn("PRI_PICKUP_ADDRESS_FULL","Pickup Address")
  	     .addColumn("PRI_DESCRIPTION","Description")
  	     
  	     .addSort("PRI_NAME","Name",SearchEntity.Sort.ASC)
  	     
  	     .addFilter("PRI_CODE",SearchEntity.StringFilter.LIKE,"BEG_%")
  	     
  	     .setPageStart(0)
  	     .setPageSize(10000);
  	     
  	  /*   .setStakeholder(rules.getUser().getCode()); */
  	     
  		 rules.add("GRP","GRP_REPORTS_OWNER",report);
  		 
  	
  		 
end
