package life.genny.rules;
import life.genny.rules.QRules;

rule "Trigger Reactivate Application"
	when
		rules: QRules(  isState("EVENT_BTN_CLICK") &&
						isState("BTN_ACTIVATE_APPLICATION") && 
						!isState("LOOP_TRIGGER_ACTIVATE_APPLICATION")) 
	 then
	 	rules.header();
		rules.setState("LOOP_TRIGGER_ACTIVATE_APPLICATION");
		
	   	String applicationCode = rules.getAsString("itemCode");
		if(applicationCode != null){

			BaseEntity application = rules.getBaseEntityByCode(applicationCode);
			if(application != null){

				if(	application.getLoopValue("PRI_IS_DEACTIVATED", false) != null &&
					application.getLoopValue("PRI_IS_DEACTIVATED", false).
					equals("TRUE") ){

					rules.saveAnswer( new Answer( rules.getUser().getCode(), applicationCode, "PRI_IS_REJECTED", "FALSE" ) );
            		rules.updateBaseEntityStatus(applicationCode, rules.getUser().getCode(), "green");            
				}
				if(	application.getLoopValue("PRI_IS_REJECTED", false) != null &&
					application.getLoopValue("PRI_IS_REJECTED", false).
					equals("TRUE") ){

					rules.saveAnswer( new Answer( rules.getUser().getCode(), applicationCode, "PRI_IS_REJECTED", "FALSE" ) );
            		rules.updateBaseEntityStatus(applicationCode, rules.getUser().getCode(), "green");            
				}
			}else{
				rules.println("application is null");
				return;
			}

			rules.setState("APPLICATION_IS_ACTIVATED");

		}else{
			rules.println("applicationCode is null");
			return;

		}
	 	rules.footer();      
end
