package life.genny.rules;
import life.genny.rules.QRules;

/* Host Company Accepts Offer */
rule "Accept Offer - Host Company"
	when
		rules: QRules( 	isState("EVENT_FORM_SUBMIT") && 
						isState("QUE_HOST_COMPANY_AGREEMENT_GRP") && 
						isState("SUBMIT") && 
						isState("PRI_IS_HOST_COMPANY") && 
						!isState("LOOP_HOST_COMPANY_ACCEPT_OFFER") ) 
	 then
	 	rules.header();
        rules.setState("LOOP_HOST_COMPANY_ACCEPT_OFFER");

		String begCode = rules.getAsString("quesTargetCode");

		rules.println("rule was executed");

		if(begCode != null){
			rules.println("begCode    ::   " + begCode);
			
			rules.saveAnswer( new Answer(rules.getUser().getCode(), begCode, "PRI_INTERN_ACCEPTED", "TRUE") );
			rules.saveAnswer( new Answer(rules.getUser().getCode(), begCode, "PRI_HOST_COMPANY_ACCEPTED", "TRUE") );
			rules.saveAnswer( new Answer(rules.getUser().getCode(), begCode, "PRI_EDU_PROVIDER_ACCEPTED", "TRUE") );

            rules.setState("HOST_COMPANY_ACCEPTED_OFFER");

            rules.setState("CHECK_OFFER_ACCEPTED");
         	rules.setState("TRIGGER_INTERNMATCH_HOMEPAGE");
         }
	 	rules.footer();      
end
