package life.genny.rules;
import life.genny.rules.QRules;

/* Trigger Duplicate BEG */
rule "Trigger Duplicate BEG"
	when
		rules: QRules( 	isState("TRIGGER_DUPLICATE_BEG") && 
						isState("QUE_INTERNSHIP_ADDITIONAL_GRP") && 
						isState("EVENT_FORM_SUBMIT") && 
						isState("SUBMIT") &&
						!isState("LOOP_TRIGGER_DUPLICATE_BEG") ) 
	 then
	 	rules.header();
        rules.setState("LOOP_TRIGGER_DUPLICATE_BEG");

		rules.setState("CREATE_NEW_BEG");	
	 	rules.footer();      
end
