package life.genny.rules;
import life.genny.rules.QRules;

/* LINK GRP_APPLIED TO NEW_BEG */
rule "Duplicate BEG - Step 10"
	when
        rules: QRules(  isState("LINK_GRP_APPLIED_TO_NEW_BEG_APPLY_INTERNSHIP") &&
		                isState("PUBLISHED_NEW_BEG_AND_KIDS_APPLY_INTERNSHIP") &&
						!isState("LOOP_DUPLICATE_BEG_STEP10"))
	 then
	 	rules.header();
        rules.setState("LOOP_DUPLICATE_BEG_STEP10");

        BaseEntity newBeg = rules.getAsBaseEntity("newBegBe");

        if(newBeg == null){
            rules.println("newBeg is null");
        }else{
            /* link GRP_APPLIED to NEW_BEG || BEG */
            rules.set("linkSourceCode", "GRP_APPLIED");
            rules.set("linkTargetCode", newBeg.getCode());
            rules.set("linkCode", "LNK_CORE");
            rules.set("linkValue", "BEG");
            rules.set("linkWeight", 1.0);
            rules.setState("CREATE_LINK");

            rules.setState("LINKED_GRP_APPLIED_TO_NEW_BEG_APPLY_INTERNSHIP");
            rules.setState("TRIGGER_INTERNMATCH_HOMEPAGE_LAYOUT");

            // trigger applied messages
            rules.setState("SEND_APPLIED_MESSAGE_TO_INTERN");
            rules.setState("SEND_APPLIED_MESSAGE_TO_HOSTCOMPANY");
            rules.setState("SEND_APPLIED_MESSAGE_TO_EDU_PROVIDER");
        }
	 	rules.footer();
end
