package life.genny.rules;
import life.genny.rules.QRules;

/* Duplicate BEG */
rule "Duplicate BEG - Step 1"
	when
		rules: QRules( 	isState("CREATE_NEW_BEG_APPLY_INTERNSHIP") &&
						!isState("LOOP_DUPLICATE_BEG_STEP1") )
	 then
	 	rules.header();
        rules.setState("LOOP_DUPLICATE_BEG_STEP1");
		rules.setState("CREATED_NEW_BEG_APPLY_INTERNSHIP");

		/* Create BEG BaseEntity*/
		rules.set("beCode", rules.getUser().getCode());
		rules.set("bePrefix", "BEG");
		rules.set("beName", "BEG");
		rules.setState("CREATE_BASE_ENTITY");

	 	rules.footer();
end
