package life.genny.rules;
import life.genny.rules.QRules;

/* LINK BEG + APPLICATION || APPLICATION */
rule "Duplicate BEG - Step 3"
	when
		rules: QRules(  isState("LINK_NEW_BEG_TO_APPLICATION") && 
						isState("COPIED_LINKS_FROM_OLD_BEG") && 
						isState("QUE_INTERNSHIP_ADDITIONAL_GRP") &&
						!isState("LOOP_SUBMIT_APPLY_INTERNSHIP_STEP3")) 
	 then
	 	rules.header();

        rules.setState("LOOP_SUBMIT_APPLY_INTERNSHIP_STEP3");

        BaseEntity application = rules.getAsBaseEntity("applicationBe");
        BaseEntity newBeg = rules.getAsBaseEntity("newBegBe");
        
        if(application == null){
            rules.println("application is null");    
        }else if(newBeg == null){
            rules.println("newBeg is null");    
        }else{

            /* link NEW BEG to APP || APPLICATION */
            rules.set("linkSourceCode",  newBeg.getCode());
            rules.set("linkTargetCode", application.getCode());
            rules.set("linkCode", "LNK_BEG");
            rules.set("linkValue", "APPLICATION");
            rules.set("linkWeight", 1.0);
            rules.setState("CREATE_LINK");

            rules.setState("LINKED_NEW_BEG_TO_APPLICATION");

            rules.setState("LINK_NEW_BEG_TO_INTERN");
        }

        rules.footer();
end