package life.genny.rules;
import life.genny.rules.QRules;

/* LINK BEG + APPLICATION || APPLICATION */
rule "Duplicate BEG - Step 3"
	when
		rules: QRules(  isState("COPIED_LINKS_FROM_OLD_BEG_APPLY_INTERNSHIP") &&
						isState("CREATED_LINK") &&
						!isState("LOOP_DUPLICATE_STEP3"))
	 then
	 	rules.header();

        rules.setState("LOOP_DUPLICATE_STEP3");

        BaseEntity application = rules.getAsBaseEntity("applicationBe");
        BaseEntity newBeg = rules.getAsBaseEntity("newBegBe");

        if(application == null){
            rules.println("application is null");
        }else if(newBeg == null){
            rules.println("newBeg is null");
        }else{
        	
            rules.setState("LINKED_NEW_BEG_TO_APPLICATION_APPLY_INTERNSHIP");

            /* link NEW BEG to APP || APPLICATION */
            rules.set("linkSourceCode",  newBeg.getCode());
            rules.set("linkTargetCode", application.getCode());
            rules.set("linkCode", "LNK_BEG");
            rules.set("linkValue", "APPLICATION");
            rules.set("linkWeight", 1.0);
            rules.setState("CREATE_LINK");
        }

        rules.footer();
end
