package life.genny.rules;
import life.genny.rules.QRules;
import life.genny.utils.VertxUtils;

/* Subscribe CREATOR to NEW_BEG */
rule "Duplicate BEG - Step 5"
	when
		rules: QRules( 	isState("SUBSCRIBE_CREATOR_TO_NEW_BEG") && 
						isState("LINKED_NEW_BEG_TO_INTERN") && 
						isState("QUE_INTERNSHIP_ADDITIONAL_GRP") && 
						isState("EVENT_FORM_SUBMIT") && 
						isState("SUBMIT") &&
						!isState("LOOP_DUPLICATE_BEG_STEP5")) 

	 then
	 	rules.header();
        rules.setState("LOOP_DUPLICATE_BEG_STEP5");

        BaseEntity creator = rules.getAsBaseEntity("creatorBe");
        BaseEntity newBeg = rules.getAsBaseEntity("newBegBe");
		
		if(creator != null && newBeg != null){
			rules.subscribeUserToBaseEntityAndChildren(creator.getCode(), newBeg.getCode(), "LNK_BEG");
	 		rules.setState("SUBSCRIBED_CREATOR_TO_NEW_BEG");

	 		rules.setState("SUBSCRIBE_COMPANY_TO_NEW_BEG");
		}
	 	rules.footer();      
end
