package life.genny.rules;
import life.genny.rules.QRules;
import life.genny.utils.VertxUtils;

/* Subscribe COMPANY to NEW_BEG */
rule "Duplicate BEG - Step 6"
	when
		rules: QRules( 	isState("SUBSCRIBED_CREATOR_TO_NEW_BEG_APPLY_INTERNSHIP") &&
						!isState("LOOP_SUBMIT_APPLY_INTERNSHIP_STEP6"))

	 then
	 	rules.header();
        rules.setState("LOOP_SUBMIT_APPLY_INTERNSHIP_STEP6");

        BaseEntity company = rules.getAsBaseEntity("companyBe");
        BaseEntity newBeg = rules.getAsBaseEntity("newBegBe");

		if(company != null && newBeg != null){
			rules.subscribeUserToBaseEntityAndChildren(company.getCode(), newBeg.getCode(), "LNK_BEG");
	 		rules.setState("SUBSCRIBED_COMPANY_TO_NEW_BEG_APPLY_INTERNSHIP");
		}
	 	rules.footer();
end
