package life.genny.rules;
import life.genny.rules.QRules;
import life.genny.utils.VertxUtils;

/* Subscribe INTERN to NEW_BEG */
rule "Duplicate BEG - Step 7"
	when
		rules: QRules( 	isState("SUBSCRIBE_INTERN_TO_NEW_BEG") && 
						isState("SUBSCRIBED_COMPANY_TO_NEW_BEG") && 
						isState("QUE_INTERNSHIP_ADDITIONAL_GRP") && 
						isState("EVENT_FORM_SUBMIT") && 
						isState("SUBMIT") &&
						!isState("LOOP_DUPLICATE_BEG_STEP7")) 

	 then
	 	rules.header();
        rules.setState("LOOP_DUPLICATE_BEG_STEP7");

        BaseEntity intern = rules.getAsBaseEntity("internBe");
        BaseEntity newBeg = rules.getAsBaseEntity("newBegBe");
		
		if(intern != null && newBeg != null){
			rules.subscribeUserToBaseEntityAndChildren(intern.getCode(), newBeg.getCode(), "LNK_BEG");
	 		rules.setState("SUBSCRIBED_INTERN_TO_NEW_BEG");

	 		rules.setState("SUBSCRIBE_EDU_PROVIDER_TO_NEW_BEG");
		}
	 	rules.footer();      
end