package life.genny.rules;
import life.genny.rules.QRules;

rule "Add To Freight Owner Group"
     when
        rules: QRules(  isState("ADD_TO_GROUP") && 
						isState("PRI_IS_FREIGHT_OWNER") &&
						!isState("LOOP_ADD_TO_FREIGHT_OWNER_GROUP") )
     then
        rules.header();
		rules.setState("LOOP_ADD_TO_FREIGHT_OWNER_GROUP");
     	
     	/* link Freight Owner to GRP_FREIGHT_OWNERS */
        rules.set("linkSourceCode",  "GRP_FREIGHT_OWNERS");
        rules.set("linkTargetCode", rules.getUser().getCode());
        rules.set("linkCode", "LNK_CORE");
        rules.set("linkValue", "FREIGHT_OWNER");
        rules.set("linkWeight", 1.0);
        rules.setState("CREATE_LINK");

     	rules.setState("ADDED_TO_FREIGHT_OWNER_GROUP");
        rules.setState("ADDDED_TO_GROUP");         
	    rules.footer();     		      
end
     	