package life.genny.rules;
import life.genny.rules.QRules;

/* Exit Sending TreeView / Buckets / BEGs / BEG KIDs */
rule "Exit Internmatch Application Data"
    when
         rules: QRules( isState("SENT_INTERNMATCH_APPLICATION_DATA") && 
                        !isState("LOOP_EXIT_INTERNMATCH_APPLICATION_DATA") )
     then
     	rules.header();
        rules.setState("LOOP_EXIT_INTERNMATCH_APPLICATION_DATA");
    
        rules.footer();      		      
end