package life.genny.rules;
import life.genny.rules.QRules;

/* Sends TreeView / Buckets / BEGs / BEG KIDs */
rule "Trigger Internmatch Application Data"
    when    
         rules: QRules( isState("TRIGGER_INTERNMATCH_APPLICATION_DATA") && 
                        !isState("LOOP_TRIGGER_INTERNMATCH_APPLICATION_DATA") )
     then
     	rules.header();
        rules.setState("LOOP_TRIGGER_INTERNMATCH_APPLICATION_DATA");
        
        rules.setState("SEND_INTERNMATCH_APPLICATION_DATA");
	    rules.footer();      		      
end
