package life.genny.rules;
import life.genny.rules.QRules;

rule "User Submitted PassCode Verification"
	when
	    rules: QRules( 	isState("QUE_MOBILE_VERIFICATION_GRP") &&
						isState("EVENT_FORM_SUBMIT") &&
						!isState("LOOP_USER_ACCEPTED_MOBILE_VERIF")) 
	 then
	 	rules.header();
        
		rules.setState("LOOP_USER_ACCEPTED_MOBILE_VERIF");
		rules.clearState("LOOP_VERIFY_MOBILE_PHONE_NUMBER");
		rules.clearState("MOBILE_VERIFICATION_REQUIRED");
		rules.setState("VERIFY_USER_PASSCODE");
		
	 	rules.footer();      
end