package life.genny.rules;
import life.genny.rules.QRules;

rule "Passcode Verification Failed"
	when
	    rules: QRules( 	isState("VERIFY_USER_PASSCODE") &&
						isState("PASSCODE_VERIFICATION_FAILED") &&
						!isState("LOOP_USER_PASSCODE_VERIFICATION_FAILED")) 
	 then
	 	rules.header();
        
			rules.setState("LOOP_USER_PASSCODE_VERIFICATION_FAILED");
			String userCode = rules.getAsString("targetCode");
			if(userCode != null){
				String[] recipients = { userCode };
				HashMap<String, String> contextMap = new HashMap<String, String>();
				contextMap.put("USER", userCode);		
				rules.println("The String Array is ::" + Arrays.toString(recipients));
				/* Sending sms message to user */
				rules.sendMessage(recipients, contextMap, "GNY_PASSCODE_VERIFICATION_FAILURE", "TOAST");
				rules.setState("ERROR_MESSAGE_SENT");
		    }else{
		    		rules.println("Error!! userCode is null");
		    }
		
	 	rules.footer();      
end