package life.genny.rules;

import life.genny.rules.QRules;
import life.genny.qwanda.entity.BaseEntity;

rule "Mobile verification is completed"
    when
        rules: QRules( isState("PASSCODE_VERIFICATION_SUCCEEDED") && !isState("LOOP_MOBILE_VERIFICATION_SUCCESS") )
    then
        rules.header();
        
		rules.setState("LOOP_MOBILE_VERIFICATION_SUCCESS");
        rules.setState("CHECK_USER_COMPANY");
		
        rules.footer();
end
