package life.genny.rules;
import life.genny.rules.QRules;

rule "Completed Internship - Step 0"
	when
		rules: QRules( 	isState("BTN_COMPLETE_INTERN") && 
						isState("EVENT_BTN_CLICK") && 
						!isState("LOOP_COMPLETED_INTERNSHIP_STEP0") ) 
	 then
	 	rules.header();
        rules.setState("LOOP_COMPLETED_INTERNSHIP_STEP0");

		String begCode = rules.getAsString("itemCode");

		if(begCode == null){
            rules.println("begCode is null");
			return;
        }else{
			rules.moveBaseEntity(begCode, "GRP_IN_PROGRESS", "GRP_COMPLETED", "LNK_CORE");
        }
	 	rules.footer();      
end