// package life.genny.rules;

// import life.genny.rules.QRules;


// rule "Send Questions To Frontend - Memberhub"
//     when
//         rules: QRules( isState("LAYOUT_CHANGE_READY") && isRealm("memberhub") && !isState("MEMBERHUB_QUESTIONS_READY") ) 
//      then
//      	rules.header();
//      	String userCode =  rules.getUser().getCode();  
        
//         rules.sendQuestions(userCode, userCode, "QUE_MEMBERHUB_GRP", false); /* false for form_view*/
//         rules.setState("MEMBERHUB_QUESTIONS_READY");
		
// 	    rules.footer();    		      
// end
