package com.sample;

import life.genny.qwanda.message.QBaseMSGMessage;
import life.genny.qwanda.message.QBaseMSGMessageType;
import io.vertx.rxjava.core.eventbus.EventBus;
import io.vertx.core.json.JsonObject;
import io.vertx.core.json.JsonArray;


rule "msg"
	date-expires "20-JUN-1964"	
    when
        $obj: Object()
        bus: EventBus()
        eval(false)
    then 
    	   QBaseMSGMessage msgMessage = new QBaseMSGMessage();
       msgMessage.setMsgMessageType(QBaseMSGMessageType.EMAIL);
       msgMessage.setMsgMessageData("hello world");
       msgMessage.setSource("genny.life.user@gmail.com");
       msgMessage.setTarget("rpgayatri@gmail.com");
       msgMessage.setSubject("test_subject");
       
       String[] emailAttachments = {};
       msgMessage.setAttachments(emailAttachments);
       
       QBaseMSGMessage msgMessage1 = new QBaseMSGMessage();
       msgMessage1.setMsgMessageType(QBaseMSGMessageType.EMAIL);
       msgMessage1.setMsgMessageData("hello world again");
       msgMessage1.setSource("genny.life.user@gmail.com");
       msgMessage1.setTarget("rpgayatri@gmail.com");
       msgMessage1.setSubject("test_subject_something");
       
       String[] emailAttachments1 = {};
       msgMessage1.setAttachments(emailAttachments1);
       
       
     /*  List<QBaseMSGMessage> msgList = new ArrayList<QBaseMSGMessage>();
       msgList.add(msgMessage);
       msgList.add(msgMessage1);
       
       
      JsonObject data = new JsonObject();
       data = JsonObject.mapFrom(msgMessage);
       
       JsonObject data1 = new JsonObject();
       data1 = JsonObject.mapFrom(msgMessage1);
       
       JsonArray msglist2 = new JsonArray();
       msglist2.add(data);
       msglist2.add(data1);    
       
           
       JsonObject eventMsg = new JsonObject();
       eventMsg.put("msg_type", "EVT_MSG");
       eventMsg.put("event_type", "message");
       eventMsg.put("msgMessageData", msglist2);
       
       bus.publish("messages", eventMsg);
 */
end

	