package life.genny.rules;
import life.genny.rules.QRules;

/* LINK BEG + USER || APPLICANT */
rule "Submit Apply Internship - Step 5_5"
	when
		rules: QRules( 	isState("LINK_BEG_TO_INTERN") && 
		                isState("LINKED_BEG_TO_APPLICATION") && 
                        isState("CREATED_LINK") && 
						isState("APPLICATION") && 
		                isState("QUE_INTERNSHIP_ADDITIONAL_GRP") && 
						isState("EVENT_FORM_SUBMIT") && 
						isState("SUBMIT") && 
						!isState("LOOP_SUBMIT_APPLY_INTERNSHIP_STEP5_5")) 
	 then
	 	rules.header();
        rules.setState("LOOP_SUBMIT_APPLY_INTERNSHIP_STEP5_5");

        /* get application from state map */
        BaseEntity beg = rules.getAsBaseEntity("begBe");
        
        if(beg != null){   
            /* link BEG to USER || APPLICANT */
            rules.set("linkSourceCode", beg.getCode());
            rules.set("linkTargetCode", rules.getUser().getCode());
            rules.set("linkCode", "LNK_BEG");
            rules.set("linkValue", "INTERN");
            rules.set("linkWeight", 1.0);
            rules.setState("CREATE_LINK");

            rules.setState("LINKED_BEG_TO_INTERN");
            
            rules.setState("PUBLISH_APPLICATION_TO_BUCKET");

        }else{
            rules.println("application BaseEntity is null");
        }
	 	rules.footer();
end