package life.genny.rules;
import life.genny.rules.QRules;
import life.genny.utils.VertxUtils;

/* Publish APPLICATION, INTERN BaseEntity To Bucket */
rule "Submit Apply Internship - Step 6"
	when
		rules: QRules( 	isState("LINKED_BEG_TO_INTERN") && 
						isState("PUBLISH_APPLICATION_TO_BUCKET") && 
						isState("CREATED_LINK") && 
						isState("INTERN") && 
						isState("EVENT_FORM_SUBMIT") && 
						isState("SUBMIT") && 
						!isState("LOOP_SUBMIT_APPLY_INTERNSHIP_STEP6") ) 
	 then
	 	rules.header();
        rules.setState("LOOP_SUBMIT_APPLY_INTERNSHIP_STEP6");
		
		/* get application, beg from state map */
        BaseEntity application = rules.getAsBaseEntity("applicationBe");
        BaseEntity beg = rules.getAsBaseEntity("begBe");
        BaseEntity companyStaff = rules.getAsBaseEntity("companyStaffBe");

		if(application != null){
			String[] applicationSubscribers = VertxUtils.getSubscribers(rules.realm(), application.getCode());

			BaseEntity applicant = rules.getChildren(application.getCode(), "LNK_APP", "APPLICANT");

			if(applicant == null){
				rules.println("applicant is null");
			}else{
				rules.publishBaseEntityByCode(beg.getCode(), "GRP_AVAILABLE", "LNK_BEG", applicationSubscribers);
				rules.publishBaseEntityByCode(application.getCode(), beg.getCode(), "LNK_BEG", applicationSubscribers);
				rules.publishBaseEntityByCode(applicant.getCode(), application.getCode(), "LNK_APP", applicationSubscribers);
				rules.publishBaseEntityByCode(rules.getUser().getCode(), beg.getCode(), "LNK_BEG", applicationSubscribers);
			}
			rules.setState("PUBLISHED_APPLICATION_TO_BUCKET");
			rules.setState("GO_TO_HOMEPAGE");
		}
	 	rules.footer();      
end
