package life.genny.rules;

import life.genny.rules.QRules;
import life.genny.qwanda.Answer;
import life.genny.qwanda.message.QEventAttributeValueChangeMessage;
import life.genny.utils.PaymentUtils;


rule "Step 1 for payments-company updation : Check if user belongs to company"
	ruleflow-group 'AttributeChange'
    when
    	m: QEventAttributeValueChangeMessage( getAnswer().getTargetCode().startsWith("CPY_") )
    	rules: QRules(!isState("LOOP_COMPANY_UPDATE") )
    then
		rules.header();
		rules.setState("LOOP_COMPANY_UPDATE");
		
		BaseEntity userBe = rules.getUser();
		BaseEntity companyBe = rules.getParent(userBe.getCode(), "LNK_STAFF"); 
		
		if(companyBe != null) {
			drools.setFocus("payments-company-update");
		}
		
		rules.footer();
end