package life.genny.rules;

import life.genny.rules.QRules;
import life.genny.qwanda.message.QEventBtnClickMessage;

rule "Check user company - Are you a company?"
	when
		 rules: QRules( 	isState("ASK_USER_COMPANY") && !isState("ASKED_USER_COMPANY") )   
	 then
	    rules.header();
		
		rules.setState("ASKED_USER_COMPANY");
		rules.sendSublayout("are-you-a-company", "/registration/company_role_selection.json", true);
		rules.navigateTo("/questions/company_selection");
	    rules.footer();     		      
end
