package life.genny.rules;

import life.genny.rules.QRules;
import life.genny.qwanda.message.QEventBtnClickMessage;

rule "Check user company - step 1"
	/* no-loop true */
	when
		 rules: QRules( 	isState("CHECK_USER_COMPANY") && !isState("LOOP_CHECKED_COMPANY_EXIST") )
	 then
	    rules.header();

		rules.setState("LOOP_CHECKED_COMPANY_EXIST");

		BaseEntity userCompany = rules.baseEntity.getParent(rules.getUser().getCode(), "LNK_STAFF");
		rules.set("baseEntity", userCompany);

		if(userCompany == null) {
			rules.setState("COMPANY_DOES_NOT_EXIST");
		}
		else {
			rules.setState("COMPANY_EXISTS");
		}

	    rules.footer();
end
