package life.genny.rules;

import life.genny.rules.QRules;
import java.util.List;

rule "Check user company - Step 3.5"
     when
     	rules: QRules( 	isState("SET_COMPANY_ADMIN_ROLE") && !isState("DID_SET_COMPANY_ADMIN_ROLE") ) 
     then      
        rules.header();     

		rules.setState("DID_SET_COMPANY_ADMIN_ROLE");
		
		BaseEntity companyBe = rules.getAsBaseEntity("baseEntity");	
		
		/* we grab the company admin role */
        BaseEntity adminRole = rules.baseEntity.getRole("COMPANY_ADMIN");
        if(adminRole == null) {
        		rules.println("============================= AIE AIE ========================");
        }
		
        /* we attach the role to the company */
		rules.baseEntity.setRole(adminRole, companyBe);
		
		/* we attach the role to the user */
		rules.baseEntity.setRole(rules.getUser(), adminRole);

		rules.setState("COMPANY_EXISTS");

		rules.footer();     		      
end
     	