package life.genny.rules;

import life.genny.rules.QRules;
import life.genny.qwanda.message.QEventBtnClickMessage;

rule "Select Intern Role"
	when
		m : QEventBtnClickMessage( 	event_type == "BTN_CLICK" && 
									data.code == "BTN_SELECT_ROLE_INTERN" )
	    rules: QRules( 	isState("STARTED") && 
						!isState("INTERN_SELECTED") ) 	    
	 then
	    
		rules.header();
		rules.updateBaseEntityAttribute(rules.getUser().getCode(), rules.getUser().getCode(), "PRI_IS_INTERN", "TRUE");
		rules.updateBaseEntityAttribute(rules.getUser().getCode(), rules.getUser().getCode(), "PRI_IS_EDU_PROVIDER", "FALSE");
		rules.updateBaseEntityAttribute(rules.getUser().getCode(), rules.getUser().getCode(), "PRI_IS_HOST_COMPANY", "FALSE");
		rules.setState("INTERN_SELECTED");
	    rules.footer();     		      
end
