package life.genny.rules;

import life.genny.rules.QRules;
import life.genny.qwanda.message.QEventBtnClickMessage;

rule "Select Host Company Role"

	when
		$m : QEventBtnClickMessage( event_type == "BTN_CLICK" && data.code == "BTN_SELECT_ROLE_HOST_COMPANY")
	    rules: QRules( isState("STARTED") && !isState("HOST_COMPANY_SELECTED") ) 
	    
	 then
	    rules.header();
		rules.setState("HAS_SENT_SUBLAYOUT");
		rules.updateBaseEntityAttribute(rules.getUser().getCode(), rules.getUser().getCode(), "PRI_IS_HOST_COMPANY", "TRUE");
		rules.setState("HOST_COMPANY_SELECTED");
	    rules.footer();     		      
end
