package life.genny.rules;

import life.genny.rules.QRules;
import java.util.List;

rule "Selected Intern Role"
     when
        $m: QEventAttributeValueChangeMessage( QEventAttributeValueChangeMessage.getData().getCode().equals("PRI_IS_INTERN") )
        rules: QRules( isState("STARTED") && !isState("HAS_SELECTED_PROFILE_INTERN") )
     then

        rules.header();
		rules.setState("HAS_SELECTED_PROFILE_INTERN");

     	rules.set("registration_question_grp", "QUE_INTERN_GRP");
     	rules.sendSelections("GRP_UNI_SELECTION", "LNK_CORE", 10);
     	rules.sendSelections("GRP_DEGREE_SELECTION", "LNK_CORE", 10);
     	rules.sendSelections("GRP_GENDERS", "LNK_CORE", 10);
     	rules.sendSelections("GRP_RESIDENTIAL_STATUS", "LNK_CORE", 10);

		/* Add Intern to GRP_INTERNS */
    	rules.setState("TRIGGER_ADD_TO_GROUP");
    	rules.setState("TRIGGER_PROFILE_CHECK");

		rules.footer();
end
