package life.genny.rules;

import life.genny.rules.QRules;
import life.genny.qwanda.message.QEventBtnClickMessage;

rule "Select Buyer Role"
	when
	    rules: QRules( 	isState("BTN_SELECT_ROLE_BUYER") && isState("ROLE_SELECTION") &&
						!isState("BUYER_SELECTED") ) 	    
	 then
	    
		rules.header();
		
		rules.setState("BUYER_SELECTED");

		rules.updateBaseEntityAttribute(rules.getUser().getCode(), rules.getUser().getCode(), "PRI_IS_BUYER", "TRUE");
		rules.updateBaseEntityAttribute(rules.getUser().getCode(), rules.getUser().getCode(), "PRI_IS_SELLER", "FALSE");

	    rules.footer();     		      
end
