package life.genny.rules;

import life.genny.rules.QRules;


rule "TV_SELECT_DRAFT_JOBS"
	   no-loop true
       ruleflow-group 'TV_SELECT'
       salience 7
     when
       rules: QRules( isState("STARTED") && isState("EVENT_TV_SELECT") && isState("GRP_DRAFTS") &&
       							!isState("TV_DRAFTS_JOB_LIST_SENT"))
     then

     rules.header();

       rules.setState("TV_DRAFTS_JOBS_LIST_SENT");
       rules.setState("TV_SELECT_RULE_EXECUTED"); /* Need to set this state compulsarily as the default rule
         												 executes based on this state */
       Object parentCodeObj = rules.get("tvSelectValue");
       if(parentCodeObj != null){
           String parentCode = parentCodeObj.toString();
           if(parentCode != null && !parentCode.isEmpty()){
		       rules.println("The tvSelectValue value is:: "+parentCode);
			   SearchEntity searchBE = new SearchEntity(drools.getRule().getName(),"Draft Jobs")
		  	     .addSort("PRI_CREATED","Created",SearchEntity.Sort.DESC)
		  	     .setSourceCode(parentCode)
		  	     .setStakeholder(rules.getUser().getCode())
		  	     .addFilter("PRI_CODE",SearchEntity.StringFilter.LIKE,"BEG_%")
		  	     .setPageStart(0)
		  	     .setPageSize(10000);
	
		  	   /* Send search result */
		       rules.sendSearchResults(searchBE, parentCode);
	
		       /* Send ListView */
		       rules.publishViewCmdMessage("LIST_VIEW", parentCode);
		       rules.setState("TV_ITEM_DATA_SENT");
	       }
        }
        else{
            rules.println("Error!! The data.value/GRP code is null");
        }

     rules.footer();
end
