package life.genny.rules;

import life.genny.rules.QRules;


rule "TV_SELECT Individual History Jobs"
       no-loop true
       ruleflow-group 'TV_SELECT'
       salience 3
     when
       rules: QRules( isState("STARTED") && isState("EVENT_TV_SELECT") && isState("PARENT_GRP_HISTORY") &&
                     					   !isState("LOOP_TV_HISTORY_ITEM_DATA_SENT") ) 
     then
     
      rules.header();
       
       rules.setState("LOOP_TV_HISTORY_ITEM_DATA_SENT");
       rules.setState("TV_SELECT_RULE_EXECUTED");   /* Need to set this state compulsarily as the default rule
         												 executes based on this state */
       Object grpCodeObj = rules.get("tvSelectValue");
      
       if(grpCodeObj != null){
             String grpCode = grpCodeObj.toString();
             if(grpCode != null && !grpCode.isEmpty()){
             	rules.sendSublayout("LOAD_DETAILS", "loadLayout.json", grpCode); 
             }	 
        }
        else{
            rules.println("Error!! Either the data.value/GRP code or the user BE is null");
        }
        
     rules.footer();
end
