package life.genny.rules;

import life.genny.qwanda.message.QEventMessage;
import life.genny.qwanda.message.QCmdMessage;
import life.genny.rules.QRules;


rule "TV_SELECT_HISTORY"
       no-loop true
       ruleflow-group 'TV_SELECT'
       salience 3
     when
       rules: QRules( isState("STARTED") && isState("EVENT_TV_SELECT") &&
                       isState("GRP_HISTORY") && !isState("LOOP_TV_ITEM_HISTORY_DATA_SENT"))
     then

      rules.header();

          rules.setState("LOOP_TV_ITEM_HISTORY_DATA_SENT");
           String parentCode = rules.get("tvSelectValue").toString();

           if(parentCode != null){

              /* we send the archived paid products */
              rules.showLoading("Loading history...");
              rules.sendCachedItem("ARCHIVED_PRODUCTS");
     	        rules.publishViewCmdMessage("LIST_VIEW", parentCode);
            }
            else{
                rules.println("Error!! Either the data.value/GRP code or the user BE is null");
            }

     rules.footer();
end
