package life.genny.rules;
import life.genny.rules.QRules;

/* LINK BEG + USER || CREATOR */
rule "Submit Internship - Step 3"
	when
		rules: QRules( 	isState("LINKED_GRP_INTERNSHIPS_TO_BEG") && 
						isState("CREATED_LINK") && 
						isState("INTERNSHIP") && 
						isState("QUE_INTERNSHIP_GRP") && 
						isState("EVENT_FORM_SUBMIT") && 
						isState("SUBMIT") && 
						!isState("LOOP_SUBMIT_INTERNSHIP_STEP3")) 
	 then
	 	rules.header();
        rules.setState("LOOP_SUBMIT_INTERNSHIP_STEP3");

        BaseEntity beg = rules.getAsBaseEntity("begBe");

		if(beg != null){
			/* link BEG to USER */
			rules.set("linkSourceCode",  beg.getCode());
			rules.set("linkTargetCode", rules.getUser().getCode());
			rules.set("linkCode", "LNK_BEG");
			rules.set("linkValue", "CREATOR");
			rules.set("linkWeight", 1.0);
			rules.setState("CREATE_LINK");

			rules.setState("LINKED_BEG_TO_USER");
		}else{
			rules.println("beg is null");			
		}

	 	rules.footer();      
end
