package life.genny.rules;
import life.genny.rules.QRules;

/* MOVE BEG from GRP_AVAILABLE >>> GRP_APPROVED */
rule "Shortlist Internship - Step 1"
	when
		rules: QRules( 	isState("MOVE_BEG_TO_APPROVED") && 
						isState("APPROVE_INTERN_READY") && 
						isState("BTN_SHORTLIST_INTERN") && 
						isState("EVENT_BTN_CLICK") && 
						!isState("LOOP_MOVE_BEG_TO_APPROVED")) 
	 then
	 	rules.header();
        rules.setState("LOOP_MOVE_BEG_TO_APPROVED");

        BaseEntity beg = rules.getAsBaseEntity("begBe");
        
        if(beg != null){
        	rules.moveBaseEntity(beg.getCode(), "GRP_AVAILABLE", "GRP_APPROVED", "LNK_CORE");
        	rules.setState("MOVED_BEG_TO_APPROVED");
					rules.setState("SEND_PROJECT_MATCHED_MESSAGE_TO_INTERN");
		}else{
			rules.println("beg is null");
		}
	 	rules.footer();      
end