package life.genny.rules;
import life.genny.rules.QRules;

rule "Send Internmatch Homepage Layout - INTERN - LISTVIEW"
     when
        rules: QRules(  isState("SEND_INTERNMATCH_HOMEPAGE_LAYOUT") &&
                        isState("LISTVIEW") &&
                        isState("PRI_IS_INTERN") &&
                        !isState("LOOP_SEND_INTERNMATCH_HOMEPAGE_LAYOUT_LISTVIEW") )
     then
        rules.header();
        rules.setState("LOOP_SEND_INTERNMATCH_HOMEPAGE_LAYOUT_LISTVIEW");
        
        rules.set("subLayoutCode", "LISTVIEW");
		rules.set("subLayoutPath", "homepage/available_internships.json");
		rules.set("subLayoutRootCode", "GRP_AVAILABLE");
		rules.set("subLayoutIsPopup", false);
		rules.setState("SEND_SUBLAYOUT");

        rules.setState("SENT_INTERNMATCH_HOMEPAGE_LAYOUT");
		rules.footer();
end