package life.genny.rules;


import life.genny.rules.QRules;
import life.genny.qwanda.Answer;
import life.genny.qwanda.message.QDataAnswerMessage;
import life.genny.rules.RulesUtils;

rule "Ch40 Role Answer"
ruleflow-group 'Answer'
    when
        $m : QDataAnswerMessage( QDataAnswerMessage.getData_type().equals(Answer.class.getSimpleName()) )
        rules: QRules( isState("STARTED") && isState("ANSWER_PROCESSED") && !isState("CH40_ROLE_ANSWER") )
    then    
        rules.header();
        	 rules.setState("CH40_ROLE_ANSWER");
		rules.processRoles($m);
	   
	  
       rules.footer();
           
end


   