package life.genny.rules;
import life.genny.rules.QRules;

/* MOVE BEG to GRP_BIN */
rule "Delete Internship - Step 3"
	when
	    rules: QRules(	isState("MOVED_BEG_TO_BIN") &&
	                    isState("BTN_DELETE_INTERNSHIP") &&
						isState("EVENT_BTN_CLICK") && 
						!isState("LOOP_DELETE_INTERNSHIP_STEP3")) 
	 then
	 	rules.header();
        rules.setState("LOOP_DELETE_INTERNSHIP_STEP3");
		
		rules.setState("TRIGGER_INTERNMATCH_HOMEPAGE_LAYOUT");
 
	 	rules.footer();      
end
