package life.genny.rules;

import life.genny.rules.QRules;
import java.util.List;

rule "Profile Completed"
     when
        $m: QEventAttributeValueChangeMessage( QEventAttributeValueChangeMessage.getData().getCode().equals("PRI_IS_PROFILE_COMPLETED") )
        rules: QRules(!isState("LOOP_PROFILE_COMPLETED") ) 
     then      
        rules.header();
        
		rules.setState("LOOP_PROFILE_COMPLETED");
		rules.setState("TRIGGER_PROFILE_CHECK");
		
		rules.footer();     		      
end
     	