package life.genny.rules;

import life.genny.rules.QRules;
import life.genny.qwanda.entity.SearchEntity;
import java.util.ArrayList;


rule "SBE_OWNERS"
    no-loop true
    salience 550
    ruleflow-group 'GenerateReports'
    
    when
        rules: QRules( !isState("SBE_OWNERS") )
     then
         rules.setState(drools.getRule().getName());
        rules.println("Generating "+drools.getRule().getName());
          
  	     SearchEntity report = new SearchEntity(drools.getRule().getName(),"List of All Owners")
  	     .addColumn("PRI_IMAGE_URL","Image")
  	     .addColumn("PRI_USERNAME","Username")
  	     .addColumn("PRI_FIRSTNAME","Firstname")
  	     .addColumn("PRI_LASTNAME","Surname")
  	     .addColumn("PRI_MOBILE","Mobile")
  	     .addColumn("PRI_EMAIL","Email")
  	     
  	     .addSort("PRI_FIRSTNAME","Firstname",SearchEntity.Sort.ASC)
  	     
  	     .addFilter("PRI_DRIVER",true)
  	     
  	     .setPageStart(0)
  	     .setPageSize(10000);
  	     
  		 rules.add("GRP","GRP_REPORTS_ADMIN",report);
end
