package life.genny.rules;

import life.genny.rules.QRules;
import life.genny.qwanda.entity.SearchEntity;
import life.genny.utils.VertxUtils;
import java.util.ArrayList;


rule "SBE_ALLJOBS"
    no-loop true
    salience 550
    ruleflow-group 'GenerateReports'

    when
        rules: QRules( !isState("SBE_ALLJOBS") )
     then
         rules.setState(drools.getRule().getName());
         rules.println("Generating "+drools.getRule().getName());

  	     SearchEntity report = new SearchEntity(drools.getRule().getName(),"List of All Loads")
  	     .addColumn("PRI_NAME","Load Name")
  	     .addColumn("PRI_JOB_ID","Job ID")
  	     .addColumn("PRI_NAME","Load Name")
  	     .addColumn("PRI_DESCRIPTION","Description")
  	     .addColumn("PRI_JOB_CREATED_DATETIME", "Job Posted Date")
  	     .addColumn("PRI_AUTHOR", "Freight Owner")
  	     .addColumn("PRI_PICKUP_DATETIME", "Pick-up Date")
  	     .addColumn("PRI_PICKUP_ADDRESS_FULL","Pickup Address")
  	     .addColumn("PRI_DROPOFF_DATETIME", "Delivery Date")
  	     .addColumn("PRI_DROPOFF_ADDRESS_FULL", "Delivery Address")

  	     .addSort("PRI_NAME","Name",SearchEntity.Sort.ASC)

  	     .addFilter("PRI_CODE",SearchEntity.StringFilter.LIKE,"BEG_%")

  	     .setPageStart(0)
  	     .setPageSize(10000);

  		 rules.add("GRP","GRP_REPORTS_ADMIN",report);



end
