package life.genny.rules;
import life.genny.rules.QRules;

/* Send Questions */
rule "Apply Internship - Step 1"
	when
	    rules: QRules(  isState("BTN_APPLY_INTERNSHIP") && 
						isState("EVENT_BTN_CLICK") && 
						!isState("LOOP_APPLY_INTERNSHIP_STEP1")) 
	 then
	 	rules.header();
        rules.setState("LOOP_APPLY_INTERNSHIP_STEP1");

        String begCode = rules.getAsString("itemCode");
        if(begCode != null){
            rules.set("questionSourceCode", rules.getUser().getCode());
            rules.set("questionTargetCode", begCode);
            rules.set("questionGroupCode", "QUE_INTERNSHIP_ADDITIONAL_GRP");
        }else{
            rules.println("begCode is null");
        }
		rules.setState("SEND_QUESTION");
	 	rules.footer();      
end


        
        
