package life.genny.rules;
import life.genny.rules.QRules;
import life.genny.utils.VertxUtils;

/* Send Popup Layout */
rule "Apply Internship - Step 2"	
	when
		rules: QRules( 	isState("BTN_APPLY_INTERNSHIP") && 
						isState("EVENT_BTN_CLICK") && 
						isState("SENT_QUESTION") && 
						!isState("LOOP_APPLY_INTERNSHIP_STEP2") ) 
	 then
	 	rules.header();
        rules.setState("LOOP_APPLY_INTERNSHIP_STEP2");
		rules.clearState("SENT_QUESTION");
		
		String begCode = rules.getAsString("itemCode");
        if(begCode != null){
			rules.set("subLayoutCode", "APPLY_INTERNSHIP");
			rules.set("subLayoutPath", "internships/apply.json");
			rules.set("subLayoutRootCode", begCode);
			rules.set("subLayoutIsPopup", true);

			rules.setState("SEND_SUBLAYOUT");
		}else{
            rules.println("begCode is null");
        }
	 	rules.footer();      
end
