package life.genny.rules;
import life.genny.rules.QRules;

/* Send Questions */
rule "Apply Internship - Step 3"
	when
	    rules: QRules(  isState("SEND_APPLY_INTERNSHIP_QUESTIONS") && 
	                    isState("SAVED_BEG_CODE_AS_ATTRIBUTE") && 
	                    isState("BTN_APPLY_INTERNSHIP") && 
						isState("EVENT_BTN_CLICK") && 
						!isState("LOOP_APPLY_INTERNSHIP_STEP3")) 
	 then
	 	rules.header();
        rules.setState("LOOP_APPLY_INTERNSHIP_STEP3");

        /* GET APPLICATION BaseEntity code from state */
		BaseEntity application = rules.getAsBaseEntity("baseEntity");
        
        if(application != null){
            rules.set("questionSourceCode", rules.getUser().getCode());
            rules.set("questionTargetCode", application.getCode());
            rules.set("questionGroupCode", "QUE_INTERNSHIP_ADDITIONAL_GRP");
		    rules.setState("SEND_QUESTION");

		    rules.setState("SEND_APPLY_INTERNSHIP_LAYOUT");

        }else{
            rules.println("application BaseEntity is null");
        }
	 	rules.footer();      
end


        
        
