package life.genny.rules;
import life.genny.rules.QRules;

/* Send Sub Layout */
rule "View Application Details - Trigger View Application"
	when
		rules: QRules(  isState("BTN_VIEW_APPLICATION") && 
						isState("EVENT_BTN_CLICK") && 
						!isState("LOOP_TRIGGER_VIEW_APPLICATION") ) 
	 then
	 	rules.header();
		rules.setState("LOOP_TRIGGER_VIEW_APPLICATION");
		
		/* get applicationCode (itemCode) from state */
		String applicationCode = rules.getAsString("itemCode");
		if(applicationCode != null){
			BaseEntity application = rules.baseEntity.getBaseEntityByCode(applicationCode);
			if(application != null){
				rules.set("applicationBe" , application);
			}else{
				rules.println("application is null");
			}
		}else{
			rules.println("applicationCode is null");
		}
		
		
		rules.setState("TRIGGERED_VIEW_APPLICATION");
	 	rules.footer();      
end

        
