package life.genny.rules;

import life.genny.qwanda.message.QCmdMessage;
import life.genny.qwanda.message.QBulkMessage;
import life.genny.qwanda.message.QDataBaseEntityMessage;
import life.genny.qwanda.message.QEventMessage;
import life.genny.rules.QRules;
import io.vertx.core.json.JsonObject;
import java.util.List;
import java.util.ArrayList;
import life.genny.qwanda.entity.BaseEntity;
import life.genny.utils.VertxUtils;

rule "Generate Base Tree"

    ruleflow-group 'GenerateTree'
    salience 700

     when
       rules: QRules(isState("GENERATE_STARTUP") && !isState("GENERATE_TREE"))
     then

    rules.header();

    rules.setState("GENERATE_TREE");
		rules.println("Generating Base Tree for "+rules.realm());

    rules.footer();

end
