package life.genny.rules;
import life.genny.rules.QRules;

rule "Update BEG - Step 1"
    when
	    rules: QRules(  isState("SEND_UPDATE_BEG_QUESTION") &&	
                        !isState("LOOP_EDIT_BEG_STEP1")) 	
     then
        rules.header();    
        rules.setState("LOOP_EDIT_BEG_STEP1");

        String begCode = rules.getAsString("itemCode");
        if(begCode != null){
            BaseEntity beg = rules.baseEntity.getBaseEntityByCode(begCode);
            if(beg != null){

                rules.set("begBe", beg);
                
                rules.println("THIS IS THE BEG :: "+beg);
                rules.set("questionSourceCode", rules.getUser().getCode());
                rules.set("questionTargetCode", beg.getCode());
                rules.set("questionGroupCode", "QUE_EDIT_BEG_GRP");
                rules.set("questionIsPopup", true);
                rules.setState("SEND_QUESTION");
                rules.setState("SEND_UPDATE_PRODUCT_QUESTION");

            }else{
                rules.println("beg is null");
            }
        }else{
            rules.println("begCode is null");
        }
		rules.setState("SENT_BEG_QUESTION");
        rules.footer();     		      
end
