package life.genny.rules;
import life.genny.rules.QRules;

rule "Send TreeView"
    when
        rules: QRules(  isState("SEND_TREEVIEW") && 
                        !isState("LOOP_SEND_TREEVIEW") )
     then
     	rules.header();
     	rules.setState("LOOP_SEND_TREEVIEW");

        rules.set("parentCode", "GRP_ROOT");            
        rules.set("linkCode", "LNK_CORE");
        rules.set("pageStart", 0);
        rules.set("pageSize", 20);
        rules.set("cache", false);

        rules.clearState("LOOP_PUBLISH_BASE_ENTITY_LIST");
        rules.setState("PUBLISH_BASE_ENTITY_LIST");
         
        rules.setState("SENT_TREEVIEW");		
	    rules.footer();     		      
end


       