package life.genny.rules;
import life.genny.rules.QRules;

rule "Send Drafts"
    when
        rules: QRules(  isState("SEND_DRAFTS") && 
                        !isState("LOOP_SEND_DRAFTS") )
     then
     	rules.header();
     	rules.setState("LOOP_SEND_DRAFTS");

        rules.set("beParentCode", "GRP_DRAFTS");            
        rules.set("beLinkCode", "LNK_CORE");
        rules.set("bePageStart", 0);
        rules.set("bePageSize", 200);
        rules.set("beCache", false);

        rules.clearState("LOOP_PUBLISH_BASE_ENTITY_LIST");
        rules.setState("PUBLISH_BASE_ENTITY_LIST");
         
        rules.setState("SENT_DRAFTS");		
	    rules.footer();     		      
end
