package life.genny.rules;

import life.genny.rules.QRules;
import life.genny.qwanda.message.QEventMessage;

rule "Host Company Registration Form Submit"
	when
	    rules: QRules( 	isState("QUE_HOST_COMPANY_GRP") && 
						isState("EVENT_FORM_SUBMIT") && 
						!isState("PRI_IS_PROFILE_COMPLETED") &&
						!isState("LOOP_HOST_COMPANY_REGISTRATION_FORM")) 
	 then
	 	rules.header();
        rules.setState("LOOP_HOST_COMPANY_REGISTRATION_FORM");

		String sourceCode = rules.getUser().getCode();
		String targetCode = rules.getUser().getCode();
		String attributeCode = "PRI_IS_PROFILE_COMPLETED";
		String value = "TRUE";

/* 		rules.updateBaseEntityAttribute(sourceCode, targetCode, attributeCode, value);
 */
		rules.saveAnswer(
			new Answer(	sourceCode, 
						targetCode, 
						attributeCode,
						value )
		);
		
	 	rules.footer();      
end
