
 
import life.genny.qwanda.message.QCmdMessage;
import life.genny.qwanda.message.QEventMessage;
import life.genny.rules.QRules;
import io.vertx.core.json.JsonObject;

rule "TV_SELECT Messages Event"
     when
       $m : QEventMessage( event_type == "TV_SELECT")
       rules: QRules()
     then
       	
     rules.header();
       	
        /* TODO: rule should not be fired if user did not click on messages => add in predicate */
       	String grpCode = $m.getData().getValue();
        if(grpCode.equals("GRP_MESSAGES")) {
        		
        		System.out.println("-----------------");
        		rules.sendSublayout("messages-layout", "layouts/messages-layout.json");
        }
        
     rules.footer();
end

