package life.genny.rules;
import life.genny.rules.QRules;

rule "Trigger Send Layouts"

    when
         rules: QRules( isState("EXIT_SEND_SYSTEM_DATA")   &&
                        !isState("LOOP_TRIGGER_SEND_LAYOUTS")   ) 
     then
     	rules.header();
        rules.setState("LOOP_TRIGGER_SEND_LAYOUTS");
    
        rules.setState("SEND_MAIN_LAYOUTS");
	    rules.footer();      		      
end
