package life.genny.rules;
import life.genny.rules.QRules;

rule "Send Main Layout"
    when
        rules: QRules(  isState("SEND_MAIN_LAYOUTS") &&
                        !isState("LOOP_SEND_MAIN_LAYOUTS") )
     then
     	rules.header();
        rules.setState("LOOP_SEND_MAIN_LAYOUTS");

        rules.sendLayout("LAY_DEFAULT", "layout.json", rules.realm());
        rules.navigateTo("/home");
        rules.setState("MAIN_LAYOUTS_SENT");

	    rules.footer();
end
