package life.genny.rules;

import life.genny.rules.QRules;
import life.genny.qwanda.entity.BaseEntity;
import java.util.List;

/* Sends Contacts */
rule "Send Contacts"
    when
        rules: QRules(  isState("SEND_CONTACTS") && 
                        !isState("LOOP_SEND_CONTACTS") )
     then
     	rules.header();
     	rules.setState("LOOP_SEND_CONTACTS");
     	rules.clearState("PUBLISHED_BASE_ENTITY_LIST");
     	
     	List<String> groupList = new ArrayList<String>();
     	groupList.add("GRP_CONTACTS");
     	groupList.add("GRP_HOST_COMPANYS");
     	groupList.add("GRP_EDU_PROVIDERS");
     	groupList.add("GRP_INTERNS");
        
        rules.set("beList", groupList);                    
        rules.clearState("LOOP_PUBLISH_BASE_ENTITY_LIST");
        rules.setState("PUBLISH_BASE_ENTITY_LIST");
        
        rules.setState("SENT_CONTACTS");		
        rules.setState("SEND_GROUPS");
        rules.setState("SEND_DASHBOARD");		

	    rules.footer();     		      
end

       


       