package life.genny.rules;
import life.genny.rules.QRules;

/* Sends Buckets for EDU_PROVIDER */
rule "Send Buckets - EDU_PROVIDER" 
    when    
        rules: QRules(  isState("SEND_BUCKETS_EDU_PROVIDER") && 
                        isState("SENT_GRP_AVAILABLE_BEG_KIDS_EDU_PROVIDER") && 
                        isState("PRI_IS_EDU_PROVIDER") && 
                        !isState("LOOP_SEND_BUCKETS_EDU_PROVIDER") )
     then
     	rules.header();
        rules.setState("LOOP_SEND_BUCKETS_EDU_PROVIDER");
		
        List<BaseEntity> buckets = rules.getBaseEntitysByParentAndLinkCode("GRP_DASHBOARD_EDU_PROVIDER", "LNK_CORE", 0, 20, false);

		if(buckets != null){

	        /* SEND EDU_PROVIDER Buckets */
			rules.publishCmd(buckets, "GRP_ROOT", "LNK_CORE");		
			rules.set("eduProviderBuckets", buckets);

        	rules.setState("SENT_BUCKETS_EDU_PROVIDER");
        	rules.setState("SEND_BEGS_AND_KIDS_EDU_PROVIDER");
		}
	    rules.footer();      		      
end