package life.genny.rules;
import life.genny.rules.QRules;

/* LINK BEG + USER || CREATOR */
rule "Submit Internship - Step 1"
	when
		rules: QRules( 	isState("QUE_INTERNSHIP_GRP") && 
						isState("EVENT_FORM_SUBMIT") && 
						!isState("LOOP_SUBMIT_INTERNSHIP_STEP1")) 
	 then
	 	rules.header();
        rules.setState("LOOP_SUBMIT_INTERNSHIP_STEP1");

		String internshipCode = rules.getAsString("quesTargetCode");

		if(internshipCode != null){

			BaseEntity internship = rules.getBaseEntityByCode(internshipCode);
			rules.set("internshipBe", internship);

			BaseEntity beg = rules.getParent(internshipCode, "LNK_BEG");
			rules.set("begBe", beg);
		
			/* link BEG to USER */
			rules.set("sourceCode",  beg.getCode());
			rules.set("targetCode", rules.getUser().getCode());
			rules.set("linkCode", "LNK_BEG");
			rules.set("linkValue", "CREATOR");
			rules.set("weight", 1.0);

			rules.clearState("LOOP_CREATE_LINK");
			rules.setState("CREATE_LINK");

			rules.setState("LINKED_BEG_TO_USER");

		}

	 	rules.footer();      
end
