package life.genny.rules;
import life.genny.rules.QRules;
import life.genny.utils.VertxUtils;

/* Subscribe to BEG */
rule "Submit Internship - Step 3"	
	when
		rules: QRules( 	isState("LINKED_BEG_TO_COMPANY") && 
						isState("EVENT_FORM_SUBMIT") && 
						!isState("LOOP_SUBMIT_INTERNSHIP_STEP3")) 

	 then
	 	rules.header();
        rules.setState("LOOP_SUBMIT_INTERNSHIP_STEP3");

		BaseEntity beg = rules.getAsBaseEntity("begBe");

		rules.subscribeUserToBaseEntity(rules.getUser().getCode(), beg);
/* 		VertxUtils.subscribe(rules.realm(), beg, rules.getUser().getCode());
 */		
 		rules.setState("SUBSCRIBED_TO_BEG");
	 	rules.footer();      
end
