package life.genny.rules;
import life.genny.rules.QRules;
import life.genny.utils.VertxUtils;

/* Subscribe to BEG */
rule "Submit Internship - Step 4"	
	when
		rules: QRules( 	isState("LINK_CREATED") && 
						isState("CREATOR") && 	
						isState("EVENT_FORM_SUBMIT") && 	
						!isState("LOOP_SUBMIT_INTERNSHIP_STEP4")) 
	 then
	 	rules.header();
        rules.setState("LOOP_SUBMIT_INTERNSHIP_STEP4");

		BaseEntity beg = rules.getAsBaseEntity("begBe");

		VertxUtils.subscribe(rules.realm(), beg, rules.getUser().getCode());
		rules.setState("SUBSCRIBED_TO_BEG");
		

	 	rules.footer();      
end
