package life.genny.rules;

import life.genny.rules.QRules;
import life.genny.qwanda.entity.BaseEntity;

rule "Send All Attributes"
    when
        rules: QRules(isState("SEND_APPLICATION_ATTRIBUTES") && (!isState("LOOP_SEND_ATTRIBUTES")) )
     then
     	rules.header();
        rules.sendAllAttributes();
        rules.setState("SENT_ALL_ATTRIBUTES");
        rules.setState("LOOP_SEND_ATTRIBUTES");
	    rules.footer();      		      
end
