package life.genny.rules;

import life.genny.rules.QRules;
import life.genny.qwanda.entity.BaseEntity;

rule "Send User"
    when
        rules: QRules( isState("SENT_PROJECT") && !isState("LOOP_SEND_USER") )
     then
     	rules.header();

     	rules.setState("LOOP_SEND_USER");
        
        BaseEntity user = rules.getUser();
        if(user != null) {
            rules.publishCmd(user, "USER");
        }
         
        rules.setState("SENT_USER");		
	    rules.footer();     		      
end
