package life.genny.rules;
import life.genny.rules.QRules;

/* Move BEG from GRP_SHORTLISTED >>> GRP_OFFERED  */
rule "Offer Intern - Step 1"
	when
		rules: QRules( 	isState("MOVE_BEG_TO_OFFERED") && 
						isState("OFFER_INTERN_READY") && 
						isState("BTN_OFFER_INTERN") && 
						isState("EVENT_BTN_CLICK") && 
						!isState("LOOP_OFFER_INTERN_STEP1")) 
	 then
	 	rules.header();
        rules.setState("LOOP_OFFER_INTERN_STEP1");

		BaseEntity beg = rules.getAsBaseEntity("begBe");
        if(beg != null){
        	rules.moveBaseEntity(beg.getCode(), "GRP_INTERVIEWS", "GRP_OFFERED", "LNK_CORE");
        	rules.setState("MOVED_BEG_TO_OFFERED");

		}else{
			rules.println("beg is null");
		}
	 	rules.footer();      
end
