package life.genny.rules;
import life.genny.rules.QRules;

/* Set BEG \ APP \ INTERN To Map */
rule "Interview Intern - Step 0"
	when
		rules: QRules( 	isState("BTN_INTERVIEW_INTERN") && 
						isState("EVENT_BTN_CLICK") && 
						!isState("LOOP_INTERVIEW_INTERN_STEP0") ) 
	 then
	 	rules.header();
        rules.setState("LOOP_INTERVIEW_INTERN_STEP0");

		String begCode = rules.getAsString("itemCode");

		if(begCode == null){
            rules.println("begCode is null");
			return;
        }else{
			BaseEntity beg = rules.getBaseEntityByCode(begCode);
			rules.set("begBe", beg);
			
			rules.setState("INTERVIEW_INTERN_READY");            
			rules.setState("MOVE_BEG_TO_INTERVIEW");
        }
	 	rules.footer();      
end
