package life.genny.rules;

import life.genny.rules.QRules;
import life.genny.qwanda.message.QDataAskMessage;
import life.genny.qwanda.QuestionSourceTarget;
import life.genny.qwanda.message.QDataQSTMessage;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.Optional;
import life.genny.qwandautils.MergeUtil;

rule "Check if Profile Completed - Channel40"
    no-loop true
    when
		
        rules: QRules( isUserPresent() == true && 
					   isState("CHECK_USER_PROFILE_COMPLETED") &&
					   !isState("LOOP_CHECK_USER_PROFILE_COMPLETED") )
     then
     	rules.header();
     	
     	rules.setState("LOOP_CHECK_USER_PROFILE_COMPLETED");
     	
		Optional<Boolean> isProfileCompleted = rules.getUser().getValue("PRI_IS_PROFILE_COMPLETED");
		if(isProfileCompleted.isPresent() && isProfileCompleted.get() == true) {
   		   	
			rules.setState("PROFILE_IS_COMPLETED");
   		   	rules.setState("APPLICATION_READY");
			rules.setState("TRIGGER_CHANNEL40_APPLICATION");
		}
		else {
   		 	rules.setState("PROFILE_NOT_COMPLETED");
		}
		
		rules.println("PRI_IS_PROFILE_COMPLETED value   ::   " +  isProfileCompleted);
		rules.footer();
end
