package life.genny.rules;

import life.genny.rules.QRules;
import life.genny.qwanda.message.QDataAskMessage;
import life.genny.qwanda.QuestionSourceTarget;
import life.genny.qwanda.message.QDataQSTMessage;

import java.util.ArrayList;
import java.util.Arrays;
import life.genny.qwandautils.MergeUtil;

rule "Has user answered mandatory profile questions - step 1 - channel40"
    when
	    rules: QRules( isUserPresent() == true && isState("CHECK_USER_PROFILE_COMPLETED") && !isState("LOOP_CHECK_USER_PROFILE_COMPLETED") )
     then
     	rules.header();

		rules.setState("LOOP_CHECK_USER_PROFILE_COMPLETED");
   	    
		
		/* we check if the user has answered the mandatory questions */
		Boolean hasAnsweredProfileQuestions = rules.isMandatoryFieldsEntered(rules.getUser().getCode(), "QUE_NEW_USER_PROFILE_GRP");
		if(hasAnsweredProfileQuestions) {
			
			//Boolean driverCompanyExists = rules.getParent(userCode, "LNK_STAFF") != null;
			rules.setState("USER_PROFILE_ANSWERED");
		}
		else {
			rules.setState("USER_DID_NOT_COMPLETE_PROFILE");
			rules.setState("PROFILE_NOT_COMPLETED");
		}
		

        /* List<BaseEntity> baseEntityList = Arrays.asList(rules.getUser(),userCompany);

        String isProfileCompleted = MergeUtil.getAttrValue(rules.getUser().getCode(), "PRI_IS_PROFILE_COMPLETED", rules.getToken());

        if( isProfileCompleted == "TRUE" && QwandaUtils.isMandatoryFieldsCompleted((QDataAskMessage)rules.get("QUE_NEW_USER_PROFILE_GRP"), baseEntityList) )
        {
        		rules.setState("PROFILE_IS_COMPLETED");
   		   	rules.setState("APPLICATION_READY");
			rules.setState("TRIGGER_CHANNEL40_APPLICATION");
        }
        else {
        		rules.setState("PROFILE_NOT_COMPLETED");
        } */

	    rules.footer();
end
