package life.genny.rules;
import life.genny.rules.QRules;

rule "Send Applications For Selected BEG"
	when
		rules: QRules(  isState("DID_SELECT_BEG") &&
						!isState("LOOP_DID_SELECT_BEG")) 
	 then
	 	rules.header();
		rules.setState("LOOP_DID_SELECT_BEG");

        /* we grab the selected item */
        String itemCode = rules.getAsString("itemCode");

        /* we grab the applications */
        List<BaseEntity> applications = rules.getAsBaseEntitys("applications");
        if(applications != null && !applications.isEmpty()) {

            /* we publish the applications */
            rules.publishBaseEntityByCode(applications, itemCode, "LNK_BEG");
        }

	 	rules.footer();      
end
