package life.genny.rules;

import life.genny.rules.QRules;
import life.genny.qwanda.message.QDataPaymentsCallbackMessage;

rule "Pre-init Assembly Callback"
	no-loop true
    when
          m : QDataPaymentsCallbackMessage( QDataPaymentsCallbackMessage.getData_type().equals(QDataPaymentsCallbackMessage.class.getSimpleName()))
          rules: QRules(!isState("STARTED")) 
        
     then    
        rules.setDrools(drools);
        rules.println("RULE INIT DATATYPE_ASSEMBLY_CALLBACK: "+m);
        rules.setState("STARTED");

  		drools.setFocus("payment-callback");
        
      		      
end
