package life.genny.rules;

import life.genny.rules.RulesUtils;
import life.genny.rules.QRules;
import life.genny.qwandautils.PaymentUtils;

rule "Check if project uses Assembly Payments"
	no-loop true
	agenda-group "ispayments"
    when
    	rules: QRules( isState("IS_LOGGED_IN")  && !isState("IS_ASSEMBLY_PAYMENTS"))
    then
     
     RulesUtils.header(drools.getRule().getName());
     
    Boolean isPaymentAssembly = rules.getProject().getValue("PRI_IS_PAYMENTS_ASSEMBLY", false);
    rules.println("isPayments assembly used in the project ::"+isPaymentAssembly);
    
    if(isPaymentAssembly) {
    		drools.setFocus("payments");
    }

   rules.setState("IS_ASSEMBLY_PAYMENTS");

	  rules.footer();      		      
end