
import life.genny.rules.QRules;
import life.genny.qwanda.entity.BaseEntity;
import life.genny.qwanda.message.QEventMessage;
import life.genny.rules.RulesUtils;

rule "Geofence Enter Pickup Point"
	when
	  $m : QEventMessage( event_type == "GEOFENCE_ENTER" && data.code.contains("PICKUP"))
	  rules: QRules()
	then
    
		RulesUtils.header(drools.getRule().getName());
  
		String begCode = $m.data.getCode();
		String action = $m.data.getValue();
			
		RulesUtils.println("---- ACTION ----");
		RulesUtils.println("ARRIVED AT PICKUP POINT");
		
		String[] recipients = new String[1];
		recipients[0] = rules.getUser().getCode();
		
		
		
		/* rules.sendMessage(begCode, recipients, "MSG_CH40_DRIVER_PICKUP_ARRIVED", "SMS"); */
		
		RulesUtils.footer(drools.getRule().getName());

end