import life.genny.rules.RulesUtils;
import life.genny.rules.QRules;
import life.genny.qwanda.entity.BaseEntity;

import life.genny.qwanda.message.QEventMessage;

rule "Geofence Exit"
   when
     $m : QEventMessage( event_type == "GEOFENCE_EXIT" )
     rules: QRules()
   then
       
   		RulesUtils.header(drools.getRule().getName());
     
   		String begCode = $m.data.getCode();
   		String action = $m.data.getValue();
   		
   		RulesUtils.println(begCode);
   		RulesUtils.println(action);
   		
  		RulesUtils.footer(drools.getRule().getName());

end