package life.genny.rules;
import life.genny.rules.QRules;

/* Move APP from GRP_APPLIED >>> GRP_SHORTLISTED  */
rule "Trigger Shortlist Application"
	when
		rules: QRules( 	isState("BTN_SHORTLIST_APPLICATION") && 
						isState("EVENT_BTN_CLICK") && 
						!isState("LOOP_SHORTLIST_APPLICATION_STEP0")) 
	 then
	 	rules.header();
        rules.setState("LOOP_SHORTLIST_APPLICATION_STEP0");

        String applicationCode = rules.getAsString("itemCode");
		String bucketCode = rules.getAsString("hintCode");

        if(applicationCode == null){
			rules.println("applicationCode is null");
		}else if(bucketCode == null){
			rules.println("bucketCode is null");
		}else{
			rules.println("current bucketCode  :: " + bucketCode);
			rules.println("applicationCode     :: " + applicationCode);
            rules.moveBaseEntity(applicationCode, bucketCode, "GRP_SHORTLISTED", "LNK_CORE");
			// BaseEntity nextBucket =rules.nextBucket(bucketCode);
			// if(nextBucket != null){
			// 	rules.println("nextBucket  ::  " + nextBucket.getCode());
			// }
        }
	 	rules.footer();      
end
