package life.genny.rules;
import life.genny.rules.QRules;

/* MOVE BEG from GRP_APPLIED >>> GRP_SHORTLISTED */
rule "Shortlist Internship - Step 1"
	when
		rules: QRules( 	isState("MOVE_NEW_BEG_TO_SHORTLIST") && 
		                isState("SHORTLIST_INTERN_READY") && 
						isState("BTN_SHORTLIST_INTERN") && 
						isState("EVENT_BTN_CLICK") && 
						!isState("LOOP_SHORTLIST_INTERN_STEP1")) 
	 then
	 	rules.header();
        rules.setState("LOOP_SHORTLIST_INTERN_STEP1");

        BaseEntity newBeg = rules.getAsBaseEntity("newBegBe");
        
        if(newBeg != null){
        	rules.moveBaseEntity(newBeg.getCode(), "GRP_APPLIED", "GRP_SHORTLISTED", "LNK_CORE");
        	rules.setState("MOVED_BEG_TO_INTERVIEW");

		}else{
			rules.println("newBeg is null");
		}
	 	rules.footer();      
end

