package life.genny.rules;
import life.genny.rules.QRules;

/* Remove the APPLICANT from the oldBeg */
rule "Shortlist Internship - Step 2"
	when
		rules: QRules( 	isState("REMOVE_APPLICANT_FROM_OLD_BEG") && 
		                isState("MOVED_BEG_TO_INTERVIEW") && 
						isState("BTN_SHORTLIST_INTERN") && 
						isState("EVENT_BTN_CLICK") && 
						!isState("LOOP_SHORTLIST_INTERN_STEP2")) 
	 then
	 	rules.header();
        rules.setState("LOOP_SHORTLIST_INTERN_STEP2");

        BaseEntity oldBeg = rules.getAsBaseEntity("oldBegBe");
        BaseEntity application = rules.getAsBaseEntity("applicationBe");
        
        if(oldBeg == null){
			rules.println("oldBeg is null");
		}else if(application == null){
			rules.println("application is null");
		}else{
            rules.updateLink(oldBeg.getCode(), application.getCode(), "LNK_BEG", "APPLICATION", 0.0);  	
        	rules.setState("REMOVED_APPLICANT_FROM_OLD_BEG");

        	rules.setState("PUBLISH_NEW_BEG_AND_KIDS_SHORTLIST_INTERNSHIP");
		}
	 	rules.footer();      
end

