package life.genny.rules;

import life.genny.rules.QRules;
import life.genny.utils.PaymentUtils;

rule "Bulk Update assembly company info"
	agenda-group "payments"
	no-loop true
    when
    	rules: QRules( isState("IS_ASSEMBLY_COMPANY_CREATED") && !isState("LOOP_IS_ASSEMBLY_USER_COMPANY_UPDATED") ) 
    then
     
     rules.header();
     rules.setState("LOOP_IS_ASSEMBLY_USER_COMPANY_UPDATED");
     
     BaseEntity userBe = rules.getUser();
     String assemblyId = userBe.getValue("PRI_ASSEMBLY_USER_ID", null);	 
     BaseEntity companyBe = rules.getParent(userBe.getCode(), "LNK_STAFF");
     
     String assemblyAuthToken = PaymentUtils.getAssemblyAuthKey();
     
     if(assemblyId != null && companyBe != null && userBe != null) {
     
     	rules.println("updating the complete company profile in Assembly");
     	rules.bulkPaymentsCompanyUpdate(userBe, companyBe, assemblyId, assemblyAuthToken);
     }
      
     rules.footer();
     
end