package life.genny.rules;
import life.genny.rules.QRules;

/* Create Application BaseEntity */
rule "Apply for BEG - Step 1"
	when
	    rules: QRules(  isState("CREATE_APPLICATION_BE") && 
						!isState("LOOP_APPLY_BEG_STEP1")) 
	 then
	 	rules.header();
        rules.setState("LOOP_APPLY_BEG_STEP1");

        /* Create BEG BaseEntity*/
		rules.set("beCode", rules.getUser().getCode());
		rules.set("bePrefix", "APP");
		rules.set("beName", "APPLICATION");		
		rules.setState("CREATE_BASE_ENTITY");	

		rules.setState("SAVE_BEG_CODE_AS_ATTRIBUTE");
	 	rules.footer();      
end


        
        
