package life.genny.rules;
import life.genny.rules.QRules;

/* Create BEG BaseEntity */
rule "Add Product - Step 1"
	when
		rules: QRules(  isState("CREATE_BEG_BASEENTITY") &&
						!isState("LOOP_CREATE_BEG_BASEENTITY") ) 
	 then
	 	rules.header();
        rules.setState("LOOP_CREATE_BEG_BASEENTITY");

		 /* Create BEG BaseEntity*/
		rules.set("beCode", rules.getUser().getCode());
		rules.set("bePrefix", "BEG");
		rules.set("beName", "BEG");		
		rules.setState("CREATE_BASE_ENTITY");	

		rules.setState("CREATE_PRODUCT_BASEENTITY");	
	 	rules.footer();      
end
