package life.genny.rules;
import life.genny.rules.QRules;

/* Move BEG from GRP_SHORTLISTED >>> GRP_OFFERED  */
rule "Offer Intern - Step 1"
	when
		rules: QRules( 	isState("CHANGE_BEG_STATUS") && 
						isState("OFFER_INTERN_READY") && 
						isState("BTN_OFFER_INTERN") && 
						isState("EVENT_BTN_CLICK") && 
						!isState("LOOP_OFFER_INTERN_STEP1")) 
	 then
	 	
	 	rules.header();
     
		rules.setState("LOOP_OFFER_INTERN_STEP1");

		BaseEntity beg = rules.getAsBaseEntity("begBe");
		BaseEntity creator = rules.getAsBaseEntity("creatorBe");
		BaseEntity intern = rules.getAsBaseEntity("internBe");

		if(beg != null){
        		
		   String[] userCodes = {creator.getCode(), intern.getCode(), rules.getUser().getCode()};
		   
		   rules.updateBaseEntityStatus(beg, Arrays.asList(userCodes), "orange");
	       rules.setState("CHANGED_STATUS_BEG");
		}
        else {
			rules.println("beg is null");
		}
   
	 	rules.footer();      
end
