package life.genny.rules;
import life.genny.rules.QRules;

rule "Add To Host Company Group - Step 3"
     when
        rules: QRules(  isState("ADD_TO_GROUP") && 
						isState("CHECKED_COMPANY_EXISTS") &&
						isState("TRUE") &&
						isState("PRI_IS_HOST_COMPANY") &&
						!isState("LOOP_ADD_TO_HOST_COMPANY_GROUP_STEP3") )
     then
        rules.header();
		rules.setState("LOOP_ADD_TO_HOST_COMPANY_GROUP_STEP3");

        rules.setState("ADDED_TO_HOST_COMPANY_GROUP");
        rules.setState("ADDDED_TO_GROUP");
	    rules.footer();     		      
end
     	
          