import life.genny.qwanda.message.QEventMessage;
import life.genny.qwanda.message.QCmdMessage;
import life.genny.qwanda.message.QMessage.MessageData;
import io.vertx.rxjava.core.eventbus.EventBus;
import com.google.gson.Gson;



rule "Layout1"
    when
        m : QEventMessage( QEventMessage.data.getCode() == "layout1" )
        bus: EventBus()
    then
        QCmdMessage cmd = new QCmdMessage("CMD_LAYOUT","layout1");
        Gson gson = new Gson();
        String json = gson.toJson(cmd);
        System.out.println(json);
        bus.publish("cmds", json);
        System.out.println(m.getData().getCode());
end

