package life.genny.rules;
import life.genny.rules.QRules;

/* MOVE BEG to GRP_BIN */
rule "Delete Internship - Step 1"
	when
	    rules: QRules(	isState("BTN_DELETE_INTERNSHIP") &&
						isState("EVENT_BTN_CLICK") && 
						!isState("LOOP_DELETE_INTERNSHIP_STEP1")) 
	 then
	 	rules.header();
        rules.setState("LOOP_DELETE_INTERNSHIP_STEP1");

		/* get begCode (itemCode) from state */		
		String begCode = rules.getAsString("itemCode");  
        if(begCode != null){
            rules.moveBaseEntity(begCode, "GRP_AVAILABLE", "GRP_BIN", "LNK_CORE");
        }else{
			rules.println("begCode is null");
		}
        rules.setState("MOVED_BEG_TO_BIN");
	 	rules.footer();      
end