package life.genny.rules;
import life.genny.rules.QRules;

/* MOVE BEG to GRP_BIN */
rule "Delete Internship - Step 2"
	when
	    rules: QRules(	isState("BTN_DELETE_INTERNSHIP") &&
						isState("EVENT_BTN_CLICK") && 
						isState("DELETED_INTERNSHIP") && 
						!isState("LOOP_DELETE_INTERNSHIP_STEP2")) 
	 then
	 	rules.header();
        rules.setState("LOOP_DELETE_INTERNSHIP_STEP2");

		rules.set("subLayoutCode", "DASHBOARD");
		rules.set("subLayoutPath", "homepage/dashboard_host_company_temp.json");
		rules.set("subLayoutRootCode", "GRP_DASHBOARD_HOST_COMPANY");
		rules.set("subLayoutIsPopup", false);

		rules.setState("SEND_SUBLAYOUT");

        rules.setState("DELETED_INTERNSHIP2");
	 	rules.footer();      
end