package life.genny.rules;

import life.genny.rules.QRules;
import java.util.List;

rule "Home Page - Send Layout"
     when
        rules: QRules( isState("HOME_PAGE_SENT_DATA") && !isState("LOOP_HOME_PAGE_SEND_LAYOUT") ) 
     then      
        rules.header();
        rules.setState("LOOP_HOME_PAGE_SEND_LAYOUT");

        String cmdView = "BUCKET_VIEW";
        String rootCode = "GRP_DASHBOARD";

        rules.set("CMD_VIEW", cmdView);
        rules.set("root", rootCode);
        rules.setState("CMD_VIEW");

        rules.setState("HOME_PAGE_SENT_LAYOUT");
		rules.footer();     		      
end
     	