package life.genny.rules;

import life.genny.rules.QRules;
import life.genny.qwanda.entity.BaseEntity;

rule "Ask Mobile verification if needeed"
    when
        rules: QRules( isState("MOBILE_VERIFICATION_REQUIRED") && 
                    !isState("LOO_ASK_MOBILE_VERIF") )
    then
        rules.header();
        
		rules.setState("LOO_ASK_MOBILE_VERIF");
        
		if(rules.isMandatoryFieldsEntered(rules.getUser().getCode(), "QUE_MOBILE_VERIFICATION_GRP")) {
        		rules.setState("MOBILE_VERIFIED");
        }
        else {
            rules.askQuestions(rules.getUser().getCode(), rules.getUser().getCode(), "QUE_MOBILE_VERIFICATION_GRP", false);
        }
		
        rules.footer();
end
