package life.genny.rules;
import life.genny.rules.QRules;

rule "User Verified Phone Number"
	when
	    rules: QRules( 	isState("QUE_MOBILE_VERIFICATION_GRP") &&
						isState("EVENT_FORM_SUBMIT") &&
						!isState("LOOP_USER_ACCEPTED_MOBILE_VERIF")) 
	 then
	 	rules.header();
        
		rules.setState("LOOP_USER_ACCEPTED_MOBILE_VERIF");
		/*rules.setState("MOBILE_VERIFIED");*/  
		
	 	rules.footer();      
end