
package life.genny.rules;

import life.genny.rules.QRules;
import life.genny.qwanda.message.QDataAnswerMessage;
import life.genny.qwanda.entity.BaseEntity;
import life.genny.qwanda.Answer;
import io.vertx.core.json.JsonObject;
import life.genny.qwandautils.PaymentUtils;
import life.genny.rules.RulesUtils;
import life.genny.qwandautils.MergeUtil;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.Set;

rule "Make Payment"
	agenda-group "makepayment"
	no-loop true
	when
		m : QDataAnswerMessage( QDataAnswerMessage.getData_type().equals(Answer.class.getSimpleName()) )
	    rules: QRules( (isState("PAYMENT_ANSWER") && !isState("PAYMENT_DONE")) )
	then
		rules.header();

		rules.println("Make Payment started");

		rules.makePayment(m);
		
		rules.footer();
end