package life.genny.rules;

import life.genny.rules.RulesUtils;
import life.genny.rules.QRules;


rule "Is Payments Assembly Company Exists"
	agenda-group "payments"
	no-loop true
	when 
		rules: QRules(isState("IS_ASSEMBLY_USER_CREATED") && !isState("IS_ASSEMBLY_COMPANY_CREATED") ) 
	then
		RulesUtils.header(drools.getRule().getName());

    	String assemblyCompanyId = rules.getUser().getValue("PRI_ASSEMBLY_COMPANY_ID", null);
    	     	
     	if(assemblyCompanyId == null) {
     	
     		rules.setState("NEW_ASSEMBLY_COMPANY_CREATED");
     		drools.setFocus("payments");
     	}
     	
     	if(assemblyCompanyId != null) {
     	
     		rules.setState("IS_ASSEMBLY_COMPANY_CREATED");
     	}
     			
		RulesUtils.footer(drools.getRule().getName());
end