package life.genny.rules;

import life.genny.rules.RulesUtils;
import life.genny.rules.QRules;

import life.genny.qwandautils.QwandaUtils;
import life.genny.qwanda.message.QCmdMessage;
import life.genny.qwanda.message.QCmdLayoutMessage;

import io.vertx.core.json.JsonObject;

rule "Send Bucket Layout To Frontend"
    no-loop true
    salience 6
    agenda-group "SendLayoutsAndData"
    when
        rules: QRules( isState("SEND_BUCKET_DATA") && (!isState("SEND_BUCKET_LAYOUT"))  ) 
     then
     	RulesUtils.header(drools.getRule().getName());
     	
     	String layout = RulesUtils.getLayout("card.json");
     	
     	/* sending cmd BUCKET_VIEW */
        rules.sendSublayout("bucket-dashboard", "dashboard_channel40.json");
           
		/*  rules.clearState("SEND_BUCKET_DATA");  */
		rules.setState("SEND_BUCKET_LAYOUT");
		
	    RulesUtils.footer(drools.getRule().getName());       		      
end
