package life.genny.rules;

import life.genny.rules.RulesUtils;
import life.genny.rules.QRules;

import life.genny.qwanda.Answer;
import life.genny.qwanda.message.QEventAttributeValueChangeMessage;

import life.genny.qwandautils.PaymentUtils;
import life.genny.qwandautils.MergeUtil;


rule "Assembly user-company updation for attribute change - ABN"
    when
    	m: QEventAttributeValueChangeMessage( event_type == "EVT_ATTRIBUTE_VALUE_CHANGE" && data.code == "PRI_ABN" ) 
    	rules: QRules( isState("STARTED") )
    then    
		RulesUtils.header(drools.getRule().getName());
        
     	String userCode = rules.getUser().getCode();
     	String tokenString = rules.getToken();
        
        /* get assembly authKey   */
    	String assemblyAuthToken = PaymentUtils.getAssemblyAuthKey();
     
    	/*  Gets assembly userId */
    	String assemblyId = MergeUtil.getAttrValue(userCode, "PRI_ASSEMBLY_USER_ID", tokenString);
    	String assemblyCompanyId = MergeUtil.getAttrValue(rules.getUser().getCode(), "PRI_ASSEMBLY_COMPANY_ID", rules.getToken());
    	
    	if(assemblyId != null && assemblyCompanyId != null) {
    		 
    	/* extract answers */
      	Answer answer = m.getAnswer();
        
        String targetCode = answer.getTargetCode();
        String sourceCode = answer.getSourceCode();
        String value = answer.getValue();
        String attributeCode = m.data.getCode();

        RulesUtils.println("Printing Answer data recieved for Update in Assembly  ::");  
        RulesUtils.println("\nSource Code: " +sourceCode + "\nTarget Code: " +targetCode + "\nAttribute Code: " +attributeCode + "\nAttribute Value: " +value);
           
        /* Updates assembly user profile */
        String response = PaymentUtils.updateUserPersonalInfo(assemblyCompanyId, assemblyId, attributeCode, value, assemblyAuthToken);
        		RulesUtils.println("updated payments response ::"+response);
         
    	}
        
        RulesUtils.footer(drools.getRule().getName());
end