package life.genny.rules;
import life.genny.rules.QRules;

/* Create HOST COMPANY BaseEntity */
rule "Create Host Company - STEP 1"
    when
		rules: QRules(	isState("CREATE_HOST_COMPANY") &&
						isState("HOST_COMPANY_DOESNT_EXISTS") &&
						isState("PRI_IS_HOST_COMPANY") &&
        				isState("PROFILE_NOT_COMPLETED") && 
						!isState("LOOP_CREATE_HOST_COMPANY_STEP1") ) 
     then 
 		rules.header();
		rules.setState("LOOP_CREATE_HOST_COMPANY_STEP1");

		rules.set("beCode", rules.getUser().getCode());
		rules.set("bePrefix", "CPY");
		rules.set("beName", "COMPANY");
		rules.setState("CREATE_BASE_ENTITY");	

		rules.setState("CREATED_HOST_COMPANY");	
		rules.setState("LINK_GRP_HOST_COMPANYS_TO_HOST_OMPANY");	
 		rules.footer();
end
