package life.genny.rules;
import life.genny.rules.QRules;

/* Link GRP_HOST_COMPANYS >>>> HOST_COMPANY  */
rule "Create Host Company - STEP 2"
     when
        rules: QRules(  isState("LINK_GRP_HOST_COMPANYS_TO_HOST_OMPANY") && 
						isState("CREATED_HOST_COMPANY") &&
						isState("PRI_IS_HOST_COMPANY") &&
        				isState("PROFILE_NOT_COMPLETED") && 
        				isState("HOST_COMPANY_DOESNT_EXISTS") && 
        				isState("CREATED_BASE_ENTITY") && 
        				isState("CPY") && 
						!isState("LOOP_CREATE_HOST_COMPANY_STEP2") )
     then
        rules.header();
		rules.setState("LOOP_CREATE_HOST_COMPANY_STEP2");
     	
        /* get company BasEntity FROM state */
        BaseEntity company =rules.getAsBaseEntity("baseEntity");
        if(company != null){
            rules.set("companyBe", company);
            
            /* link GRP_HOST_COMPANYS to HOST_COMPANY */
            rules.set("linkSourceCode",  "GRP_HOST_COMPANYS");
            rules.set("linkTargetCode", company.getCode());
            rules.set("linkCode", "LNK_COMPANY");
            rules.set("linkValue", "HOST_COMPANY");
            rules.set("linkWeight", 1.0);
            rules.setState("CREATE_LINK");
            
            rules.setState("LINKED_GRP_HOST_COMPANYS_TO_HOST_OMPANY");
            rules.setState("LINK_HOST_COMPANY_TO_USER");
        }

	    rules.footer();     		      
end
     	
          