package life.genny.rules;

import life.genny.rules.RulesUtils;
import life.genny.rules.QRules;
import life.genny.qwanda.entity.BaseEntity;
import life.genny.qwanda.GPS;
import io.vertx.rxjava.core.eventbus.EventBus;
import io.vertx.core.json.JsonObject;
import io.vertx.core.json.JsonArray;
import java.util.Map;
import java.util.List;

import java.util.ArrayList;

import life.genny.qwanda.message.QDataGPSMessage;
import life.genny.qwandautils.QwandaUtils;
import life.genny.rules.RulesUtils;
import life.genny.qwandautils.GPSUtils;

import life.genny.qwanda.Answer;

rule "RX GPS Data"
	no-loop true
	ruleflow-group 'GPS'
	
    when
	    m : QDataGPSMessage()
	    rules: QRules( isState("STARTED") && !isState("RX_GPS") )
     then
     	rules.setState("RX_GPS");
 	  	 rules.updateGPS(m); 


 		    	
end
