package life.genny.rules;
import life.genny.rules.QRules;

/* Move APPLICATION to GRP_DECLINE   */
rule "Trigger Decline Application"
	when
		rules: QRules( 	isState("BTN_DECLINE_APPLICATION") && 
						isState("EVENT_BTN_CLICK") && 
						!isState("LOOP_DECLINE_APPLICATION_STEP0")) 
	 then
	 	rules.header();
        rules.setState("LOOP_DECLINE_APPLICATION_STEP0");

        String applicationCode = rules.getAsString("itemCode");
		String bucketCode = rules.getAsString("hintCode");

        if(applicationCode == null){
			rules.println("applicationCode is null");
		}else if(bucketCode == null){
			rules.println("bucketCode is null");
		}else{
			rules.saveAnswer( new Answer( rules.getUser().getCode(), applicationCode, "PRI_IS_DECLINED", "TRUE" ) );
            rules.updateBaseEntityStatus(applicationCode, rules.getUser().getCode(), "grey");
			
			rules.setState("APPLICATION_IS_DECLINED");
        }
	 	rules.footer();      
end
