package life.genny.rules;

import life.genny.rules.QRules;
import life.genny.qwanda.message.QEventBtnClickMessage;

rule "Select Seller Role - Step 1"

	when
		 rules: QRules( 	isState("BTN_SELECT_ROLE_SELLER") && isState("SELLER_SELECTED") &&
						!isState("HAS_CREATED_COMPANY") )   
	 then
	    rules.header();

		/*BaseEntity newCompany = QwandaUtils.createBaseEntityByCode(QwandaUtils.getUniqueId(userCode, null, "CPY", rules.getToken()), "COMPANY", rules.getQwandaServiceUrl(), rules.getToken());
		companyCode = newCompany.getCode();
		Link userCompanyLink =  QwandaUtils.createLink(companyCode, userCode, "LNK_STAFF", null, (double) 1, rules.getToken());
		comapnyQst = new QuestionSourceTarget("QUE_NEW_USER_COMPANY_GRP", userCode, companyCode);
		userCompany = newCompany; */
	
		rules.setState("HAS_CREATED_COMPANY");
		
		rules.set("bePrefix", "CPY");
		rules.set("beName", "COMPANY");
		rules.setState("CREATE_BASE_ENTITY");	

		rules.setState("CREATED_CPY_SELLER");			
		
	    rules.footer();     		      
end
