package life.genny.rules;
import life.genny.rules.QRules;
import java.util.HashMap;
import java.util.LinkedHashMap;

/* MOVE BEG from current Bucket to GRP_BIN */
rule "Trigger Delete BEG"
    when 
        rules: QRules(	isState("BTN_DELETE_BEG") &&
						isState("EVENT_BTN_CLICK") && 
						!isState("LOOP_TRIGGER_DELETE_BEG") )
    then
        rules.header();
        rules.setState("LOOP_TRIGGER_DELETE_BEG");

        /* get begCode (itemCode) from state */		
		String begCode = rules.getAsString("itemCode"); 
		if(begCode != null){
			BaseEntity beg = rules.getBaseEntityByCode(begCode);
			
			if(beg != null){
				rules.set("begBe", beg);	
			
				BaseEntity parentBe = rules.getParent(beg.getCode(), "LNK_CORE");
				if(parentBe != null){
					rules.println("beg Code   ::   " + beg.getCode());
					rules.println("beg's current parent is   ::   " + parentBe.getCode());
					
					rules.moveBaseEntitySetLinkValue(beg.getCode(), parentBe.getCode(), "GRP_BIN", "LNK_CORE", "BEG");
					
					
					rules.setState("TRIGGER_HOMEPAGE");
					rules.setState("TRIGGER_DELETE_BEG_MESSAGE");
					rules.println("Message had been triggered");
				}else{
					rules.println("parentBe is null");
				}

			}else{
				rules.println("beg is null");
				return;
			}
		}else{
			rules.println("begCode is null");
			return;
		}
        rules.footer();
end
