package life.genny.rules;
import life.genny.rules.QRules;

/* MOVE BEG to GRP_BIN */
rule "Delete BEG - Step 2"
	when
	    rules: QRules(	isState("MOVED_BEG_TO_BIN") &&
	                    isState("BTN_DELETE_BEG") &&
						isState("EVENT_BTN_CLICK") && 
						!isState("LOOP_DELETE_BEG_STEP2")) 
	 then
	 	rules.header();
        rules.setState("LOOP_DELETE_BEG_STEP2");
		
		rules.setState("TRIGGER_HOMEPAGE");
 
	 	rules.footer();      
end
