package life.genny.rules;
import life.genny.rules.QRules;

/* Sends INTERN DATA */
rule "Send Internmatch Application Data - INTERN "
    when    
         rules: QRules( isState("SEND_INTERNMATCH_APPLICATION_DATA") && 
                        isState("PRI_IS_INTERN") && 
                        !isState("LOOP_SEND_INTERNMATCH_APPLICATION_DATA_INTERN") )
     then
     	rules.header();
        rules.setState("LOOP_SEND_INTERNMATCH_APPLICATION_DATA_INTERN");
    
        rules.setState("SEND_ROOT_INTERN");
	    rules.footer();      		      
end
