package life.genny.rules;

import life.genny.rules.QRules;
import life.genny.qwanda.entity.BaseEntity;

rule "Setup New User"
    when
        rules: QRules( isState("DID_CREATE_NEW_USER") && isState("APPLICATION_NOT_READY") &&
                    !isState("LOOP_SETUP_NEW_USER") )
    then
        rules.header();
        rules.setState("LOOP_SETUP_NEW_USER");

        BaseEntity user = rules.getUser();

        /*  saving the default profile image   */
        rules.saveAnswer( new Answer (user.getCode(),
                          user.getCode(),
                          "PRI_IMAGE_URL", "https://s3.ap-southeast-2.amazonaws.com/channel40-images/jtaQozJT5HSpn3bX6P4EXSqQj3NDalkQ") );

        /*  set PRI_IS_PROFILE_COMPLETED = FALSE */
        rules.saveAnswer( new Answer (user.getCode(),
                          user.getCode(),
                          "PRI_IS_PROFILE_COMPLETED",
                          "FALSE") );

        rules.setState("DID_SETUP_NEW_USER");

        rules.println("New User is   ::   " + user);

        rules.clearState("PROFILE_CHECK_COMPLETED");
        rules.footer();
end
