package life.genny.rules;
import life.genny.rules.QRules;

rule "Trigger Internmatch Home Page"
    when
        rules: QRules(  isState("TRIGGER_INTERNMATCH_HOMEPAGE") && 
                        !isState("LOOP_TRIGGER_INTERNMATCH_HOMEPAGE")) 
     then       
        rules.header();
        rules.setState("LOOP_TRIGGER_INTERNMATCH_HOMEPAGE");
        
        rules.clearState("HOME_PAGE_SENT_DATA");   

        rules.setState("HOME_PAGE_SEND_DATA");
        rules.footer(); 		      
end
