package life.genny.rules;
import life.genny.rules.QRules;

rule "Send BEG deleted message"
	when
		rules: QRules(  isState("TRIGGER_DELETE_BEG_MESSAGE") && 
                        !isState("LOOP_TRIGGER_DELETE_BEG_MESSAGE") )
	then
        rules.header();
        rules.setState("LOOP_TRIGGER_DELETE_BEG_MESSAGE");

        BaseEntity beg = rules.getAsBaseEntity("begBe");

        if(beg == null){
            rules.println("beg is null");
            return;
        }
        else {
            HashMap<String, String> contextMap = new HashMap<String, String>(); 
            contextMap.put("BEG", beg.getCode());

            String[] recipients = {rules.getUser().getCode()};
            //rules.println("No. of deleted begs   ::   " + recipients.size() );

            rules.sendMessage(null, recipients, contextMap, "GNY_MSG_BEG_DELETED", "TOAST");

            rules.setState("SENT_BEG_DELETED_MESSAGE");
        }
        rules.footer();
end    