package life.genny.rules;

import life.genny.rules.QRules;

rule "Pre Init Btn Click"
	no-loop true
	lock-on-active true
	ruleflow-group 'Init'
    when
          m : QEventMessage( event_type == "BTN_CLICK" && data.value == "ADD_NEW_LOAD" )
          rules: QRules(!isState("STARTED")) 
     then    
        rules.setDrools(drools);
        rules.header();
        rules.setState("EVENT_BTN_CLICK");
        rules.setState("STARTED");

        
        rules.footer();
      		      
end
