package life.genny.rules;

import life.genny.rules.QRules;

rule "Pre Init Btn Click"
	no-loop true
	ruleflow-group 'Init'
    when
          m : QEventMessage( event_type == "BTN_CLICK" )
          rules: QRules(!isState("STARTED")) 
     then    
        rules.setDrools(drools);
        rules.header();
        rules.setState("EVENT_BTN_CLICK");
        rules.setState("STARTED");

        
        rules.footer();
      		      
end
