package life.genny.rules;

import life.genny.rules.QRules;

rule "Pre Init EVT_TV_SELECT"
	no-loop true
	ruleflow-group 'Init'
    when
          m : QEventMessage( event_type == "TV_SELECT") 
          rules: QRules(!isState("STARTED")) 
     then    
        rules.setDrools(drools);
        rules.header();
          rules.setState("EVENT_TV_SELECT");
        rules.setState("STARTED");

        
        rules.footer();
      		      
end
