package life.genny.rules;

import life.genny.rules.QRules;

rule "Pre Init Link Change"
	no-loop true
	ruleflow-group 'Init'
    when
         $m: QEventLinkChangeMessage( event_type == "EVT_LINK_CHANGE" )
          rules: QRules(!isState("STARTED")) 
     then    
        rules.setDrools(drools);
        rules.header();
        rules.setState("EVENT_LINK_CHANGE");
        rules.setState("STARTED");
		
        	drools.setFocus("AttributeChange");
        rules.footer();
      		      
end
