package life.genny.rules;

import life.genny.rules.QRules;

rule "Pre Init Auth Init"
	no-loop true
	ruleflow-group 'Init'
    when
          m : QEventMessage( getData().getCode().equals("AUTH_INIT") )
          rules: QRules(!isState("STARTED")) 
     then    
        rules.setDrools(drools);
        rules.println("RULE INIT AUTH_INIT: "+m);
 
         rules.setState("EVENT_AUTH_INIT");
        rules.setState("STARTED");

        
        rules.footer();
      		      
end
