package life.genny.rules;

import life.genny.rules.QRules;

rule "Pre Init Answer"
	no-loop true
	ruleflow-group 'Init'
    when
        m : QDataAnswerMessage( QDataAnswerMessage.getData_type().equals(Answer.class.getSimpleName()) )
          rules: QRules(!isState("STARTED")) 
     then    
        rules.setDrools(drools);
        rules.header();
        rules.setState("DATA_ANSWER");
        rules.setState("STARTED");
		
        	drools.setFocus("Answer");
        rules.footer();
      		      
end
