package life.genny.rules;

import life.genny.rules.QRules;

rule "Pre Init Menu Profile"
	no-loop true
	ruleflow-group 'Init'
    when
          m : QEventMessage( event_type == "PROFILE" && data.code == "PROFILE" )
          rules: QRules(!isState("STARTED")) 
     then    
        rules.setDrools(drools);
        rules.header();
        rules.setState("EVENT_BTN_CLICK");
        rules.setState("STARTED");

        
        rules.footer();
      		      
end
