package life.genny.rules;

import life.genny.rules.QRules;

rule "Pre Init User Logout"
	no-loop true
	ruleflow-group 'Init'
    when
  		m : QEventMessage( event_type == "LOGOUT" && data.code == "LOGOUT" )
          rules: QRules(!isState("STARTED")) 
     then    
        rules.setDrools(drools);
        rules.header();
          rules.setState("EVENT_USER_LOGOUT");
        rules.setState("STARTED");

        drools.setFocus("UserLogout");
        rules.footer();
      		      
end
