package life.genny.rules;

import life.genny.rules.QRules;

rule "Pre Init Attribute Change"
	no-loop true
	ruleflow-group 'Init'
    when
          m : QEventMessage( QEventMessage.getData().getCode().equals("EVT_ATTRIBUTE_VALUE_CHANGE") )
          rules: QRules(!isState("STARTED")) 
     then    
        rules.setDrools(drools);
        rules.header();
        rules.setState("EVENT_ATTRIBUTE_VALUE_CHANGE");
        rules.setState("STARTED");
		
        	drools.setFocus("AttributeChange");
        rules.footer();
      		      
end
