package life.genny.rules;
import life.genny.rules.QRules;

/* Show Compliance Document when Redirecting from email */
rule "Show Compliance Document On Redirect"
	when
		rules: QRules( 	isState("REDIRECT_EVENT") && 
						isState("REDIRECT_SHOW_OFFER") && 
						isState("PRI_IS_INTERN") && 
						isState("EXIT_HOME_PAGE") &&
						!isState("LOOP_REDIRECT_SHOW_COMPLIANCE_DOCUMENT") ) 
	 then
	 	rules.header();
        rules.setState("LOOP_REDIRECT_SHOW_COMPLIANCE_DOCUMENT");

		String begCode = rules.getAsString("valueCode");
        if(begCode != null){
			rules.set("begCode", begCode);
            rules.setState("SHOW_COMPLIANCE_DOCUMENT");
        }else{
			rules.println("begCode is null");
		}
	 	rules.footer();      
end
