package life.genny.rules;
import life.genny.rules.QRules;

/* Duplicate BEG */
rule "Shortlist Internship - Step 1"
	when
		rules: QRules( 	isState("CREATE_NEW_BEG") && 
						isState("SHORTLIST_INTERN_READY") && 
						isState("BTN_SHORTLIST_INTERN") && 
						isState("EVENT_BTN_CLICK") && 
						!isState("LOOP_SHORTLIST_INTERN_STEP1")) 
	 then
	 	rules.header();
        rules.setState("LOOP_SHORTLIST_INTERN_STEP1");

		/* Create BEG BaseEntity*/
		rules.set("beCode", rules.getUser().getCode());
		rules.set("bePrefix", "BEG");
		rules.set("beName", "BEG");		
		rules.setState("CREATE_BASE_ENTITY");	

		rules.setState("CREATED_NEW_BEG");	
		rules.setState("COPY_LINKS_FROM_OLD_BEG");	
	 	rules.footer();      
end
