package life.genny.rules;
import life.genny.rules.QRules;
import life.genny.utils.VertxUtils;

/* Subscribe INTERN to NEW_BEG */
rule "Shortlist Internship - Step 6"	
	when
		rules: QRules( 	isState("SUBSCRIBE_INTERN_TO_NEW_BEG") && 
						isState("SUBSCRIBED_COMPANY_TO_NEW_BEG") && 
						isState("BTN_SHORTLIST_INTERN") && 
						isState("EVENT_BTN_CLICK") && 
						!isState("LOOP_SHORTLIST_INTERN_STEP6")) 

	 then
	 	rules.header();
        rules.setState("LOOP_SHORTLIST_INTERN_STEP6");

        BaseEntity intern = rules.getAsBaseEntity("internBe");
        BaseEntity newBeg = rules.getAsBaseEntity("newBegBe");
		
		if(intern != null && newBeg != null){
			rules.subscribeUserToBaseEntityAndChildren(intern.getCode(), newBeg.getCode(), "LNK_BEG");
	 		rules.setState("SUBSCRIBED_INTERN_TO_NEW_BEG");

	 		rules.setState("PUBLISH_NEW_BEG_AND_KIDS");
		}
	 	rules.footer();      
end