package life.genny.rules;
import life.genny.rules.QRules;

rule "Add To Driver Group"
     when
        rules: QRules(  isState("ADD_TO_GROUP") && 
						isState("PRI_IS_DRIVER") &&
						!isState("LOOP_ADD_TO_DRIVER_GROUP") )
     then
        rules.header();
		rules.setState("LOOP_ADD_TO_DRIVER_GROUP");
     	
     	/* link Driver to GRP_DRIVERS */
        rules.set("linkSourceCode",  "GRP_DRIVERS");
        rules.set("linkTargetCode", rules.getUser().getCode());
        rules.set("linkCode", "LNK_CORE");
        rules.set("linkValue", "DRIVER");
        rules.set("linkWeight", 1.0);
        rules.setState("CREATE_LINK");

     	rules.setState("ADDED_TO_DRIVER_GROUP");
        rules.setState("ADDDED_TO_GROUP");         
	    rules.footer();     		      
end
     	