package life.genny.rules;

import life.genny.rules.QRules;
import java.util.List;

rule "Home Page"
     when
        rules: QRules( isState("PROFILE_IS_COMPLETED") && !isState("LOOP_HOME_PAGE") ) 
     then      
        rules.header();
        rules.setState("LOOP_HOME_PAGE");

        String cmdView = "BUCKET_VIEW";
        String rootCode = "GRP_DASHBOARD";

        rules.set("CMD_VIEW", cmdView);
        rules.set("root", rootCode);
        rules.setState("CMD_VIEW");
        
		rules.footer();     		      
end
     	