// /			rules.setState("TRIGGER_HOME_PAGE");

package life.genny.rules;
import life.genny.rules.QRules;

rule "Trigger Application"
    when
        rules: QRules( isState("PROFILE_IS_COMPLETED") && 
                    !isState("LOOP_TRIGGER_APPLICATION")) 
     then       
        rules.header();

        rules.setState("LOOP_TRIGGER_APPLICATION");
        rules.setState("TRIGGER_HOME_PAGE");

        rules.footer(); 		      
end
