package life.genny.rules;
import life.genny.rules.QRules;

rule "Trigger Application - Internmatch"
    when
        rules: QRules(  isState("PROFILE_IS_COMPLETED") && 
                        !isState("LOOP_TRIGGER_APPLICATION") ) 
     then       
        rules.header();
        rules.setState("LOOP_TRIGGER_APPLICATION");
        
        /* to do */
        rules.setState("TRIGGER_SUBSCRIPTION"); /* trigger subscription then only app data */
        rules.setState("TRIGGER_SEND_APPLICATION_DATA");
        rules.setState("TRIGGER_HOME_PAGE");
/*      rules.setState("TRIGGER_WELCOME_PAGE");   */
        rules.footer(); 		      
end
