package life.genny.rules;
import life.genny.rules.QRules;

rule "Trigger Add Note"
	when
		rules: QRules(  isState("EVENT_BTN_CLICK") &&
						isState("BTN_ADD_NOTE") && 
						!isState("LOOP_TRIGGER_ADD_NOTE")) 
	 then
	 	rules.header();
		rules.setState("LOOP_TRIGGER_ADD_NOTE");
		
	   	String contextCode = rules.getAsString("itemCode");
	   	String messageCode = rules.getAsString("messageCode");
		
		if(contextCode == null){
			rules.println("contextCode is null");
		}
		else if(messageCode == null){
			rules.println("messageCode is null");
		}else{
			BaseEntity context = rules.getBaseEntityByCode(contextCode);
			if(context != null){
				rules.set("contextBe", context);
			}
			rules.setState("CREATE_NOTE_BASEENTITY");
		}
	 	rules.footer();      
end
