package life.genny.rules;
import life.genny.rules.QRules;

/* LINK GRP_NOTES + NOTE */
rule "Add Note - STEP 3"
	when
		rules: QRules( 	isState("LINK_GRP_NOTES_AND_NOTE") &&
						!isState("LOOP_LINK_GRP_NOTES_AND_NOTE"))
	 then
	 	rules.header();
        rules.setState("LOOP_LINK_GRP_NOTES_AND_NOTE");

		BaseEntity note = rules.getAsBaseEntity("noteBe");

		if(note == null){
			rules.println("note is null");
			return;

		}else{
			/* link GRP_DRAFTS to BEG */
			rules.set("linkSourceCode", "GRP_NOTES");
			rules.set("linkTargetCode", note.getCode());
			rules.set("linkCode", "LNK_CORE");
			rules.set("linkValue", "NOTE");
			rules.set("linkWeight", 1.0);

			rules.setState("CREATE_LINK");
			rules.setState("LINK_NOTE_AND_CONTEXT");
		}
		rules.footer();
end


        
        

        
