package life.genny.rules;
import life.genny.rules.QRules;

/* LINK NOTE + CREATOR */
rule "Add Note - STEP 5"
	when
		rules: QRules( 	isState("LINK_NOTE_AND_CREATOR") &&
						isState("CREATED_LINK") &&
						isState("CONTEXT") &&
						!isState("LOOP_LINK_NOTE_AND_CREATOR"))
	 then
	 	rules.header();
        rules.setState("LOOP_LINK_NOTE_AND_CREATOR");

		BaseEntity note = rules.getAsBaseEntity("noteBe");

		if(note == null){
			rules.println("note is null");
			return;

		}else{
			/* link GRP_DRAFTS to BEG */
			rules.set("linkSourceCode", note.getCode());
			rules.set("linkTargetCode", rules.getUser().getCode());
			rules.set("linkCode", "LNK_NOTE");
			rules.set("linkValue", "CREATOR");
			rules.set("linkWeight", 1.0);

			rules.setState("CREATE_LINK");
			rules.setState("PUBLISH_NOTE_BASEENTITY");

		}
		rules.footer();
end


        
        

        
