package life.genny.rules;

import life.genny.rules.QRules;
import life.genny.utils.PaymentUtils;

rule "Payments Company Creation Step 2 : Check if user has a company or not"
	agenda-group "payments"
	no-loop true
    when
    	rules: QRules( isState("CHECK_USER_BELONGS_TO_COMPANY") && !isState("COMPANY_EXISTS_TRIGGER_PAYMENTS_CREATE_COMPANY") && !isState("LOOP_CHECK_USER_COMPANY")  )
    then
    		rules.header();
    		rules.setState("LOOP_CHECK_USER_COMPANY");
    		
    		BaseEntity userBe = rules.getUser();
    		
    		/* Get the company if exists */
    		BaseEntity companyBe = rules.getParent(userBe.getCode(), "LNK_STAFF");
    		
    		if(companyBe != null) {
    			rules.setState("COMPANY_EXISTS_TRIGGER_PAYMENTS_CREATE_COMPANY");
    		} else {
    			rules.println("User has no company");
    		}
    		
    		rules.footer();
 end