package life.genny.rules;

import life.genny.rules.QRules;
import life.genny.qwanda.message.QEventBtnClickMessage;

rule "Check user company - User is NOT a company - SELLER"
	when
		 rules: QRules( 	isState("SET_USER_CAPABILITIES") && isState("PRI_IS_SELLER") && !isState("LOOP_SET_USER_CAPABILITIES") )
	 then
	    rules.header();

		rules.setState("LOOP_SET_USER_CAPABILITIES");

		/* we grab the seller role */
		BaseEntity sellerRole = rules.baseEntity.getRole("SELLER");
		
		if(sellerRole != null) {
			
			/* we assign this role to the current user */
			rules.baseEntity.setRole(rules.getUser(), sellerRole);
		}
		
		rules.setState("COMPANY_IS_READY");
	    rules.footer();
end
