package life.genny.rules;
import life.genny.rules.QRules;

rule "Exit Application Setup"

    when
         rules: QRules( isState("EXIT_SEND_LAYOUTS") &&
                        !isState("LOOP_EXIT_APPLICATION_SETUP") )
     then
     	rules.header();
        rules.setState("LOOP_EXIT_APPLICATION_SETUP");

        BaseEntity project = rules.getProject();
        Boolean doesProjectRequireRole = project.getValue("PRI_DOES_PROJECT_ASK_FOR_ROLE", null);
        if (doesProjectRequireRole == null || doesProjectRequireRole == true) {
        	 rules.setState("TRIGGER_ROLE_CHECK");
        }
        else {
        	rules.setState("PRI_IS_BUYER");
        	rules.setState("TRIGGER_PROFILE_CHECK");
        }

	    rules.footer();
end
