package life.genny.rules;

import life.genny.rules.QRules;
import life.genny.qwanda.entity.SearchEntity;
import life.genny.utils.VertxUtils;
import java.util.ArrayList;


rule "SBE_ADMINS"

    ruleflow-group 'GenerateReports'

    when
        rules: QRules( !isState("SBE_ADMINS") )
     then
         rules.setState(drools.getRule().getName());
         rules.println("Generating "+drools.getRule().getName());

  	     SearchEntity report = new SearchEntity(drools.getRule().getName(),"List of Admins")
  	     .addColumn("PRI_IMAGE_URL","Image")
  	     .addColumn("PRI_USERNAME","Username")
  	     .addColumn("PRI_FIRSTNAME","Firstname")
  	     .addColumn("PRI_LASTNAME","Surname")
  	     .addColumn("PRI_MOBILE","Mobile")
  	     .addColumn("PRI_EMAIL","Email")
  	     .addColumn("PRI_REGISTRATION_DATETIME", "Registered Date")
  	     .addColumn("PRI_LAST_LOGIN_DATETIME","Last Login Date")

  	     .addSort("PRI_FIRSTNAME","Firstname",SearchEntity.Sort.ASC)

  	     .addFilter("PRI_CODE",SearchEntity.StringFilter.LIKE,"PER_%")
  	     .addFilter("PRI_IS_ADMIN",true)

  	     .setPageStart(0)
  	     .setPageSize(1000);

  		 rules.add("GRP","GRP_REPORTS_ADMIN",report);
  		
end
