package life.genny.rules;

import life.genny.rules.RulesUtils;
import life.genny.rules.QRules;
import io.vertx.core.json.JsonObject;
import life.genny.qwanda.message.QEventMessage;
import life.genny.qwandautils.QwandaUtils;

rule "Select Report Item - SBE"

    when
	    $m :  QEventMessage( event_type == "BTN_CLICK" && data.code == "SELECT_EVENT" )
        rules: QRules( !isState("REPORTS_SENT") )
     then

     	rules.header();
     	rules.setState("REPORTS_SENT");
	    String data = $m.getData().getValue();

  		rules.selectReport(data);
     	rules.footer();
end
