package life.genny.rules;

import life.genny.rules.QRules;
import life.genny.payments.QPaymentsProvider;

rule "Make Payment - Step 3 Make Payment"
	when
	    rules: QRules( (isState("PAYMENT_ITEM_AVAILABLE") && isState("MAKE_PAYMENT") && !isState("DID_PAYMENT_DONE")) )
	then
		rules.header();
			rules.setState("DID_PAYMENT_DONE");
	        rules.println("Making Payment");
	        
	        String paymentItemIdAttributeCode = rules.getAsString("paymentItemIDAttributeCode");
	        
	        String paymentTitle = rules.getKeyValue("PaymentTitle");
			String sourceEntityCode = rules.getKeyValue("PaymentSourceEntityCode");
			String amountAttributeCode = rules.getKeyValue("PaymentAmountAttributeCode");
			String sellerCode = rules.getKeyValue("PaymentSeller");
			String buyerCode = rules.getKeyValue("PaymentBuyer");
			QPaymentsProvider paymentsProvider = rules.getPaymentsServiceProvider();
			String assemblyToken = paymentsProvider.getPaymentsAuthKey();
						
			rules.println("paymentTitle :: "+paymentTitle);
			rules.println("srcEntityCode :: "+sourceEntityCode);
			rules.println("amountAttributeCode :: "+amountAttributeCode);
		    rules.println("sellerCode :: "+sellerCode);
	        rules.println("buyerCode :: "+buyerCode);
	        rules.println("paymentItemIdAttrCode :: "+paymentItemIdAttributeCode);
			
			if(paymentTitle != null && sourceEntityCode != null && amountAttributeCode != null &&
	                    sellerCode != null && buyerCode != null && paymentItemIdAttributeCode != null ){
	            BaseEntity srcBe =  rules.baseEntity.getBaseEntityByCode(sourceEntityCode);
	            BaseEntity buyerBe =  rules.baseEntity.getBaseEntityByCode(buyerCode);  
	            BaseEntity sellerBe =  rules.baseEntity.getBaseEntityByCode(sellerCode);
	            
			    rules.println(" The buyer be is  :: "+buyerBe.getCode());
				rules.println(" The seller be is  :: "+sellerBe.getCode());
			    
	        	 	Boolean paymentDone = paymentsProvider.makePayment(buyerBe, sellerBe, srcBe, paymentItemIdAttributeCode,
														amountAttributeCode, paymentTitle, assemblyToken);
				
			    rules.setState("PAYMENT_DONE"); 
			    if(paymentDone){
			     
			        //rules.set("srcEntityCode", srcBe.getCode());
			        rules.setState(paymentTitle);
			    		rules.setState("PAYMENT_SUCCESSFUL"); 
			     }else{
			     	rules.setState("PAYMENT_UNSUCCESSFUL");
			     }
				                     
	         }          

		rules.footer();
end