package life.genny.rules;
import life.genny.rules.QRules;

rule "Trigger Send Note"
	when
		rules: QRules(  isState("SEND_NOTE") &&
						!isState("LOOP_SEND_NOTE")) 
	 then
	 	rules.header();
		rules.setState("LOOP_SEND_NOTE");
		
	   	BaseEntity context = rules.getAsBaseEntity("contextBe");
		
		if(context != null){
			rules.println("context is null");
		}else{
			rules.sendNotes(context);
			rules.setState("SENT_NOTE");
		}
	 	rules.footer();      
end
