package life.genny.rules;

import life.genny.rules.QRules;
import life.genny.qwanda.entity.BaseEntity;

rule "Create New User"
    when
        rules: QRules( isState("CREATE_NEW_USER") && 
                    !isState("LOOP_CREATE_NEW_USER") )
    then
        rules.header();
        rules.setState("LOOP_CREATE_NEW_USER");
        BaseEntity be = rules.createUser();
        BaseEntity user = rules.getUser();

        /*  saving the default profile image   */
        rules.updateBaseEntityAttribute(user.getCode(), 
                                        user.getCode(), 
                                        "PRI_IMAGE_URL",
                                        "https://s3.ap-southeast-2.amazonaws.com/channel40-images/jtaQozJT5HSpn3bX6P4EXSqQj3NDalkQ");

        /*  set PRI_IS_PROFILE_COMPLETED = FALSE */
        rules.updateBaseEntityAttribute(user.getCode(), user.getCode(), "PRI_IS_PROFILE_COMPLETED", "FALSE");
        rules.setState("NEW_USER_CREATED");
        rules.println("New User is   ::   " + user);
        
        rules.clearState("PROFILE_CHECK_COMPLETED");
        rules.footer();
end
