package life.genny.rules;
import life.genny.rules.QRules;

rule "Trigger Update BEG"
	when
		rules: QRules(  isState("EVENT_BTN_CLICK") &&
                    isState("BTN_EDIT_BEG") && 
                    !isState("LOOP_TRIGGER_UPDATE_BEG")) 
	 then
	 	rules.header();
		rules.setState("LOOP_TRIGGER_UPDATE_BEG");
		
		rules.setState("TRIGGER_UPDATE_BEG");
		rules.setState("SEND_UPDATE_BEG_QUESTION");
	 	rules.footer();      
end
