package life.genny.rules;
import life.genny.rules.QRules;

/* Send User Company Question */
rule "Ask Registration - Host Company - STEP 1"
    when
        rules: QRules(  isState("SEND_USER_QUESTION") &&
        				isState("HOST_COMPANY_EXISTS") &&
        				isState("PROFILE_NOT_COMPLETED") &&
        				isState("PRI_IS_HOST_COMPANY") &&
        				isState("SENT_REGISTRATION_DATA") &&
						!isState("LOOP_ASK_REGISTRATION_HOST_COMPANY_STEP1") ) 
     then 
 		rules.header();		
		rules.setState("LOOP_ASK_REGISTRATION_HOST_COMPANY_STEP1");
 		
 		String questionSourceCode = rules.getUser().getCode();
		String questionTargetCode = rules.getUser().getCode();

		/* send question group for user */
		rules.set("questionSourceCode", questionTargetCode);
		rules.set("questionTargetCode", questionTargetCode);
		rules.set("questionGroupCode", "QUE_USER_HOST_COMPANY_GRP");
		rules.setState("SEND_QUESTION");

		rules.setState("SENT_USER_QUESTION");	
		rules.setState("SEND_HOST_COMPANY_QUESTION");	
 		rules.footer();
end
