package life.genny.rules;

import life.genny.rules.RulesUtils;
import life.genny.rules.QRules;
import life.genny.qwanda.message.QEventMessage;
import life.genny.qwanda.message.QCmdMessage;
import life.genny.qwanda.entity.EntityEntity;
import org.apache.commons.lang3.StringUtils;
import life.genny.qwanda.Answer;
import life.genny.qwanda.message.QDataAnswerMessage;
import life.genny.qwandautils.QwandaUtils;
import life.genny.rules.RulesUtils;
import life.genny.qwanda.entity.User;
import life.genny.qwanda.Link;
import life.genny.qwanda.entity.BaseEntity;

import io.vertx.core.json.JsonObject;

rule "Send DropDown Datas"
   agenda-group "CreateLoad"
   no-loop true
   when
     rules: QRules()
   then
    RulesUtils.header(drools.getRule().getName());
     
    String qwandaServiceUrl = rules.getQwandaServiceUrl();
     String userCode =  rules.getUser().getCode();
     System.out.println("The user Code is  ::  " +userCode);

   /* Get the users Company Code  */
    BaseEntity company =  rules.getParent(userCode,"LNK_STAFF");
    System.out.println("The users company code is  ::   " +company.getCode());
   
    /*      Getting list of loads      */
     JsonObject loadLists = new JsonObject( QwandaUtils.apiGet(qwandaServiceUrl+"/qwanda/baseentitys/GRP_LOADS/linkcodes/LNK_"+company.getCode()+"/attributes", rules.getToken()));
     loadLists.put("token", rules.getToken());
     System.out.println("List of Load Json: "+loadLists.toString());
     rules.getEventBus().publish("cmds",loadLists);

    /*   Getting list of the load category   */
     JsonObject loadCategoryLists = new JsonObject( QwandaUtils.apiGet(qwandaServiceUrl+"/qwanda/baseentitys/GRP_LOAD_CATEGORY/linkcodes/LNK_CORE?pageStart=0&pageSize=20", rules.getToken()));
     loadCategoryLists.put("token", rules.getToken());
     System.out.println("List of Load category Json: "+loadCategoryLists.toString());
     rules.getEventBus().publish("cmds",loadCategoryLists);
     
 	RulesUtils.footer(drools.getRule().getName());
  
end
