package life.genny.rules;

import life.genny.rules.RulesUtils;
import life.genny.rules.QRules;
import life.genny.qwandautils.QwandaUtils;
import life.genny.qwanda.Answer;
import life.genny.qwanda.message.QEventAttributeValueChangeMessage;
import life.genny.qwanda.entity.BaseEntity;
import io.vertx.core.json.JsonObject;
import io.vertx.core.json.JsonArray;

rule "Load Title Attribute Change"
/*  Update Jobs title based on Loads name value change  */
    when
    $m: QEventAttributeValueChangeMessage(  QEventAttributeValueChangeMessage.getData().getCode().equals("PRI_NAME")  && getAnswer().getTargetCode().startsWith("LOD_") )
    	rules : QRules()
    then    
    	    RulesUtils.header(drools.getRule().getName());
	    
         Answer newAnswer = $m.getAnswer();
         System.out.println(" Indside the Load Title Attribute Change  rule  "   );
         RulesUtils.println("The created value  ::  "+newAnswer.getCreatedDate());
         RulesUtils.println("Answer from QEventAttributeValueChangeMessage in Load Title Attribute Change ::  "+newAnswer.toString());
  
         String loadTitle = newAnswer.getValue();
         System.out.println("The new laod title is     ::"  +loadTitle );
           
       /* Get the sourceCode(Job code) for this LOAD */
        BaseEntity job = rules.getParent(newAnswer.getTargetCode(), "LNK_BEG");
       
       Answer jobTitleAnswer = new Answer(rules.getUser().getCode() ,job.getCode(), "PRI_TITLE" ,loadTitle);             
       rules.publishData(jobTitleAnswer);
        
       RulesUtils.footer(drools.getRule().getName());
       

end

