package life.genny.rules;

import life.genny.rules.RulesUtils;
import life.genny.rules.QRules;

import life.genny.qwanda.Answer;
import life.genny.qwanda.message.QEventAttributeValueChangeMessage;

import life.genny.qwanda.entity.BaseEntity;

rule "Load Title Attribute Change"
/*  Update Jobs title based on Load's name value change  */
    when
    $m: QEventAttributeValueChangeMessage(  QEventAttributeValueChangeMessage.getData().getCode().equals("PRI_NAME")  && getAnswer().getTargetCode().startsWith("LOD_") )
    	rules : QRules()
    then    
    	    RulesUtils.header(drools.getRule().getName());
	    
         Answer newAnswer = $m.getAnswer();
         
         RulesUtils.println("The created value  ::  "+newAnswer.getCreatedDate());
         RulesUtils.println("Answer from QEventAttributeValueChangeMessage  ::  "+newAnswer.toString());
  
         String loadTitle = newAnswer.getValue();
           
       /* Get the sourceCode(Job code) for this LOAD */
       BaseEntity job = rules.getParent(newAnswer.getTargetCode(),newAnswer.getAttributeCode());
       
         Answer jobTitleAnswer = new Answer(rules.getUser().getCode() ,job.getCode(), "PRI_TITLE" ,loadTitle);  
            
       rules.publishData(jobTitleAnswer);
        
       RulesUtils.footer(drools.getRule().getName());
       

end

