package life.genny.rules;

import life.genny.rules.RulesUtils;
import life.genny.rules.QRules;

import life.genny.qwanda.Answer;
import life.genny.qwanda.message.QEventAttributeValueChangeMessage;

import life.genny.qwanda.entity.BaseEntity;
 

rule "Load Description Attribute Change"
/*  Update Jobs description based on Load's desc value change  */

    when
      $m: QEventAttributeValueChangeMessage( QEventAttributeValueChangeMessage.getData().getCode().equals("PRI_DESCRIPTION") && getAnswer().getTargetCode().startsWith("LOD_") )
      rules : QRules()
    then    
	    RulesUtils.header(drools.getRule().getName());
	    
        /*     Collect load code from answer    */
         Answer newAnswer = $m.getAnswer();
         
         RulesUtils.println("The created value  ::  "+newAnswer.getCreatedDate());
         RulesUtils.println("Answer from QEventAttributeValueChangeMessage  ::  "+newAnswer.toString());
  
         String loadDescription = newAnswer.getValue();
           
       /* Get the sourceCode(Job code) for this LOAD */
       BaseEntity job = rules.getParent(newAnswer.getTargetCode(),newAnswer.getAttributeCode());
       
         Answer jobDescriptionAnswer = new Answer(rules.getUser().getCode() ,job.getCode(), newAnswer.getAttributeCode() ,loadDescription);  
            
       rules.publishData(jobDescriptionAnswer);
        
       RulesUtils.footer(drools.getRule().getName());
end

