
import life.genny.rules.QRules;
import life.genny.qwanda.entity.BaseEntity;
import life.genny.qwanda.message.QEventMessage;
import life.genny.rules.RulesUtils;
import io.vertx.core.json.JsonObject;
import java.util.List;
import java.util.Set;
import java.util.HashSet;
import java.util.HashMap;
import life.genny.qwanda.Link;

rule "Job Confirm Delivery"
when
  $m : QEventMessage( event_type == "BTN_CLICK" && data.code == "BTN_CONFIRM_DELIVERY")
  rules: QRules()
then
    
		RulesUtils.header(drools.getRule().getName());
  		String data = $m.getData().getValue();
		
  		if(data != null) {
		
		     JsonObject dataJson = new JsonObject(data);
		     String begCode = dataJson.getString("itemCode");
		     if(begCode != null) {
		    	 	rules.moveBaseEntity(begCode, "GRP_COMPLETED", "GRP_PAID","LNK_CORE");
		    	 	
		    	 	HashMap<String, String> contextMap = new HashMap<String, String>();
			    contextMap.put("JOB", begCode);
			    
			    List<BaseEntity> begKids = rules.getBaseEntitysByParentAndLinkCode(begCode,"LNK_BEG", 0, 20, false) ;
			    Set<String> recipientSet = new HashSet<String>();
			    
 				for (BaseEntity kid : begKids) {
					RulesUtils.println(kid.getCode());
			    		/*List<Link> links = rules.getLinks(kid.getCode(),"LNK_BEG");
			    		for (Link link : links) {
			    			contextMap.put(link.getLinkValue(), link.getTargetCode());
			    			if (link.getTargetCode().startsWith("PER_")) {
			    				recipientSet.add(link.getTargetCode());
			    			} 
			    		}
			    		*/
			    }
			    
		/* String[] recipients = recipientSet.toArray(new String[0]);

		 rules.sendMessage(begCode, recipients, contextMap, "MSG_CH40_DRIVER_IN_TRANSIT", "SMS"); */
		     }
		}

		RulesUtils.footer(drools.getRule().getName());

end