
import life.genny.rules.QRules;
import life.genny.qwanda.entity.BaseEntity;
import life.genny.qwanda.message.QEventMessage;
import life.genny.rules.RulesUtils;
import io.vertx.core.json.JsonObject;
import java.util.List;
import java.util.Set;
import java.util.HashSet;
import java.util.HashMap;
import life.genny.qwanda.Link;

rule "Job Confirm Delivery"
when
  $m : QEventMessage( event_type == "BTN_CLICK" && data.code == "BTN_CONFIRM_DELIVERY")
  rules: QRules()
then
    
		RulesUtils.header(drools.getRule().getName());
  		String data = $m.getData().getValue();
		
  		if(data != null) {
		
		     JsonObject dataJson = new JsonObject(data);
		     String begCode = dataJson.getString("itemCode");
		     if(begCode != null) {
		    	 	
		    	 	rules.moveBaseEntity(begCode, "GRP_COMPLETED", "GRP_PAID","LNK_CORE");
		    	 	
		    	 	HashMap<String, String> contextMap = new HashMap<String, String>();
			    contextMap.put("JOB", begCode);
			    
			    String[] recipients = new String[1];
		    		recipients[0] = rules.getUser().getCode();
		    		rules.sendMessage(begCode, recipients, contextMap, "MSG_CH40_DRIVER_DELIVERY_ARRIVED", "SMS");
		     }
		}

		RulesUtils.footer(drools.getRule().getName());

end