
import life.genny.rules.QRules;
import life.genny.qwanda.entity.BaseEntity;
import life.genny.qwanda.message.QEventMessage;
import life.genny.rules.RulesUtils;
import io.vertx.core.json.JsonObject;

rule "Manually Confirm Delivery"
when
  $m : QEventMessage( event_type == "BTN_CLICK" && data.code == "BTN_CONFIRM_DELIVERY")
  rules: QRules()
then
    
		RulesUtils.header(drools.getRule().getName());
  		String data = $m.getData().getValue();
		
  		if(data != null) {
		
		     JsonObject dataJson = new JsonObject(data);
		     String begCode = dataJson.getString("itemCode");
		     if(begCode != null) {
		    	 	rules.moveBaseEntity(begCode, "GRP_COMPLETED", "GRP_PAID","LNK_CORE");
		    	 	
		    	 	HashMap<String, String> contextMap = new HashMap<String, String>();
			    contextMap.put("JOB", begCode);
			    
			    List<BaseEntity> begKids = rules.getBaseEntitysByParentAndLinkCode(begCode,"LNK_BEG", 0, 20, false) ;
 				for (BaseEntity kid : begKids) {
			    		/* Get kid */
			    		contextMap.put("DRIVER", kid.getCode());
			    }
		
		 rules.sendMessage(begCode, recipients, contextMap, "MSG_CH40_DRIVER_IN_TRANSIT", "SMS"); 
		     }
		}

		RulesUtils.footer(drools.getRule().getName());

end