package life.genny.rules;

import life.genny.rules.RulesUtils;
import life.genny.rules.QRules;
import life.genny.qwanda.message.QEventMessage;
import life.genny.qwanda.message.QCmdMessage;
import life.genny.qwanda.message.QEventLinkChangeMessage;
import life.genny.qwanda.entity.EntityEntity;
import com.google.gson.Gson;
import life.genny.qwanda.Answer;
import life.genny.qwanda.message.QDataAnswerMessage;
import life.genny.qwanda.message.QEventAttributeValueChangeMessage;
import life.genny.qwandautils.KeycloakUtils;
import life.genny.qwandautils.QwandaUtils;
import life.genny.qwandautils.MergeUtil;
import life.genny.rules.RulesUtils;
import life.genny.qwanda.entity.User;
import life.genny.qwanda.Link;
import life.genny.qwanda.entity.BaseEntity;
import java.util.Map;
import java.util.HashMap; 
import java.time.LocalDateTime;
import java.time.ZonedDateTime;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonParseException;
import com.google.gson.JsonPrimitive;
import com.google.gson.JsonSerializationContext;
import com.google.gson.FieldNamingPolicy;
import io.vertx.core.json.JsonObject;
import io.vertx.core.json.JsonArray;
import java.time.format.DateTimeFormatter;
import life.genny.qwanda.DateTimeDeserializer;

/* Rule handling Submit Button click in the Create Load  */
rule "Submit LOAD"
   agenda-group "BucketView"
   no-loop true
    when
     /*  rules: QRules( isState("NEW_LOAD_SUBMISSION_COMPLETED") )     */  
       rules: QRules( ) 
    then
        RulesUtils.header(drools.getRule().getName());
        JsonObject newJobDetails = new JsonObject( QwandaUtils.apiGet(rules.getQwandaServiceUrl()+"/qwanda/baseentitys/GRP_NEW_ITEMS/linkcodes/LNK_CORE/attributes?pageStart=0&pageSize=10", rules.getToken()));
        newJobDetails.put("token", rules.getToken());
        System.out.println("The newly submitted Job details     ::     "+newJobDetails.toString());
       /*  Publish new Job/BEG data to the EventBus   */
         rules.publish("cmds",newJobDetails);
        
       String layout = RulesUtils.getLayout("card.json");
     	/* sending cmd BUCKET_VIEW */
        QCmdMessage cmdBucketView = new QCmdMessage("CMD_VIEW","BUCKET_VIEW");
        JsonObject bucketViewJson = new JsonObject().mapFrom(cmdBucketView);
        bucketViewJson.put("root", "GRP_DRIVER_VIEW");
        bucketViewJson.put("token",rules.getToken());
  		
        rules.publish("cmds",bucketViewJson);
           
        RulesUtils.println("  Submit LOAD :: BUCKET  LAYOUT (CMD VIEW) SENT TO FRONTEND");
	/*	rules.clearState("NEW_LOAD_SUBMISSION_COMPLETED");
        update(rules);   */
	    RulesUtils.footer(drools.getRule().getName()); 
end