package life.genny.rules;

import life.genny.rules.QRules;

import life.genny.qwanda.message.QEventMessage;

rule "User go offline event"
    when
        m : QEventMessage( event_type == "USER_GO_OFFLINE")
 		rules: QRules() 
    then
        
    		rules.header();
        
        /*Sending a toast message as soon as a user logs in */
        String[] recipientArr = {rules.getUser().getCode()};
        HashMap<String,String> contextMap = new HashMap<String, String>();
        rules.sendMessage("", recipientArr, contextMap,"MSG_CH40_WELCOME_TOAST", "TOAST");
        
        rules.updateBaseEntityAttribute(rules.getUser().getCode(), rules.getUser().getCode(), "PRI_ONLINE", "TRUE");
        
		rules.footer();      
end