package com.sample;

import life.genny.qwanda.message.QEventMessage;
import life.genny.qwanda.message.QCmdMessage;
import life.genny.qwanda.message.QMessage.MessageData;
import io.vertx.rxjava.core.eventbus.EventBus;
import life.genny.qwandautils.QwandaUtils;
import io.vertx.core.json.JsonObject;
import com.google.gson.Gson;
import com.sample.*;
import java.util.Map;
import java.util.HashSet;
import java.util.Set;




rule "User-Profile Update"
    when
        $m : QEventMessage( event_type == "FORM_SUBMIT" && data.code == "QUE_USER_PROFILE_GRP" )
  
        rules: QRules( ) 
    then
    	rules.header();
    	    /*  Get data.value and decode   */
        String dataString = $m.data.getValue();
        JsonObject dataJson = new JsonObject(dataString);
        String userCode = rules.getUser().getCode();
        String jobCode = dataJson.getString("targetCode");
        String actionCode = dataJson.getString("action"); 
  	   if(actionCode.equalsIgnoreCase("submit")) { 
  		   
             rules.set("IS_USER_PROFILE_COMPLETE", ( QwandaUtils.isMandatoryFieldsEntered(userCode, userCode, "QUE_USER_PROFILE_GRP", rules.getToken() ) ));           
  /*          rules.println("The profile completed value now is   ::    " + $user.getIsProfileCompleted()); */
           drools.setFocus("layout"); 
        }

        rules.footer();
  end

