package life.genny.rules;

import life.genny.rules.RulesUtils;
import life.genny.rules.QRules;

import life.genny.qwanda.message.QEventMessage;
import life.genny.qwanda.entity.BaseEntity;


rule "User-Profile"
    when
        m : QEventMessage( event_type == "PROFILE" && data.code == "PROFILE" && isState("STARTED"))
       rules: QRules( ) 
    then
         rules.header();
  	    String userCode = rules.getUser().getCode();
  	    
        rules.askQuestions(userCode,userCode,"QUE_USER_PROFILE_GRP");
       /*  Get Company Code of the current user   */
        BaseEntity company = rules.getParent(userCode, "LNK_STAFF");
        String companyCode = company.getCode();
        rules.println("The Company Code is :: "+companyCode);
       /*    Send Company asks   */       
        rules.askQuestions(userCode, companyCode, "QUE_USER_COMPANY_GRP");
	  /* Send SubLayout  */	
		rules.sendSublayout("SUB_USER_PROFILE", "user-profile.json");
         
       rules.footer(); 
end

