package life.genny.rules;

import life.genny.rules.QRules;

import life.genny.qwanda.message.QEventMessage;

rule "User go offline event"
    when
        m : QEventMessage( event_type == "USER_GO_OFFLINE")
 		rules: QRules( isState("STARTED") ) 
    then
        
    		rules.header();
        
        String userCode = rules.getUser().getCode();
        rules.updateBaseEntityAttribute(userCode, userCode, "PRI_ONLINE", "false");
        
		rules.footer();      
end