
package life.genny.rules;
import life.genny.rules.QRules;

/* trigger deselection for APPs
   state comes from the pre init DESELECT EVENT
*/
rule "00_Trigger_Deselect_APP"
	when
		rules: QRules(  isState("DESELECT_EVENT") &&
                        (getAsString("itemCode") != null) && (getAsString("itemCode").startsWith("APP_")) && 
						!isState("LOOP_TRIGGER_APP_DESELECT_EVENT")) 
	 then
	 	rules.header();
		rules.setState("LOOP_TRIGGER_APP_DESELECT_EVENT");

        /* we grab the code of the selected item */
        String applicationCode = rules.getAsString("itemCode");
       	if(applicationCode != null) {
       		BaseEntity application = rules.baseEntity.getBaseEntityByCode(applicationCode);
       		if(application != null) {
       			String parentBegCode = application.getValue("PRI_BEG_CODE", null);
       			if(parentBegCode != null) {
       				rules.set("begCode",parentBegCode);
       				rules.set("application", application);
       				rules.setState("SEND_NOTES_FOR_PARENT_BEG");
       			}		
       		}
       	}

	 	rules.footer();      
end
