
package life.genny.rules;
import life.genny.rules.QRules;


rule "10_SendNotes_For_ParentBEG"
	when
		rules: QRules(  isState("SEND_NOTES_FOR_PARENT_BEG") &&
						!isState("LOOP_SEND_NOTES_FOR_DESELECTED_APPLICATION")) 
	 then
	 	rules.header();
		rules.setState("LOOP_SEND_NOTES_FOR_DESELECTED_APPLICATION");
       
       	String begCode = rules.getAsString("begCode");
       	rules.sendNotes(begCode);
       	
       	rules.setState("SENT_NOTES_FOR_PARENT_BEG");

	 	rules.footer();      
end
