package life.genny.rules;

import life.genny.rules.RulesUtils;
import life.genny.rules.QRules;

import life.genny.qwandautils.QwandaUtils;
import life.genny.qwanda.message.QCmdMessage;
import life.genny.qwanda.message.QCmdLayoutMessage;

import io.vertx.core.json.JsonObject;

rule "Send Bucket Layout To Frontend"
    no-loop true
    salience 6
    agenda-group "SendLayoutsAndData"
    when
        rules: QRules( isState("SEND_BUCKET_DATA") && (!isState("SEND_BUCKET_LAYOUT"))  ) 
     then
     	RulesUtils.header(drools.getRule().getName());
     	
     	String layout = RulesUtils.getLayout("card.json");
     	
     	/* sending cmd BUCKET_VIEW */
        QCmdMessage cmdBucketView = new QCmdMessage("CMD_VIEW","BUCKET_VIEW");
        JsonObject bucketViewJson = new JsonObject().mapFrom(cmdBucketView);
        bucketViewJson.put("root", "GRP_DASHBOARD");
        bucketViewJson.put("token", rules.getToken());
        rules.publish("cmds",bucketViewJson);
           
        RulesUtils.println("BUCKET  LAYOUT (CMD VIEW) SENT TO FRONTEND");
		/*  rules.clearState("SEND_BUCKET_DATA");  */
		rules.setState("SEND_BUCKET_LAYOUT");
		
	    RulesUtils.footer(drools.getRule().getName());       		      
end
