package life.genny.rules;

import life.genny.rules.QRules;

rule "Trigger Search - Step 0"
     when
       rules: QRules( isState("TRIGGER_SEARCH") && 
                      !isState("DID_TRIGGER_SEARCH") ) 
     then

        String searchCode = rules.getAsString("searchCode");
        if(searchCode != null) {

            SearchEntity searchEntity = rules.baseEntity.getSearchEntityByCode(searchCode);
            if(searchEntity != null) {

                rules.set("searchEntity", searchEntity);
                rules.setState("PERFORM_SEARCH");
                drools.setFocus("SEARCH_DYNAMIC");
            }
        }

end
