package life.genny.rules;
import life.genny.rules.QRules;

rule "Trigger Search"
	when
		rules: QRules(  isState("TRIGGER_SEARCH") && 
						!isState("LOOP_TRIGGER_SEARCH") ) 
	 then
	 	rules.header();
		rules.setState("LOOP_TRIGGER_SEARCH");
		
		String searchCode = rules.getAsString("searchCode");
		if(searchCode != null) {
			
			/* we fetch the base entity */
			SearchEntity searchEntity = rules.getAsSearchEntity(searchCode);
			if(searchEntity != null) {
				
				rules.set("searchBe", searchEntity);
				rules.setState("PERFORM_SEARCH");
				drools.setFocus("SEARCH_DYNAMIC");
			}
		}

	 	rules.footer();      
end