package life.genny.rules;

import life.genny.rules.QRules;

rule "Perform Search - DEFAULT"
	   no-loop true
       ruleflow-group 'SEARCH_DYNAMIC'
       salience 1
     when
       rules: QRules( isState("PERFORM_SEARCH") && 
                      !isState("DID_PERFORM_SEARCH") ) 
     then

      rules.header();
     
	     rules.setState("DID_PERFORM_SEARCH");
         
	     /* perform generic search */
		
     rules.footer();
end