package com.sample;

import life.genny.qwanda.message.QEventMessage;
import life.genny.qwanda.message.QCmdMessage;
import life.genny.qwanda.message.QMessage.MessageData;
import io.vertx.rxjava.core.eventbus.EventBus;
import life.genny.qwandautils.QwandaUtils;
import io.vertx.core.json.JsonObject;
import com.google.gson.Gson;
import com.sample.*;
import java.util.Map;
import java.util.HashSet;
import java.util.Set;
import life.genny.qwanda.entity.User;

global java.lang.String REACT_APP_QWANDA_API_URL;


rule "Logout"
    when
        m : QEventMessage( event_type == "LOGOUT" && data.code == "LOGOUT" )
        $map : Map($value: this["token"] != null)
        bus: EventBus()
    then
        System.out.println("-------- Rule:- Logout --------");	
        QCmdMessage cmd = new QCmdMessage("CMD_LOGOUT","LOGOUT");
      Gson gson = new Gson();
        String json = gson.toJson(cmd);      
        System.out.println(json);
        JsonObject json2 = new JsonObject(json);
        json2.put("token", $value);
        bus.publish("cmds", json2);       
end