package com.sample;

import life.genny.qwanda.message.QEventMessage;
import life.genny.qwanda.message.QCmdMessage;
import life.genny.qwanda.message.QMessage.MessageData;
import io.vertx.rxjava.core.eventbus.EventBus;
import life.genny.qwandautils.QwandaUtils;
import io.vertx.core.json.JsonObject;
import com.google.gson.Gson;
import com.sample.*;
import java.util.Map;
import java.util.HashSet;
import java.util.Set;
import life.genny.qwanda.entity.User;

global java.lang.String REACT_APP_QWANDA_API_URL;




rule "test-user"
   when
      $map : Map($value: this["token"] != null)
      /* $user: User1(uname == "user1") */
      $user : User()
     /* $roles : Set(!isEmpty()) */
      $roles : Set( this.contains("user") && !this.contains("admin"))
     
   then
      System.out.println("-------- Rule:- Test user role- user--------");	
      System.out.println(" Hello!!! "+ $user.getFullName());
      System.out.println(" Your username is: "+ $user.getUname());
      System.out.println(" Your have user role: user");   
end

