package com.sample;

import life.genny.qwanda.message.QEventMessage;
import life.genny.qwanda.message.QCmdMessage;
import life.genny.qwanda.message.QMessage.MessageData;
import io.vertx.rxjava.core.eventbus.EventBus;
import life.genny.qwandautils.QwandaUtils;
import io.vertx.core.json.JsonObject;
import com.google.gson.Gson;
import com.sample.*;
import java.util.Map;
import java.util.HashSet;
import java.util.Set;
import life.genny.qwanda.entity.User;

global java.lang.String REACT_APP_QWANDA_API_URL;


rule "User-Profile"
    when
        m : QEventMessage( event_type == "PROFILE" && data.code == "PROFILE" )
        $map : Map($value: this["token"] != null)
        $user: User(realm != null)
        bus: EventBus()
    then
        System.out.println("-------- Rule:- User Profile --------");		    
		String qwandaServiceUrl = System.getenv("REACT_APP_QWANDA_API_URL")==null?System.getenv("REACT_APP_QWANDA_API_URL"):REACT_APP_QWANDA_API_URL;
  	    String tokenString = (String)$map.get("token");
       /* JsonObject obj = new JsonObject(QwandaUtils.apiGet(qwandaServiceUrl+"/qwanda/asksmsg", tokenString)); */
		JsonObject obj = new JsonObject(QwandaUtils.apiGet(qwandaServiceUrl+"/qwanda/baseentitys/"+$user.getuCode()+"/asks2/QUE_USER_PROFILE_GRP/"+$user.getuCode(), tokenString));
		System.out.println("*******************");
		System.out.println("Profile Json="+obj.toString());	
		System.out.println("*******************");	
		obj.put("token", $value);					
		bus.publish("cmds", obj);
		
		/* sending cmd form view */
        QCmdMessage cmd = new QCmdMessage("CMD_VIEW","FORM_VIEW");
        /* Convert cmd to JSON Obj */
        JsonObject cmdObj = new JsonObject().mapFrom(cmd);
         cmdObj.put("root", "QUE_USER_PROFILE_GRP");
        /* cmdObj.put("data", "itemsPerPage:8");        */ 
        System.out.println(" ##################### ");
        System.out.println("Form View ="+cmdObj.toString()); 
        System.out.println(" #################### ");
        cmdObj.put("token", $value);
        /* Publish it to the EventBus */
        bus.publish("cmds", cmdObj); 
end

