package life.genny.rules;

import life.genny.rules.QRules;
import java.util.List;

rule "Welcome Page - Send Layout"
     when
        rules: QRules(  isState("WELCOME_PAGE_SEND_LAYOUT") && 
                        !isState("LOOP_WELCOME_PAGE_SEND_LAYOUT") ) 
     then      
        rules.header();
        rules.setState("LOOP_WELCOME_PAGE_SEND_LAYOUT");

        rules.sendSublayout("LAY_DEFAULT", "thankyou.json");
        rules.setState("WELCOME_PAGE_SENT_LAYOUT");
        
		rules.footer();     		      
end
     	