package life.genny.rules;

import life.genny.rules.QRules;
import life.genny.qwanda.message.QEventBtnClickMessage;

rule "Selected Role"
	when
		m : QEventBtnClickMessage( 	event_type == "BTN_CLICK" && data.code.startsWith("BTN_SELECT_NEW_ROLE"))
	    rules: QRules( 	isState("STARTED") &&
											!isState("ROLE_WAS_SELECTED") )
	 then

		rules.header();

		/* format of the code: BTN_SELECT_NEW_ROLE_PRI_IS_ROLE */
		String selectedRoleCode = m.getData().getCode();
		if(selectedRoleCode != null) {

			/* we compute the selected role */

			/* we update the user attribute */
			//rules.updateBaseEntityAttribute(rules.getUser().getCode(), rules.getUser().getCode(), "PRI_IS_INTERN", "TRUE");

		}

	/*	rules.updateBaseEntityAttribute(rules.getUser().getCode(), rules.getUser().getCode(), "PRI_IS_EDU_PROVIDER", "FALSE");
		rules.updateBaseEntityAttribute(rules.getUser().getCode(), rules.getUser().getCode(), "PRI_IS_HOST_COMPANY", "FALSE"); */

		rules.setState("ROLE_WAS_SELECTED");

		rules.footer();
end

/*
package life.genny.rules;

import life.genny.rules.QRules;
import life.genny.qwanda.message.QEventBtnClickMessage;

rule "Select Education Provider Role"

	when
		$m : QEventBtnClickMessage( event_type == "BTN_CLICK" &&
									data.code == "BTN_SELECT_ROLE_EDU_PROVIDER")
	    rules: QRules( 	isState("STARTED") &&
						!isState("EDU_PROVIDER_SELECTED") )
	 then
	    rules.header();

		rules.updateBaseEntityAttribute(rules.getUser().getCode(), rules.getUser().getCode(), "PRI_IS_EDU_PROVIDER", "TRUE");
		rules.updateBaseEntityAttribute(rules.getUser().getCode(), rules.getUser().getCode(), "PRI_IS_INTERN", "FALSE");
		rules.updateBaseEntityAttribute(rules.getUser().getCode(), rules.getUser().getCode(), "PRI_IS_HOST_COMPANY", "FALSE");

		rules.setState("EDU_PROVIDER_SELECTED");
	    rules.footer();
end */
