package life.genny.rules;

import life.genny.rules.QRules;
import java.util.List;

rule "Handle new Role Selection"
  when
    $m: QEventAttributeValueChangeMessage( QEventAttributeValueChangeMessage.getData().getCode().startsWith("PRI_IS") )
    rules: QRules( isState("STARTED") && !isState("HAS_SELECTED_NEW_ROLE") )
  then

    rules.header();
    rules.setState("HAS_SELECTED_NEW_ROLE");

    rules.set("registration_question_grp", "QUE_INTERN_GRP");
  /*  rules.sendSelections("GRP_UNI_SELECTION", "LNK_CORE", 10);
    rules.sendSelections("GRP_DEGREE_SELECTION", "LNK_CORE", 10);
    rules.sendSelections("GRP_GENDERS", "LNK_CORE", 10);
    rules.sendSelections("GRP_RESIDENTIAL_STATUS", "LNK_CORE", 10); */

    /* TODO: this needs to be moved to prj_client folder
    /* Add Intern to GRP_INTERNS */
    /*rules.setState("TRIGGER_ADD_TO_GROUP"); */

    /* We check if profile has been completed */
    rules.setState("TRIGGER_PROFILE_CHECK");

    rules.footer();
end
