package life.genny.rules;
import life.genny.rules.QRules;

rule "Select Messages"
    when
      rules: QRules(  isState("EVENT_TV_SELECT") &&
                      isState("TV1") &&
                      isState("GRP_MESSAGES") &&
                      !isState("LOOP_SELECT_MESSAGES") )
    then
      rules.header();
      rules.setState("LOOP_SELECT_MESSAGES");

      String tvSelectValue = rules.getAsString("tvSelectValue");
      
      if(tvSelectValue.equals("GRP_MESSAGES")){
        rules.sendSublayout("messages-layout", "messages-layout.json");
        rules.setState("SELECTED_MESSAGES");
        rules.clearState(tvSelectValue);
      }
      rules.footer();
end