package life.genny.rules;

import life.genny.qwanda.message.QEventMessage;
import life.genny.qwanda.message.QCmdMessage;
import life.genny.rules.QRules;


rule "TV_SELECT_HISTORY"
     when
       rules: QRules( isState("STARTED") && isState("EVENT_TV_SELECT") && isState("GRP_HISTORY") && !isState("LOOP_TV_ITEM_DATA_SENT")) 
     then

     rules.header();
       rules.setState("LOOP_TV_ITEM_DATA_SENT");
       String parentCode = rules.get("tvSelectValue").toString();
       rules.println("The tvSelectValue value is:: "+rules.get("tvSelectValue").toString());
	   SearchEntity searchBE = new SearchEntity(drools.getRule().getName(),"Archieved Jobs")
  	     .addSort("PRI_CREATED","Created",SearchEntity.Sort.DESC)
  	     .setSourceCode(parentCode)
  	     .setStakeholder(rules.getUser().getCode())
  	     .addFilter("PRI_CODE",SearchEntity.StringFilter.LIKE,"BEG_%")
  	     .setPageStart(0)
  	     .setPageSize(10000);
  	     
  	   /* Send search result */
       rules.sendSearchResults(searchBE, parentCode);
       
       /* Send ListView */
       rules.publishViewCmdMessage("LIST_VIEW", parentCode);

     rules.setState("TV_ITEM_DATA_SENT");
     rules.footer();
end
