package life.genny.rules;
import life.genny.rules.QRules;

import life.genny.qwanda.Answer;
import life.genny.qwanda.message.QDataAnswerMessage;
import life.genny.qwanda.message.QEventAttributeValueChangeMessage;


rule "Listen Attribute Change - PRI_DRIVER_CONFIRMED_DELIVERY"
ruleflow-group 'AttributeChange'
    when
        $m: QEventAttributeValueChangeMessage( answer.attributeCode == "PRI_DRIVER_CONFIRMED_DELIVERY" )
        rules : QRules( isState("ATTRIBUTE_CHANGE") && !isState("SENT_DELIVERY_MESSAGES") )
     then    
      	rules.header();
 
       /* rules.publishData(new QDataAnswerMessage($m.getAnswer()));  */
        String[] recipientCodes = rules.getRecipientCodes($m);
        
        HashMap<String, String> contextMap = new HashMap<String, String>();
		contextMap.put("JOB", $m.getBe().getCode());
			    		
		rules.sendMessage("OK", recipientCodes, contextMap, "MSG_CH40_DELIVERED", "TOAST");
		rules.sendMessage("OK", recipientCodes, contextMap, "MSG_CH40_DELIVERED", "SMS");
		rules.sendMessage("OK", recipientCodes, contextMap, "MSG_CH40_DELIVERED", "EMAIL");
        
 
     	rules.setState("SENT_DELIVERY_MESSAGES");
   	    rules.footer();
  
end