package life.genny.rules;

import life.genny.rules.QRules;
import life.genny.qwanda.message.QEventBtnClickMessage;

rule "Select Driver Role - Step 0"

	when
		 rules: QRules( 	isState("BTN_SELECT_ROLE_DRIVER") && 
						!isState("DRIVER_SELECTED") )   
	 then
	    rules.header();

		/* PRI_IS_DRIVER and PRI_IS_OWNER */
		rules.updateBaseEntityAttribute(rules.getUser().getCode(), rules.getUser().getCode(), "PRI_IS_OWNER", "FALSE");
		rules.updateBaseEntityAttribute(rules.getUser().getCode(), rules.getUser().getCode(), "PRI_IS_DRIVER", "TRUE");

		rules.setState("DRIVER_SELECTED");
	    rules.footer();     		      
end
