package life.genny.rules;

import life.genny.rules.QRules;
import java.util.List;

rule "Selected Freight Owner Role"
     when
        $m: QEventAttributeValueChangeMessage( QEventAttributeValueChangeMessage.getData().getCode().equals("PRI_IS_OWNER") )
        rules: QRules( isState("STARTED") && !isState("HAS_SELECTED_PROFILE_FREIGHT_OWNER") && isState("BTN_SELECT_ROLE_FREIGHT_OWNER") )
     then

        rules.header();
		rules.setState("HAS_SELECTED_PROFILE_FREIGHT_OWNER");

     	/*rules.set("registration_question_grp", "QUE_INTERN_GRP");
     	rules.sendSelections("GRP_UNI_SELECTION", "LNK_CORE", 10);
     	rules.sendSelections("GRP_DEGREE_SELECTION", "LNK_CORE", 10);
     	rules.sendSelections("GRP_GENDERS", "LNK_CORE", 10);
     	rules.sendSelections("GRP_RESIDENTIAL_STATUS", "LNK_CORE", 10); */
		
		/* to remove */
		String userCode = rules.getUser().getCode();
		
		/* Get company code for this user */
        BaseEntity company = rules.getParent(userCode, "LNK_STAFF");
        String companyCode = company.getCode();
       /* Update link with the link Value  */
        rules.println("UPDATING link value OF LINK BETWEEN   ::   " + companyCode + "  &  " + userCode);
        Link updateLink = new Link( companyCode, userCode, "LNK_STAFF", "OWNER", (double) 1);
        String result = QwandaUtils.apiPutEntity(rules.getQwandaServiceUrl() + "/qwanda/links", JsonUtils.toJson(updateLink),rules.getToken());
        rules.publishBE(rules.getUser());

		/* Add Freight Owner to GRP_FREIGHT_OWNERS */
     	rules.setState("TRIGGER_ADD_TO_GROUP");
     	rules.setState("TRIGGER_PROFILE_CHECK");

		rules.footer();
end
