package life.genny.rules;

import life.genny.rules.QRules;

rule "Pre Init Answer"
    when
        m : QDataAnswerMessage( QDataAnswerMessage.getData_type().equals(Answer.class.getSimpleName()) )
        rules: QRules(!isState("STARTED"))
     then
        rules.setDrools(drools);
    
        rules.println("RULE INIT ANSWER: "+ m + " - " + m.getItems());
		
		/* we grab the data associated to the answers */
		 Answer[] answers = m.getItems();
		 if(answers.length > 0) {
		 	
		 	/* TODO: update to handle multiple answers */
		 	Answer firstAnswer = answers[0];
		 	String attributeCode = firstAnswer.getAttributeCode();
		 	String sourceCode = firstAnswer.getSourceCode();
		 	String targetCode = firstAnswer.getTargetCode();
		 	String value = firstAnswer.getValue();
		 	
		 	if(attributeCode != null && sourceCode != null && targetCode != null && value != null ){
		 	    rules.set("attributeCode", attributeCode);
		 	    rules.set("sourceCode", sourceCode);
		 		rules.set("targetCode", targetCode);
		 	    rules.set("value", value);
		 	    
		 	    rules.setState(attributeCode);
		 	}
		 		 	
		 }
       
        rules.setState("DATA_ANSWER");
        rules.setState("STARTED");
        
        drools.setFocus("Answer");
end
