package life.genny.rules;
import life.genny.rules.QRules;
import life.genny.qwanda.message.QEventMessage;

rule "View Seller Profile"
    when
        m : QEventMessage(  event_type == "PROFILE" && 
                            data.code == "PROFILE")
                            
	    rules: QRules(  isState("ROLE_FOUND") &&
                        isState("PRI_IS_SELLER") &&	
                        !isState("LOOP_VIEW_SELLER_PROFILE")) 	
     then
        rules.header();    
        rules.setState("LOOP_VIEW_SELLER_PROFILE");
        rules.setState("SEND_SELLER_DROPDOWN_SELECTIONS");

        rules.set("questionSourceCode", rules.getUser().getCode());
		rules.set("questionTargetCode", rules.getUser().getCode());
		rules.set("questionGroupCode", "QUE_SELLER_PROFILE_GRP");
		rules.set("questionIsPopup", false);

        rules.setState("ASK_QUESTION");
        rules.footer();     		      
end
