package life.genny.rules;

import life.genny.rules.RulesUtils;
import life.genny.rules.QRules;
import life.genny.qwanda.message.QDataAnswerMessage;

rule "Answer - Rating "
ruleflow-group 'Answer'
    when
        m : QDataAnswerMessage( QDataAnswerMessage.getData_type().equals(Answer.class.getSimpleName()))
        rules: QRules()
    then    
       
    	   rules.header();
	   rules.processAnswerRating(m, "PRI_DRIVER_RATING"); 
       rules.footer();
           
end
