package life.genny.rules;

import life.genny.rules.QRules;

import life.genny.qwanda.Answer;

import life.genny.qwanda.message.QDataAnswerMessage;


/* Update address */ 
rule "Update Address Answers"
        ruleflow-group 'Answer'
	when
		m : QDataAnswerMessage( QDataAnswerMessage.getData_type().equals(Answer.class.getSimpleName()) )
	    rules: QRules()
	then
	    rules.header();	    
	
		rules.processAddressAnswers(m);
		
     rules.footer();
end