package life.genny.rules;


import life.genny.rules.QRules;
import life.genny.qwanda.Answer;
import life.genny.qwanda.message.QDataAnswerMessage;


rule "Answer"
ruleflow-group 'Answer'
    when
        m : QDataAnswerMessage( QDataAnswerMessage.getData_type().equals(Answer.class.getSimpleName()) )
        rules: QRules()
    then    
        rules.header();
        
	   rules.processAnswer(m); 
 
       rules.footer();
           
end


   