package life.genny.rules;


import life.genny.rules.QRules;
import life.genny.qwanda.Answer;
import life.genny.qwanda.message.QDataAnswerMessage;
import life.genny.rules.RulesUtils;

rule "Answer"
ruleflow-group 'Answer'
    when
        $m : QDataAnswerMessage( QDataAnswerMessage.getData_type().equals(Answer.class.getSimpleName()) )
        rules: QRules()
    then    
        rules.header();
        	
        Answer[] answers = $m.getItems();
		if(answers != null && answers.length > 0) {
			
			Answer firstAnswer = answers[0];
			String attributeCode = firstAnswer.getAttributeCode();
			
			if(attributeCode.contains("ADDRESS_FULL")) {
				rules.processAddressAnswers($m);
			}
			else if(attributeCode.contains("_RATING")) {
				
				RulesUtils.println("----------------------");
				rules.processAnswerRating($m, "PRI_DRIVER_RATING"); 
			}
			else if(PaymentUtils.checkIfAnswerContainsPaymentAttribute($m) == true && !rules.isState("PAYMENT_ANSWER")) {
				rules.setState("PAYMENT_ANSWER");
				drools.setFocus("makepayment");
			}
			else {
				rules.processAnswer($m); 
			}	
		}
	   
       rules.footer();
           
end


   