package life.genny.rules;
import life.genny.rules.QRules;

/* LINK BEG + APPLICATION || APPLICATION */
rule "Submit Apply BEG - Step 2"
	when
		rules: QRules(  isState("LINK_GRP_APPLIED_TO_APPLICATION") && 
                        isState("CREATED_LINK") && 
						isState("APPLICATION") && 
						!isState("LOOP_SUBMIT_APPLY_BEG_STEP2")) 
	 then
	 	rules.header();
        rules.setState("LOOP_SUBMIT_APPLY_BEG_STEP2");

        BaseEntity application = rules.getAsBaseEntity("applicationBe");
        BaseEntity beg = rules.getAsBaseEntity("begBe");
        
        if(beg == null){   
            rules.println("beg is null");
        }else if(application == null){
            rules.println("application is null");    
        }else{
            /* because APPLICATION is in the state from prevoius rule  */
            rules.clearState("APPLICATION");

            /* link BEG to APPLICATION || APPLICATION */
            rules.set("linkSourceCode",  "GRP_APPLIED");
            rules.set("linkTargetCode", application.getCode());
            rules.set("linkCode", "LNK_CORE");
            rules.set("linkValue", "APPLICATION");
            rules.set("linkWeight", 1.0);
            rules.setState("CREATE_LINK");

            rules.setState("LINK_APPLICATION_TO_APPLICANT");
        }
        rules.footer();
end