package life.genny.rules;
import life.genny.rules.QRules;
import life.genny.utils.VertxUtils;

/* Subscribe Users to APPLICATION BE */
rule "Submit Apply BEG - Step 4"
	when
		rules: QRules( 	isState("SUBSCRIBE_USERS_TO_APPLICATION") && 
						isState("CREATED_LINK") &&
						isState("APPLICANT") &&
						!isState("LOOP_SUBMIT_APPLY_BEG_STEP4") ) 
	 then
	 	rules.header();
        rules.setState("LOOP_SUBMIT_APPLY_BEG_STEP4");
		
		/* get application, beg's creator from state map */
        BaseEntity application = rules.getAsBaseEntity("applicationBe");
        BaseEntity creator = rules.getAsBaseEntity("creatorBe");

		if(application == null){
            rules.println("application is null");
            return;
        }else if(creator == null){
            rules.println("creator is null");
            return;
        }else{
            rules.subscribeUserToBaseEntity(rules.getUser().getCode(), application.getCode());
            rules.subscribeUserToBaseEntity(creator.getCode(), application.getCode());
            rules.setState("PUBLISH_APPLICATION_AND_KIDS");
		}
	 	rules.footer();      
end
