package life.genny.rules;

import life.genny.rules.QRules;
import life.genny.qwanda.message.QDataAskMessage;
import life.genny.qwanda.QuestionSourceTarget;
import life.genny.qwanda.message.QDataQSTMessage;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.Optional;
import life.genny.qwandautils.MergeUtil;

rule "Check if Profile Completed"
  no-loop true
  when

    rules: QRules(  isUserPresent() == true &&
                    isState("CHECK_USER_PROFILE_COMPLETED") &&
                    !isState("LOOP_CHECK_USER_PROFILE_COMPLETED") )
  then
    rules.header();

    rules.setState("LOOP_CHECK_USER_PROFILE_COMPLETED");

    /* User is either a buyer or a seller -> we check if they have completed one of these 2 forms */
    Boolean isProfileCompleted = false;

    /* we try buyer group */
    isProfileCompleted = rules.isMandatoryFieldsEntered(rules.getUser().getCode(), "QUE_BUYER_GRP");
    if(isProfileCompleted == false) {

      /* if not buyer, we try seller */
      isProfileCompleted = rules.isMandatoryFieldsEntered(rules.getUser().getCode(), "QUE_SELLER_GRP");;
    }

    if(isProfileCompleted == true) { // profile was completed

      rules.setState("PROFILE_IS_COMPLETED");
      rules.setState("APPLICATION_READY");
    }
    else {
      rules.setState("PROFILE_NOT_COMPLETED");
    }

    rules.println("PRI_IS_PROFILE_COMPLETED value   ::   " +  isProfileCompleted);
    rules.footer();
end
