package life.genny.rules;

import life.genny.rules.QRules;
import life.genny.qwanda.message.QDataAskMessage;
import life.genny.qwanda.QuestionSourceTarget;
import life.genny.qwanda.message.QDataQSTMessage;

import java.util.ArrayList;
import java.util.Arrays;
import life.genny.qwandautils.MergeUtil;

rule "Profile is completed - step 3 - channel40"
    when
	    rules: QRules( isState("USER_PROFILE_ANSWERED") && !isState("LOOP_PROFILE_COMPLETED") )
     then
     	rules.header();

		rules.setState("LOOP_PROFILE_COMPLETED");
   	    
		rules.updateBaseEntityAttribute(rules.getUser().getCode(), rules.getUser().getCode(), "PRI_IS_PROFILE_COMPLETED", "TRUE");
		rules.setState("PROFILE_IS_COMPLETED");
		rules.setState("CHECK_USER_COMPANY");
		
	    rules.footer();
end
