package life.genny.rules;

import life.genny.rules.QRules;
import life.genny.qwanda.message.QDataAskMessage;
import life.genny.qwanda.QuestionSourceTarget;
import life.genny.qwanda.message.QDataQSTMessage;

import java.util.ArrayList;
import java.util.Arrays;
import life.genny.qwandautils.MergeUtil;

rule "Profile is NOT completed - step 3 - channel40"
    when
	    rules: QRules( isState("PROFILE_NOT_COMPLETED") && !isState("LOOP_PROFILE_NOT_COMPLETED") )
     then
     	rules.header();

		rules.setState("LOOP_PROFILE_NOT_COMPLETED");
		rules.updateBaseEntityAttribute(rules.getUser().getCode(), rules.getUser().getCode(), "PRI_IS_PROFILE_COMPLETED", "FALSE");
		rules.setState("TRIGGER_REGISTRATION");

	    rules.footer();
end
