package life.genny.rules;

import life.genny.rules.QRules;
import life.genny.qwanda.message.QDataAskMessage;
import life.genny.qwanda.QuestionSourceTarget;
import life.genny.qwanda.message.QDataQSTMessage;

import java.util.ArrayList;
import java.util.Arrays;
import life.genny.qwandautils.MergeUtil;

rule "Is user company setup - step 2 - driver"
    when
	    rules: QRules( isState("USER_PROFILE_ANSWERED") && !isState("LOOP_CHECK_USER_COMPANY_COMPLETED") )
     then
     	rules.header();

		rules.setState("LOOP_CHECK_USER_COMPANY_COMPLETED");
   	    
		
		/* we check if the user is linked to a company */
		BaseEntity company = rules.getParent(rules.getUser().getCode(), "LNK_STAFF");
		Boolean driverCompanyExists = company != null;
		
		if(driverCompanyExists && rules.isMandatoryFieldsEntered(company.getCode(), "QUE_NEW_USER_COMPANY_GRP")) {
			rules.setState("USER_COMPANY_READY");
		}
		else {
			rules.setState("USER_COMPANY_NOT_READY");
			rules.setState("PROFILE_NOT_COMPLETED");
		}

        rules.setState("PROFILE_CHECK_COMPLETED");

	    rules.footer();
end
