package life.genny.rules;
import life.genny.rules.QRules;

rule "Send Project Matched Message to Student"
    when
        rules: QRules(  isState("SEND_PROJECT_MATCHED_MESSAGE_TO_INTERN") && 
                        !isState("LOOP_SEND_PROJECT_MATCHED_MESSAGE_TO_INTERN") )
    then
        rules.header();
        rules.setState("LOOP_SEND_PROJECT_MATCHED_MESSAGE_TO_INTERN");
        rules.println("SEND MESSAGES TO INTERNS");
         
        BaseEntity beg = rules.getAsBaseEntity("begBe");
        BaseEntity hostCompany = rules.getAsBaseEntity("companyBe");
        BaseEntity internship = rules.getAsBaseEntity("internshipBe");

        
        if(beg == null){
            rules.println("beg is null");
            return;
        }else if(hostCompany == null){
            rules.println("hostCompany is null");
            return;
        }else if(internship == null){
            rules.println("internship is null");
            return;
        }else{
            
            HashMap<String, String> contextMap = new HashMap<String, String>(); 
            contextMap.put("BEG", beg.getCode());
            contextMap.put("HOSTCOMPANY", hostCompany.getCode());
            contextMap.put("INTERNSHIP", internship.getCode());

            
            
            String[] recipients = null;

            List<BaseEntity> students = rules.getChildrens(beg.getCode(), "LNK_BEG", "INTERN");
            if(students != null) {
                rules.println("No. of students   ::   " + students.size() );
                recipients = new String[students.size()];
                int i = 0;
                for(BaseEntity student : students) {
                    recipients[i] = student.getCode();
                    i++;
                }
            }
             
            // rules.sendMessage(null, recipients, contextMap, "MSG_INTERNMATCH_CPM_CAPSTONE_PRJ_APPROVAL_INTERN", "EMAIL");
            rules.sendMessage(null, recipients, contextMap, "MSG_INTERNMATCH_CPM_CAPSTONE_PRJ_APPROVAL_INTERN", "SMS");
            
            rules.setState("SENT_PROJECT_MATCHED_MESSAGE_TO_INTERN");
         }
         
         rules.footer();      
end