package life.genny.rules;
import life.genny.rules.QRules;

/* LINK BEG + APPLICATION || APPLICATION */
rule "Submit Apply BEG - Step 1"
	when
		rules: QRules(  isState("LINK_BEG_AND_APPLICATION") && 
						!isState("LOOP_SUBMIT_APPLY_BEG_STEP1")) 
	 then
	 	rules.header();
        rules.setState("LOOP_SUBMIT_APPLY_BEG_STEP1");

        BaseEntity beg = rules.getAsBaseEntity("begBe");
        BaseEntity application = rules.getAsBaseEntity("applicationBe");
        
        if(beg == null){   
            rules.println("beg is null");
        }else if(application == null){
            rules.println("application is null");    
        }else{
            /* link BEG to APPLICATION || APPLICATION */
            rules.set("linkSourceCode",  beg.getCode());
            rules.set("linkTargetCode", application.getCode());
            rules.set("linkCode", "LNK_BEG");
            rules.set("linkValue", "APPLICATION");
            rules.set("linkWeight", 1.0);
            rules.setState("CREATE_LINK");

            rules.setState("LINK_GRP_APPLIED_TO_APPLICATION");
        }
        rules.footer();
end