package life.genny.rules;
import life.genny.rules.QRules;

/* LINK BEG + CURRENT USER || APPLICANT */
rule "Submit Apply BEG - Step 3"
	when
		rules: QRules( 	isState("LINK_APPLICATION_TO_APPLICANT") && 
                        isState("CREATED_LINK") && 
						isState("APPLICATION") && 
						!isState("LOOP_SUBMIT_APPLY_BEG_STEP3")) 
	 then
	 	rules.header();
        rules.setState("LOOP_SUBMIT_APPLY_BEG_STEP3");

        /* get application from state map */
        BaseEntity application = rules.getAsBaseEntity("applicationBe");
        
        if(application != null){   
            /* link BEG to CURRENT USER || APPLICANT */
            rules.set("linkSourceCode", application.getCode());
            rules.set("linkTargetCode", rules.getUser().getCode());
            rules.set("linkCode", "LNK_APP");
            rules.set("linkValue", "APPLICANT");
            rules.set("linkWeight", 1.0);
            rules.setState("CREATE_LINK");

            rules.setState("SUBSCRIBE_USERS_TO_APPLICATION");
        }else{
            rules.println("application BaseEntity is null");
        }
	 	rules.footer();
end