package life.genny.rules;
import life.genny.rules.QRules;

rule "Trigger Create Note - Step 0"
	when
		rules: QRules(  isState("EVENT_BTN_CLICK") &&
						isState("BTN_ADD_NOTE") && 
						!isState("LOOP_TRIGGER_ADD_NOTE")) 
	 then
	 	rules.header();
		
		rules.setState("LOOP_TRIGGER_ADD_NOTE");
		
	   	String contextCode = rules.getAsString("itemCode");
	   	String message = rules.getAsString("message");
	   	
		if(contextCode != null && message != null) {
			rules.setState("CREATE_NOTE_BASEENTITY");
		}

	 	rules.footer();      
end