package life.genny.rules;
import life.genny.rules.QRules;

rule "Trigger Create Note - Step 1"
	when
		rules: QRules(  isState("CREATE_NOTE_BASEENTITY") &&
						!isState("LOOP_CREATE_NOTE_BASEENTITY")) 
	 then
	 	rules.header();
		
		rules.setState("LOOP_CREATE_NOTE_BASEENTITY");
		
	   	String contextCode = rules.getAsString("itemCode");
		String message = rules.getAsString("message");
		
		rules.createNote(contextCode, message, "USER");
		
		rules.sendNotes(contextCode);
	 	rules.footer();      
end