package life.genny.rules;
import life.genny.rules.QRules;
import life.genny.utils.VertxUtils;

/* Subscribe COMPANY to NEW_BEG */
rule "Shortlist Internship - Step 5"	
	when
		rules: QRules( 	isState("SUBSCRIBE_COMPANY_TO_NEW_BEG") && 
						isState("SUBSCRIBED_CREATOR_TO_NEW_BEG") && 
						isState("BTN_SHORTLIST_INTERN") && 
						isState("EVENT_BTN_CLICK") &&  
						!isState("LOOP_SHORTLIST_INTERN_STEP5")) 

	 then
	 	rules.header();
        rules.setState("LOOP_SHORTLIST_INTERN_STEP5");

        BaseEntity company = rules.getAsBaseEntity("companyBe");
        BaseEntity newBeg = rules.getAsBaseEntity("newBegBe");
		
		if(company != null && newBeg != null){
			rules.subscribeUserToBaseEntityAndChildren(company.getCode(), newBeg.getCode(), "LNK_BEG");
	 		rules.setState("SUBSCRIBED_COMPANY_TO_NEW_BEG");

	 		rules.setState("SUBSCRIBE_INTERN_TO_NEW_BEG");
		}
	 	rules.footer();      
end
