package life.genny.rules;
import life.genny.rules.QRules;

/* MOVE BEG TO SHORTLIST */
rule "Shortlist Internship - Step 8"
	when
		rules: QRules( 	isState("MOVE_NEW_BEG_TO_SHORTLIST") && 
		                isState("PUBLISHED_NEW_BEG_AND_KIDS") && 
						isState("BTN_SHORTLIST_INTERN") && 
						isState("EVENT_BTN_CLICK") && 
						!isState("LOOP_SHORTLIST_INTERN_STEP8")) 
	 then
	 	rules.header();
        rules.setState("LOOP_SHORTLIST_INTERN_STEP8");

        BaseEntity newBeg = rules.getAsBaseEntity("newBegBe");
        
        if(newBeg == null){
            rules.println("newBeg is null");    
        }else{
            /* link GRP_SHORTLIST to BEG || BEG */
            rules.set("linkSourceCode", "GRP_SHORTLISTED");
            rules.set("linkTargetCode", newBeg.getCode());
            rules.set("linkCode", "LNK_CORE");
            rules.set("linkValue", "BEG");
            rules.set("linkWeight", 1.0);
            rules.setState("CREATE_LINK");

            rules.setState("MOVED_NEW_BEG_TO_SHORTLIST");

            rules.setState("GO_TO_HOMEPAGE");
        }
	 	rules.footer();      
end
