// package life.genny.rules;
// import life.genny.rules.QRules;
// import life.genny.utils.VertxUtils;

// /* Unsubscribe INTERN from OLD_BEG */
// rule "Shortlist Internship - Step 60"	
// 	when
// 		rules: QRules( 	isState("UNSUBSCRIBE_INTERN_FROM_OLD_BEG") && 
// 						isState("BTN_SHORTLIST_INTERN") && 
// 						isState("EVENT_BTN_CLICK") && 
// 						!isState("LOOP_SHORTLIST_INTERN_STEP60")) 

// 	 then
// 	 	rules.header();
//         rules.setState("LOOP_SHORTLIST_INTERN_STEP60");

//         BaseEntity intern = rules.getAsBaseEntity("internBe");
//         BaseEntity oldBeg = rules.getAsBaseEntity("begBe");
		
// 		if(intern != null && oldBeg != null){
// 			rules.subscribeUserToBaseEntityAndChildren(intern.getCode(), newBeg.getCode(), "LNK_BEG");
// 	 		rules.setState("UNSUBSCRIBED_INTERN_FROM_OLD_BEG");

// 	 		rules.setState("PUBLISH_NEW_BEG_AND_KIDS");
// 		}
// 	 	rules.footer();      
// end