package life.genny.rules;
import life.genny.rules.QRules;

rule "Check If Mobile Verificaiton Required"
    when
        rules: QRules( isState("CHECK_USER_PHONE_NUMBER") &&
                       !isState("LOOP_VERIFY_MOBILE_PHONE_NUMBER") )
    then
        rules.header();
		rules.setState("LOOP_VERIFY_MOBILE_PHONE_NUMBER");

		if(rules.doesQuestionGroupExist("QUE_MOBILE_VERIFICATION_GRP")) {
			rules.setState("MOBILE_VERIFICATION_REQUIRED");
		}
		else {
			rules.setState("MOBILE_VERIFICATION_NOT_REQUIRED");
			rules.setState("MOBILE_VERIFIED");
		}
        rules.footer();
end
