package life.genny.rules;
import life.genny.rules.QRules;

rule "Resend Mobile Verification Code"
	when
	    rules: QRules( 	isState("STARTED") &&
						isState("BTN_RESEND_VERIFICATION_SMS") &&
						!isState("LOOP_RESENT_VERIFICATION_SMS") ) 
	then
	 	rules.header();
        
		rules.setState("LOOP_RESENT_VERIFICATION_SMS");
		/* we resendsend the new verification code */
		rules.sendMobileVerificationPasscode(rules.getUser().getCode());
		
	 	rules.footer();      
end