package life.genny.rules;

import life.genny.rules.QRules;


rule "Send Layout Change To Frontend - Channel 40"

    salience 699
    no-loop true
    ruleflow-group "SendLayoutsAndData"
    when
        rules: QRules( !isState("LAYOUT_CHANGE_READY") ) 
     then
     	rules.header();
     	
        rules.sendLayout("LAY_DEFAULT","layouts/layout1.json");
           
        rules.setState("LAYOUT_CHANGE_READY");
 
		
	    rules.footer();    		      
end
