package life.genny.rules;

import life.genny.rules.RulesUtils;
import life.genny.rules.QRules;

rule "Send ListView Layout To Frontend - User is Driver"
    salience 660
    agenda-group "SendLayoutsAndData"
    when
        rules: QRules(  isState("SEND_BUCKET_DATA") && isState("USER_IS_DRIVER") && (!isState("SEND_LIST_VIEW")) ) 
     then
     	rules.header();
     	
     	/* sending cmd LIST_VIEW */
           rules.sendViewCmd("LIST_VIEW", "GRP_NEW_ITEMS"); 

		rules.setState("SEND_LIST_VIEW");
		
	    rules.footer();     		      
end
