package life.genny.rules;
import life.genny.rules.QRules;

rule "Send Internship Data"
	when
		rules: QRules(  isState("TRIGGER_ADD_BEG") && 
						!isState("LOOP_SEND_INTERNSHIP_DATA")  )
	then 
		rules.header();
		rules.setState("LOOP_SEND_INTERNSHIP_DATA");

		rules.sendSelections("GRP_FIELD_OF_WORK", "LNK_CORE", 10);
		rules.sendSelections("GRP_DURATION", "LNK_CORE", 10);

		rules.setState("SENT_INTERNSHIP_DATA");
		rules.footer();
end
