package life.genny.rules;
import life.genny.rules.QRules;

/* Create Internship BaseEntity */
rule "Add Internship - Step 2"
	when
		rules: QRules(  isState("CREATE_INT") && 
						isState("CREATED_BASE_ENTITY") && 
						isState("BEG") && 
						isState("CREATED_BEG") && 
						!isState("LOOP_ADD_INTERNSHIP_STEP2") ) 
	 then
	    rules.header();
		rules.setState("LOOP_ADD_INTERNSHIP_STEP2");

		/* GET newly created BEG BaseEntity */
		BaseEntity beg = rules.getAsBaseEntity("baseEntity");	
		
		/* SET BEG BaseEntity to state */
		rules.set("begBe", beg);	

        /* Create Internship BaseEntity*/
		rules.set("beCode", rules.getUser().getCode());
		rules.set("bePrefix", "INT");
		rules.set("beName", "INTERNSHIP");
		rules.setState("CREATE_BASE_ENTITY");	

		rules.setState("CREATED_INT");			
        rules.setState("LINK_BEG_TO_INT");
	    rules.footer();     		      
end