package life.genny.rules;
import life.genny.rules.QRules;

rule "Add Internship - Step 5"
	when
        rules: QRules(  isState("ASK_INTERNSHIP_QUESTION") && 
						isState("LINK_CREATED") && 
						isState("BEG") && 
                        !isState("LOOP_ADD_INTERNSHIP_STEP5")  )
     then 
 		rules.header();
		rules.setState("LOOP_ADD_INTERNSHIP_STEP5");

		BaseEntity internship = rules.getAsBaseEntity("internshipBe");

		rules.set("sourceCode", rules.getUser().getCode());
		rules.set("targetCode", internship.getCode());
		rules.set("questionGroup", "QUE_INTERNSHIP_GRP");
		rules.set("isPopup", false);
		
		rules.setState("ASK_QUESTION");
 		rules.footer();
end
