package life.genny.rules;

import life.genny.qwanda.message.QCmdMessage;
import life.genny.qwanda.message.QBulkMessage;
import life.genny.qwanda.message.QDataBaseEntityMessage;
import life.genny.qwanda.message.QEventMessage;
import life.genny.rules.QRules;
import io.vertx.core.json.JsonObject;
import java.util.List;
import java.util.ArrayList;
import life.genny.qwanda.entity.BaseEntity;
import life.genny.utils.VertxUtils;

rule "Generate Tree Roles"

    ruleflow-group 'GenerateTree'
 
     when
       rules: QRules(isState("GENERATE_TREE") && !isState("GENERATE_TREE_RULES"))
     then
        rules.header();
        rules.setState("GENERATE_TREE_RULES");

        rules.println("Generating Base Tree Rules for "+rules.realm());
        rules.generateTreeRules();	
        
        rules.footer();
end
