package life.genny.rules;
import life.genny.rules.QRules;

rule "Select Role - BUYER"
	when
	    rules: QRules( 	isState("BTN_SELECT_ROLE_BUYER") && 
						isState("ROLE_SELECTION") &&
						!isState("BUYER_SELECTED") )
	 then

		rules.header();
		rules.setState("BUYER_SELECTED");

		rules.baseEntity.updateBaseEntityAttribute(rules.getUser().getCode(), rules.getUser().getCode(), "PRI_IS_BUYER", "TRUE");
		rules.baseEntity.updateBaseEntityAttribute(rules.getUser().getCode(), rules.getUser().getCode(), "PRI_IS_SELLER", "FALSE");

		rules.setState("PRI_IS_BUYER");
		rules.setState("ROLE_SET");
	    rules.footer();
end
