package life.genny.rules;
import life.genny.rules.QRules;

  rule "Show Terms and Conditions On Form Submit - mentormatch"
     no-loop true
     salience 560
      when
          $m : QEventMessage( event_type == "FORM_SUBMIT" && data.code == "QUE_NEW_USER_PROFILE_GRP_MENTORMATCH" )
          rules: QRules( isState("STARTED") )
       then

            rules.header();
     	    String userCode = rules.getUser().getCode();
    		rules.askQuestions(userCode, userCode, "QUE_NEW_USER_TC_GRP");
            rules.footer();
  end
