package life.genny.rules;

import life.genny.rules.QRules;
import life.genny.qwanda.message.QEventMessage;

rule "Edit user profile"

    when
	    $m : QEventMessage( event_type == "BTN_CLICK" && data.code == "BTN_EDIT_MENTORMATCH_PROFILE" )
	    rules: QRules( !isState("EDIT_PROFILE") )
     then

     	rules.header();
    	rules.setState("EDIT_PROFILE");
    	rules.sendMentorMatchLayoutsAndData(true);
    	rules.footer();       		      
end
