package life.genny.rules;

import life.genny.rules.QRules;
import life.genny.qwanda.message.QEventMessage;
import io.vertx.core.json.JsonObject;

rule "Mentor Form Submit"
   no-loop true
    when
        $m : QEventMessage( event_type == "FORM_SUBMIT" && data.code == "QUE_MENTOR_GRP")
        rules: QRules( !isState("USER_MENTOR_COMPLETED"))
    then
    	rules.header();

        String userCode = rules.getUser().getCode();

        rules.updateBaseEntityAttribute(userCode, userCode, "PRI_MENTORMATCH_PROFILE_COMPLETED", "TRUE");
        rules.setState("USER_MENTOR_COMPLETED");
        drools.setFocus("SendLayoutsAndData");

        rules.footer();
  end
