package life.genny.rules;

import life.genny.rules.QRules;
import life.genny.qwanda.message.QEventMessage;
import io.vertx.core.json.JsonObject;

rule "User-Profile Submit - mentormatch"
   no-loop true
   ruleflow-group 'FormSubmit'
    when
        $m : QEventMessage( event_type == "FORM_SUBMIT" && data.code == "QUE_NEW_USER_PROFILE_GRP")
        rules: QRules( !isState("USER_PROFILE_COMPLETED") ) 
    then
    	rules.header();

        /*  Get data.value and decode   */
        String dataString = $m.data.getValue();
        JsonObject dataJson = new JsonObject(dataString);
        String userCode = rules.getUser().getCode();
        String jobCode = dataJson.getString("targetCode");
        String actionCode = dataJson.getString("action");

  	   if(actionCode.equalsIgnoreCase("submit")) {
           rules.setState("USER_PROFILE_COMPLETED");
           drools.setFocus("SendLayoutsAndData");
        }
  	    else {
           drools.setFocus("SendLayoutsAndData");
        }

        rules.footer();
  end
