package life.genny.rules;
import life.genny.rules.QRules;

rule "Send Invite Message to Intern"
	when
		rules: QRules(  isState("SEND_INVITATION_MESSAGE_TO_INTERN") && 
						        !isState("LOOP_SEND_INVITATION_MESSAGE_TO_INTERN") )
	then
	 	rules.header();
		rules.setState("LOOP_SEND_INVITATION_MESSAGE_TO_INTERN");
    
    BaseEntity intern = rules.getAsBaseEntity("internBe");

    if(intern == null){
        rules.println("intern is null");
        return;
    }else {
      
      HashMap<String, String> contextMap = new HashMap<String, String>(); 
      contextMap.put("INTERN", intern.getCode());

      String[] recipients = new String[1];
      recipients[0] = intern.getCode();

      rules.sendMessage(null, recipients, contextMap, "MSG_INTERNMATCH_INVITE_INTERN", "EMAIL");
      rules.sendMessage(null, recipients, contextMap, "MSG_INTERNMATCH_INVITE_INTERN", "SMS");


      rules.setState("SENT_INVITATION_MESSAGE_TO_INTERN");
 		}
	 	
	 	rules.footer();      
end
