package life.genny.rules;
import life.genny.rules.QRules;

/* Send Dashboard */
rule "Shortlist Internship - Step 1"
	when
		rules: QRules( 	isState("DUPLICATE_BEG") && 
						isState("BEG_APPLICATION_READY") && 
						isState("BTN_SHORTLIST_INTERN") && 
						isState("EVENT_BTN_CLICK") && 
						!isState("LOOP_SHORTLIST_INTERN_STEP1")) 
	 then
	 	rules.header();
        rules.setState("LOOP_SHORTLIST_INTERN_STEP1");

		BaseEntity beg = rules.getAsBaseEntity("begBe");
		BaseEntity newBeg = rules.duplicateBaseEntity(beg, "BEG", "BEG");
		rules.println("Duplicated BE   ::   " +newBeg);
		
	 	rules.footer();      
end
