package life.genny.rules;
import life.genny.rules.QRules;

/* Duplicate BEG */
rule "Shortlist Internship - Step 1"
	when
		rules: QRules( 	isState("DUPLICATE_BEG") && 
						isState("BEG_APPLICATION_READY") && 
						isState("BTN_SHORTLIST_INTERN") && 
						isState("EVENT_BTN_CLICK") && 
						!isState("LOOP_SHORTLIST_INTERN_STEP1")) 
	 then
	 	rules.header();
        rules.setState("LOOP_SHORTLIST_INTERN_STEP1");

		BaseEntity oldBeg = rules.getAsBaseEntity("begBe");
		BaseEntity application = rules.getAsBaseEntity("applicationBe");

		BaseEntity newBeg = rules.createBaseEntityByCode(rules.getUser().getCode(), "BEG", "BEG");
		if(newBeg != null && application != null){
			
			String[] linkValues = {"APPLICATION"};
			rules.copyLinksExcept(oldBeg, newBeg, linkValues);
			rules.set("newBegBe", newBeg);
        	rules.setState("DUPLICATED_BEG");

        	rules.setState("LINK_BEG_TO_APPLICATION");
		}
	 	rules.footer();      
end
