package life.genny.rules;
import life.genny.rules.QRules;

/* LINK BEG + APPLICATION || APPLICATION */
rule "Shortlist Intern - Step 2"
	when
		rules: QRules(  isState("LINK_BEG_TO_APPLICATION") && 
						isState("DUPLICATED_BEG") && 
						isState("BTN_SHORTLIST_INTERN") && 
						isState("EVENT_BTN_CLICK") && 
						!isState("LOOP_SHORTLIST_INTERN_STEP2")) 
	 then
	 	rules.header();
        rules.setState("LOOP_SHORTLIST_INTERN_STEP2");

        BaseEntity application = rules.getAsBaseEntity("applicationBe");
        BaseEntity beg = rules.getAsBaseEntity("begBe");
        BaseEntity newBeg = rules.getAsBaseEntity("newBegBe");
        
        if(beg == null){   
            rules.println("beg is null");
        }else if(application == null){
            rules.println("application is null");    
        }else if(newBeg == null){
            rules.println("newBeg is null");    
        }else{

            /* link NEW BEG to APPLICATION || APPLICATION */
            rules.set("linkSourceCode",  newBeg.getCode());
            rules.set("linkTargetCode", application.getCode());
            rules.set("linkCode", "LNK_BEG");
            rules.set("linkValue", "APPLICATION");
            rules.set("linkWeight", 1.0);
            rules.setState("CREATE_LINK");

            rules.setState("LINKED_BEG_TO_APPLICATION");

            rules.setState("LINK_SHORTLIST_TO_BEG");
        }
end