package life.genny.rules;
import life.genny.rules.QRules;

/* LINK GRP_SHORTLIST + BEG */
rule "Submit Internship - Step 3"
	when
		rules: QRules( 	isState("LINK_SHORTLIST_TO_BEG") && 
						isState("LINKED_BEG_TO_APPLICATION") && 
						isState("BTN_SHORTLIST_INTERN") && 
						isState("EVENT_BTN_CLICK") && 
						!isState("LOOP_SHORTLIST_INTERN_STEP3")) 
	 then
	 	rules.header();
        rules.setState("LOOP_SHORTLIST_INTERN_STEP3");

		BaseEntity application = rules.getAsBaseEntity("applicationBe");
        BaseEntity beg = rules.getAsBaseEntity("begBe");
        BaseEntity newBeg = rules.getAsBaseEntity("newBegBe");
        
        if(beg == null){   
            rules.println("beg is null");
        }else if(application == null){
            rules.println("application is null");    
        }else if(newBeg == null){
            rules.println("newBeg is null");    
        }else{
            /* link GRP_SHORTLIST to BEG || BEG */
            rules.set("linkSourceCode", "GRP_SHORTLISTED");
            rules.set("linkTargetCode", newBeg.getCode());
            rules.set("linkCode", "LNK_CORE");
            rules.set("linkValue", "BEG");
            rules.set("linkWeight", 1.0);
            rules.setState("CREATE_LINK");

            rules.setState("LINKED_SHORTLIST_TO_BEG");

            rules.setState("SUBSCRIBE_INTERN_TO_BEG");
        }
		
	 	rules.footer();      
end
