package life.genny.rules;
import life.genny.rules.QRules;
import life.genny.qwanda.entity.BaseEntity;

rule "Submit Internship - Step 4"
	when
		rules: QRules( 	isState("SUBSCRIBE_INTERN_TO_BEG") && 
						isState("LINKED_SHORTLIST_TO_BEG") &&
						!isState("LOOP_SHORTLIST_INTERN_STEP4") ) 
	 then
	 	rules.header();
        rules.setState("LOOP_SHORTLIST_INTERN_STEP4");

		BaseEntity newBeg = rules.getAsBaseEntity("newBegBe");
		BaseEntity applicant = rules.getAsBaseEntity("applicantBe");


		if(beg != null){
			if(applicant != null){
				rules.subscribeUserToBaseEntity(applicant.getCode(), newBeg.getCode());

				String[] begSubscribers = rules.getSubscribers(beg.getCode());
				rules.println("SUBSCRIBERS of newly copied BEG   ::   " + Arrays.toString(begSubscribers));
				
				rules.setState("SUBSCRIBED_INTERN_TO_NEW_BEG");

			}else{
				rules.println("applicant is null");
			}
		}else{
			rules.println("beg is null");
		}
	 	rules.footer();      
end
