package life.genny.rules;

import life.genny.rules.QRules;
import java.util.List;
import java.util.stream.Collectors;
import life.genny.qwanda.entity.BaseEntity;
import life.genny.qwanda.attribute.EntityAttribute;

rule "Invite New User - Step 1"
     when
        rules: QRules(  isState("CREATE_USER_INVITE") && !isState("DID_CREATE_USER_INVITE") )
     then
        rules.header();

		rules.setState("DID_CREATE_USER_INVITE");
		
		/* we get the company */
		BaseEntity company = rules.getUserCompany();
		BaseEntity newUser = rules.baseEntity.create(company.getCode(), "PER", "New user");
		
		if(newUser != null) {
			rules.set("newUser", newUser);
			rules.setState("INVITE_USER_SEND_DATA"); 
		}

		rules.footer();
end
