package life.genny.rules;

import life.genny.rules.QRules;
import java.util.List;
import java.util.stream.Collectors;
import life.genny.qwanda.entity.BaseEntity;
import life.genny.qwanda.attribute.EntityAttribute;

rule "Invite New User - Step 0 - Create New User"
     when
        rules: QRules(  isState("EVENT_BTN_CLICK") && isState("BTN_CPY_ADD_STAFF") && !isState("LOOP_INVITE_USER") )
     then
        rules.header();

		rules.setState("LOOP_INVITE_USER");

		rules.setState("INVITE_USER_SEND_DATA");
      	rules.footer();
end
