package life.genny.rules;

import life.genny.rules.QRules;
import java.util.List;
import java.util.stream.Collectors;
import life.genny.qwanda.entity.BaseEntity;
import life.genny.qwanda.attribute.EntityAttribute;

rule "Invite New User - Step 2 - Send Data"
     when
        rules: QRules(  isState("INVITE_USER_SEND_DATA") && !isState("LOOP_INVITE_USER_SENT_DATA") )
     then
        rules.header();

		rules.setState("LOOP_INVITE_USER_SENT_DATA");
		
		BaseEntity newUser = rules.getAsBaseEntity("newUser");
		if(newUser != null) {
			
			/* we send the questions */
			rules.sendQuestions(rules.getUser().getCode(), newUser.getCode(), "QUE_INVITE_USER_GRP");
		}

		rules.setState("INVITE_USER_SEND_LAYOUT");
		
		rules.footer();
end
