package life.genny.rules;

import life.genny.rules.QRules;
import java.util.List;
import java.util.stream.Collectors;
import life.genny.qwanda.entity.BaseEntity;
import life.genny.qwanda.attribute.EntityAttribute;

rule "Invite New User - Step 1 - Send Layout"
     when
        rules: QRules(  isState("INVITE_USER_SEND_LAYOUT") && !isState("LOOP_INVITE_USER_SEND_LAYOUT") )
     then
        rules.header();

		rules.setState("LOOP_INVITE_USER_SEND_LAYOUT");

    	  	/* we send the popup layout */
		rules.sendSublayout("invite-user", "/company/invite_user.json", true);
		/*rules.askQuestions(rules.getUser().getCode(), rules.getUser().getCode(), "QUE_INVITE_USER_GRP", true, true); */
      
      	rules.footer();
end
