package life.genny.rules;

import life.genny.rules.QRules;
import java.util.List;
import java.util.stream.Collectors;
import life.genny.qwanda.entity.BaseEntity;
import life.genny.qwanda.attribute.EntityAttribute;

rule "Invite New User - Step 4 - Cancel New User"
     when
        rules: QRules(  isState("EVENT_FORM_SUBMIT") && isState("CANCEL") && isState("QUE_INVITE_USER_GRP") && !isState("LOOP_DID_CANCEL_NEW_USER") )
     then
        rules.header();

		rules.setState("LOOP_DID_CANCEL_NEW_USER");
		rules.setState("RETURN_TO_HOMEPAGE");
      
      	rules.footer();
end
