package life.genny.rules;

import life.genny.rules.QRules;
import java.util.List;
import java.util.stream.Collectors;
import life.genny.qwanda.entity.BaseEntity;
import life.genny.qwanda.attribute.EntityAttribute;

rule "Invite New User - Step 4 - Submit New User"
     when
        rules: QRules(  isState("EVENT_FORM_SUBMIT") && isState("SUBMIT") && isState("QUE_INVITE_USER_GRP") && !isState("LOOP_DID_SUBMIT_NEW_USER") )
     then
        rules.header();

		rules.setState("LOOP_DID_SUBMIT_NEW_USER");
		
		rules.showLoading("", true);
		
		String targetCode = rules.getAsString("targetCode");
		
		if(targetCode != null) {
			
			/* we grab the new user that was just created */
			BaseEntity newUser = rules.baseEntity.getBaseEntityByCode(targetCode);
			if(newUser != null) {
				
				rules.set("newUser", newUser);
				rules.setState("CREATE_NEW_KEYCLOAK_ACCOUNT");
			}
		}
      
      	rules.footer();
end
