package life.genny.rules;

import life.genny.rules.QRules;
import java.util.List;
import java.util.stream.Collectors;
import life.genny.qwanda.entity.BaseEntity;
import life.genny.qwanda.attribute.EntityAttribute;

rule "Invite New User - Step 5 - Create User Account"
     when
        rules: QRules(  isState("CREATE_NEW_KEYCLOAK_ACCOUNT") && !isState("LOOP_DID_CREATE_KEYCLOAK_ACCOUNT") )
     then
        rules.header();

		rules.setState("LOOP_DID_CREATE_KEYCLOAK_ACCOUNT");

		BaseEntity newUser = rules.getAsBaseEntity("newUser");
		
		/* we grab the user details */
		String firstname = newUser.getValue("PRI_FIRSTNAME", null);
		String lastname = newUser.getValue("PRI_LASTNAME", null);
		String email = newUser.getValue("PRI_EMAIL", null);
		String username = email;
		
		if(firstname != null && lastname != null && email != null && username != null) {
			
			String name = firstname + " " + lastname;
			
			rules.showLoading("Creating user account...", true);

			/* we set up the new user on keycloak + generate the final baseEntity */
			BaseEntity createdUser = rules.createUser(firstname, lastname, name, username, email);
			if(createdUser != null) {
				rules.set("createdUser", createdUser);
				rules.setState("LINK_NEW_USER_TO_COMPANY");
			}
			else {
				rules.setState("RETURN_TO_HOMEPAGE");
			}
		}
	
      
      	rules.footer();
end
