package life.genny.rules;

import life.genny.rules.QRules;
import java.util.List;
import java.util.stream.Collectors;
import life.genny.qwanda.entity.BaseEntity;
import life.genny.qwanda.attribute.EntityAttribute;

rule "Invite New User - Step 5 - Create User Account"
     when
        rules: QRules(  isState("CREATE_NEW_KEYCLOAK_ACCOUNT") && !isState("LOOP_DID_CREATE_KEYCLOAK_ACCOUNT") )
     then
        rules.header();

		rules.setState("LOOP_DID_CREATE_KEYCLOAK_ACCOUNT");

		BaseEntity newUser = rules.getAsBaseEntity("newUser");
		
		/* we grab the user details */
		String firstname = newUser.getValue("PRI_FIRSTNAME", null);
		String lastname = newUser.getValue("PRI_LASTNAME", null);
		String email = newUser.getValue("PRI_EMAIL", null);
		String username = email;
		
		if(firstname != null && lastname != null && email != null && username != null) {
			
			String name = firstname + " " + lastname;
			
			rules.showLoading("Creating user account...", true);

			/* we setup the attribute map */
			HashMap<String, String> attributes = new HashMap<String, String>();
			attributes.put("PRI_IMAGE_URL", "https://s3.ap-southeast-2.amazonaws.com/channel40-images/jtaQozJT5HSpn3bX6P4EXSqQj3NDalkQ");
			attributes.put("PRI_REGISTRATION_DATETIME", DateUtils.getCurrentUTCDateTime());
			attributes.put("PRI_IS_COMPANY", "FALSE");
			
			/* if the current user is buyer */
			if(rules.isUserBuyer()) {
				attributes.put("PRI_IS_BUYER", "TRUE");
				attributes.put("PRI_IS_SELLER", "FALSE");
			}
			else if(rules.isUserSeller()) {
				attributes.put("PRI_IS_SELLER", "FALSE");
				attributes.put("PRI_IS_BUYER", "TRUE");
			}
			
			/* links */
			
			Link[] links = new Link[1];
			
			/* we setup the link to the role */
			String selectedRole = newUser.getValue("LNK_ASSIGNED_CPY_ROLE", "");
			if(selectedRole != null) {
				
				/* we create the link from the user to the role */
				Link newLink = new Link(null, selectedRole, "LNK_ROLE", "ROLE", 1.0);
				links[0] = newLink;
			}
			
			/* we set up the new user on keycloak + generate the final baseEntity */
			BaseEntity createdUser = rules.createUser(firstname, lastname, name, username, email, attributes, links);
			if(createdUser != null) {
			    
				rules.set("createdUser", createdUser);
				rules.setState("SEND_MESSAGE_TO_NEW_USER");
			}
			else {
				rules.setState("RETURN_TO_HOMEPAGE");
			}
		}
	
      
      	rules.footer();
end
