package life.genny.rules;

import life.genny.rules.QRules;
import java.util.List;
import java.util.stream.Collectors;
import life.genny.qwanda.entity.BaseEntity;
import life.genny.qwanda.attribute.EntityAttribute;

rule "Invite New User - Step 7 - Assign Role To User"
     when
        rules: QRules(  isState("ASSIGN_ROLE_TO_USER") && !isState("LOOP_DID_ASSIGN_ROLE_TO_USER") )
     then
        rules.header();

		rules.setState("LOOP_DID_ASSIGN_ROLE_TO_USER");

		BaseEntity newUser = rules.getAsBaseEntity("newUser");
		BaseEntity createdUser = rules.getAsBaseEntity("createdUser");
		
		if(createdUser != null) {
			
			rules.showLoading("Assigning role to user...", true);
			
			String selectedRole = newUser.getValue("LNK_ASSIGNED_CPY_ROLE", "");
			if(selectedRole != null) {
				
				/* we link the user to the role */
				rules.baseEntity.createLink(createdUser.getCode(), selectedRole, "LNK_ROLE", "ROLE", 1.0);
				
				rules.setState("SEND_MESSAGE_TO_NEW_USER");
			}
		}
	
      
      	rules.footer();
end
