package life.genny.rules;

import life.genny.rules.QRules;
import java.util.List;
import java.util.stream.Collectors;
import life.genny.qwanda.entity.BaseEntity;
import life.genny.qwanda.attribute.EntityAttribute;

rule "Invite New User - Step 8 - Send Message to User"
     when
        rules: QRules(  isState("SEND_MESSAGE_TO_NEW_USER") && !isState("LOOP_DID_SEND_MESSAGE_TO_USER") )
     then
        rules.header();

		rules.setState("LOOP_DID_SEND_MESSAGE_TO_USER");

		BaseEntity newUser = rules.getAsBaseEntity("newUser");
		BaseEntity createdUser = rules.getAsBaseEntity("createdUser");
		
		if(newUser != null && createdUser != null) {
			
			
		}
	
      
      	rules.footer();
end
