package life.genny.rules;

import life.genny.rules.QRules;
import java.util.List;
import java.util.stream.Collectors;
import life.genny.qwanda.entity.BaseEntity;
import life.genny.qwanda.attribute.EntityAttribute;

rule "Invite New User - Step 9 - Return to homepage"
     when
        rules: QRules(  isState("RETURN_TO_HOMEPAGE") && !isState("LOOP_DID_RETURN_TO_HOMEPAGE") )
     then
        rules.header();

		rules.setState("LOOP_DID_RETURN_TO_HOMEPAGE");
		rules.redirectToHomePage();
		rules.sendToastNotification("User was added to your company. An email was sent to them so they can join the platform.", "info");
      	rules.footer();
end
