package life.genny.rules;

import life.genny.rules.QRules;


rule "Ask First User Profile"
    no-loop true
    when
        rules: QRules(  isState("NEW_USER") && (!isState("ASK_FIRST_PROFILE")) ) 
     then
     	rules.header();
     	rules.debug();
   
    		rules.sendLayout("LAY_FULL_SCREEN","layouts/initial-profile-update");
   	
  		rules.askQuestions(rules.getUser().getCode(),rules.getUser().getCode(),"QUE_NEW_USER_PROFILE_GRP");
  		
        rules.setState("ASK_FIRST_PROFILE");
 		
	    rules.footer();     		      
end
