package life.genny.rules;

import life.genny.rules.QRules;


rule "Ask First User Profile"
    no-loop true
	salience 5
    agenda-group "NewUserProfile"
    when
        rules: QRules( isState("NEW_USER") && isNewUserProfileCompleted() == false ) 
     then
     	rules.header();
     	rules.debug();   		
   	
   		rules.sendSelections("GRP_USER_ROLE", "LNK_CORE", 10);
   	
  		rules.askQuestions(rules.getUser().getCode(),rules.getUser().getCode(),"QUE_NEW_USER_PROFILE_GRP");

	    rules.footer();     		      
end
