package life.genny.rules;

import life.genny.rules.QRules;


rule "Ask First User Profile"
    no-loop true
    when
        rules: QRules( isState("NO_USER") && (!isState("LAYOUT_CHANGE_READY")) &&  (!isState("ASK_FIRST_PROFILE")) ) 
     then
     	rules.header();
     	
     	
  		rules.askQuestions(rules.getUser().getCode(),rules.getUser().getCode(),"QUE_NEW_USER_PROFILE_GRP");
  		rules.sendLayout("LAY_FULL_SCREEN","layouts/initial-profile-update");
  		
        rules.setState("ASK_FIRST_PROFILE");
 		
	    rules.footer();     		      
end
