package life.genny.rules;

import life.genny.rules.RulesUtils;
import life.genny.rules.QRules;
import life.genny.qwandautils.QwandaUtils;
import life.genny.qwanda.Answer;
import life.genny.qwanda.message.QEventAttributeValueChangeMessage;
import life.genny.qwanda.entity.BaseEntity;
import io.vertx.core.json.JsonObject;
import io.vertx.core.json.JsonArray;

/*  Find Company for the given ABN  */
rule "Company ABN Value Entered"

    when
    $m: QEventAttributeValueChangeMessage( QEventAttributeValueChangeMessage.getData().getCode().equals("PRI_ABN") )
    	rules : QRules()
    then    
    	    rules.header();
	    
         Answer newAnswer = $m.getAnswer();

         RulesUtils.println(" Inside :: "+rules.header() );
         RulesUtils.println("Answer from QEventAttributeValueChangeMessage in Company ABN Attribute Change ::  "+newAnswer.toString());
  
         String companyABN = newAnswer.getValue();
         RulesUtils.println("The Company ABN is  ::  "+companyABN);
         
         
         
        
       rules.footer();
       

end

