package life.genny.rules;

import life.genny.rules.QRules;
import life.genny.qwanda.entity.BaseEntity;
import life.genny.qwanda.message.QEventMessage;


rule "New User Profile Submit"
	no-loop true
    when
        $m : QEventMessage( event_type == "FORM_SUBMIT" && data.code == "QUE_NEW_USER_PROFILE_GRP" )
        rules: QRules( isNewUserProfileCompleted() == true ) 
      then
     	rules.header();

        /*  Send Layouts and initial Datas    */
        drools.setFocus("SendLayoutsAndData");
        
	    rules.footer();   		      
end
