package life.genny.rules;

import life.genny.rules.QRules;


rule "Send Initial User Profile Layout"
	no-loop true
	salience 4
    agenda-group "NewUserProfile"
    when
        rules: QRules( isState("NEW_USER")  && isNewUserProfileCompleted() == false ) 
      then
     	rules.header();   	
     	rules.sendLayout("LAY_FULL_SCREEN","layouts/initial-profile-update.json");
     	rules.sendSublayout("SUB_LAY_WELCOME_NEW_USER", "welcome-new-user.json");
     	rules.clearState("NEW_USER");
	    rules.footer();   		      
end
