package life.genny.rules;
import life.genny.rules.QRules;
import java.util.List;

rule "Send Internmatch Homepage Layout Data - EDU PROVIDER - BUCKETVIEW"
     when
        rules: QRules(  isState("SEND_INTERNMATCH_HOMEPAGE_LAYOUT_DATA") &&
                        isState("SENT_INTERNMATCH_HOMEPAGE_LAYOUT") &&
                        isState("PRI_IS_EDU_PROVIDER") &&
                        isState("SENT_SUBLAYOUT") &&
                        !isState("LOOP_SEND_INTERNMATCH_HOMEPAGE_LAYOUT_DATA") )
     then
        rules.header();
        rules.setState("LOOP_SEND_INTERNMATCH_HOMEPAGE_LAYOUT_DATA");

		List<BaseEntity> buckets = rules.getBaseEntitysByParentAndLinkCode("GRP_DASHBOARD_EDU_PROVIDER", "LNK_CORE", 0, 500, false);
        rules.publishCmd(buckets, "GRP_DASHBOARD_EDU_PROVIDER", "LNK_CORE");		
        
        rules.setState("SENT_INTERNMATCH_HOMEPAGE_LAYOUT_DATA");
		rules.footer();
end
     	