package life.genny.rules;
import life.genny.rules.QRules;

rule "Setting Admin user role"
     when
        rules: QRules(  isState("SET_ADMIN_ROLE_IF_NEEDED") &&
                        !isState("LOOP_SET_ADMIN_ROLE") )
     then
        rules.header();
		rules.setState("LOOP_SET_ADMIN_ROLE");

        rules.setAdminRoleIfAdmin();

        rules.setState("EXIT_ROLE_CHECK");
      	rules.footer();
end
