package life.genny.rules;
import life.genny.rules.QRules;

/* Trigger Submit ADD NOTE  */
rule "Trigger Submit ADD NOTE"
	when
		rules: QRules( 	isState("QUE_ADD_NOTE_GRP") &&
						isState("EVENT_FORM_SUBMIT") &&
						isState("SUBMIT") &&
						!isState("LOOP_TRIGGER_SUBMIT_ADD_NOTE"))
	 then
	 	rules.header();
        rules.setState("LOOP_TRIGGER_SUBMIT_ADD_NOTE");

		/* get noteCode from targetCode */
		String noteCode = rules.getAsString("targetCode");
		
		if(noteCode != null){
			BaseEntity note = rules.baseEntity.getBaseEntityByCode(noteCode);
			rules.set("noteBe", note);

            String applicationCode = note.getLoopValue("PRI_APPLICATION_CODE", null);
			if(applicationCode != null){
				
				BaseEntity application = rules.baseEntity.getBaseEntityByCode(applicationCode);
				rules.set("applicationBe", application);

				rules.setState("LINK_APPLICATION_AND_NOTE");
				
			}else{
				rules.println("applicationCode is null || note has no attribiute :: PRI_APPLICATION_CODE");
				return;
				
			}
		}else{
			rules.println("noteCode is null");
		}
		rules.footer();
end


        
        
