
package life.genny.rules;
import life.genny.rules.QRules;


rule "10_SendNotesForSelectedApplication"
	when
		rules: QRules(  isState("SEND_NOTES_FOR_SELECTED_APPLICATION") &&
						!isState("LOOP_SEND_NOTES_FOR_SELECTED_APPLICATION")) 
	 then
	 	rules.header();
		rules.setState("LOOP_SEND_NOTES_FOR_SELECTED_APPLICATION");
       
       	BaseEntity application = rules.getAsBaseEntity("application");
       	rules.sendNotes(application.getCode());
       	BaseEntity user = rules.getUser();
       	
       	/* THIS IS FOR FRONT_END TO APPLY PROPS FOR "SELECTION OF A APP" */ 
       	/* Since the itemCode of selection starts with APP, we fetch the parent of the APP and save it as the value for PRI_SELECTED_BEG */
		String begCode = application.getValue("PRI_BEG_CODE", null);
		if(begCode != null) {
			rules.baseEntity.saveAnswer( new Answer(user.getCode(), user.getCode(), "PRI_SELECTED_BEG", begCode) );
		}
    		 
       	
       	rules.setState("SENT_NOTES_FOR_SELECTED_APPLICATION");

	 	rules.footer();      
end
