
package life.genny.rules;
import life.genny.rules.QRules;


rule "10_SendNotesForSelectedApplication"
	when
		rules: QRules(  isState("SEND_NOTES_FOR_SELECTED_APPLICATION") &&
						!isState("LOOP_SEND_NOTES_FOR_SELECTED_APPLICATION")) 
	 then
	 	rules.header();
		rules.setState("LOOP_SEND_NOTES_FOR_SELECTED_APPLICATION");
       
       	BaseEntity application = rules.getAsBaseEntity("application");
       	rules.sendNotes(application.getCode());
       	
       	rules.setState("SENT_NOTES_FOR_SELECTED_APPLICATION");

	 	rules.footer();      
end
