package life.genny.rules;
import life.genny.rules.QRules;

rule "Video Conference Intern - Step 0"
	when
		rules: QRules( 	isState("BTN_VIDEO_CONFERENCE_INTERN") && 
						isState("EVENT_BTN_CLICK") && 
						!isState("LOOP_VIDEO_CONFERENCE_INTERN_STEP0") ) 
	 then
	 	rules.header();
        rules.setState("LOOP_VIDEO_CONFERENCE_INTERN_STEP0");
        rules.sendSublayout("messages-layout", "messages-layout.json");
        rules.setState("VIDEO_CONFERENCE_READY");
end
