package life.genny.rules;
import life.genny.rules.QRules;

rule "Trigger Auth Init"
    when
        rules: QRules( 	isState("TRIGGER_AUTH_INIT") && !isState("LOOP_TRIGGER_AUTH_INIT") )
     then
        rules.setDrools(drools);

        rules.header();
        rules.setState("LOOP_TRIGGER_AUTH_INIT");

        rules.getUser();

        if(rules.isUserPresent() == true) {

            rules.getUser();
            rules.setState("USER_IS_READY"); /* this starts application workflow */
        }
        else {
            rules.setState("USER_IS_NOT_READY");
        }
	    rules.footer();
end
