package life.genny.rules;

import life.genny.rules.QRules;
import life.genny.qwanda.entity.BaseEntity;
import java.util.List;
import java.util.ArrayList;
import java.util.Optional;
import life.genny.utils.VertxUtils;

rule "Send internmatch BucketData To Frontend"
    salience 700
    agenda-group 'SendLayoutsAndData'
    when
        rules: QRules( !isState("SEND_BUCKET_DATA")  && isState("PROFILE_IS_COMPLETED"))
     then
     	rules.header();

     	rules.setState("SEND_BUCKET_DATA");
		rules.sendInternMatchLayoutsAndData();
		
	    rules.footer();
end
