package life.genny.rules;

import life.genny.rules.QRules;
import life.genny.qwanda.message.QEventAttributeValueChangeMessage;

rule "Selected Driver Role - channel40"

	when
		 evt: QEventAttributeValueChangeMessage(  event_type == "EVT_ATTRIBUTE_VALUE_CHANGE" && data.code == "PRI_IS_SELLER" )
		 rules: QRules( !isState("SELECTED_DRIVER_ROLE") )   
	 then
	    rules.header();
	
		rules.setState("SELECTED_DRIVER_ROLE");
		rules.updateBaseEntityAttribute(rules.getUser().getCode(), rules.getUser().getCode(), "PRI_IS_OWNER", "FALSE");
		rules.updateBaseEntityAttribute(rules.getUser().getCode(), rules.getUser().getCode(), "PRI_IS_DRIVER", "TRUE");

	    rules.footer();     		      
end
