package life.genny.rules;

import life.genny.rules.QRules;
import life.genny.qwanda.message.QEventAttributeValueChangeMessage;

rule "Selected Owner Role - channel40"

	when
		 evt: QEventAttributeValueChangeMessage(  event_type == "EVT_ATTRIBUTE_VALUE_CHANGE" && data.code == "PRI_IS_BUYER" && getAnswer().getValue().equals("TRUE") )
		 rules: QRules( !isState("SELECTED_OWNER_ROLE") )   
	 then
	    rules.header();
	
		rules.setState("SELECTED_OWNER_ROLE");
		rules.updateBaseEntityAttribute(rules.getUser().getCode(), rules.getUser().getCode(), "PRI_IS_OWNER", "TRUE");
		rules.updateBaseEntityAttribute(rules.getUser().getCode(), rules.getUser().getCode(), "PRI_IS_DRIVER", "FALSE");

	    rules.footer();     		      
end
