package life.genny.rules;
import life.genny.rules.QRules;

/* Email Lecturer */
rule "Email Lecturer - Step 0"
	when
		rules: QRules( 	isState("QUE_LECTURER_GRP") &&
						isState("EVENT_FORM_SUBMIT") &&
						isState("EMAIL") &&
						!isState("LOOP_EMAIL_LECTURER") )
	 then
	 	rules.header();
        rules.setState("LOOP_EMAIL_LECTURER");

        rules.set("internBe", rules.getUser().getCode());
        rules.setState("TRIGGER_SEND_EMAIL_TO_LECTURER");

        rules.footer();
end