package life.genny.rules;
import life.genny.rules.QRules;

rule "Submit Invite Intern - Step 1"
	when
        rules: QRules(  isState("ADD_TO_GRP_INVITED_INTERNS") && 
                        isState("SUBMIT_INVITE_INTERN_READY") && 
                        isState("EVENT_FORM_SUBMIT") && 
						isState("QUE_INVITE_INTERNS_GRP") && 
						isState("SUBMIT") && 
                        !isState("LOOP_ADD_TO_GRP_INVITED_INTERNS")  )
     then 
 		rules.header();
		rules.setState("LOOP_ADD_TO_GRP_INVITED_INTERNS");
        
        BaseEntity intern = rules.getAsBaseEntity("internBe");
        if(intern != null){

            /* link INTERN to GRP_INVITED_INTERNS */
            rules.set("linkSourceCode",  "GRP_INVITED_INTERNS");
            rules.set("linkTargetCode", intern.getCode());
            rules.set("linkCode", "LNK_INTERN");
            rules.set("linkValue", "INTERN");
            rules.set("linkWeight", 1.0);
            rules.setState("CREATE_LINK");

            rules.setState("ADDED_TO_GRP_INVITED_INTERNS");
            rules.setState("SAVE_UNI_NAME_AS_AN_ANSWER");
        }
 		rules.footer();
end