package life.genny.rules;
import life.genny.rules.QRules;

rule "Submit Invite Intern - Step 2"
	when
        rules: QRules(  isState("SAVE_UNI_NAME_AS_AN_ANSWER") && 
                        isState("ADDED_TO_GRP_INVITED_INTERNS") && 
                        isState("CREATED_LINK") && 
						isState("INTERN") && 
                        !isState("LOOP_SAVE_UNI_NAME_AS_AN_ANSWER")  )
     then 
 		rules.header();
		rules.setState("LOOP_SAVE_UNI_NAME_AS_AN_ANSWER");
        
        BaseEntity intern = rules.getAsBaseEntity("internBe");
        BaseEntity eduProvider = rules.getParent(rules.getUser().getCode(), "LNK_EDU");
        
        if(intern == null){
            rules.println("intern is null");
        } else if(eduProvider == null){
            rules.println("eduProvider is null");
        }else{
            rules.saveAnswer( new Answer(intern.getCode(), intern.getCode(), "LNK_UNI", eduProvider.getCode()) );
            rules.setState("SAVED_UNI_NAME_AS_AN_ANSWER");
            rules.setState("SEND_MESSAGE_TO_INVITED_INTERN");
        }
 		rules.footer();
end
