package life.genny.rules;
import life.genny.rules.QRules;

/* MOVE BEG from current Bucket to GRP_FILLED */
rule "Trigger Fill BEG"
    when 
        rules: QRules(	isState("BTN_FILL_BEG") &&
						isState("EVENT_BTN_CLICK") && 
						!isState("LOOP_TRIGGER_FILL_BEG") )
    then
        rules.header();
        rules.setState("LOOP_TRIGGER_FILL_BEG");

        /* get begCode (itemCode) from state */		
		String begCode = rules.getAsString("itemCode"); 
		if(begCode != null){
			BaseEntity beg = rules.baseEntity.getBaseEntityByCode(begCode);
			
			if(beg != null){
				rules.set("begBe", beg);	
			
				BaseEntity parentBe = rules.baseEntity.getParent(beg.getCode(), "LNK_CORE");
				if(parentBe != null){
					rules.println("beg Code   ::   " + beg.getCode());
					rules.println("beg's current parent is   ::   " + parentBe.getCode());
					
					rules.baseEntity.moveBaseEntity(beg.getCode(), parentBe.getCode(), "GRP_FILLED", "LNK_CORE", "BEG");
					
                    /* Done to Go Back */

					rules.set("tvSelectValue", "GRP_NEW_ITEMS");
					rules.setState("EVENT_TV_SELECT");
					rules.setState("GRP_NEW_ITEMS");

					rules.setState("TRIGGER_FILL_BEG_MESSAGE");
				}else{
					rules.println("parentBe is null");
				}

			}else{
				rules.println("beg is null");
				return;
			}
		}else{
			rules.println("begCode is null");
			return;
		}
        rules.footer();
end
