package life.genny.rules;
import life.genny.rules.QRules;
import life.genny.qwanda.message.QEventMessage;

rule "Update Internship - Step 1"
    when
	    rules: QRules(  isState("BTN_UPDATE_INTERNSHIP") &&
                        isState("EVENT_BTN_CLICK") &&	
                        isState("QUE_INTERNSHIP_GRP") &&	
                        !isState("LOOP_UPDATE_INTERNSHIP_STEP1")) 	
     then
        rules.header();    
        rules.setState("LOOP_UPDATE_INTERNSHIP_STEP1");

        String internshipCode = rules.getAsString("quesTargetCode");
        if(internshipCode != null){
            rules.set("questionSourceCode", rules.getUser().getCode());
            rules.set("questionTargetCode", internshipCode);
            rules.set("questionGroupCode", "QUE_INTERNSHIP_GRP");
            rules.set("questionIsPopup", false);
            
            rules.setState("ASK_QUESTION");
        }else{
            rules.println("internshipCode is null");
        }
		rules.setState("SENT_INTERNSHIP_QUESTION");
        rules.footer();     		      
end
