package life.genny.rules;
import life.genny.rules.QRules;

/* Send Dashboard on Submit */
rule "Update Internship - Step 2"
	when
	    rules: QRules(	isState("SENT_INTERNSHIP_QUESTION") &&
						isState("ASKED_QUESTION") && 
						isState("QUE_INTERNSHIP_GRP") && 
						!isState("LOOP_UPDATE_INTERNSHIP_STEP2")) 
	 then
	 	rules.header();
        rules.setState("LOOP_UPDATE_INTERNSHIP_STEP2");
        rules.clearState("SENT_INTERNSHIP_QUESTION");

		rules.set("subLayoutCode", "DASHBOARD");
		rules.set("subLayoutPath", "homepage/dashboard_host_company.json");
		rules.set("subLayoutRootCode", "GRP_DASHBOARD");
		rules.set("subLayoutIsPopup", false);

		rules.setState("SEND_SUBLAYOUT");

	 	rules.footer();      
end