package life.genny.rules;
import life.genny.rules.QRules;
import life.genny.qwanda.message.QEventMessage;
import life.genny.qwanda.entity.BaseEntity;

rule "Create New Role - Step 4 - Submit"
    when
        rules: QRules( 	isState("EVENT_FORM_SUBMIT")  &&
        					isState("QUE_ROLE_GRP") &&
                        !isState("DID_SUBMIT_NEW_ROLE") )
     then

        rules.header();

        rules.setState("DID_SUBMIT_NEW_ROLE");
        
        String targetCode = rules.getAsString("targetCode");
        if(targetCode != null) {
        		
        		BaseEntity newRoleBe = rules.baseEntity.getBaseEntityByCode(targetCode);
        		if(newRoleBe != null) {
        			
        			/* we grab the name of the new role */
        			String roleName = newRoleBe.getValue("PRI_NAME", null);
        			
        			/* we grab the capabilities */
        			String capabilities = newRoleBe.getValue("LNK_SELECT_CAPABILITY", null);
        			
        			if(roleName != null && capabilities != null) {
        				
        				/* we get an array of capabilities */
        				capabilities = capabilities.replaceAll("[\\[\\](){}]", "");
        				String[] capabilitiesArray = capabilities.split(",");
        				
        				
        			}
        		}
        }
        
	    rules.footer();
end
