package com.sample;
import org.apache.commons.lang3.StringUtils;

import life.genny.qwanda.message.QEventMessage;
import life.genny.qwanda.message.QMessage.MessageData;
import life.genny.qwanda.message.QCmdMessage;
import life.genny.qwanda.message.QDataBaseEntityMessage;
import io.vertx.rxjava.core.eventbus.EventBus;
import io.vertx.core.buffer.Buffer;
import com.google.gson.Gson;
import life.genny.qwanda.Answer;
import life.genny.qwanda.message.QDataAnswerMessage;
import life.genny.qwandautils.KeycloakUtils;
import life.genny.qwandautils.MergeUtil;
import life.genny.qwandautils.QwandaUtils;
import life.genny.qwandautils.MessageUtils;
import life.genny.qwanda.message.QDataAskMessage;
import life.genny.qwanda.message.QCmdMessage;
import life.genny.qwanda.Ask;
import life.genny.qwanda.entity.BaseEntity;
import life.genny.qwanda.message.QMSGMessage;
import life.genny.qwanda.message.QBaseMSGMessageType;

import java.lang.reflect.Type;
import java.util.Map;
import java.util.HashMap;
import java.util.Set;
import java.util.HashMap;
import java.util.List;
import java.util.ArrayList;
import java.time.LocalDateTime;
import java.time.ZonedDateTime;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonParseException;
import com.google.gson.JsonPrimitive;
import com.google.gson.JsonSerializationContext;
import com.google.gson.FieldNamingPolicy;
import io.vertx.core.json.JsonObject;
import io.vertx.core.json.JsonArray;
import java.time.format.DateTimeFormatter;
import life.genny.qwanda.DateTimeDeserializer;
import life.genny.qwanda.entity.User;
import life.genny.qwanda.Link;



rule "Confirm Offer"
    when
        $m : QEventMessage( event_type == "BTN_CLICK" && data.code == "BTN_CONFIRM_OFFER")
        bus: EventBus()
        $user: User(realm != null )
        $map : Map($value: this["token"] != null)
        $map1 : Map($value1: this["realm"] != null)
    then

        System.out.println(QwandaUtils.executeRuleLogger("Confirm Offer"));
        /* Prepare GSON Deserialization */
            Gson gson = new GsonBuilder()
            .registerTypeAdapter(LocalDateTime.class, new JsonDeserializer<LocalDateTime>() {
                @Override
                public LocalDateTime deserialize(final JsonElement json, final Type type,
                    final JsonDeserializationContext jsonDeserializationContext)
                    throws JsonParseException {
                return LocalDateTime.parse(json.getAsJsonPrimitive().getAsString(), DateTimeFormatter.ISO_LOCAL_DATE_TIME);
                }

                public JsonElement serialize(final LocalDateTime date, final Type typeOfSrc,
                    final JsonSerializationContext context) {
                return new JsonPrimitive(date.format(DateTimeFormatter.ISO_LOCAL_DATE_TIME)); 
                }
            }).create();
        
        
        /* Prepare Token & qwandaServiceUrl */
            String qwandaServiceUrl = System.getenv("REACT_APP_QWANDA_API_URL");
            String tokenString = (String)$map.get("token");   
        
        /* retrieve jsonObj's values sent on data.value*/
        String data = $m.getData().getValue();
        if(data != null) {

            JsonObject dataJson = new JsonObject(data);
            String offerCode = dataJson.getString("itemCode"); /* COMPANY who quoted */
            String userCode = $user.getuCode();
            String linkCode= "LNK_BEG";
            String linkValue= "OFFER";

            /* GET attributes of the OFFER that's being accepted */
                JsonArray offerBe = new JsonArray(QwandaUtils.apiGet(qwandaServiceUrl + "/qwanda/baseentitys/" + offerCode + "/attributes", tokenString));
                System.out.println("------------------------------------------------------------------------");
                System.out.println("OFEER DATA   ::   " + offerBe.toString());
                System.out.println("------------------------------------------------------------------------");
                
                Map<String, String> map = new HashMap<>();
                /* loop to GET attributeCodes and VALUE */
                for(Object obj : offerBe) {
                    JsonObject offerObj = (JsonObject) obj;
                    String attributeCode = offerObj.getString("attributeCode");
                    String attributeValue = offerObj.getString("valueString");
                    map.put(attributeCode, attributeValue); /* PUT in map */

                }
                System.out.println("------------------------------------------------------------------------");
                System.out.println("MAP DATA   ::   " + map);
                System.out.println("------------------------------------------------------------------------");
                
                String begCode= map.get("PRI_BEG_CODE");
                String begPrice= map.get("PRI_OFFER_PRICE");
                String quoterCode= map.get("PRI_QUOTER_CODE");
                String quoterUname= map.get("PRI_QUOTER_USERNAME");

                System.out.println("------------------------------------------------------------------------");
                System.out.println("BEG CODE          ::   " + begCode);
                System.out.println("BEG PRICE         ::   " + begPrice);
                System.out.println("QUOTER CODE       ::   " + quoterCode);
                System.out.println("QUOTER USERNAME   ::   " + quoterUname);
                System.out.println("------------------------------------------------------------------------");

            /* Update link between BEG and QUOTR as DRIVER */
                System.out.println("\nCREATING DRIVER LINK BETWEEN          ::   " + begCode + "  &  " + quoterCode);
                Link link = new Link( begCode, quoterCode, linkCode, "DRIVER");
                link.setWeight(1.0);
                String output1 = QwandaUtils.apiPutEntity(qwandaServiceUrl + "/qwanda/links", gson.toJson(link),tokenString);
            
            
            /* SEND QUOTER BE UPDATE */
                JsonObject quoterObj = new JsonObject(QwandaUtils.apiGet(qwandaServiceUrl+"/qwanda/baseentitys/"+ begCode +"/linkcodes/"+ linkCode +"/attributes?PRI_USERNAME=" + quoterUname, tokenString));
                System.out.println("------------------------------------------------------------------------");
                System.out.println("QUOTER BE   ::  " + quoterObj.toString());
                System.out.println("------------------------------------------------------------------------");
                quoterObj.put("token", tokenString);      
                bus.publish("cmds", quoterObj);
            
             /* Update link between BEG and OFFER to weight= 0 */
                System.out.println("UPDATING weight OF LINK BETWEEN          ::   " + begCode + "  &  " + offerCode);
                Link link3 = new Link( begCode, offerCode, linkCode, linkValue);
                link3.setWeight(0.0);
                String output3 = QwandaUtils.apiPutEntity(qwandaServiceUrl + "/qwanda/links", gson.toJson(link3),tokenString);
                
            /* Sending updated link of BEG */
                JsonArray updatedLink1 = new JsonArray(QwandaUtils.apiGet(qwandaServiceUrl + "/qwanda/entityentitys/" + begCode + "/linkcodes/" + linkCode + "/children", tokenString));
                /* Creating a data msg */
                JsonObject newLink1 = new JsonObject();
                newLink1.put("msg_type", "DATA_MSG");
                newLink1.put("data_type", "LINK_CHANGE");
                newLink1.put("items", updatedLink1);

                System.out.println("------------------------------------------------------------------------");
                System.out.println("Updated Link   ::  "+newLink1.toString());
                System.out.println("------------------------------------------------------------------------");
                /* publish new link data */
                newLink1.put("token", tokenString );
                bus.publish("cmds", newLink1);

                
            /* Move BEG to GRP_APPROVED */
                String oldGroup = "GRP_NEW_ITEMS";
                String newGroup = "GRP_APPROVED";
                String linkCode2 = "LNK_CORE";
                /* Moving the BEG */
                JsonObject begEntity = new JsonObject();
                begEntity.put("sourceCode", oldGroup);
                begEntity.put("targetCode", begCode);
                begEntity.put("attributeCode", linkCode2);
            
                System.out.println("------------------------------------------------------------------------");
                System.out.println("EntityLink   ::   "+begEntity.toString());
                System.out.println("------------------------------------------------------------------------");

                String output2= QwandaUtils.apiPostEntity(qwandaServiceUrl+"/qwanda/baseentitys/move/" + newGroup, begEntity.toString(), tokenString);
                System.out.println("The Output after POST: "+output2);

            /* Sending updated link of GRP_APPROVED */
                JsonArray updatedLink2 = new JsonArray(QwandaUtils.apiGet(qwandaServiceUrl + "/qwanda/entityentitys/" + begCode + "/linkcodes/" + linkCode2, tokenString));

                /* Creating a data msg */
                JsonObject newLink = new JsonObject();
                newLink.put("msg_type", "DATA_MSG");
                newLink.put("data_type", "LINK_CHANGE");
                newLink.put("items", updatedLink2);

                System.out.println("------------------------------------------------------------------------");
                System.out.println("Updated Link   ::  "+newLink.toString());
                System.out.println("------------------------------------------------------------------------");
                /* publish new link data */
                newLink.put("token", tokenString );
                bus.publish("cmds", newLink);


            /* Sending message to QUOTER | COMPANY */
                String code= "code:" + begCode ;
                String recipient = "recipient:OWNER";
                String[] msgMessageData = {code, recipient};
                String templateCode = "MSG_CH40_CONFIRM_OFFER";
                String[] attachments = {};           
                QBaseMSGMessageType method = QBaseMSGMessageType.SMS;

                System.out.println("------------------------------------------------------------------------");
                System.out.println("msgMessageData Array   ::   " + msgMessageData.toString());
                
                /* Creating messageData MSG_MESSAGE */
                QMSGMessage msgMessage = new QMSGMessage("MSG_MESSAGE", templateCode, msgMessageData, method, attachments);
                JsonObject jsonMessage = new JsonObject().mapFrom(msgMessage);

                System.out.println("------------------------------------------------------------------------");
                System.out.println("MESSAGE TO COMPANY   ::   " + jsonMessage.toString());
                System.out.println("------------------------------------------------------------------------");
                
                jsonMessage.put("token",tokenString);
                bus.publish("messages", jsonMessage);

            
        }

        /* sending cmd BUCKETVIEW */
            drools.setFocus("bucketview"); 
        System.out.println(QwandaUtils.terminateRuleLogger("Confirm Offer"));
end
