package life.genny.rules;
import life.genny.rules.QRules;

/* Create Application BaseEntity */
rule "Add BE to BEG - Step 1"
	when
	    rules: QRules(  isState("CREATE_BE_TO_BEG") && 
						!isState("LOOP_ADD_BE_TO_BEG_STEP1")) 
	 then
	 	rules.header();
        rules.setState("LOOP_ADD_BE_TO_BEG_STEP1");

        /* Create BEG BaseEntity*/
		rules.set("beCode", rules.getUser().getCode());
		rules.set("bePrefix", "APL");
		rules.set("beName", "APPLICATION");		
		rules.setState("CREATE_BASE_ENTITY");	

		rules.setState("SAVE_BE_TO_BEG_CODE_AS_ATTRIBUTE");
	 	rules.footer();      
end


        
        
