package life.genny.rules;
import life.genny.rules.QRules;

/* Send QUE_APPLY_BEG_GRP Question */
rule "Add BE to BEG - Step 3"
	when
	    rules: QRules(  isState("SEND_ADD_BE_TO_BEG_QUESTIONS") && 
						!isState("LOOP_ADD_BE_TO_BEG_STEP3")) 
	 then
	 	rules.header();
        rules.setState("LOOP_ADD_BE_TO_BEG_STEP3");

        /* GET APPLICATION BE from state */
		BaseEntity application = rules.getAsBaseEntity("baseEntity");
        
        if(application != null){

            rules.set("questionSourceCode", rules.getUser().getCode());
            rules.set("questionTargetCode", application.getCode());
            rules.set("questionGroupCode", "QUE_ADD_BE_TO_BEG_GRP");
            rules.set("questionIsPopup", true);
		    rules.setState("ASK_QUESTION");

        }else{
            rules.println("application is null");
        }
	 	rules.footer();      
end


        
        
