package life.genny.rules;

import life.genny.rules.QRules;
import life.genny.qwanda.entity.BaseEntity;
import life.genny.qwandautils.KeycloakUtils;
import life.genny.qwanda.message.QEventMessage;
import io.vertx.core.json.JsonObject;

rule "Reset User Password"

    when
	    $m : QEventMessage( event_type == "BTN_CLICK" && data.code == "RESET_USER_PASSWORD" )
	    rules: QRules(!isState("RESET_USER_PASSWORD"))
     then     
     	
     	rules.header();
	    	rules.setState("RESET_USER_PASSWORD");
	    	
	    	String data = $m.getData().getValue();
	    	if(data != null) {
	    		
	    		JsonObject dataJson = new JsonObject(data);
	    		String userCode = dataJson.getString("userCode");
	    		if(userCode != null) {
	    			
	    			/* omg this is so bad. to be fixed. */
			    	KeycloakUtils.resetUserPassword(userCode, rules.getToken(), rules.getAsString("realm"));
	    		}
	    	}
	    	    	
	    	rules.footer();       		      
end
