package life.genny.rules;
import life.genny.rules.QRules;

rule "Trigger View BEG"
	when
			rules: QRules(  ((isState("EVENT_BTN_CLICK") && isState("BTN_VIEW_BEG")) || isState("TRIGGER_VIEW_BEG")) &&
							!isState("LOOP_TRIGGER_VIEW_BEG"))
	 then
			rules.header();
			rules.setState("LOOP_TRIGGER_VIEW_BEG");
			
			String begCode = rules.getAsString("itemCode");
			if(begCode != null){
				BaseEntity beg = rules.baseEntity.getBaseEntityByCode(begCode);
				if(beg !=null){
					/*rules.sendNotes(beg); */
					rules.set("begBe", beg);
					rules.setState("TRIGGER_VIEW_LINKS");
					rules.setState("TRIGGER_VIEW_BEG");
				}else{
					rules.println("beg is null");
				}
			}else{
				rules.println("begCode is null");
			}

			rules.footer();
end
