package life.genny.rules;
import life.genny.rules.QRules;

/* Send Sub Layout */
rule "View BEG Details"
	when
		rules: QRules(  isState("TRIGGER_VIEW_BEG") && 
                    !isState("LOOP_VIEW_BEG_DETAILS") ) 
	 then
	 	rules.header();
    	rules.setState("LOOP_VIEW_BEG_DETAILS");

		/* get begCode (itemCode) from state */
		BaseEntity beg = rules.getAsBaseEntity("begBe");
		if(beg != null) {
			
			rules.set("subLayoutCode", "BEG_DETAILS");
			rules.set("subLayoutPath", "beg/beg_details.json");
			rules.set("subLayoutRootCode", beg.getCode());
			rules.set("subLayoutIsPopup", false);

			rules.setState("SEND_SUBLAYOUT"); 
      		rules.setState("VIEWED_BEG_DETAILS");
      		rules.sendNotes(beg.getCode());
		}
		else {
			rules.println("begCode is null");
		}
		
	 	rules.footer();      
end
