package life.genny.rules;
import life.genny.rules.QRules;

/* Link GRP_EDU_PROVIDER  >>>>  USER \\ STAFF */
rule "Edu Provider Registration Form Submit - Step 1"
	when
	    rules: QRules( 	isState("EDU_PROVIDER_REGISTRATION_FORM_SUBMIT_READY") && 
	    				isState("LINK_EDU_PROVIDER_TO_STAFF") && 
	    				isState("QUE_EDU_PROVIDER_GRP") && 
						isState("EVENT_FORM_SUBMIT") && 						
						!isState("PRI_IS_PROFILE_COMPLETED") && 
						!isState("LOOP_EDU_PROVIDER_REGISTRATION_FORM_SUBMIT_STEP1") ) 
	 then
	 	rules.header();
		rules.setState("LOOP_EDU_PROVIDER_REGISTRATION_FORM_SUBMIT_STEP1");
		 
        BaseEntity eduProvider = rules.getAsBaseEntity("eduProviderBe");
		if(eduProvider != null){
			
			/* link EDU_PROVIDER to USER || STAFF */
			rules.set("linkSourceCode",  eduProvider.getCode());
			rules.set("linkTargetCode", rules.getUser().getCode());
			rules.set("linkCode", "LNK_EDU");
			rules.set("linkValue", "STAFF");
			rules.set("linkWeight", 1.0);
			rules.setState("CREATE_LINK");

			rules.setState("LINKED_EDU_PROVIDER_TO_STAFF");
			rules.setState("SET_PROFILE_IS_COMPLETED");
		}
	 	rules.footer();      
end