package life.genny.rules;
import life.genny.rules.QRules;

rule "Trigger Send System Data"

    when
         rules: QRules( isState("TRIGGER_SEND_SYSTEM_DATA") && 
                        !isState("LOOP_TRIGGER_SEND_SYSTEM_DATA") )
     then
     	rules.header();
        rules.setState("LOOP_TRIGGER_SEND_SYSTEM_DATA");
    
        rules.setState("SEND_APPLICATION_ATTRIBUTES");
	    rules.footer();      		      
end
