package life.genny.rules;

import life.genny.rules.QRules;


rule "Send User Company"
    when
        rules: QRules( isState("SENT_USER")  && !isState("LOOP_SEND_USER_COMPANY") )
     then
     	rules.header();
     	rules.setState("LOOP_SEND_USER_COMPANY");

     	String userCode = rules.getUser().getCode();
     	
     	/*  Get Company Code of the current user   */
        BaseEntity company = rules.getParent(userCode, "LNK_STAFF");
        
        if(company != null)
        {
            String companyCode = company.getCode();
            rules.publishCmd(company, "USER_COMPANY");
            
        }      

        rules.setState("SENT_USER_COMPANY");
	    rules.footer();     		      
end
