package life.genny.rules;
import life.genny.rules.QRules;

rule "Profile Is Completed - Internmatch - Step 1"
    when
        rules: QRules(  isState("PROFILE_IS_COMPLETED") && 
                        !isState("LOOP_PROFILE_IS_COMPLETED_SETP1") ) 
     then       
        rules.header();
        rules.setState("LOOP_PROFILE_IS_COMPLETED_SETP1");
        
        rules.setState("TRIGGER_SUBSCRIPTION");
        rules.footer(); 		      
end
