package life.genny.rules;
import life.genny.rules.QRules;

rule "Profile Is Completed - Internmatch - Step 2"
    when
        rules: QRules(  isState("PROFILE_IS_COMPLETED") && 
                        isState("EXIT_SUBSCRIPTION") &&
                        !isState("LOOP_PROFILE_IS_COMPLETED_SETP2") ) 
     then       
        rules.header();
        rules.setState("LOOP_PROFILE_IS_COMPLETED_SETP2");
        
        rules.setState("TRIGGER_SEND_APPLICATION_DATA");
        rules.footer(); 		      
end

