package life.genny.rules;
import life.genny.rules.QRules;
import life.genny.qwanda.message.QDataAskMessage;
import life.genny.qwanda.QuestionSourceTarget;
import life.genny.qwanda.message.QDataQSTMessage;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.Optional;

rule "Check if Offer is accepted by all 3 parties"
    no-loop true
    when
        m: QEventAttributeValueChangeMessage(   data.code == "PRI_INTERN_ACCEPTED" ||
                                                data.code == "PRI_EDU_PROVIDER_ACCEPTED" ||
                                                data.code == "PRI_HOST_COMPANY_ACCEPTED" )
        
        rules: QRules( !isState("LOOP_CHECK_OFFER_ACCEPTED") )
     then
     	rules.header();
     	rules.setState("LOOP_CHECK_OFFER_ACCEPTED");

        String begCode = m.getBe().getCode();
        BaseEntity beg = rules.getBaseEntityByCode(begCode);

        if(beg != null){
			rules.println("begCode    ::   " + beg.getCode());
            rules.set("begBe", beg);
            
            Boolean internAccepted = beg.getValue("PRI_INTERN_ACCEPTED", false);
            Boolean eduProviderAccepted = beg.getValue("PRI_EDU_PROVIDER_ACCEPTED", false);
            Boolean hostCompanyAccepted = beg.getValue("PRI_HOST_COMPANY_ACCEPTED", false);

            rules.println("PRI_INTERN_ACCEPTED value         ::   " +  internAccepted);
            rules.println("PRI_EDU_PROVIDER_ACCEPTED value   ::   " +  eduProviderAccepted);
            rules.println("PRI_HOST_COMPANY_ACCEPTED value   ::   " +  hostCompanyAccepted);
            
            if( internAccepted == true &&
                eduProviderAccepted == true &&
                hostCompanyAccepted == true  ) {
                    
                rules.setState("OFFER_ACCEPTED_BY_ALL");
            }
            rules.println("checked");
        }
    	rules.footer();
end
