package life.genny.rules;

import life.genny.qwanda.message.QCmdMessage;
import life.genny.qwanda.message.QBulkMessage;
import life.genny.qwanda.message.QDataBaseEntityMessage;
import life.genny.qwanda.message.QEventMessage;
import life.genny.rules.QRules;
import io.vertx.core.json.JsonObject;
import java.util.List;
import java.util.ArrayList;
import life.genny.qwanda.entity.BaseEntity;
import life.genny.utils.VertxUtils;

rule "Generate Tree Roles - Internmatch"
    ruleflow-group 'GenerateTree'
    salience 680
     when
       rules: QRules( 	realm() == "internm,atch" && 
	   					          isState("GENERATE_TREE_RULES") && 
						            !isState("LOOP_GENERATE_TREE_RULES") )
     then
        rules.header();
        rules.setState("LOOP_GENERATE_TREE_RULES");

        rules.println("Generating specific Tree Roles for "+rules.realm());
        
        List<Answer> attributesAns = new ArrayList<>();
        attributesAns.add(new Answer("GRP_BEGS", "GRP_BEGS", "GRP_DRAFTS", "PRI_IS_SELLER"));
        attributesAns.add(new Answer("GRP_BEGS", "GRP_BEGS", "GRP_BIN", "PRI_IS_SELLER"));
        rules.saveAnswers(attributesAns);
        
        rules.footer();
end
