package life.genny.rules;

import life.genny.rules.QRules;

rule "Trigger Profile Check"
    when
        rules: QRules(  isState("TRIGGER_PROFILE_CHECK") && 
                        !isState("LOOP_TRIGGER_PROFILE_CHECK") ) 
     then         
        rules.header();

        rules.setState("LOOP_TRIGGER_PROFILE_CHECK");
        rules.setState("CHECK_USER_PROFILE_COMPLETED");   

        rules.footer();
end
