package life.genny.rules;
import life.genny.rules.QRules;

/* Send Company Questions */
rule "Ask Registration - Host Company - STEP 4"
    when
        rules: QRules(  isState("PROFILE_NOT_COMPLETED") &&
						isState("SENT_QUESTION") && 
						isState("QUE_USER_HOST_COMPANY_GRP") &&
						!isState("LOOP_ASK_REGISTRATION_HOST_COMPANY_STEP4") ) 
     then 
 		rules.header();		
		rules.setState("LOOP_ASK_REGISTRATION_HOST_COMPANY_STEP4");
 		
		/* Get Company BaseEntity from map */
		BaseEntity company = rules.getAsBaseEntity("companyBe");
		if(company != null){
			String questionSourceCode = rules.getUser().getCode();
			String questionTargetCode = company.getCode();

			/* send question group for host company */
			rules.set("questionSourceCode", questionSourceCode);
			rules.set("questionTargetCode", questionTargetCode);	
			rules.set("questionGroupCode", "QUE_HOST_COMPANY_GRP");
			
			rules.setState("SEND_QUESTION");
			
			/* we send the layout */
			rules.sendSublayout("LAY_HOST_COMPANY", "registration/hostcompany.json", null, false);

		}else{
			rules.println("company is null");
		}
		
 		rules.footer();
end
