package life.genny.rules;
import life.genny.rules.QRules;

/* LINK GRP_DRAFTS + BEG  */
rule "Add Product - Step 3"
	when
		rules: QRules(  isState("LINK_GRP_DRAFTS_TO_BEG") &&
						isState("CREATED_BASE_ENTITY") &&
						!isState("LOOP_LINK_GRP_DRAFTS_TO_BEG") ) 
	 then
	 	rules.header();
        rules.setState("LOOP_LINK_GRP_DRAFTS_TO_BEG");

		BaseEntity product = rules.getAsBaseEntity("baseEntity");	
		if(product != null){
			rules.set("productBe", product);
		}else{
			rules.println("product is null");
			return;
		}

		BaseEntity beg = rules.getAsBaseEntity("begBe");
		if(beg != null){
			
			/* link GRP_DRAFTS to BEG */
			rules.set("linkSourceCode", "GRP_DRAFTS");
			rules.set("linkTargetCode", beg.getCode());
			rules.set("linkCode", "LNK_CORE");
			rules.set("linkValue", "LINK");
			rules.set("linkWeight", 1.0);
			rules.setState("CREATE_LINK");

			rules.setState("LINK_BEG_TO_PRODUCT");	
		}else{
			rules.println("beg is null");
			return;
		}
	 	rules.footer();      
end
