package life.genny.rules;
import life.genny.rules.QRules;

/* LINK BEG + PRODUCT  */
rule "Add Product - Step 4"
	when
		rules: QRules(  isState("LINK_BEG_TO_PRODUCT") &&
						isState("CREATED_LINK") &&
						!isState("LOOP_LINK_BEG_TO_PRODUCT") ) 
	 then
	 	rules.header();
        rules.setState("LOOP_LINK_BEG_TO_PRODUCT");

		BaseEntity beg = rules.getAsBaseEntity("begBe");
		BaseEntity product = rules.getAsBaseEntity("productBe");

		if(beg == null){
			rules.println("beg is null");
		}else if (product == null){
			rules.println("product s null");
		}else{

			/* link BEG to PRODUCT */
			rules.set("linkSourceCode", beg.getCode());
			rules.set("linkTargetCode", product.getCode());
			rules.set("linkCode", "LNK_BEG");
			rules.set("linkValue", "PRODUCT");
			rules.set("linkWeight", 1.0);

			rules.clearState("CREATED_LINK");

			rules.setState("CREATE_LINK");

			rules.setState("SEND_BEG_QUESTION");
		}
	 	rules.footer();      
end
