package life.genny.rules;
import life.genny.rules.QRules;

rule "Add Internship - Step 7"
	when
        rules: QRules(  isState("SEND_ADD_PRODUCT_QUESTION_LAYOUT") && 
                        isState("SENT_QUESTION")  &&
                        isState("QUE_ADD_PRODUCT_GRP")  &&
                        !isState("LOOP_SEND_ADD_PRODUCT_QUESTION_LAYOUT")  )
     then 
 		rules.header();
		rules.setState("LOOP_SEND_ADD_PRODUCT_QUESTION_LAYOUT");

		rules.set("subLayoutCode", "ADD_PRODUCT_LAYOUT");
		rules.set("subLayoutPath", "/beg/add_beg.json");
		rules.set("subLayoutRootCode", null);
		rules.set("subLayoutIsPopup", true);
		
		rules.setState("SEND_SUBLAYOUT");
 		rules.footer();
end
