package life.genny.rules;

import life.genny.rules.QRules;
import life.genny.qwanda.message.QDataAskMessage;
import life.genny.qwanda.QuestionSourceTarget;
import life.genny.qwanda.message.QDataQSTMessage;

import java.util.ArrayList;
import java.util.Arrays;

rule "Check if Profile Completed"
    no-loop true
    agenda-group "CheckIfProfileCompleted"
    salience 8
    when
        rules: QRules( !isState("PROFILE_CHECK_COMPLETED")  ) 
     then
     	rules.header(); 		
   	    
         
       if( rules.isNewUserProfileCompleted())
        {
            rules.setState("PROFILE_COMPLETED");
            drools.setFocus("SendLayoutsAndData");
        }else{
           rules.setState("PROFILE_NOT_COMPLETED");
           drools.setFocus("NewUserProfile");
        }

        rules.setState("PROFILE_CHECK_COMPLETED");
   	  
	    rules.footer();     		      
end
