package life.genny.rules;
import life.genny.rules.QRules;

/* LINK BEG + INT || INTERNSHIP */
rule "Internship Form Submit - Step 2"
	when
	    rules: QRules( 	isState("BASE_ENTITY_CREATED") && 
						isState("BEG") &&
						isState("EVENT_FORM_SUBMIT") && 
						!isState("LOOP_INTERNSHIP_FORM_SUBMIT_STEP2")) 
	 then
	 	rules.header();
        rules.setState("LOOP_INTERNSHIP_FORM_SUBMIT_STEP2");

		String internshipCode = rules.getAsString("quesTargetCode");
		rules.println("internshipCode   ::   " + internshipCode);
		
		BaseEntity beg = rules.getAsBaseEntity("baseEntity");
		
		/* Setting beg BaseEntity to state */
		rules.set("begBe", beg);		

		/* link BEG to INT */
		rules.set("sourceCode", beg.getCode());
		rules.set("targetCode", internshipCode);
		rules.set("linkCode", "LNK_BEG");
		rules.set("linkValue", "INTERNSHIP");
		rules.set("weight", 1.0);

		rules.setState("CREATE_LINK");

	 	rules.footer();      
end
