package life.genny.rules;
import life.genny.rules.QRules;

/* LINK BEG + CPY || COMPANY */
rule "Internship Form Submit - Step 3"
	when
	    rules: QRules( 	isState("LINK_CREATED") && 
						isState("INTERNSHIP") && 		
						!isState("LOOP_INTERNSHIP_FORM_SUBMIT_STEP3")) 
	 then
	 	rules.header();
        rules.setState("LOOP_INTERNSHIP_FORM_SUBMIT_STEP3");

		String userCode = rules.getUser().getCode();
		
		BaseEntity beg = rules.getAsBaseEntity("begBe");

		/*  Get Company Code of the current user   */
        BaseEntity company = rules.getParent(userCode, "LNK_STAFF");     
        if(company != null){
            String companyCode = company.getCode();

			/* link BEG to CPY */
			rules.set("sourceCode", beg.getCode());
			rules.set("targetCode", companyCode);
			rules.set("linkCode", "LNK_BEG");
			rules.set("linkValue", "COMPANY");
			rules.set("weight", 1.0);

			rules.clearState("LOOP_CREATE_LINK");
			rules.setState("CREATE_LINK");
		}else{
			rules.println("Company not found");
		}
end
