package life.genny.rules;
import life.genny.rules.QRules;

/* LINK BEG + USER || CREATOR */
rule "Internship Form Submit - Step 4"
	when
		rules: QRules( 	isState("LINK_CREATED") && 
						isState("COMPANY") && 		
						isState("EVENT_FORM_SUBMIT") && 
						!isState("LOOP_INTERNSHIP_FORM_SUBMIT_STEP4")) 
	 then
	 	rules.header();
        rules.setState("LOOP_INTERNSHIP_FORM_SUBMIT_STEP4");

		BaseEntity beg = rules.getAsBaseEntity("begBe");

		/* link BEG to CPY */
		rules.set("sourceCode",  beg.getCode());
		rules.set("targetCode", rules.getUser().getCode());
		rules.set("linkCode", "LNK_BEG");
		rules.set("linkValue", "CREATOR");
		rules.set("weight", 1.0);

		rules.clearState("LOOP_CREATE_LINK");
		rules.setState("CREATE_LINK");

	 	rules.footer();      
end
