package life.genny.rules;
import life.genny.rules.QRules;
import life.genny.utils.VertxUtils;

/* Subscribe to BEG */
rule "Internship Form Submit - Step 6"
	when
		rules: QRules( 	isState("SUBSCRIBED_TO_BEG") && 		
						!isState("LOOP_INTERNSHIP_FORM_SUBMIT_STEP6")) 
	 then
	 	rules.header();
        rules.setState("LOOP_INTERNSHIP_FORM_SUBMIT_STEP6");

		BaseEntity beg = rules.getAsBaseEntity("begBe");

		/* link BEG to CPY */
		rules.set("sourceCode", "GRP_AVAILABLE");
		rules.set("targetCode", beg.getCode());
		rules.set("linkCode", "LNK_CORE");
		rules.set("linkValue", "BEG");
		rules.set("weight", 1.0);

		rules.clearState("LOOP_CREATE_LINK");
		rules.setState("CREATE_LINK");
		
		rules.setState("PUBLISH_BEG");
	 	rules.footer();      
end
