package life.genny.rules;
import life.genny.rules.QRules;
import life.genny.utils.VertxUtils;

/* Subscribe to BEG */
rule "Internship Form Submit - Step 7"
	when
		rules: QRules( 	isState("LINK_CREATED") && 
						isState("BEG") && 
						isState("PUBLISH_BEG") && 
						!isState("LOOP_INTERNSHIP_FORM_SUBMIT_STEP7")) 
	 then
	 	rules.header();
        rules.setState("LOOP_INTERNSHIP_FORM_SUBMIT_STEP7");

		BaseEntity beg = rules.getAsBaseEntity("begBe");
		
		String[] begRecipients = VertxUtils.getSubscribers(rules.realm(), beg.getCode());
		rules.publishBaseEntityByCode(	beg.getCode(), 
										"GRP_AVAILABLE" , 
										"LNK_CORE", 
										begRecipients);
		rules.setState("TRIGGER_HOME_PAGE");
	 	rules.footer();      
end
