package life.genny.rules;
import life.genny.rules.QRules;

rule "Ask Terms And Conditions"
    when
        rules: QRules(  isState("TERMS_AND_CONDITIONS_NOT_ACCEPTED") &&
                        !isState("LOOP_TERMS_AND_CONDITIONS_NOT_ACCEPTED") )
    then
        rules.header();
        rules.setState("LOOP_TERMS_AND_CONDITIONS_NOT_ACCEPTED");

        if(rules.isMandatoryFieldsEntered(rules.getUser().getCode(), "QUE_TERMS_AND_CONDITIONS_GRP")) {
            rules.clearState("LOOP_SUBMIT_ACCEPTED_T_C");
            rules.setState("TERMS_AND_CONDITIONS_ACCEPTED");

        }
        else {
            rules.setState("IS_REGISTRATION");
            rules.askQuestions(rules.getUser().getCode(), rules.getUser().getCode(), "QUE_TERMS_AND_CONDITIONS_GRP");
            
        }
        rules.footer();
end
