package life.genny.rules;
import life.genny.rules.QRules;

rule "Terms and conditions have been accepted"
    when
        rules: QRules(  isState("TERMS_AND_CONDITIONS_ACCEPTED") && 
                        !isState("LOOP_TERMS_AND_CONDITIONS_ACCEPTED") )
    then
        rules.header();
        rules.setState("LOOP_TERMS_AND_CONDITIONS_ACCEPTED");

        rules.setState("TRIGGER_APPLICATION_READY");
        rules.setState("DID_REGISTER");
        rules.footer();
end
