package life.genny.rules;
import life.genny.rules.QRules;
import life.genny.qwanda.message.QEventMessage;

rule "Send Self Sourced Internship Approval Message To Host Company"
	when
		rules: QRules(  isState("SEND_SELF_SOURCED_INTERNSHIP_APPROVAL_MESSAGE_TO_HOST_COMPANY") && 
                        !isState("SEND_SELF_SOURCED_INTERNSHIP_APPROVAL_MESSAGE_TO_HOST_COMPANY_LOOP") )
	then
	
	 	rules.header();

 		rules.setState("SEND_SELF_SOURCED_INTERNSHIP_APPROVAL_MESSAGE_TO_HOST_COMPANY_LOOP");
 		
        BaseEntity beg = rules.getAsBaseEntity("begBe");
        BaseEntity intern = rules.getAsBaseEntity("internBe");
        BaseEntity internship = rules.getAsBaseEntity("internshipBe");
        BaseEntity hostCompany = rules.getAsBaseEntity("hostCompanyBe");
 		
        if(beg == null){
            rules.println("beg is null");
            return;
        }else if(intern == null){
            rules.println("intern is null");
            return;
        }else if(internship == null){
            rules.println("internship is null");
            return;
        }else if(hostCompany == null){
            rules.println("hostCompany is null");
            return;
        }else{
        			
	 		HashMap<String, String> contextMap = new HashMap<String, String>(); 
	        contextMap.put("BEG", beg.getCode());
	        contextMap.put("INTERNSHIP", internship.getCode());
            contextMap.put("INTERN", intern.getCode());
	        contextMap.put("HOSTCOMPANY", hostCompany.getCode());
	        
            String[] recipients = null;

            /* Get all the HOSTCOMPANY staffs */
            List<BaseEntity> hostCompanyStaffs = rules.getChildrens(hostCompany.getCode(), "LNK_STAFF", "STAFF");
            if(hostCompanyStaffs != null) {
                rules.println("No. of hostCompanyStaffs   ::   " + hostCompanyStaffs.size() );	
                recipients = new String[hostCompanyStaffs.size()];
                int i = 0;
                for(BaseEntity hostCompanyStaff : hostCompanyStaffs) {
                    recipients[i] = hostCompanyStaff.getCode();
                    i++;
                }
            }
            
            rules.sendMessage(null, recipients, contextMap, "MSG_INTERNMATCH_INTERNSHIP_APPROVAL_HOST", "EMAIL");
 		    rules.setState("SENT_SELF_SOURCED_INTERNSHIP_APPROVAL_MESSAGE_TO_HOST_COMPANY_LOOP");
 		}
	 	rules.footer();      
end
