package life.genny.rules;

import life.genny.rules.QRules;
import java.util.List;

rule "Selected Buyer Role"
     when
        $m: QEventAttributeValueChangeMessage( QEventAttributeValueChangeMessage.getData().getCode().equals("PRI_IS_BUYER") )
        rules: QRules( isState("STARTED") && !isState("HAS_SELECTED_PROFILE_BUYER") && isState("BTN_SELECT_ROLE_BUYER") )
     then

        rules.header();
		rules.setState("HAS_SELECTED_PROFILE_BUYER");

		/* to remove */
		/*String userCode = rules.getUser().getCode();
		
        BaseEntity company = rules.getParent(userCode, "LNK_STAFF");
        String companyCode = company.getCode();
        rules.println("UPDATING link value OF LINK BETWEEN   ::   " + companyCode + "  &  " + userCode);
        Link updateLink = new Link( companyCode, userCode, "LNK_STAFF", "OWNER", (double) 1);
        String result = QwandaUtils.apiPutEntity(rules.getQwandaServiceUrl() + "/qwanda/links", JsonUtils.toJson(updateLink),rules.getToken());
        rules.publishBE(rules.getUser());
		 
		*/

		rules.setState("EXIT_ROLE_SELECTION");

		rules.footer();
end
