package life.genny.rules;
import life.genny.rules.QRules;

rule "Send offer notification to Host Company"
	when
		rules: QRules(  isState("INTERN_WAS_OFFERED_INTERNSHIP") )
	then
	 	rules.header();
 		
 		//this is to grab a parameter from the previous rule
 		String internCode = rules.getAsString("internCode");
 		//String urlCode = rules.getAsString("urlCode");
 		
 		if(internCode != null) {
 		
	 		HashMap<String, String> contextMap = new HashMap<String, String>(); 
	        contextMap.put("INTERN", internCode);
	        contextMap.put("HOST_COMPANY_REP", rules.getUser().getCode());
	        
 			String[] recipients = new String[1];
 			recipients[0] = internCode;
 			rules.sendMessage(null, recipients, contextMap, "MSG_INTERNMATCH_INTERNSHIP_OFFER_HOST_COMPANY", "EMAIL");
 		}
	 	
	 	rules.footer();      
end
