package life.genny.rules;


import life.genny.rules.QRules;



import life.genny.qwanda.Answer;
import life.genny.qwanda.message.QDataAnswerMessage;
import life.genny.qwanda.message.QEventAttributeValueChangeMessage;


rule "Listen Attribute Change"
    when
        $m: QEventAttributeValueChangeMessage( event_type == "EVT_ATTRIBUTE_VALUE_CHANGE" )
        rules : QRules()
     then    
      	rules.header();
 
        rules.publishData(new QDataAnswerMessage($m.getAnswer()));
    
   	    rules.footer();
  
end