package life.genny.rules;


import life.genny.rules.QRules;
import life.genny.qwanda.Answer;
import life.genny.qwanda.message.QDataAnswerMessage;
import life.genny.utils.RulesUtils;

rule "RAW_SURNAME"
ruleflow-group 'AnswerProcessing'
    when
        answer : Answer( attributeCode == "RAW_SURNAME")
        rules: QRules( 	!isState("RAW_SURNAME")  )
    then
        rules.header();

		rules.println("RAW_SURNAME!");
		rules.setState("RAW_SURNAME");
		
		List<Answer> answersToSave = new ArrayList<Answer>();
		
		String value = answer.getValue();
		
		/* Map to new attribute
		Answer pojo = new Answer(answer.getSourceCode(), answer.getTargetCode(), "PRI_LASTNAME", ea.getAsLoopString());
					pojo.setWeight(0.0);
					pojo.setInferred(true);
					pojo.setExpired(false);
					pojo.setRefused(false);
					pojo.setChangeEvent(true);
					
					answersToSave.add(pojo);  
		
		if (!answersToSave.isEmpty()) {
	   		rules.baseEntity.saveAnswers(answersToSave);
		}
*/

       rules.footer();

end
