package life.genny.rules;
import life.genny.rules.QRules;

rule "User Registration Form Submit - Step 1 - channel40"
	when
	    rules: QRules( 	isState("SET_PROFILE_IS_COMPLETED") && 
	    					isState("QUE_NEW_USER_DETAILS_GRP") && 
						isState("EVENT_FORM_SUBMIT") && 						
						!isState("PRI_IS_PROFILE_COMPLETED") && 
						!isState("LOOP_USER_REGISTRATION_FORM_SUBMIT_STEP1")) 
	 then
	 	rules.header();
        rules.setState("LOOP_USER_REGISTRATION_FORM_SUBMIT_STEP1");

		String sourceCode = rules.getUser().getCode();
		String targetCode = rules.getUser().getCode();
		String attributeCode = "PRI_IS_PROFILE_COMPLETED";
		String value = "TRUE";

		rules.saveAnswer(
			new Answer(	sourceCode, 
						targetCode, 
						attributeCode,
						value )
		);
	 	rules.footer();      
end
