package life.genny.rules;
import life.genny.rules.QRules;

/* LINK BEG + USER || INTERN */
rule "Apply Internship - Step 3.1"
	when
		rules: QRules( 	isState("QUE_INTERNSHIP_ADDITIONAL_GRP") && 
						isState("EVENT_FORM_SUBMIT") && 
						isState("SUBMIT") && 
						!isState("LOOP_APPLY_INTERNSHIP_STEP3_1")) 
	 then
	 	rules.header();
        rules.setState("LOOP_APPLY_INTERNSHIP_STEP3");

        /* get begCode from state */
        String begCode = rules.getAsString("quesTargetCode");
        if(begCode != null){   
            /* link BEG to USER || INTERN */
            rules.set("linkSourceCode",  begCode);
            rules.set("linkTargetCode", rules.getUser().getCode());
            rules.set("linkCode", "LNK_BEG");
            rules.set("linkValue", "INTERN");
            rules.set("linkWeight", 1.0);
            rules.setState("CREATE_LINK");

            rules.setState("LINKED_BEG_TO_INTERN");

/*          rules.createLink(begCode, rules.getUser().getCode(), "LNK_BEG", "INTERN", 1.0); */
        }else{
            rules.println("begCode is null");
        }
        rules.setState("TRIGGER_HOME_PAGE");
end