package life.genny.rules;
import life.genny.rules.QRules;

/* Subscribe Intern to BEG */
rule "Apply Internship - Step 3.2"
	when
		rules: QRules( 	isState("LINKED_BEG_TO_INTERN") && 
						isState("CREATED_LINK") && 
						isState("INTERN") && 
						isState("QUE_INTERNSHIP_ADDITIONAL_GRP") && 
						isState("EVENT_FORM_SUBMIT") && 
						isState("SUBMIT") && 
						!isState("LOOP_APPLY_INTERNSHIP_STEP3_2")) 

	 then
	 	rules.header();
        rules.setState("LOOP_APPLY_INTERNSHIP_STEP3_2");

		/* Get beg BaseEntity */
		BaseEntity beg = rules.getAsBaseEntity("begBe");

		rules.subscribeUserToBaseEntity(rules.getUser().getCode(), beg.getCode());
 		rules.setState("INTERN_SUBSCRIBED_TO_BEG");
	 	rules.footer();      
end
