package life.genny.rules;

import life.genny.rules.QRules;

rule "Application is ready - memberhub"
    when
        rules: QRules( isState("TRIGGER_APPLICATION") && isState("APPLICATION_READY") &&
                    !isState("LOOP_APPLICATION_READY_MEMBERHUB") )
    then
        rules.header();

		rules.setState("LOOP_APPLICATION_READY_MEMBERHUB");
		rules.setState("TRIGGER_HOMEPAGE");

        rules.footer();
end
