package life.genny.rules;
import life.genny.rules.QRules;
import java.util.List;

rule "Send Internmatch Homepage Layout Data - HOST COMPANY - BUCKETVIEW"
     when
        rules: QRules(  isState("SEND_INTERNMATCH_HOMEPAGE_LAYOUT_DATA") &&
                        isState("SENT_INTERNMATCH_HOMEPAGE_LAYOUT") &&
                        isState("PRI_IS_HOST_COMPANY") &&
                        isState("SENT_SUBLAYOUT") &&
                        !isState("LOOP_SEND_INTERNMATCH_HOMEPAGE_LAYOUT_DATA") )
     then
        rules.header();
        rules.setState("LOOP_SEND_INTERNMATCH_HOMEPAGE_LAYOUT_DATA");

		List<BaseEntity> buckets = rules.getBaseEntitysByParentAndLinkCode("GRP_DASHBOARD", "LNK_CORE", 0, 500, false);
		List<BaseEntity> removeBuckets = new ArrayList<BaseEntity>();
        
        /* Remove  GRP_APPLIED bucket from GRP_DASHBOARD */
		for (BaseEntity bucket : buckets) {
			if (bucket.getCode().equalsIgnoreCase("GRP_APPLIED")) {
				removeBuckets.add(bucket);
			}
		}
		buckets.removeAll(removeBuckets);
		rules.publishCmd(buckets, "GRP_DASHBOARD", "LNK_CORE");
        
        rules.setState("SENT_INTERNMATCH_HOMEPAGE_LAYOUT_DATA");
		rules.footer();
end
