package life.genny.rules;
import life.genny.rules.QRules;

rule "Add Internship - Step 6"
	when
        rules: QRules(  isState("SEND_PRODUCT_QUESTION") && 
                        isState("ASKED_QUESTION")  &&
                        !isState("LOOP_SEND_PRODUCT_QUESTION")  )
     then 
 		rules.header();
		rules.setState("LOOP_SEND_PRODUCT_QUESTION");

		BaseEntity product = rules.getAsBaseEntity("productBe");
		if(product != null){
			rules.set("questionSourceCode", rules.getUser().getCode());
			rules.set("questionTargetCode", product.getCode());
			rules.set("questionGroupCode", "QUE_ADD_PRODUCT_GRP");
			rules.set("questionIsPopup", true);
			
			rules.clearState("ASKED_QUESTION");

			rules.setState("ASK_QUESTION");

			rules.setState("SEND_ADD_PRODUCT_QUESTION_LAYOUT");
		}else{
			rules.println("product is null");
		}
 		rules.footer();
end
