package life.genny.rules;

import life.genny.rules.QRules;


rule "Add Insurance - Step 3 Payment Item Creation Failed"
	when
		rules: QRules( isState("ITEM_CREATION_FAILED") && !isState("DID_ITEM_CREATION_FAILED") )		
	then
	   rules.header();
	   
		 rules.setState("DID_ITEM_CREATION_FAILED");
		 
			String paymentTitle = rules.getKeyValue("PaymentTitle");
			String sourceEntityCode = rules.getKeyValue("PaymentSourceEntityCode");
			String amountAttributeCode = rules.getKeyValue("PaymentAmountAttributeCode");
			String sellerCode = rules.getKeyValue("PaymentSeller");
			String buyerCode = rules.getKeyValue("PaymentBuyer");
		
			rules.println("paymentTitle :: "+paymentTitle);
			rules.println("srcEntityCode :: "+sourceEntityCode);
			rules.println("amountAttributeCode :: "+amountAttributeCode);
		    rules.println("sellerCode :: "+sellerCode);
	        rules.println("buyerCode :: "+buyerCode);
	        
	        if(paymentTitle != null && sourceEntityCode != null && amountAttributeCode != null &&
	                    sellerCode != null && buyerCode != null ){
                  rules.setState("ASK_AVAILABLE_PAYMENT_METHODS");
	     	}    
	      
	   rules.footer();
end
