package life.genny.rules;

import life.genny.rules.QRules;


rule "User Profile is not completed - step 1 - channel40"
    when
	    rules: QRules( 	isState("PROFILE_NOT_COMPLETED") && 
	    					isState("USER_DID_NOT_COMPLETE_PROFILE") &&
						!isState("LOOP_PROFILE_NOT_COMPLETED")	)
     then
     	rules.header();
   	   	
		rules.setState("LOOP_PROFILE_NOT_COMPLETED");
		
		rules.sendSelections("GRP_USER_ROLE", "LNK_CORE", 10); /* TODO to remove */
  		rules.askQuestions(rules.getUser().getCode(), rules.getUser().getCode(), "QUE_NEW_USER_PROFILE_GRP");
		rules.setState("ASKED_USER_PROFILE_QUESTIONS");
		
	    rules.footer();
end
