package life.genny.rules;
import life.genny.rules.QRules;

rule "Update BEG - Step 1"
    when
	    rules: QRules(  isState("BTN_EDIT_BEG") &&
                        isState("EVENT_BTN_CLICK") &&	
                        !isState("LOOP_EDIT_BEG_STEP1")) 	
     then
        rules.header();    
        rules.setState("LOOP_EDIT_BEG_STEP1");

        String begCode = rules.getAsString("itemCode");
        if(begCode != null){
            BaseEntity beg = rules.getChildren(begCode, "LNK_BEG", "PRODUCT");
            if(beg != null){
                rules.println("THIS IS THE BEG AWWAWA :: "+beg);
                rules.set("questionSourceCode", rules.getUser().getCode());
                rules.set("questionTargetCode", beg.getCode());
                rules.set("questionGroupCode", "QUE_EDIT_BEG_GRP");
                rules.set("questionIsPopup", false);
                rules.setState("SEND_QUESTION");
                rules.setState("SEND_UPDATE_PRODUCT_QUESTION");

            }else{
                rules.println("beg is null");
            }
        }else{
            rules.println("begCode is null");
        }
		rules.setState("SENT_BEG_QUESTION");
        rules.footer();     		      
end
