package life.genny.rules;
import life.genny.rules.QRules;

/* Send Host Company Dashboard on Update */
rule "Update BEG - Step 3"
	when
	    rules: QRules(	isState("SENT_PRODUCT_QUESTION") &&
						isState("SENT_QUESTION") && 
						isState("QUE_EDIT_BEG_GRP") && 
						isState("EVENT_FORM_SUBMIT") && 
						isState("SUBMIT") && 
						!isState("LOOP_EDIT_BEG_STEP2")) 
	 then
	 	rules.header();
        rules.setState("LOOP_EDIT_BEG_STEP2");
        rules.clearState("SENT_BEG_QUESTION");

		// rules.set("subLayoutCode", "DASHBOARD");
		// rules.set("subLayoutPath", "homepage/dashboard_host_company_temp.json");
		// rules.set("subLayoutRootCode", "GRP_DASHBOARD_HOST_COMPANY");
		// rules.set("subLayoutIsPopup", false);

		// rules.setState("SEND_SUBLAYOUT");
		rules.setState("TRIGGER_HOMEPAGE");


	 	rules.footer();      
end