package life.genny.rules;


import life.genny.rules.QRules;
import life.genny.qwanda.Link;

import life.genny.qwandautils.QwandaUtils;

import life.genny.qwanda.Answer;
import life.genny.qwanda.message.QDataAnswerMessage;
import life.genny.qwanda.message.QEventLinkChangeMessage;


rule "Listen Link Change"
    when
        $m: QEventLinkChangeMessage( event_type == "EVT_LINK_CHANGE" )
        rules : QRules()
     then    
      	rules.header();
 
 		Link link = $m.getLink();
 		 		
 		rules.sendParentLinks(link.getTargetCode(),link.getAttributeCode());
 		
 	   
   	    rules.footer();
  
end