package life.genny.rules;
import life.genny.rules.QRules;

rule "Ask Registration"
    when
        rules: QRules(  isState("PROFILE_NOT_COMPLETED") && 
						isState("SENT_REGISTRATION_DATA") && 
						!isState("PRI_IS_HOST_COMPANY") && 
						!isState("LOOP_ASK_REGISTRATION") )
     then 
 		rules.header();
		rules.setState("LOOP_ASK_REGISTRATION");

		String questionSourceCode = rules.getUser().getCode();
		String questionTargetCode = rules.getUser().getCode();
 		String questionGroupCode = rules.getAsString("registration_question_grp");
		Boolean questionIsPopup = false;

		rules.set("questionSourceCode", questionSourceCode);
		rules.set("questionTargetCode", questionTargetCode);
		rules.set("questionGroupCode", questionGroupCode);
		rules.set("questionIsPopup", questionIsPopup);
		
		rules.setState("ASK_QUESTION");
 		rules.footer();
end
