package life.genny.rules;
import life.genny.rules.QRules;

/* Check No. Of Applied Interns */
rule "Check Number Of Applied Interns"
	when
		rules: QRules( 	isState("CHECK_NUMBER_OF_APPLIED_INTERNS_FOR_BEG") && 
						isState("SUBMITTED_APPLICATION_FOR_INTERNSHIP") &&
						!isState("LOOP_CHECK_NUMBER_OF_APPLIED_INTERNS_FOR_BEG")) 

	 then
	 	rules.header();
		rules.setState("LOOP_CHECK_NUMBER_OF_APPLIED_INTERNS_FOR_BEG");

		/* get beg from state map */
        BaseEntity beg = rules.getAsBaseEntity("begBe");
        if(beg != null){
            List<BaseEntity> applications = rules.getChildrens(beg.getCode(), "LNK_BEG", "APPLICATION");
            
            if(applications != null){
                rules.println("Application Size   ::   " + applications.size());
                if(applications.size() == 3){
                    rules.setState("NUMBER_OF_APPLIED_INTERNS_FOR_BEG_IS_FULL");
                }
            }else{
                rules.println("applications is null");
            }
            rules.setState("CHECKED_NUMBER_OF_APPLIED_INTERNS_FOR_BEG");
    		rules.setState("TRIGGER_INTERNMATCH_HOMEPAGE_LAYOUT");
        }else{
            rules.println("beg is null");
        }
	 	rules.footer();
end
