package life.genny.rules;
import life.genny.rules.QRules;

/* Check No. Of Applied Interns */
rule "Update Applications Recieved For BEG as FULL"
	when
		rules: QRules( 	isState("CHECKED_NUMBER_OF_APPLIED_INTERNS_FOR_BEG") && 
						isState("NUMBER_OF_APPLIED_INTERNS_FOR_BEG_IS_FULL") &&
						!isState("LOOP_CHECKED_NUMBER_OF_APPLIED_INTERNS_FOR_BEG")) 
	 then
	 	rules.header();
		rules.setState("LOOP_CHECKED_NUMBER_OF_APPLIED_INTERNS_FOR_BEG");

		/* get beg from state map */
        BaseEntity beg = rules.getAsBaseEntity("begBe");
        if(beg != null){
            rules.saveAnswer( new Answer(beg.getCode(), beg.getCode(), "PRI_APPLICATION_LIMIT_FULL", "TRUE") );
        }else{
            rules.println("beg is null");
        }
	 	rules.footer();
end
