package life.genny.rules;

import life.genny.rules.QRules;

rule "Delete BEG - Step 1"
	when
		rules: QRules( isState("EVENT_BTN_CLICK") && isState("BTN_DELETE_BEG") && !isState("DID_TRIGGER_DELETE_BEG") )
	then
	
		rules.header();

		rules.setState("DID_TRIGGER_DELETE_BEG");

		String begCode = rules.getAsString("itemCode");
		String groupCode = rules.getAsString("hintCode");
		
		rules.println(begCode);
		rules.println(groupCode);
		
         if(begCode != null && begCode != null ){
        	 	
             rules.println("Deleting beg: " + begCode);
             rules.setState("HIDE_BEG_FROM_USERS");
         }     

	    rules.footer();
end
