package life.genny.rules;

import life.genny.rules.QRules;

rule "Delete BEG - Step 3"
	when
		rules: QRules( isState("MOVE_BEG_TO_BIN") && !isState("DID_MOVE_BEG_TO_BIN") )
	then
	
		rules.header();

		rules.setState("DID_MOVE_BEG_TO_BIN");

		String begCode = rules.getAsString("itemCode");
		String groupCode = rules.getAsString("hintCode");

         if(begCode != null && begCode != null) {
        	 
			   	/* We move the BEG to GRP_BIN */
		        rules.baseEntity.moveBaseEntity(begCode, groupCode, "GRP_BIN", "LNK_CORE", "BEG");
		        
		        /*  publishing beg again as it was deleted and will be needed for GRP_BIN again  */
		        rules.publishBaseEntityByCode(begCode);
		        
		        rules.setState("RELOAD_CACHE");
         }     

	    rules.footer();
end
