package com.sample
 
import life.genny.qwanda.message.QEventMessage;
import life.genny.qwanda.message.QCmdMessage;
import io.vertx.rxjava.core.eventbus.EventBus;
import io.vertx.core.buffer.Buffer;
import com.google.gson.Gson;
import life.genny.qwanda.Answer;
import life.genny.qwanda.message.QDataAnswerMessage;
import life.genny.qwandautils.KeycloakUtils;
import life.genny.qwandautils.QwandaUtils;
import life.genny.qwanda.message.QDataAskMessage;
import life.genny.qwanda.Ask;

import java.lang.reflect.Type;
import java.time.LocalDateTime;
import java.time.ZonedDateTime;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonParseException;
import com.google.gson.JsonPrimitive;
import com.google.gson.JsonSerializationContext;
import com.google.gson.FieldNamingPolicy;
//import io.vertx.core.json.JsonObject;
import java.time.format.DateTimeFormatter;
import life.genny.qwanda.DateTimeDeserializer;

global java.lang.String REACT_APP_QWANDA_API_URL;
global java.lang.String REACT_APP_VERTX_URL;
global java.lang.String KEYCLOAKIP;
   
rule "Facebook Redirect"
  when
    $m : QEventMessage( event_type == "BTN_CLICK" && data.code == "SOC_FB_BASIC_GENNY")
    bus: EventBus()
    $map : Map($value: this["token"] != null)
  then
    System.out.println("-------- Rule:- Redirect Executed --------");
    String tokenString = (String)$map.get("token");
    System.out.println("tokenstr="+tokenString);

    String clientId= "423902461306952";
    String clientSecret= "a7bd50640f9914b95756ae8f5680751b";
    String redirectUrl= "https://www.facebook.com/v2.8/dialog/oauth?response_type=code";

    JsonObject items = new JsonObject();
    items.put("clientId", clientId);
    items.put("clientSecret", clientSecret);
    items.put("redirectUrl", redirectUrl);  

    System.out.println("*******************");
    System.out.println("Redirect Data="+items.toString());	
    System.out.println("*******************");						
    
    JsonObject obj = new JsonObject();
    obj.put("msg_type", "DATA_MSG");
    obj.put("data_type", "FB_REDIRECT");
    obj.put("items", items);        
    bus.publish("cmds", obj); 
end




