package life.genny.rules;

import life.genny.qwandautils.RulesUtils;
import life.genny.rules.QRules;
import life.genny.qwanda.entity.BaseEntity;
import life.genny.qwanda.GPS;
import io.vertx.rxjava.core.eventbus.EventBus;
import io.vertx.core.json.JsonObject;
import io.vertx.core.json.JsonArray;
import java.util.Map;
import java.util.List;

import life.genny.qwanda.message.QDataGPSMessage;
import life.genny.qwandautils.QwandaUtils;
import life.genny.qwandautils.RulesUtils;

rule "Receive GPS Data"
	
    when
	    m : QDataGPSMessage()
	    rules: QRules()
	    bus: EventBus()
        $map : Map($value: this["token"] != null)
     then
     	
     	RulesUtils.header(drools.getRule().getName());
     	
        BaseEntity user = rules.getUser();
        String qwandaServiceUrl = System.getenv("REACT_APP_QWANDA_API_URL");
        String tokenString = (String)$map.get("token");   
        
        /* Get Jobs in transit */
        /* http://localhost:8280/qwanda/baseentitys/GRP_IN_TRANSIT/linkcodes/LNK_CORE
         * 
         */
        List<BaseEntity> jobsInTransit = rules.getBaseEntitysByAttributeAndValue("STT_IN_TRANSIT", rules.getUser().getCode());
 		System.out.println(jobsInTransit.toString());
	    RulesUtils.footer(drools.getRule().getName());       		      
end
