package com.sample

import life.genny.qwanda.message.QEventMessage;
import life.genny.qwanda.message.QCmdMessage;
import life.genny.qwanda.message.QMessage.MessageData;
import io.vertx.rxjava.core.eventbus.EventBus;
import life.genny.qwandautils.QwandaUtils;
import io.vertx.core.json.JsonObject;
import com.google.gson.Gson;
import com.sample.*;
import java.util.Map;
import java.util.HashSet;
import java.util.Set;
import life.genny.qwanda.entity.User;

global java.lang.String REACT_APP_QWANDA_API_URL;


rule "Post Job"
    when
      $m : QEventMessage( event_type == "FORM_SUBMIT" && data.code == "QUE_POST_JOB_GRP" )
      bus: EventBus()
      $user: User(realm != null)
      $map : Map($value: this["token"] != null)    
    then
        System.out.println(LOG_YELLOW + "================================================================================================================================================" + LOG_RESET);
        System.out.println(LOG_GREEN + "RULE EXECUTED      ::    POST Job - Submit  " + LOG_RESET);
        //Prepare Token & qwandaServiceUrl
        String qwandaServiceUrl = System.getenv("REACT_APP_QWANDA_API_URL");
        String tokenString = (String)$map.get("token"); 
        String jobCode = $m.data.getValue();
        System.out.println("The Job/BEG code submitted is    :: "+jobCode);
        //link current user as load-owner to the Job/BEG
        boolean linkedLoadOwner = EBCHandlers.linkEntityEntityWithLinkvalue(jobCode, $user.getuCode(), "LNK_BEG","OWNER",tokenString);  
        System.out.println("The linked owner to beg (true/false)?   ::  " +linkedLoadOwner);
        //link Job to the GRP_NO_QUOTES
        boolean linkedBEGtoGRPNoquotes = EBCHandlers.linkEnitytEntity("GRP_NO_QUOTES", $m.data.getValue(), "LNK_CORE",tokenString);  
        System.out.println("Linked job/beg to GRP_NO_QUOTES (true/false)?   ::  " +linkedBEGtoGRPNoquotes);
        
        //Calling the rule group : layout to redirect user to home/bucketView page
        drools.setFocus("layout"); 
        
        System.out.println( "\n" + LOG_RED + "RULE TERMINATED    ::  POST Job - Submit  " + LOG_RESET);
        System.out.println(LOG_YELLOW + "------------------------------------------------------------------------------------------------------------------------------------------------" + LOG_RESET);
end

