package life.genny.rules;
import life.genny.rules.QRules;

/* Add BEG, APPLICATION, CPY to map */
rule "Trigger Submit Add BE To BEG"
	when
		rules: QRules( 	isState("QUE_ADD_BE_TO_BEG_GRP") &&
						isState("EVENT_FORM_SUBMIT") &&
						isState("SUBMIT") &&
						!isState("LOOP_SUBMIT_ADD_TO_BEG_STEP0"))
	then
	 	rules.header();
  		rules.setState("LOOP_SUBMIT_ADD_TO_BEG_STEP0");

		/* get applicationCode from targetCode */
		String applicationCode = rules.getAsString("targetCode");
		
		if(applicationCode != null){

			BaseEntity application = rules.baseEntity.getBaseEntityByCode(applicationCode);
			rules.set("subBe", application);

			/* get begCode(attribute) from application */
			String begCode = application.getLoopValue("PRI_BEG_CODE", null);

			if(begCode != null) {

				BaseEntity beg = rules.baseEntity.getBaseEntityByCode(begCode);
				rules.set("begBe", beg);
				
				/* link BE to BEG */
				rules.setState("LINK_BE_TO_BEG");
				
			}else{
				rules.println("begCode is null");
			}
		}else{
			rules.println("applicationCode is null");
		}
		rules.footer();
end
