package life.genny.rules;
import life.genny.rules.QRules;

/* LINK GRP_DRAFTS + INT || INTERNSHIP */
rule "Add Internship - Step 4"
	when
	    rules: QRules(  isState("LINK_DRAFTS_TO_BEG") && 
						isState("LINKED_BEG_TO_INT") &&
	     				isState("BTN_CREATE_INTERNSHIP") && 
						isState("CREATED_LINK") &&
						isState("INTERNSHIP") &&
						!isState("LOOP_ADD_INTERNSHIP_STEP4")) 
	 then
	 	rules.header();
        rules.setState("LOOP_ADD_INTERNSHIP_STEP4");

		BaseEntity beg = rules.getAsBaseEntity("begBe");	

		/* link GRP_DRAFTS to BEG */
		rules.set("linkSourceCode", "GRP_DRAFTS");
		rules.set("linkTargetCode", beg.getCode());
		rules.set("linkCode", "LNK_CORE");
		rules.set("linkValue", "BEG");
		rules.set("linkWeight", 1.0);
		rules.setState("CREATE_LINK");

		rules.setState("LINKED_DRAFTS_TO_BEG");
		rules.setState("SEND_INTERNSHIP_DATA");
	 	rules.footer();      
end
