package life.genny.rules;
import life.genny.rules.QRules;

/* Create BEG BaseEntity */
rule "Add Internship - Step 1"
	when
		rules: QRules(  isState("EVENT_BTN_CLICK") &&
						isState("BTN_CREATE_INTERNSHIP") &&
						!isState("LOOP_ADD_INTERNSHIP_STEP1") ) 
	 then
	 	rules.header();
        rules.setState("LOOP_ADD_INTERNSHIP_STEP1");

		 /* Create BEG BaseEntity*/
		rules.set("beCode", rules.getUser().getCode());
		rules.set("bePrefix", "BEG");
		rules.set("beName", "BEG");		
		rules.setState("CREATE_BASE_ENTITY");	

		rules.setState("CREATED_BEG");	
		rules.setState("CREATE_INT");	
	 	rules.footer();      
end
