package life.genny.rules;
import life.genny.rules.QRules;

rule "Add Internship - Step 5"
	when
        rules: QRules(  isState("BTN_CREATE_INTERNSHIP") && 
						isState("ASK_INTERNSHIP_QUESTION") && 
						isState("CREATED_LINK") && 
						isState("BEG") && 
						isState("LINKED_DRAFTS_TO_BEG") && 
                        !isState("LOOP_ADD_INTERNSHIP_STEP5")  )
     then 
 		rules.header();
		rules.setState("LOOP_ADD_INTERNSHIP_STEP5");

		BaseEntity internship = rules.getAsBaseEntity("internshipBe");

		rules.set("questionSourceCode", rules.getUser().getCode());
		rules.set("questionTargetCode", internship.getCode());
		rules.set("questionGroupCode", "QUE_INTERNSHIP_GRP");
		rules.set("questionIsPopup", false);
		
		rules.setState("ASK_QUESTION");
		rules.setState("ASKED_INTERNSHIP_QUESTION");
 		rules.footer();
end
