package life.genny.rules;
import life.genny.rules.QRules;

rule "Add Internship - Step 5"
	when
		rules: QRules(  isState("SEND_INTERNSHIP_DATA") && 
										isState("LINKED_DRAFTS_TO_BEG") && 
        						isState("BTN_CREATE_INTERNSHIP") && 
										isState("CREATED_LINK") && 
										isState("BEG") && 
										!isState("LOOP_ADD_INTERNSHIP_STEP5")  )
     then 
				rules.header();
				rules.setState("LOOP_ADD_INTERNSHIP_STEP5");

				rules.sendSelections("GRP_FIELD_OF_WORK", "LNK_CORE", 10);
				rules.sendSelections("GRP_DURATION", "LNK_CORE", 10);

				rules.setState("SENT_INTERNSHIP_DATA");
				rules.setState("ASK_INTERNSHIP_QUESTION");
				rules.footer();
end
