package life.genny.rules;
import life.genny.rules.QRules;

rule "Add Internship - Step 6"
	when
        rules: QRules(  isState("ASK_INTERNSHIP_QUESTION") && 
						isState("SENT_INTERNSHIP_DATA") && 
	     				isState("BTN_CREATE_INTERNSHIP") && 
                        !isState("LOOP_ADD_INTERNSHIP_STEP6")  )
     then 
 		rules.header();
		rules.setState("LOOP_ADD_INTERNSHIP_STEP6");

		BaseEntity internship = rules.getAsBaseEntity("internshipBe");

		rules.set("questionSourceCode", rules.getUser().getCode());
		rules.set("questionTargetCode", internship.getCode());
		rules.set("questionGroupCode", "QUE_INTERNSHIP_GRP");
		rules.set("questionIsPopup", true);
		
		rules.setState("ASK_QUESTION");
		rules.setState("ASKED_INTERNSHIP_QUESTION");
 		rules.footer();
end
