package life.genny.rules;
import life.genny.rules.QRules;

/* Send ROOT - HOST_COMPANY */
rule "Send Root - HOST_COMPANY" 
    when    
        rules: QRules(  isState("SEND_ROOT_HOST_COMPANY") && 
                        isState("PRI_IS_HOST_COMPANY") && 
                        (isState("PROFILE_IS_COMPLETED") || isState("PRI_IS_PROFILE_COMPLETED")) && 
                        !isState("LOOP_SEND_ROOT_HOST_COMPANY") )
     then
     	rules.header();
        rules.setState("LOOP_SEND_ROOT_HOST_COMPANY");
		
        /* SEND ROOT BaseEntity */
        rules.publishBaseEntityByCode("GRP_ROOT", null, null, recipient);			
        rules.setState("SENT_ROOT_HOST_COMPANY");

        rules.setState("SEND_ROOT_KIDS_HOST_COMPANY");
	    rules.footer();      		      
end


