package life.genny.rules;
import life.genny.rules.QRules;
import life.genny.qwanda.message.QEventMessage;

rule "Send Offer Message To Host Company"
	when
		rules: QRules(  isState("SEND_OFFER_MESSAGE_TO_HOST_COMPANY") && 
                        !isState("LOOP_SEND_OFFER_MESSAGE_TO_HOST_COMPANY") )
	then
	 	rules.header();
 		rules.setState("LOOP_SEND_OFFER_MESSAGE_TO_HOST_COMPANY");
 		
        BaseEntity beg = rules.getAsBaseEntity("begBe");
        BaseEntity intern = rules.getAsBaseEntity("internBe");
        BaseEntity internship = rules.getAsBaseEntity("internshipBe");
        BaseEntity hostCompany = rules.getAsBaseEntity("hostCompanyBe");
 		
        if(beg == null){
            rules.println("beg is null");
            return;
        }else if(intern == null){
            rules.println("intern is null");
            return;
        }else if(internship == null){
            rules.println("internship is null");
            return;
        }else if(hostCompany == null){
            rules.println("hostCompany is null");
            return;
        }else{
        
            String json = "{\"loading\":\"Loading your documents...\",\"evt_type\":\"REDIRECT_EVENT\",\"evt_code\":\"REDIRECT_SHOW_OFFER\",\"data\":{\"value\": \"" + beg.getCode() + "\"}}";
			String base64 = rules.encodeToBase64(json);
			
	 		HashMap<String, String> contextMap = new HashMap<String, String>(); 
	        contextMap.put("BEG", beg.getCode());
	        contextMap.put("INTERNSHIP", internship.getCode());
            contextMap.put("INTERN", intern.getCode());
	        contextMap.put("HOSTCOMPANY", hostCompany.getCode());
	        contextMap.put("URL", "http://localhost:3000/?state=" + base64);
	        
            String[] recipients = null;

            /* Get all the HOSTCOMPANY staffs */
            List<BaseEntity> hostCompanyStaffs = rules.getChildrens(hostCompany.getCode(), "LNK_STAFF", "STAFF");
            if(hostCompanyStaffs != null) {
                rules.println("No. of hostCompanyStaffs   ::   " + hostCompanyStaffs.size() );	
                recipients = new String[hostCompanyStaffs.size()];
                int i = 0;
                for(BaseEntity hostCompanyStaff : hostCompanyStaffs) {
                    recipients[i] = hostCompanyStaff.getCode();
                    i++;
                }
            }
            rules.sendMessage(null, recipients, contextMap, "MSG_INTERNMATCH_INTERNSHIP_TO_HOST", "EMAIL");
 		    rules.setState("SENT_OFFER_MESSAGE_TO_HOST_COMPANY");
 		}
	 	rules.footer();      
end
