package life.genny.rules;

import life.genny.rules.QRules;

rule "New payment method - payment submit"
	no-loop true
    when
          m : QEventMessage( event_type == "PAYMENT_SUBMIT" )
          rules: QRules(!isState("STARTED")) 
     then    
        rules.setDrools(drools);
        rules.println("RULE INIT PAYMENT_SUBMIT: "+m.getData().getValue());
        rules.setState("STARTED");

  		drools.setFocus("payment-method");
        
      		      
end
