package life.genny.rules;

import life.genny.rules.QRules;
import life.genny.qwanda.Answer;
import io.vertx.core.json.JsonArray;
import io.vertx.core.json.JsonObject;
import life.genny.utils.PaymentUtils;
import java.util.List;
import life.genny.qwanda.payments.QPaymentsAuthorizationToken.AuthorizationPaymentType;

rule "Delete new payment method - user"
	agenda-group "payment-method"
	when
		rules: QRules( isState("STARTED") && !isState("DELETED_PAYMENT_METHOD") )
		$m : QEventMessage( event_type == "PAYMENT_SUBMIT" && data.code == "USER_DELETE_NEW_PAYMENT_METHOD" )

	then

		rules.header();

		String deletedPaymentMethodId = $m.getData().getValue();

		String assemblyAuthKey = PaymentUtils.getAssemblyAuthKey();
       	String assemblyId = rules.getUser().getValue("PRI_ASSEMBLY_USER_ID", null);

       	/* Save tokens */
       	if(assemblyId != null) {

  			String oneTimeTransactionCardToken = null;
  			String oneTimeTransactionBankToken = null;
       		oneTimeTransactionCardToken = rules.fetchOneTimePaymentsToken(assemblyId, assemblyAuthKey, AuthorizationPaymentType.card);
       		oneTimeTransactionBankToken = rules.fetchOneTimePaymentsToken(assemblyId, assemblyAuthKey, AuthorizationPaymentType.bank);

			Answer cardTokenAnswer = new Answer(rules.getUser().getCode(), rules.getUser().getCode(), "PRI_ASSEMBLY_CARD_TOKEN", oneTimeTransactionCardToken);
			Answer bankTokenAnswer = new Answer(rules.getUser().getCode(), rules.getUser().getCode(), "PRI_ASSEMBLY_BANK_TOKEN", oneTimeTransactionBankToken);
			
			List<Answer> answers = new ArrayList<Answer>();
			answers.add(cardTokenAnswer);
			answers.add(bankTokenAnswer);

			rules.saveAnswers(answers);
       	}

		if(deletedPaymentMethodId != null) {

			String userCode = rules.getUser().getCode();
			String userCurrentPaymentMethods = rules.getUser().getValue("PRI_USER_PAYMENT_METHODS", null);
			
			Boolean isDeleted = false;
			if(userCurrentPaymentMethods != null) {

				JsonArray currentPaymentMethods = new JsonArray(userCurrentPaymentMethods);
				JsonArray newPaymentMethodsArray = new JsonArray();
				for(Object paymentMethodObj: currentPaymentMethods) {

					if(paymentMethodObj instanceof JsonObject) {

						JsonObject paymentMethod = (JsonObject)paymentMethodObj;
						if(paymentMethod.getString("id").equals(deletedPaymentMethodId) == false) {
							newPaymentMethodsArray.add(paymentMethod);
						} else {
							if(PaymentUtils.isBankAccount(paymentMethod.toString())) {
								isDeleted = rules.deleteBankAccount(deletedPaymentMethodId, assemblyAuthKey);
							} else {
								isDeleted = rules.deleteCard(deletedPaymentMethodId, assemblyAuthKey);
							}
						}
					}
				}

				/* Delete only if payments API returns success response for delete API */
				rules.println("is card/bank-account deleted :: "+isDeleted);
				if(isDeleted) {
					String finalPaymentMethods = newPaymentMethodsArray.toString();
					Answer paymentAnswer = new Answer(userCode, userCode, "PRI_USER_PAYMENT_METHODS", finalPaymentMethods);
	            		rules.saveAnswer(paymentAnswer);
				}
				
			}
		}

		rules.setState("DELETED_PAYMENT_METHOD");
		rules.footer();

end
