package life.genny.rules;

import life.genny.rules.QRules;

import life.genny.qwanda.entity.BaseEntity;
import life.genny.qwanda.message.QEventMessage;
import java.util.HashMap;
import java.util.ArrayList;
import life.genny.rules.RulesUtils;

rule "Display Dashboard On Rating Submission"
	when 
		$m : QEventMessage( event_type == "FORM_SUBMIT" && data.code == "QUE_USER_RATING_GRP" )
      	rules: QRules( !isState("DRIVER_RATING_DONE") )
	then
	
	 	rules.header();
	 	rules.setState("DRIVER_RATING_DONE");
	 	BaseEntity user = rules.getUser();
	 	
	    String begCode = user.getValue("STT_JOB_IS_RATING", null);
       	 
       	 BaseEntity jobBe = rules.getBaseEntityByCode(begCode);
         String offerCode = jobBe.getValue("STT_HOT_OFFER",null);
         BaseEntity offerBe = rules.getBaseEntityByCode(offerCode);
         String quoterCode = offerBe.getValue("PRI_QUOTER_CODE", null);
         
         rules.println("The BEG/JOB Code is :: "+begCode);
         rules.println("The offer Code is :: "+offerCode);
         rules.println("The quoter Code is :: "+quoterCode);
         
         /* list of users for status-change */
       	List<String> userCodesForStatusColourChange = new ArrayList<>();
       	userCodesForStatusColourChange.add(user.getCode());
       	userCodesForStatusColourChange.add(quoterCode);
       
       /* change status colour to both driver and owner to Orange (warning) :  Funds Cleared disbursement processing */
		rules.updateBaseEntityStatus(begCode, userCodesForStatusColourChange, "warning");
		
	 	
	  /* redirecting user to bucket */
        rules.sendSublayout("bucket-dashboard", "dashboard_channel40.json");
        
	 	rules.footer();
	 	
end
