package life.genny.rules;

import life.genny.rules.RulesUtils;
import life.genny.rules.QRules;
import life.genny.qwanda.Answer;
import life.genny.utils.PaymentUtils;



rule "New Payments User"
	agenda-group "payments"
	no-loop true
    when
    	rules: QRules( isState("NEW_ASSEMBLY_USER_CREATION") && !isState("IS_ASSEMBLY_USER_CREATED") )
    then
     
     RulesUtils.header(drools.getRule().getName());
     	     
     /* get assembly authKey   */
     String assemblyAuthToken = PaymentUtils.getAssemblyAuthKey();
     
     /*  Creates assembly userId */
     String assemblyId = PaymentUtils.getAssemblyId(rules.getToken());
     
     			
     /* logic to create assembly user & set the payments userProfileExists flag  */
     rules.paymentUserCreation(assemblyId, assemblyAuthToken);
    
        
	 rules.footer();      		      
end