package life.genny.rules;

import life.genny.rules.QRules;
import java.util.List;

rule "Home Page - Send Layout - EDU PROVIDER"
     when
        rules: QRules(  isState("HOME_PAGE_SENT_DATA") && 
                        isState("PRI_IS_EDU_PROVIDER") &&
                        !isState("LOOP_HOME_PAGE_SEND_LAYOUT") ) 
     then      
        rules.header();
        rules.setState("LOOP_HOME_PAGE_SEND_LAYOUT");

        rules.sendSublayout("DASHBOARD", "homepage/dashboard_edu_provider.json", "GRP_DASHBOARD_EDU_PROVIDER", false);
        rules.setState("HOME_PAGE_SENT_LAYOUT");
        
		rules.footer();     		      
end
     	