package life.genny.rules;
import life.genny.rules.QRules;

/* Send Root */
rule "Send Root"
    when
        rules: QRules(  isState("SEND_ROOT") && 
                        !isState("LOOP_SEND_ROOT") )
     then
     	rules.header();
     	rules.setState("LOOP_SEND_ROOT");

        rules.set("beParentCode", "GRP_ROOT");            
        rules.set("beLinkCode", "LNK_CORE");
        rules.set("bePageStart", 0);
        rules.set("bePageSize", 20);
        rules.set("beCache", false);

        rules.clearState("LOOP_PUBLISH_BASE_ENTITY_LIST");
        rules.setState("PUBLISH_BASE_ENTITY_LIST");
         
        rules.setState("SENT_ROOT");		
        rules.setState("SEND_DASHBOARD");		
        rules.setState("SEND_CONTACT");		
	    rules.footer();     		      
end


       