package life.genny.rules;
import life.genny.rules.QRules;

rule "Send Bin"
    when
        rules: QRules(  isState("SEND_BIN") && 
                        !isState("LOOP_SEND_BIN") )
     then
     	rules.header();
     	rules.setState("LOOP_SEND_BIN");
        
        rules.set("beParentCode", "GRP_BIN");            
        rules.set("beLinkCode", "LNK_CORE");
        rules.set("bePageStart", 0);
        rules.set("bePageSize", 200);
        rules.set("beCache", false);
        
        rules.clearState("LOOP_PUBLISH_BASE_ENTITY_LIST");
        rules.setState("PUBLISH_BASE_ENTITY_LIST");
         
        rules.setState("SENT_BIN");		
	    rules.footer();     		      
end
