package life.genny.rules;
import life.genny.rules.QRules;

/* Send ROOT for EDU_PROVIDER */
rule "Send Root - EDU_PROVIDER" 
    when    
        rules: QRules(  isState("SEND_ROOT_EDU_PROVIDER") && 
                        isState("PRI_IS_EDU_PROVIDER") && 
                        (isState("PROFILE_IS_COMPLETED") || isState("PRI_IS_PROFILE_COMPLETED")) && 
                        !isState("LOOP_SEND_ROOT_EDU_PROVIDER") )
     then
     	rules.header();
        rules.setState("LOOP_SEND_ROOT_EDU_PROVIDER");
		
        /* SEND ROOT BaseEntity */
        rules.publishBaseEntityByCode("GRP_ROOT", null, null, recipient);			
        rules.setState("SENT_ROOT_EDU_PROVIDER");

        rules.setState("SEND_ROOT_KIDS_EDU_PROVIDER");
	    rules.footer();      		      
end


