package life.genny.rules;

import life.genny.rules.QRules;
import life.genny.qwanda.message.QEventBtnClickMessage;

rule "Check user company - User is a company"
	when
		 rules: QRules( 	(isState("EVENT_BTN_CLICK") && isState("BTN_SELECT_COMPANY_YES")) && !isState("SELECTED_COMPANY_ROLE") )   
	 then
	    rules.header();
		
		rules.setState("SELECTED_COMPANY_ROLE");
		
		/* we set the company role */
		rules.setState("PRI_IS_COMPANY");
		rules.baseEntity.updateBaseEntityAttribute(rules.getUser().getCode(), rules.getUser().getCode(), "PRI_IS_COMPANY", "TRUE");
		
		rules.setState("CHECK_COMPANY_EXISTS");
	    rules.footer();     		      
end
