package life.genny.rules;

import life.genny.rules.QRules;
import life.genny.qwanda.message.QEventBtnClickMessage;

rule "Check user company - Step 6"

	when
		 rules: QRules( 	isState("EVENT_FORM_SUBMIT") && isState("QUE_USER_COMPANY_GRP") &&
						!isState("HAS_ANSWERED_COMPANY_QUESTIONS") )   
	 then
	    rules.header();
		
		rules.setState("HAS_ANSWERED_COMPANY_QUESTIONS");
		rules.setState("COMPANY_IS_READY");
		
	    rules.footer();     		      
end
