package life.genny.rules;

import life.genny.qwanda.message.QCmdMessage;
import life.genny.qwanda.message.QBulkMessage;
import life.genny.qwanda.message.QDataBaseEntityMessage;
import life.genny.qwanda.message.QEventMessage;
import life.genny.rules.QRules;
import io.vertx.core.json.JsonObject;
import java.util.List;
import java.util.ArrayList;
import life.genny.qwanda.entity.BaseEntity;
import life.genny.qwanda.entity.SearchEntity;
import life.genny.utils.VertxUtils;

rule "Generate Bucket caches"

    ruleflow-group 'GenerateBucketCaches'
     when
       rules: QRules( !isState("GENERATE_BUCKET_CACHES"))
     then
     rules.header();
        rules.setState("GENERATE_BUCKET_CACHES");
		rules.println("Generating  Bucket Caches for "+rules.realm());

		rules.reloadCache();


     rules.footer();
end
