package life.genny.rules;
import life.genny.rules.QRules;

rule "Send Bucket Data"
    when
        rules: QRules( 	isState("SEND_BUCKET_DATA") && 
						isState("PRI_IS_BUYER") &&		
						!isState("LOOP_SENT_BUCKET_DATA_INTERNMATCH") )
     then
     	rules.header();

     	rules.setState("LOOP_SENT_BUCKET_DATA_INTERNMATCH");
		rules.sendInternData();
		  
		rules.setState("APPLICATION_READY");
		rules.setState("TRIGGER_APPLICATION");
	    rules.footer();
end

