package life.genny.rules;

import life.genny.rules.QRules;
import life.genny.qwanda.entity.SearchEntity;
import life.genny.utils.VertxUtils;
import java.util.ArrayList;


rule "GenerateCapabilities"

    ruleflow-group 'GenerateCapabilities'

    when
        rules: QRules( !isState("GENERATE_CAPABILITIES") )
     then
         rules.setState("GENERATE_CAPABILITIES");
         rules.println("Generating Genny Capabilities");

		rules.generateCapabilities();

	
end
