package life.genny.rules;
import life.genny.rules.QRules;
import life.genny.qwanda.message.QEventMessage;
import life.genny.qwanda.entity.BaseEntity;

rule "Auth Init"
    when
        m : QEventMessage( "AUTH_INIT" == data.code  )
        rules: QRules( isState("STARTED") && !isState("USER_CHECKED") && !isState("AUTH_INIT"))
     then
     	rules.header();

     	rules.header();
        rules.setState("AUTH_INIT");
        rules.setState("LOOP_AUTH_INIT_EVT");

        rules.getUser();

        if(rules.isUserPresent() == true) {

            rules.getUser();
            rules.setState("TRIGGER_APPLICATION_SETUP"); /* this starts application workflow */
        }

	    rules.footer();
end
