package life.genny.rules;

import life.genny.rules.QRules;
import life.genny.qwanda.entity.BaseEntity;

import life.genny.qwanda.message.QEventMessage;

rule "Auth Init"

    when
        m : QEventMessage( "AUTH_INIT" == data.code  )
        rules: QRules( isState("STARTED") && !isState("USER_FOUND") && !isState("AUTH_INIT"))
     then     

     	rules.header();
        rules.setState("AUTH_INIT");
        BaseEntity user = rules.getUser();
        if(user == null ){
            rules.setState("USER_NOT_FOUND");
            rules.setState("TRIGGER_REGISTRATION");
        }else{
            rules.setState("USER_FOUND");
        }
        
	    rules.footer();       		      
end
