package life.genny.rules;

import life.genny.rules.QRules;
import life.genny.qwanda.entity.BaseEntity;

rule "Application Ready"
    when
        rules: QRules(  isState("EXIT_APPLICATION_SETUP") && 
                        !isState("LOOP_APPLICATION_READY") ) 
     then
        rules.header();
        
        rules.setState("LOOP_APPLICATION_READY");
        rules.setState("APPLICATION_READY");
        
	    rules.footer();     		      
end
