package life.genny.rules;

import life.genny.rules.QRules;
import java.util.List;
import java.util.stream.Collectors;
import life.genny.qwanda.attribute.EntityAttribute;

rule "Check User Role"
     when
        /* rules: QRules( isState("USER_FOUND") &&  !isState("LOOP_CHECK_ROLE") )  */
        rules: QRules(isState("USER_FOUND") && !isState("LOOP_CHECK_ROLE") )
     then
        rules.header();
		rules.setState("LOOP_CHECK_ROLE");

		BaseEntity user = rules.getUser();
		List<EntityAttribute> roles = user.getBaseEntityAttributes()
								.stream()
								.filter(x -> (x.getAttributeCode().contains("PRI_IS")))
								.collect(Collectors.toList());

		Boolean has_role_been_found = false;

		for(EntityAttribute role: roles) {
			if(role != null && role.getValue() != null) {
				Boolean isRole = role.getValueBoolean() != null && role.getValueBoolean() == true;
				if(isRole) {
					rules.setState(role.getAttributeCode());
					has_role_been_found = true;
				}
			}
		}

		if(has_role_been_found) {
			rules.setState("ROLE_FOUND");
		}
		else {
			rules.setState("ROLE_NOT_FOUND");
		}

		rules.setState("ROLE_CHECKED");
	    rules.footer();
end
