package life.genny.rules;

import life.genny.rules.QRules;


rule "Is Not Logged In"
    when
        rules: QRules(	isUserPresent() == false  &&  					
						isState("USER_NOT_CHECKED") && 
						!isState("LOOP_IS_NOT_LOGGED_IN"))
      then
		rules.header();
		rules.setState("LOOP_IS_NOT_LOGGED_IN");
		/* we mark the user as logged in */
		rules.setState("IS_NOT_LOGGED_IN");
		rules.footer();     		      
end
