package life.genny.rules;

import life.genny.rules.QRules;
import life.genny.qwanda.entity.BaseEntity;

rule "Is Logged In"
    when
        rules: QRules(  isUserPresent() == true  && 
                        isState("ROLE_CHECKED") && 
                        !isState("LOOP_LOGGED_IN") ) 
     then
        rules.header();
        rules.setState("LOOP_LOGGED_IN");
        BaseEntity user = rules.getUser();
  		
  		/* we mark the user as logged in */
        rules.setState("IS_LOGGED_IN");
        
		/* drools.setFocus("payments");  MOVE TO CHANNEL40 FOLDER */		
	    rules.footer();     		      
end
