package life.genny.rules;

import life.genny.rules.QRules;
import java.util.List;

rule "Check If Intern Profile Completion"
     when
        rules: QRules( isState("STARTED") && !isState("LOOP_INTERN_ROLE_CHECK") && isState("PRI_IS_INTERN")) 
     then
        
        rules.header();
        rules.setState("LOOP_INTERN_ROLE_CHECK");
        
     	rules.set("registration_question_grp", "QUE_USER_INTERNMATCH_GRP");
     	rules.sendSelections("GRP_UNI_SELECTION", "LNK_CORE", 10);
     	rules.sendSelections("GRP_DEGREE_SELECTION", "LNK_CORE", 10);
     	rules.sendSelections("GRP_GENDERS", "LNK_CORE", 10);
     	rules.setState("CHECK_USER_PROFILE_COMPLETED");
		
		rules.footer();     		      
end
     	