package life.genny.rules;

import life.genny.rules.QRules;
import java.util.List;

rule "Check Intern Profile Completion"
     when
        $m: QEventAttributeValueChangeMessage( QEventAttributeValueChangeMessage.getData().getCode().equals("PRI_IS_INTERN") )
        rules: QRules( isState("STARTED") && !isState("HAS_CHECKED_PROFILE_INTERN") ) 
     then
        
        rules.header();
        
		rules.setState("HAS_CHECKED_PROFILE_INTERN");
     	rules.set("registration_question_grp", "QUE_USER_INTERNMATCH_GRP");
     	rules.sendSelections("GRP_UNI_SELECTION", "LNK_CORE", 10);
     	rules.sendSelections("GRP_DEGREE_SELECTION", "LNK_CORE", 10);
     	rules.sendSelections("GRP_GENDERS", "LNK_CORE", 10);
     	rules.setState("CHECK_USER_PROFILE_COMPLETED");
		
		rules.footer();     		      
end
     	