package life.genny.rules;

import life.genny.rules.QRules;


import java.util.ArrayList;
import java.util.List;
import java.util.Arrays;
import life.genny.qwandautils.MergeUtil;

rule "Check if Role Is Set - Intermatch"
    no-loop true
    when
        rules: QRules( isState("IS_LOGGED_IN") && !isState("ROLE_CHECKED_LOOP"))
     then
     
     	rules.header();
     	
     	String[] roles = new String[3];
     	roles[0] = "PRI_IS_INTERN";
		roles[1] = "PRI_IS_ED_PROVIDER";
     	roles[2] = "PRI_IS_HOST_COMPANY";
     	
   	   	rules.set("roleCodes", roles);	
		rules.setState("ROLE_CHECKED_LOOP");
		rules.setState("CHECK_ROLE");
   	    
    	    rules.footer();
end
