package life.genny.rules;
import life.genny.rules.QRules;

rule "Ask Registration"
    	no-loop true
    when
        rules: QRules(  isState("PROFILE_NOT_COMPLETED") && !isState("ASK_REGISTRATION")  )
     then
     
 		rules.header();
 		
 		String userCode = rules.getUser().getCode();
 		rules.setState("ASK_REGISTRATION");
 		String questionGroupCode = rules.getAsString("registration_question_grp");
 		if(questionGroupCode != null) {
 			rules.askQuestions(userCode, userCode, questionGroupCode, false, false);
 		}
 		
 		rules.footer();
end
