package life.genny.rules;
import life.genny.rules.QRules;

/* LINK APPLICATION + NOTE */
rule "Submit Add Note - STEP 1"
	when
		rules: QRules( 	isState("LINK_APPLICATION_AND_NOTE") &&
						!isState("LOOP_LINK_APPLICATION_AND_NOTE"))
	 then
	 	rules.header();
        rules.setState("LOOP_LINK_APPLICATION_AND_NOTE");

		BaseEntity note = rules.getAsBaseEntity("noteBe");
		BaseEntity application = rules.getAsBaseEntity("applicationBe");

		if(application == null){
			rules.println("application is null");
			return;

		}else if(note == null){
			rules.println("note is null");
			return;

		}else{
			/* link GRP_DRAFTS to BEG */
			rules.set("linkSourceCode", application.getCode());
			rules.set("linkTargetCode", note.getCode());
			rules.set("linkCode", "LNK_APP");
			rules.set("linkValue", "NOTE");
			rules.set("linkWeight", 1.0);

			rules.setState("CREATE_LINK");
			rules.setState("SEND_VIEW_APPLICATION_DETAILS_LAYOUT");
		}
		rules.footer();
end


        
        

        
