package life.genny.rules;
import life.genny.rules.QRules;

rule "Select Dashboard Kids"
    when
      rules: QRules(  isState("EVENT_TV_SELECT") &&
                      isState("TV1") &&
                      !isState("LOOP_SELECT_DASHBOARD_KIDS") )
    then
      rules.header();
      rules.setState("LOOP_SELECT_DASHBOARD_KIDS");

      String tvSelectValue = rules.getAsString("tvSelectValue");
		  BaseEntity parent = rules.getParent(tvSelectValue, "LNK_CORE");

      if(parent != null){
        if(parent.getCode().equals("GRP_DASHBOARD")){
          rules.set("cmdViewType", "LIST_VIEW");
          rules.set("cmdViewRootCode", tvSelectValue);
          rules.setState("SEND_CMD_VIEW");

          rules.setState("SELECTED_DASHBOARD_KIDS");
        }
      }
      rules.footer();
end
