package life.genny.rules;
import life.genny.rules.QRules;

rule "Exit Send Application Data"

    when
         rules: QRules( isState("SENT_APPLICATION_DATA") && 
                        !isState("LOOP_EXIT_SEND_APPLICATION_DATA") )
     then
     	rules.header();
        rules.setState("LOOP_EXIT_SEND_APPLICATION_DATA");
    
        rules.setState("EXIT_SEND_APPLICATION_DATA");
	    rules.footer();      		      
end
