package life.genny.rules;
import life.genny.rules.QRules;

/* Sends Grp / BEGS / BEG kids */
rule "Send Application Data - EDU PROVIDER" 
    when    
         rules: QRules( isState("SEND_APPLICATION_DATA") && 
                        isState("PRI_IS_EDU_PROVIDER") && 
                        isState("PROFILE_IS_COMPLETED") && 
                        !isState("LOOP_SEND_APPLICATION_DATA_EDU_PROVIDER") )
     then
     	rules.header();
        rules.setState("LOOP_SEND_APPLICATION_DATA_EDU_PROVIDER");
        rules.sendInternApplicationData();
        
        rules.setState("SENT_APPLICATION_DATA");
	    rules.footer();      		      
end
