package life.genny.rules;
import life.genny.rules.QRules;

rule "Add Note - STEP 2"
	when
		rules: QRules(  isState("SAVE_APPLICATION_CODE_AS_ATTRIBUTE") &&
						isState("CREATED_BASE_ENTITY") &&
						!isState("LOOP_SAVE_APPLICATION_CODE_AS_ATTRIBUTE")) 
	 then
	 	rules.header();
		rules.setState("LOOP_SAVE_APPLICATION_CODE_AS_ATTRIBUTE");
		
		BaseEntity note = rules.getAsBaseEntity("baseEntity");
		BaseEntity application = rules.getAsBaseEntity("applicationBe");
		if(application == null){
			rules.println("application is null");
			return;

		}else if(note == null){
			rules.println("note is null");
			return;

		}else{
			rules.set("noteBe", note);
        	rules.baseEntity.saveAnswer(new Answer (rules.getUser().getCode(), note.getCode(), "PRI_APPLICATION_CODE", application.getCode()));
			rules.setState("ASK_NOTE_QUESTION");

		}
	 	rules.footer();      
end
