package life.genny.rules;

import life.genny.rules.QRules;


rule "TV_SELECT Individual Chat Message"
	   no-loop true
       ruleflow-group 'TV_SELECT'
       salience 6
     when
       rules: QRules( isState("STARTED") && isState("EVENT_TV_SELECT") && 
                       isState("PARENT_GRP_MESSAGES") && !isState("TV_CHAT_ITEM_DATA_SENT") ) 
     then

      rules.header();
     
	     rules.setState("TV_CHAT_ITEM_DATA_SENT");
         rules.setState("TV_SELECT_RULE_EXECUTED"); /* Need to set this state compulsarily as the default rule
         												 executes based on this state */
         Object grpCodeObj = rules.get("tvSelectValue");
         
         if(grpCodeObj != null){
             String grpCode = grpCodeObj.toString();
             if(grpCode != null && !grpCode.isEmpty()){
		         rules.sendChatMessages(grpCode, 0, 10000);
		  		 rules.sendCmdSplitView("GRP_MESSAGES", grpCode);
	  		 }
		}
		
     rules.footer();
end
