package life.genny.rules;
 
import life.genny.rules.QRules;
import life.genny.qwanda.message.QEventMessage;
import life.genny.qwanda.message.QCmdMessage;

 
   
/* Treeview element CONTRACT */
rule "Contract TreeView Items"
    when
        m : QEventMessage( event_type == "TV_CONTRACT" && data.code == "TV1" )
		rules : QRules()
    then
 	    rules.println("-------- Rule:- CONTRACT TreeView Items --------");
 /* 	    String tokenString = (String)$map.get("token");
		System.out.println("tokenstr="+tokenString);
		JsonObject obj = new JsonObject();
		obj.put("msg_type", "CMD_MSG");
		obj.put("cmd_type", "TV_CONTRACT");
		obj.put("code", $m.getData().getValue());
		obj.put("token", $value);		
		System.out.println("*******************");
		System.out.println("Json="+obj.toString());	
		System.out.println("*******************");						
		bus.publish("cmds", obj);       */
end