package life.genny.rules;

import life.genny.rules.QRules;
import life.genny.qwanda.entity.BaseEntity;
import life.genny.qwanda.message.QEventMessage;
import life.genny.rules.RulesUtils;
import io.vertx.core.json.JsonObject;

import life.genny.qwanda.message.QCmdMessage;

rule "Show more info about job"
	when
		$m: QEventMessage( event_type == "BTN_CLICK" && data.code == "BTN_LOAD_SEE_MORE")
		rules: QRules()
	then
		
		RulesUtils.header(drools.getRule().getName());
		
		String data = $m.getData().getValue();
		if(data != null) {
			
			JsonObject dataJson = new JsonObject(data);
			String hint = dataJson.getString("hint");
			String baseEntityCode = dataJson.getString("itemCode");
			
			/* first we check if the base entity is a load, a driver, or an owner etc... The BE code will tell us: */
			if(baseEntityCode != null) {
			
				if(baseEntityCode.contains("LOD_")) {
			     	return; 
				}
			}
			
		    if(hint != null && baseEntityCode != null) {
		    		
		    		switch(hint) {
				case "GRP_NEW_ITEMS": 
				case "GRP_IN_TRANSIT": 
				case "GRP_APPROVED": 
				case "GRP_PAID": 
				case "GRP_DELIVERED": 
			     		
				     QCmdMessage cmdLoadSublayout = new QCmdMessage("CMD_SUBLAYOUT", "LoadLayout");
				     
				     JsonObject cmdLoadSublayoutJson = new JsonObject().mapFrom(cmdLoadSublayout);
				     
				     String sublayout = RulesUtils.getLayout("loadLayout.json");
				     cmdLoadSublayoutJson.put("items", sublayout);
				     cmdLoadSublayoutJson.put("root", baseEntityCode);
				     cmdLoadSublayoutJson.put("token", rules.getToken());
				     rules.publish("cmds", cmdLoadSublayoutJson); 
				    
				break;
			      
				default:
					break;
				}
		    }
		}
		
		RulesUtils.footer(drools.getRule().getName());
end
