package life.genny.rules;

import life.genny.rules.QRules;
import life.genny.qwanda.entity.BaseEntity;

rule "Check if mobile phone number verification is required"
    when
        rules: QRules( isState("VERIFIY_MOBILE_PHONE_NUMBER") && 
                    !isState("LOOP_VERIFY_MOBILE_PHONE_NUMBER") )
    then
        rules.header();
        
		rules.setState("LOOP_VERIFY_MOBILE_PHONE_NUMBER");
        
		if(rules.getQuestions(rules.getUser().getCode(), rules.getUser().getCode(), "QUE_TERMS_AND_CONDITIONS_GRP") != null) {
			rules.setState("TERMS_AND_CONDITIONS_NOT_ACCEPTED");
		}
		else {
			rules.setState("TERMS_AND_CONDITIONS_ACCEPTED");
		}
		
        rules.footer();
end
