package life.genny.rules;
import life.genny.rules.QRules;

rule "User Accepted Terms and Conditions"
	when
	    rules: QRules( 	isState("QUE_TERMS_AND_CONDITIONS_GRP") &&
						isState("EVENT_FORM_SUBMIT") &&
						!isState("LOOP_USER_ACCEPTED_T_C")) 
	 then
	 	rules.header();
        
		rules.setState("LOOP_USER_ACCEPTED_T_C");
		rules.setState("TERMS_AND_CONDITONS_ACCEPTED");  
		
	 	rules.footer();      
end