package life.genny.rules;
import life.genny.rules.QRules;

/* Send Questions */
rule "Apply Internship - Step 2"
	when
	    rules: QRules(  isState("SAVE_BEG_CODE_AS_ATTRIBUTE") && 
	                    isState("CREATED_APPLICATION") && 
	                    isState("CREATED_BASE_ENTITY") && 
	                    isState("APP") && 
	                    isState("BTN_APPLY_INTERNSHIP") && 
						isState("EVENT_BTN_CLICK") && 
						!isState("LOOP_APPLY_INTERNSHIP_STEP2")) 
	 then
	 	rules.header();
        rules.setState("LOOP_APPLY_INTERNSHIP_STEP2");

        /* GET APPLICATION BaseEntity code from state */
		BaseEntity application = rules.getAsBaseEntity("baseEntity");

        /* GET begCode from itemCode State */		
		String begCode = rules.getAsString("itemCode");
        
        if(application == null){
            rules.println("application BaseEntity is null");
		}else if(begCode == null){
            rules.println("begCode is null");			
		}else{
			rules.saveAnswer(   new Answer(	rules.getUser().getCode(), 
											application.getCode(), 
											"PRI_BEG_CODE", 
											begCode
										)
							);
		    rules.setState("SAVED_BEG_CODE_AS_ATTRIBUTE");

		    rules.setState("SEND_APPLY_INTERNSHIP_QUESTIONS");
		}
	 	rules.footer();      
end


        
        
