package life.genny.rules;
import life.genny.rules.QRules;
import life.genny.qwanda.message.QEventMessage;

rule "View Education Provider Profile"
    when
        m : QEventMessage(  event_type == "PROFILE" && 
                            data.code == "PROFILE")
                            
	    rules: QRules(  isState("ROLE_FOUND") &&
                        isState("PRI_IS_EDU_PROVIDER") &&	
                        !isState("LOOP_VIEW_EDU_PROVIDER_PROFILE")) 	
     then
        rules.header();    
        rules.setState("LOOP_VIEW_EDU_PROVIDER_PROFILE");

       rules.sendSelections("GRP_UNI_SELECTION", "LNK_CORE", 10);
     	rules.sendSelections("GRP_DEGREE_SELECTION", "LNK_CORE", 10);

        rules.set("questionSourceCode", rules.getUser().getCode());
		rules.set("questionTargetCode", rules.getUser().getCode());
		rules.set("questionGroupCode", "QUE_EDU_PROVIDER_GRP");
		rules.set("questionIsPopup", false);

        rules.setState("ASK_QUESTION");
        rules.footer();     		      
end
