package life.genny.rules;

import life.genny.rules.QRules;


rule "Send Layout Change To Frontend"

    salience 699
    no-loop true
    ruleflow-group "SendLayoutsAndData"
    when
        rules: QRules( !isState("LAYOUT_CHANGE_READY") )
     then
     	rules.header();

        rules.sendLayout("LAY_DEFAULT", "layout.json", "shared");
        rules.setState("LAYOUT_CHANGE_READY");

	    rules.footer();
end
