package life.genny.rules;

import life.genny.rules.RulesUtils;
import life.genny.rules.QRules;

import life.genny.qwandautils.QwandaUtils;
import life.genny.qwanda.message.QCmdMessage;
import life.genny.qwanda.message.QCmdLayoutMessage;
import life.genny.qwanda.Layout;
import life.genny.qwanda.message.QDataSubLayoutMessage;

import io.vertx.core.json.JsonObject;
import io.vertx.core.json.JsonArray;



rule "Send Sub Layouts To Frontend"

     salience 680
    agenda-group "SendLayoutsAndData"
    when
        rules: QRules( isState("LAYOUT_CHANGE_READY") && (!isState("SUBLAYOUT_CHANGE_READY"))  ) 
     then

        rules.header();
  
  		rules.sendSubLayouts();
		
		rules.setState("SUBLAYOUT_CHANGE_READY");
		
	    rules.footer();     		      
end
