package life.genny.rules;

import life.genny.rules.QRules;
import life.genny.qwanda.entity.BaseEntity;
import java.util.List;
import java.util.ArrayList;
import java.util.Optional;
import life.genny.utils.VertxUtils;


rule "Send Ch40 BucketData To Frontend"
    salience 670
    agenda-group "SendLayoutsAndData"
    when
        rules: QRules(  !isState("SEND_BUCKET_DATA")  && isState("SUBLAYOUT_CHANGE_READY") ) 
     then
     	rules.header();
     	
     	rules.setState("SEND_BUCKET_DATA");
 
	
		rules.sendLayoutsAndData();
       	   		
	    rules.footer();       		      
end
