package life.genny.rules;

import life.genny.rules.RulesUtils;
import life.genny.rules.QRules;

rule "Send Bucket Layout To Frontend"
    salience 660
    agenda-group "SendLayoutsAndData"
    when
        rules: QRules( isState("STARTED") && isState("SEND_BUCKET_DATA") && isState("USER_IS_OWNER") && (!isState("SEND_BUCKET_LAYOUT")) ) 
     then
     	rules.header();
     	
     	String layout = RulesUtils.getLayout("card.json");
     	
     	/* sending cmd BUCKET_VIEW */
     	rules.sendSublayout("bucket-dashboard", "dashboard_channel40.json", "GRP_DASHBOARD");

		rules.setState("SEND_BUCKET_LAYOUT");
		
	    rules.footer();     		      
end
