package life.genny.rules;


import life.genny.rules.QRules;
import life.genny.qwanda.Answer;
import life.genny.qwanda.message.QDataAnswerMessage;
import life.genny.rules.RulesUtils;

rule "Answer Helper"
ruleflow-group 'Answer'
    when
        $m : QDataAnswerMessage( QDataAnswerMessage.getData_type().equals(Answer.class.getSimpleName()) )
        rules: QRules( isState("STARTED") && isState("ANSWER_PROCESSED") && (!isState("ANSWER_HELPER")))
    then    
        rules.header();
        	
        Answer[] answers = $m.getItems();
		if(answers != null && answers.length > 0) {
			Answer firstAnswer = answers[0];
			String attributeCode = firstAnswer.getAttributeCode();
				
			if(attributeCode.equals("PRI_CPY_NAME")) {
				String name = firstAnswer.getValue();
				if ("Crowtech".equals(name)) {
				List<Answer> helperAnswers = new ArrayList<Answer>();
				
					helperAnswers.add(new Answer(firstAnswer.getSourceCode(),firstAnswer.getTargetCode(),"PRI_ACN","058716582"));
					helperAnswers.add(new Answer(firstAnswer.getSourceCode(),firstAnswer.getTargetCode(),"PRI_ABN","82145623575"));
					helperAnswers.add(new Answer(firstAnswer.getSourceCode(),firstAnswer.getTargetCode(),"PRI_LANDLINE","61398857159"));
					helperAnswers.add(new Answer(firstAnswer.getSourceCode(),firstAnswer.getTargetCode(),"PRI_GST","TRUE"));
					helperAnswers.add(new Answer(firstAnswer.getSourceCode(),firstAnswer.getTargetCode(),"PRI_ADDRESS_JSON","{\"street_address\":\"61 Fakenham Road\",\"suburb\":\"Ashburton\",\"state\":\"VIC\",\"postal_code\":\"3147\",\"country\":\"AU\",\"full_address\":\"61 Fakenham Rd, Ashburton VIC 3147, Australia\",\"latitude\":-37.862308,\"longitude\":145.08747100000005}"));
					helperAnswers.add(new Answer(firstAnswer.getSourceCode(),firstAnswer.getTargetCode(),"PRI_ADDRESS_FULL","64 Fakenham Rd, Ashburton, VIC"));
					rules.publishData(new Answer(firstAnswer.getSourceCode(),firstAnswer.getTargetCode(),"PRI_ADDRESS_FULL","64 Fakenham Rd, Ashburton, VIC"));
					rules.publishData(new Answer(firstAnswer.getSourceCode(),firstAnswer.getTargetCode(),"PRI_ADDRESS_JSON","{\"street_address\":\"61 Fakenham Road\",\"suburb\":\"Ashburton\",\"state\":\"VIC\",\"postal_code\":\"3147\",\"country\":\"AU\",\"full_address\":\"61 Fakenham Rd, Ashburton VIC 3147, Australia\",\"latitude\":-37.862308,\"longitude\":145.08747100000005}"));
					rules.saveAnswers(helperAnswers);
				}
			}
			
	
		}
	   
	   rules.setState("ANSWER_HELPER");
       rules.footer();
           
end


   