// package life.genny.rules;

// import life.genny.rules.RulesUtils;
// import life.genny.rules.QRules;
// import life.genny.qwanda.message.QEventMessage;
// import life.genny.qwanda.message.QMessage.MessageData;
// import life.genny.qwanda.message.QCmdMessage;
// import io.vertx.rxjava.core.eventbus.EventBus;
// import io.vertx.core.buffer.Buffer;
// import com.google.gson.Gson;
// import life.genny.qwanda.Answer;
// import life.genny.qwanda.message.QDataAnswerMessage;
// import life.genny.qwanda.message.QEventAttributeValueChangeMessage;
// import life.genny.qwandautils.KeycloakUtils;
// import life.genny.qwandautils.MergeUtil;
// import life.genny.qwandautils.QwandaUtils;
// import life.genny.qwandautils.MergeUtil;
// import life.genny.qwanda.message.QDataAskMessage;
// import life.genny.qwanda.message.QCmdMessage;
// import life.genny.qwanda.message.QDataAnswerMessage;
// import life.genny.qwanda.Ask;
// import life.genny.qwanda.Link;


// import java.lang.reflect.Type;
// import java.util.Map;
// import java.util.Set;
// import java.util.Iterator;
// import java.util.HashMap; 
// import java.time.LocalDateTime;
// import java.time.ZonedDateTime;
// import com.google.gson.GsonBuilder;
// import com.google.gson.JsonDeserializationContext;
// import com.google.gson.JsonDeserializer;
// import com.google.gson.JsonElement;
// import com.google.gson.JsonParseException;
// import com.google.gson.JsonPrimitive;
// import com.google.gson.JsonSerializationContext;
// import com.google.gson.FieldNamingPolicy;
// import io.vertx.core.json.JsonObject;
// import io.vertx.core.json.JsonArray;
// import java.time.format.DateTimeFormatter;
// import life.genny.qwanda.DateTimeDeserializer;


// rule "Answer"
//     when
//         m : QDataAnswerMessage( QDataAnswerMessage.getData_type().equals(Answer.class.getSimpleName()) )
//         rules: QRules()
//     then    
//         rules.header();
        
// 	rules.processAnswer(m); 
 
//        rules.footer();
           
// end


   