package life.genny.rules;
import life.genny.rules.QRules;

rule "Invite Intern - Step 1"
	when
        rules: QRules(  isState("EVENT_BTN_CLICK") && 
						isState("BTN_INVITE_INTERN") && 
                        !isState("LOOP_CREATE_INTERN_BASE_ENTITY")  )
     then 
 		rules.header();
		rules.setState("LOOP_CREATE_INTERN_BASE_ENTITY");

		/* Create USER BaseEntity*/
		rules.set("beCode", rules.getUser().getCode());
		rules.set("bePrefix", "PER");
		rules.set("beName", "PERSON");
		rules.setState("CREATE_BASE_ENTITY");	

		rules.setState("CREATED_INTERN_BASE_ENTITY");	
		rules.setState("ASK_INVITE_INTERN_QUESTION");	
 		rules.footer();
end
