package life.genny.rules;
import life.genny.rules.QRules;

/* Send Sub Layout */
rule "View Internship Details - Step 0"
	when
		rules: QRules(  isState("BTN_VIEW_INTERNSHIP_DETAILS") && 
						isState("EVENT_BTN_CLICK") && 
						!isState("LOOP_VIEW_INTERNSHIP_DETAILS_STEP0") ) 
	 then
	 	rules.header();
        rules.setState("LOOP_VIEW_INTERNSHIP_DETAILS_STEP0");

		/* get begCode (itemCode) from state */
		String begCode = rules.getAsString("itemCode");
		String bucketCode = rules.getAsString("hintCode");
		if(begCode != null){
			/* send report and research docs question */
        	rules.sendQuestions(rules.getUser().getCode() ,begCode, "QUE_RESEARCH_DOC_GRP", false);
        	rules.sendQuestions(rules.getUser().getCode() ,begCode, "QUE_REPORT_DOC_GRP", false);

			rules.setState("SENT_UPLOAD_DOC_QUESTIONS");	
			rules.setState("VIEW_INTERNSHIP_DETAILS");	
				
		}else{
			rules.println("begCode is null");
		}
	 	rules.footer();      
end
