package life.genny.rules;
import life.genny.rules.QRules;

rule "Exit Subscription - Internmatch"

    when
         rules: QRules( isState("SUBSCRIBED_INTERN_TO_GRP_AVAILABLE_BEGS") &&
         				isState("PROFILE_IS_COMPLETED") &&
         				!isState("LOOP_EXIT_SUBSCRIPTION") )
     then
     	rules.header();
        rules.setState("LOOP_EXIT_SUBSCRIPTION");
        
        rules.setState("EXIT_SUBSCRIPTION");
	    rules.footer();      		      
end
