package life.genny.rules;
import life.genny.rules.QRules;
import life.genny.qwanda.entity.BaseEntity;

rule "Subscribe Interns to GRP_AVAILABLE BEGs"
	when
		rules: QRules( 	isState("SUBSCRIBE_INTERN_TO_GRP_AVAILABLE_BEGS") && 
						isState("PRI_IS_INTERN") &&
						!isState("LOOP_SUBSCRIBE_INTERN_TO_GRP_AVAILABLE_BEGS") ) 
	 then
	 	rules.header();
        rules.setState("LOOP_SUBSCRIBE_INTERN_TO_GRP_AVAILABLE_BEGS");

        List<BaseEntity> begs = rules.getBaseEntitysByParentAndLinkCode("GRP_AVAILABLE", "LNK_CORE", 0, 500, false);
		rules.subscribeUserToBaseEntities(rules.getUser().getCode(), begs);

		for(BaseEntity beg : begs){
			String[] recipents = rules.getSubscribers(beg.getCode());
			rules.println("SUBSCRIBER of beg   ::   " + Arrays.toString(recipents));
		}
		
        rules.setState("SUBSCRIBED_INTERN_TO_GRP_AVAILABLE_BEGS");
	 	rules.footer();      
end