// package life.genny.rules;
// import life.genny.rules.QRules;
// import life.genny.qwanda.entity.BaseEntity;

// rule "Subscribe All Interns to New BEG"
// 	when
// 		rules: QRules( 	isState("SUBSCRIBE_ALL_INTERNS_TO_NEW_BEG") && 
// 						!isState("LOOP_SUBSCRIBE_ALL_INTERNS_TO_NEW_BEG") ) 
// 	 then
// 	 	rules.header();
//         rules.setState("LOOP_SUBSCRIBE_ALL_INTERNS_TO_NEW_BEG");

// 		/* Get All Interns */
//         List<BaseEntity> interns = rules.getBaseEntitysByParentAndLinkCode("GRP_INTERNS", "LNK_CORE", 0, 500, false);
// 		for(BaseEntity intern : interns){
// 			rules.subscribeUserToBaseEntity(intern.getCode(), beg.getCode());
// 		}

// 		String[] begSubscribers = rules.getSubscribers(beg.getCode());
// 		rules.println("SUBSCRIBERS of newly created BEG   ::   " + Arrays.toString(begSubscribers));
		
//         rules.setState("SUBSCRIBED_ALL_INTERNS_TO_NEW_BEG");
// 	 	rules.footer();      
// end
