/* package life.genny.rules;
import life.genny.rules.QRules;
import life.genny.qwanda.entity.BaseEntity;
import java.util.ArrayList;
import java.util.List;

rule "Subscribe Interns to LINKED BEGs"
	when
		rules: QRules( 	isState("SUBSCRIBE_INTERN_TO_LINKED_BEGS") && 
						isState("SUBSCRIBED_INTERN_TO_GRP_AVAILABLE_BEGS") &&
						isState("PRI_IS_INTERN") &&
						!isState("LOOP_SUBSCRIBE_INTERN_TO_LINKED_BEGS") ) 
	 then
	 	rules.header();
        rules.setState("LOOP_SUBSCRIBE_INTERN_TO_LINKED_BEGS");

		List<BaseEntity> bucketList = getBaseEntitysByParentAndLinkCode("GRP_DASHBOARD", "LNK_CORE", 0, 500, false);
		if(bucketList != null){

			for(BaseEntity bucket: bucketList) {  
				rules.println("BUCKET CODE   ::   " + bucket.getCode());

				List<BaseEntity> internbegs = getBaseEntitysByParentAndLinkCode(bucket.getCode(), "LNK_CORE", 0, 500, false, rules.getUser().getCode());
				rules.println("FETCHED linked BEGS for the intern   ::   " + internbegs.size() );

				rules.subscribeUserToBaseEntities(rules.getUser().getCode(), internbegs);
				rules.setState("SUBSCRIBED_INTERN_TO_LINKED_BEGS");
			}
		}
	 	rules.footer();      
end
						 */