package life.genny.rules;

import life.genny.qwandautils.RulesUtils;
import life.genny.rules.QRules;

import life.genny.qwanda.Answer;
import life.genny.qwanda.message.QDataAnswerMessage;

import life.genny.qwandautils.PaymentUtils;
import life.genny.qwandautils.QwandaUtils;
import life.genny.qwandautils.MergeUtil;
import life.genny.qwandautils.RulesUtils;

import java.util.Map;


rule "Assembly user updation for attribute change"
    when
    	m : QDataAnswerMessage( QDataAnswerMessage.getData_type().equals(Answer.class.getSimpleName()) )
    	rules : QRules()
    then    
		RulesUtils.header(drools.getRule().getName());
        
        String userName = rules.getAsString("preferred_username");
     	String userCode =  QwandaUtils.getBaseEntityCodeForUserName(userName, rules.getToken());
     	String tokenString = rules.getToken();
        
        /* get assembly authKey   */
    	String assemblyAuthToken = PaymentUtils.getAssemblyAuthKey();
     
    	/*  Gets assembly userId */
    	String assemblyId = MergeUtil.getAttrValue(userCode, "PRI_ASSEMBLY_USER_ID", tokenString);
    	String companyId = MergeUtil.getAttrValue(userCode, "PRI_ASSEMBLY_COMPANY_ID", tokenString);

        /* extract answers */
        Answer[] answers = m.getItems();
        for (Answer answer : answers) {
        
            Long askId = answer.getAskId();
            String sourceCode = answer.getSourceCode();
            String targetCode = answer.getTargetCode();
            answer.setSourceCode(answer.getTargetCode());
            String attributeCode = answer.getAttributeCode();
            String value = answer.getValue();

            RulesUtils.println("Printing Answer data recieved for Update in Assembly  ::");  
            RulesUtils.println("\nAskId: " +askId + "\nSource Code: " +sourceCode + "\nTarget Code: " +targetCode + "\nAttribute Code: " +attributeCode + "\nAttribute Value: " +value);
           
           	/* Updates assembly user profile */
        	String response = PaymentUtils.updateUserPersonalInfo(companyId, assemblyId, attributeCode, value, assemblyAuthToken);
        	RulesUtils.println("updated payments response ::"+response);
         } 
        
        RulesUtils.footer(drools.getRule().getName());
end