package life.genny.rules;

import life.genny.rules.RulesUtils;
import life.genny.rules.QRules;
import life.genny.qwanda.entity.BaseEntity;

import life.genny.qwanda.Answer;

import life.genny.qwandautils.PaymentUtils;
import life.genny.qwandautils.PaymentEndpoint;
import life.genny.qwandautils.QwandaUtils;
import life.genny.qwandautils.MergeUtil;
import life.genny.rules.RulesUtils;
import com.google.gson.Gson;

import java.time.LocalDateTime;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import java.time.format.DateTimeFormatter;
import life.genny.qwanda.DateTimeDeserializer;

import java.util.Map;


rule "New assembly user creation"
 no-loop true
 when
     rules: QRules(( isUserPresent() == true)  && isState("USER_CHECKED")) 
   then
     RulesUtils.header(drools.getRule().getName());
     System.out.println(QwandaUtils.executeRuleLogger("Payments User creation Rule"));
     
     Gson gson = new Gson();
     GsonBuilder gsonBuilder = new GsonBuilder();
     gsonBuilder.registerTypeAdapter(LocalDateTime.class, new DateTimeDeserializer());
     gson = gsonBuilder.create();
     
     String userName = rules.getAsString("preferred_username");
     String userCode =  QwandaUtils.getBaseEntityCodeForUserName(userName, rules.getToken());
     String tokenString = rules.getToken();
     String qwandaServiceUrl = rules.getQwandaServiceUrl();
     
     /* get assembly authKey   */
     String assemblyAuthToken = PaymentUtils.getAssemblyAuthKey();
     
     /*  Creates assembly userId */
     String assemblyId = PaymentUtils.getAssemblyId(tokenString);
     
     /* Check If user already exists in Assembly    */  
     Boolean isAssemblyUserExists = PaymentUtils.checkIfAssemblyUserExists(assemblyId, assemblyAuthToken);
     RulesUtils.println("isAssemblyUserExists::"+isAssemblyUserExists);
     RulesUtils.println("Assembly user::"+PaymentEndpoint.getAssemblyUserById(assemblyId, assemblyAuthToken));
     
     if(!isAssemblyUserExists) {
     	/* logic to create assembly user & set the payments userProfileExists flag  */
     	PaymentUtils.createAssemblyUser(assemblyId, assemblyAuthToken, tokenString); 
     	
     	Boolean isUserExists = PaymentUtils.checkIfAssemblyUserExists(assemblyId, assemblyAuthToken);
     	System.out.println("isAssemblyUserExists::"+isUserExists);
     	
     	if(isUserExists == true) {
     		rules.setState("IS_ASSEMBLY_USER_CREATED");
    		update(rules);
     	}
     	
     	/* Creates a new attribute for assembly user ID */
    	Answer assemblyIdAnswer = new Answer(userCode, userCode, "PRI_ASSEMBLY_USER_ID", assemblyId);
    	System.out.println("assemblyIdAnswer ::"+assemblyIdAnswer);
    	System.out.println("assembly ID created in our system ::"+assemblyId);
     	QwandaUtils.apiPostEntity(qwandaServiceUrl+"/qwanda/answers",gson.toJson(assemblyIdAnswer), tokenString);
     	
      }

	 /* If user already exists */
	 if(isAssemblyUserExists) {
		
		rules.setState("IS_ASSEMBLY_USER_CREATED");
    	update(rules);
     	
     	if(MergeUtil.getAttrValue(userCode, "PRI_ASSEMBLY_USER_ID", tokenString) == null) {
     		System.out.println("Assembly ID is null");
     		Answer assemblyIdAnswer = new Answer(userCode, userCode, "PRI_ASSEMBLY_USER_ID", assemblyId);
     		QwandaUtils.apiPostEntity(qwandaServiceUrl+"/qwanda/answers",gson.toJson(assemblyIdAnswer), tokenString);
     	}
	 } 
	
	RulesUtils.footer(drools.getRule().getName());
   
end     



