package life.genny.rules;

import life.genny.rules.RulesUtils;
import life.genny.rules.QRules;
import life.genny.qwanda.entity.BaseEntity;

import life.genny.qwanda.Answer;

import life.genny.qwandautils.PaymentUtils;
import life.genny.qwandautils.PaymentEndpoint;
import life.genny.qwandautils.QwandaUtils;
import life.genny.qwandautils.MergeUtil;
import life.genny.rules.RulesUtils;
import com.google.gson.Gson;

import java.time.LocalDateTime;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import java.time.format.DateTimeFormatter;
import life.genny.qwanda.DateTimeDeserializer;

import java.util.Map;

rule "New Payments User"
	no-loop true
    when
    	
       rules: QRules( isState("NEW_USER")) 
      then
     	RulesUtils.header(drools.getRule().getName());
     	
     Gson gson = new Gson();
     GsonBuilder gsonBuilder = new GsonBuilder();
     gsonBuilder.registerTypeAdapter(LocalDateTime.class, new DateTimeDeserializer());
     gson = gsonBuilder.create();	
     	
     String userName = rules.getAsString("preferred_username");
     String userCode =  QwandaUtils.getBaseEntityCodeForUserName(userName, rules.getToken());
     String tokenString = rules.getToken();
     String qwandaServiceUrl = rules.getQwandaServiceUrl();
     
     /* get assembly authKey   */
     String assemblyAuthToken = PaymentUtils.getAssemblyAuthKey();
     
     /*  Creates assembly userId */
     String assemblyId = PaymentUtils.getAssemblyId(tokenString);
     
      /* Check If user already exists in Assembly    */  
     Boolean isAssemblyUserExists = PaymentUtils.checkIfAssemblyUserExists(assemblyId);
     RulesUtils.println("isAssemblyUserExists::"+isAssemblyUserExists);
     
	 if(!isAssemblyUserExists) {
     	
     	/* logic to create assembly user & set the payments userProfileExists flag  */
     	PaymentUtils.createAssemblyUser(assemblyId, assemblyAuthToken, tokenString); 
     	
     	Boolean isUserExists = PaymentUtils.checkIfAssemblyUserExists(assemblyId);
     	System.out.println("isAssemblyUserExists::"+isUserExists);
     	
     	/* Creates a new attribute for assembly user ID */
    	Answer assemblyIdAnswer = new Answer(userCode, userCode, "PRI_ASSEMBLY_USER_ID", assemblyId);
    	System.out.println("assemblyIdAnswer ::"+assemblyIdAnswer);
    	System.out.println("assembly ID created in our system ::"+assemblyId);
     	QwandaUtils.apiPostEntity(qwandaServiceUrl+"/qwanda/answers",gson.toJson(assemblyIdAnswer), tokenString);
     	
     	if(isUserExists == true) {
     		rules.setState("IS_ASSEMBLY_USER_CREATED");
     	}
     	
      }
	
	  update(rules);	
	  RulesUtils.footer(drools.getRule().getName());       		      
end