package life.genny.rules;

import life.genny.rules.RulesUtils;
import life.genny.rules.QRules;
import life.genny.qwanda.entity.BaseEntity;

import life.genny.qwanda.Answer;

import life.genny.qwandautils.PaymentUtils;
import life.genny.rules.RulesUtils;


rule "New Payments User"
	agenda-group "payments"
	no-loop true
    when
    	rules: QRules( isState("IS_LOGGED_IN") && (!isState("IS_ASSEMBLY_USER_CREATED"))) 
    then
     
     RulesUtils.header(drools.getRule().getName());
     	     
     /* get assembly authKey   */
     String assemblyAuthToken = PaymentUtils.getAssemblyAuthKey();
     
     /*  Creates assembly userId */
     String assemblyId = PaymentUtils.getAssemblyId(rules.getToken());
     
      /* Check If user already exists in Assembly    */  
     Boolean isAssemblyUserExists = PaymentUtils.checkIfAssemblyUserExists(assemblyId);
     rules.println("isAssemblyUserExists::"+isAssemblyUserExists);
     
	 if(!isAssemblyUserExists) {
     			
     	/* logic to create assembly user & set the payments userProfileExists flag  */
     	PaymentUtils.createAssemblyUser(assemblyId, assemblyAuthToken, rules.getToken()); 
     	
     	/* Creates a new attribute for assembly user ID */
     	Answer assemblyIdAnswer = new Answer(rules.getUser().getCode(), rules.getUser().getCode(), "PRI_ASSEMBLY_USER_ID", assemblyId);
     	
     	PaymentUtils.saveAnswer(rules.getQwandaServiceUrl(), assemblyIdAnswer, rules.getToken());
    	
     	rules.println("assembly ID created in our system ::"+assemblyId);
     	RulesUtils.println("Assembly Company created");
     	
      }
      
      Boolean isCheckUserExists = PaymentUtils.checkIfAssemblyUserExists(assemblyId);
      rules.println("isAssemblyUserExists::"+isCheckUserExists);
     	
      if(isCheckUserExists == true) {  	
     	rules.setState("IS_ASSEMBLY_USER_CREATED");
      }
	

	  rules.footer();      		      
end