// package life.genny.rules;

// import life.genny.rules.QRules;
// import life.genny.qwanda.entity.BaseEntity;
// import java.util.List;

// /* Sends BEGs */
// rule "Send All Beg Attrs"
//     when
//         rules: QRules(  isState("SENT_DASHBOARD") && 
//                         isState("SEND_ALL_BEGS") && 
//                         isState("PUBLISHED_BASE_ENTITY_LIST") && 
//                         !isState("LOOP_SEND_DASHBOARD_BEGS") )
//      then
//      	rules.header();
//      	rules.setState("LOOP_SEND_DASHBOARD_BEGS");
        
//         /* Get BaseEntity list from map */
//         List<BaseEntity> baseEntityList = rules.getAsBaseEntitys("beList");
        
//         /*  baseEntityList has ::  
//             GRP_AVAILABLE
//             GRP_SHORTLISTED
//             GRP_INTERVIEWS
//             GRP_OFFERED
//             GRP_PLACED
//             GRP_IN_PROGRESS
//         */
        
//         List<BaseEntity> begs = null;
//         for(BaseEntity be: baseEntityList) {  /* each be is  GRP_AVAILABLE, GRP_SHORTLISTED ..... */
//             begs = rules.sendBaseEntityWithChildren(be, "LNK_CORE", 0, 500, false);

//             for(BaseEntity beg: begs) {
//                 rules.sendBaseEntityWithChildren(beg, "LNK_BEG", 0, 500, false);
//             }
//         }
         
//         rules.setState("SENT_DASHBOARD_BEGS");		
// 	    rules.footer();     		      
// end


       
