package life.genny.rules;

import life.genny.rules.QRules;
import java.util.List;
import java.util.stream.Collectors;
import life.genny.qwanda.entity.BaseEntity;
import life.genny.qwanda.attribute.EntityAttribute;

rule "Setting user role"
     when
        rules: QRules(  isState("STARTED") &&
                        isUserPresent() == true &&
						            !isState("LOOP_CHECK_ROLE") )
     then
        rules.header();

		rules.setState("LOOP_CHECK_ROLE");

    	  	rules.loadUserRole();
      	rules.setState("ROLE_CHECKED");
      	rules.footer();
end
