package life.genny.rules;

import life.genny.rules.QRules;
import java.util.List;
import java.util.stream.Collectors;
import life.genny.qwanda.entity.BaseEntity;
import life.genny.qwanda.attribute.EntityAttribute;

rule "Setting Admin user role"
     when
        rules: QRules(  isState("STARTED") &&
                        isState("ROLE_CHECKED") &&
						            !isState("LOOP_SET_ADMIN_ROLE") )
     then
        rules.header();

		rules.setState("LOOP_SET_ADMIN_ROLE");
    	  	rules.setAdminRoleIfAdmin();
    	  	
      	rules.footer();
end
