package life.genny.rules;

import life.genny.rules.QRules;
import life.genny.qwanda.message.QEventBtnClickMessage;

rule "Check user company - step 0 - SELLER"
	when
		 rules: QRules( 	isState("CHECK_USER_COMPANY") && isState("PRI_IS_SELLER") && !isState("CHECKED_COMPANY") )   
	 then
	    rules.header();
		
		rules.setState("CHECKED_COMPANY");
		
		/* a project attribute exists that tells us if a user can be a company or not */
		Boolean canUserBeACompany = rules.getProject().getValue("CAN_SELLER_HAVE_COMPANY", false);
		if(canUserBeACompany) {
			
			/* if the user is not a company yet */
			if(rules.isState("PRI_IS_COMPANY") == false) {
				rules.setState("ASK_USER_COMPANY"); /* we start the workflow */
			}
			else {
				
				/* if the user is a company we check if it has been set up correctly */
				rules.setState("CHECK_USER_COMPANY");
			}
		}
		else {
			rules.setState("COMPANY_EXISTS"); /* we skip the workflow */
		}
				
	    rules.footer();     		      
end
