package life.genny.rules;

import life.genny.rules.QRules;
import life.genny.qwanda.message.QEventBtnClickMessage;

rule "Check user company - Step 7"

	when
		 rules: QRules( isState("COMPANY_IS_READY") &&
						!isState("COMPANY_IS_READY_LOOP") )   
	 then
	    rules.header();
		
		rules.setState("COMPANY_IS_READY_LOOP");
		rules.setState("CHECK_MOBILE_VERIFICATION");
		
	    rules.footer();     		      
end
