package life.genny.rules;

import life.genny.rules.QRules;
import life.genny.qwanda.entity.BaseEntity;

rule "Create New User"
    when
        rules: QRules(  isState("NEW_REGISTRATION") && 
                        isState("TRIGGER_REGISTRATION") && 
                        !isState("NEW_USER_CREATED") )
    then
        rules.header();
        rules.println("Creating User  ");
        BaseEntity be = rules.createUser();
        be = rules.getUser();
        if(be){
          rules.setState("NEW_USER_CREATED");         
        }

        rules.saveAnswer( be.getCode(), 
                          be.getCode(), 
                          "PRI_IMAGE_URL", "https://s3.ap-southeast-2.amazonaws.com/channel40-images/jtaQozJT5HSpn3bX6P4EXSqQj3NDalkQ");

        rules.saveAnswer( be.getCode(), 
                          be.getCode(), 
                          "PRI_IS_PROFILE_COMPLETED", 
                          "FALSE");


        rules.clearState("NEW_REGISTRATION");
        rules.setState("NEW_USER_CREATED");
        rules.clearState("PROFILE_CHECK_COMPLETED");

        rules.footer();
end
