package com.sample;

import life.genny.qwanda.message.QEventMessage;
import life.genny.qwanda.message.QCmdMessage;
import life.genny.qwanda.message.QMSGMessage;
import life.genny.qwanda.message.QMessage.MessageData;
import io.vertx.rxjava.core.eventbus.EventBus;
import io.vertx.core.json.JsonObject;
import java.util.Map;

import life.genny.qwandautils.QwandaUtils;
import life.genny.qwanda.message.QCmdMessage;

global java.lang.String LOG_RESET;
global java.lang.String LOG_RED;
global java.lang.String LOG_GREEN;
global java.lang.String LOG_YELLOW;
global java.lang.String LOG_BLUE;
global java.lang.String LOG_PURPLE;
global java.lang.String LOG_CYAN;
global java.lang.String LOG_WHITE;
global java.lang.String LOG_BOLD;


rule "MsgCommTest-button"
	when
		$m : QEventMessage( event_type == "BTN_EVT_BUTTON" )
        bus: EventBus()
        $map : Map($value: this["token"] != null)
    then
    	System.out.println("Message layout submit event");
end