package life.genny.rules;

import life.genny.rules.RulesUtils;
import life.genny.rules.QRules;
import io.vertx.core.json.JsonObject;

rule "Send Message"

    when
	    $m : QEventMessage( event_type == "BTN_CLICK" && data.code == "BTN_SEND_MESSAGE" )
        rules: QRules( ) 
     then
     	
     	rules.header();
     		
	    String data = $m.getData().getValue();
		
  		if(data != null) {
  			
  			JsonObject dataJson = new JsonObject(data);
  		   
  		}
     	
     	rules.footer();
end
