package life.genny.rules;
import life.genny.rules.QRules;

/* TRIGGER Create HOST_COMPANY */
rule "Host Company Profile is not completed"
    when
    		rules: QRules(  isState("HOST_COMPANY_DOESNT_EXISTS") &&
						isState("PRI_IS_HOST_COMPANY") &&
						isState("PROFILE_NOT_COMPLETED") && 
						!isState("LOOP_HC_PROFILE_NOT_COMPLETED") ) 
     then 
 		rules.header();
		rules.setState("LOOP_HC_PROFILE_NOT_COMPLETED");
		rules.setState("TRIGGER_CREATE_HOST_COMPANY");
 		rules.footer();
end
