package life.genny.rules;

import life.genny.rules.QRules;
import life.genny.qwandautils.MergeUtil;

rule "Ask User Role - Intermatch"
    no-loop true
    when
        rules: QRules( isState("ASK_USER_ROLE") && !isState("ASKED_USER_ROLE") )
     then
     	rules.header();
     	rules.setState("ASKED_USER_ROLE");
     	
     	rules.set("sublayoutcode", "LAY_ROLE_SELECTION");
     	rules.set("sublayoutpath", "registration/role_selection.json");
     	
		rules.setState("SEND_SUBLAYOUT");
    	    rules.footer();
end
