package life.genny.rules;

import life.genny.rules.QRules;
import life.genny.qwandautils.MergeUtil;

rule "Ask User Role - Intermatch"
    when
        rules: QRules( isState("ASK_USER_ROLE") && !isState("ASKED_USER_ROLE"))
     then
     	rules.header();
     	rules.setState("ASK_USER_ROLE");
     	
		rules.sendSublayout("ROLE_SELECTION","registration/role_selection.json", null, false);

     	rules.setState("ASKED_USER_ROLE");
		
    	rules.footer();
end
