package life.genny.rules;

import life.genny.qwanda.message.QEventMessage;
import life.genny.rules.QRules;


rule "Selected Dashboard"
     when
       $m : QEventMessage( event_type == "TV_SELECT" && (data.code.contains("GRP_DASHBOARD") || data.code.contains("GRP_AVAILABLE")))
       rules: QRules( !isState("SELECTED_HOMEPAGE"))
     then

     rules.header();
       
     rules.setState("SELECTED_HOMEPAGE");
     rules.setState("TRIGGER_INTERNMATCH_HOMEPAGE");

     rules.footer();
end
