package life.genny.rules;

import life.genny.qwanda.message.QEventMessage;
import life.genny.rules.QRules;

rule "Selected Dashboard Item"
    when
      m : QEventMessage( event_type == "TV_SELECT" && 
                        !(data.value.contains("GRP_DASHBOARD") || data.value.contains("GRP_AVAILABLE")  )
                      )
      rules: QRules( !isState("SELECTED_HOMEPAGE"))
    then
      rules.header();

      rules.setState("SELECTED_HOMEPAGE");
			
      String[] recipient = { rules.getUser().getCode() };
      rules.publishBaseEntityByCode("GRP_INTERNS", "GRP_ROOT", "LNK_CORE", recipient);

      rules.setState("TRIGGER_INTERNMATCH_HOMEPAGE");
      rules.footer();
end
