package life.genny.rules;

import life.genny.rules.QRules;


rule "Report: Send All Users"
    no-loop true
    salience 570
    ruleflow-group 'ButtonClick'
    
    when
        m : QEventMessage( event_type == "BTN_CLICK"  && data.code == "BTN_SHOW_ADMIN_USERS" )
        rules: QRules( !isState("USER_LIST_SENT") )
     then
         rules.header();
         rules.setState("USER_LIST_SENT");
         rules.sendAllUsers("SBE_GET_ALL_USERS");

		 rules.footer();
	      		      
end
