package life.genny.rules;

import life.genny.rules.QRules;


rule "Report: Send All Loads"
    no-loop true
    salience 560
    ruleflow-group 'ButtonClick'
    
    when
        m : QEventMessage( event_type == "BTN_CLICK"  && data.code == "BTN_SHOW_ADMIN_JOBS" )
        rules: QRules( !isState("JOB_LIST_SENT") )
     then
         rules.header();
         rules.setState("JOB_LIST_SENT");
         rules.sendAllUsers("SBE_GET_ALL_LOADS");

		 rules.footer();
	      		      
end
