package life.genny.rules;

import life.genny.rules.QRules;


rule "Report: Send All Load Owners"
    no-loop true
    salience 540
    ruleflow-group 'ButtonClick'
    
    when
        m : QEventMessage( event_type == "BTN_CLICK"  && data.code == "BTN_SHOW_ADMIN_OWNERS" )
        rules: QRules( !isState("OWNERS_LIST_SENT") )
     then
         rules.header();
         
         rules.setState("OWNERS_LIST_SENT");
         rules.sendAllOwners("SBE_GET_ALL_OWNERS");
        
		 rules.footer();
	      		      
end
