package life.genny.rules;

import life.genny.rules.QRules;


rule "Report: Send All Drivers"
    no-loop true
    salience 550
    ruleflow-group 'ButtonClick'
    
    when
        m : QEventMessage( event_type == "BTN_CLICK"  && data.code == "BTN_SHOW_ADMIN_DRIVERS" )
        rules: QRules( !isState("DRIVERS_LIST_SENT") )
     then
         rules.header();
         rules.setState("DRIVERS_LIST_SENT");
         rules.sendAllDrivers("SBE_GET_ALL_DRIVERS");
		 rules.footer();
	      		      
end
