package life.genny.rules;

import life.genny.rules.QRules;
import life.genny.qwandautils.MergeUtil;

rule "Ask User Role"
    when
        rules: QRules( 	isState("ASK_USER_ROLE") &&
						!isState("ASKED_USER_ROLE")	)
     then
     	rules.header();
     	rules.setState("ASK_USER_ROLE");

		  rules.sendSublayout("ROLE_SELECTION", "registration/role_selection.json", null, false);

      /* TODO: to remove. test for the guys */
      rules.sendQuestions(rules.getUser().getCode(), rules.getUser().getCode(), "QUE_BUYER_GRP", false);
      rules.navigateTo("/homepage");

     	rules.setState("ASKED_USER_ROLE");

    	rules.footer();
end
