package life.genny.rules;
import life.genny.rules.QRules;
import life.genny.qwanda.message.QEventMessage;
import life.genny.qwanda.entity.BaseEntity;

rule "Create New Role - Step 2"
    when
        rules: QRules( 	isState("CREATE_NEW_ROLE")  &&
                        !isState("DID_CREATE_NEW_ROLE") )
     then

        rules.header();

        rules.setState("DID_CREATE_NEW_ROLE");
        	
        String roleCode = null;
        
        /* we grab the company linked to the user */
		BaseEntity company = rules.baseEntity.getParent(rules.getUser().getCode(), "LNK_STAFF");
		if(company != null) {
			roleCode = company.getCode();
		}
		else {
			roleCode = rules.getUser().getCode();
		}
		
		rules.println(roleCode);
		
        BaseEntity newRole = rules.baseEntity.create(roleCode, "ROL", "New Role");
        if(newRole != null) {
        		
        		rules.set("newRole", newRole);
        		rules.setState("SEND_QUESTION_DATA_FOR_ROLE");
        }
        
	    rules.footer();
end
