package life.genny.rules;
import life.genny.rules.QRules;
import life.genny.qwanda.message.QEventMessage;
import life.genny.qwanda.entity.BaseEntity;

rule "Create New Role - Step 2.5 - send data"
    when
        rules: QRules( 	isState("SEND_QUESTION_DATA_FOR_ROLE")  &&
                        !isState("DID_SEND_ROLE_QUESTION_DATA") )
     then

        rules.header();

        rules.setState("DID_SEND_ROLE_QUESTION_DATA");
        
        BaseEntity newRole = rules.getAsBaseEntity("newRole");
        
        if(newRole != null) {
        	
        		/* we grab GRP_CAPABILITIES which contains all the capabilities of the system */
    			List<BaseEntity> capabilities = rules.getAvailableCapabilities(rules.getUser());
    			if(capabilities != null) {
    				
    				/* we publish the filtered capabilities */
    				rules.publishCmd(capabilities, "GRP_CAPABILITIES", "LNK_CORE");
            		rules.setState("ASK_ROLE_CREATION_QUESTIONS");
    			}
        }
        
	    rules.footer();
end
