package life.genny.rules;
import life.genny.rules.QRules;
import life.genny.qwanda.message.QEventMessage;
import life.genny.qwanda.entity.BaseEntity;
import life.genny.qwanda.attribute.Attribute;

rule "Create New Role - Step 4 - Submit"
    when
        rules: QRules( 	isState("EVENT_FORM_SUBMIT")  &&
        					isState("QUE_ROLE_GRP") &&
        					isState("SUBMIT") &&
                        !isState("DID_SUBMIT_NEW_ROLE") )
     then

        rules.header();

        rules.setState("DID_SUBMIT_NEW_ROLE");
        
        /* we show a loading */
        rules.showLoading("", true);

        String targetCode = rules.getAsString("targetCode");
        if(targetCode != null) {

        		BaseEntity newRoleBe = rules.baseEntity.getBaseEntityByCode(targetCode);
        		if(newRoleBe != null) {

        			/* we grab the name of the new role */
        			String roleName = newRoleBe.getValue("PRI_NAME", null);

        			/* we grab the capabilities */
        			String capabilities = newRoleBe.getValue("LNK_SELECT_CAPABILITY", null);

        			/* we grab the current user's company */
        			BaseEntity company = rules.getUserCompany();

        			if(roleName != null && capabilities != null && company != null) {

        				/* we get an array of capabilities */
        				capabilities = capabilities.replaceAll("[\\[\\](){}]", "").replaceAll("\"", "");
        				String[] capabilitiesArray = capabilities.split(",");

        				/* we add the capabilities to the role */
        				rules.baseEntity.setupNewRole(newRoleBe, roleName, capabilitiesArray);

        				/* we add the role to the company */
        				rules.baseEntity.setRole(company, newRoleBe);
        				
        				/* we resend the company roles */
        				rules.setState("LOOP_SEND_PROJECT");
        				rules.setState("SEND_ROLES");
        			}
        		}
        }

        rules.setState("SHOW_COMPANY_ROLES");

	    rules.footer();
end
