package life.genny.rules;

import life.genny.rules.RulesUtils;
import life.genny.rules.QRules;

import life.genny.qwanda.Answer;
import life.genny.qwanda.message.QEventBtnClickMessage;

import life.genny.qwandautils.PaymentUtils;
import life.genny.qwandautils.MergeUtil;
import java.util.HashMap;


rule "Create Payment Item"
	agenda-group "payments"
	when
		m : QEventBtnClickMessage( event_type == "BTN_CLICK" && data.code == "BTN_CONFIRM_OFFER" )
		rules: QRules( !isState("CREATED_PAYMENT_ITEM") )
	then
		rules.header();

		rules.println("Item creation process started");

		String offerCode = m.getItemCode();
		String assemblyAuthKey = PaymentUtils.getAssemblyAuthKey();
       	String assemblyId = rules.getBaseEntityValueAsString(rules.getUser().getCode(), "PRI_ASSEMBLY_USER_ID");


		/*Getting BEG code from offerCode that has been confirmed */
		String BEGCode = PaymentUtils.getBegCode(offerCode, rules.getToken());
		RulesUtils.println("BEG CODE ::"+BEGCode);

      	if(assemblyId != null) {

       		RulesUtils.println("Refreshing tokens");

  			String oneTimeTransactionCardToken = null;
  			String oneTimeTransactionBankToken = null;
       		oneTimeTransactionCardToken = PaymentUtils.fetchOneTimeAssemblyToken(rules.getQwandaServiceUrl(), rules.getUser().getCode(), rules.getToken(), assemblyId, assemblyAuthKey, "card");
       		oneTimeTransactionBankToken = PaymentUtils.fetchOneTimeAssemblyToken(rules.getQwandaServiceUrl(), rules.getUser().getCode(), rules.getToken(), assemblyId, assemblyAuthKey, "bank");
						Answer cardTokenAnswer = new Answer(rules.getUser().getCode(), rules.getUser().getCode(), "PRI_ASSEMBLY_CARD_TOKEN", oneTimeTransactionCardToken);
						rules.publishData(cardTokenAnswer);

						Answer bankTokenAnswer = new Answer(rules.getUser().getCode(), rules.getUser().getCode(), "PRI_ASSEMBLY_BANK_TOKEN", oneTimeTransactionBankToken);
						rules.publishData(bankTokenAnswer);
						rules.println("***** ONE TIME TOKEN "+oneTimeTransactionCardToken);
						rules.println("***** ONE TIME TOKEN "+oneTimeTransactionBankToken);

       	}

       	/* Creating Payment Item */
       	String paymentItemId = MergeUtil.getAttrValue(BEGCode, "PRI_ITEM_ID", rules.getToken());
       	if(paymentItemId == null) {

       		String itemId = PaymentUtils.createPaymentItem(offerCode, BEGCode, assemblyAuthKey, rules.getToken());
       	 	rules.println("Payment item Id="+itemId);
       	 	
       	 	if(itemId != null) {
       	 		rules.println("Saving Answer");
				Answer itemIdAnswer = new Answer(BEGCode, BEGCode, "PRI_ITEM_ID", itemId);
	    			rules.saveAnswer(itemIdAnswer);
       	 	} 
       	 	else {
       	 		HashMap<String,String> contextMap = new HashMap<String, String>();
       	 		contextMap.put("JOB",BEGCode);
       	 		
       	 		String[] recipientArray = {rules.getUser().getCode()};
       	 		
       	 		rules.sendMessage("", recipientArray, contextMap,"MSG_CH40_ITEM_CREATION_FAILED", "TOAST");
       	 		
       	 		rules.sendSublayout("bucket-dashboard", "dashboard_channel40.json");
       	 	}
        		
       	}

		/* Ugly way of checking */
		String paymentIdAttributeValue = MergeUtil.getAttrValue(BEGCode, "PRI_ITEM_ID", rules.getToken());
		RulesUtils.println("payment ID attribute value ::"+paymentIdAttributeValue);

		if(paymentIdAttributeValue != null && assemblyId != null) {
			RulesUtils.println("BEG CODE ::"+BEGCode);
			RulesUtils.println("payment itemID and assemblyUserId is not null, hence the payment gateway layout is sent now!");
	        rules.askQuestions(rules.getUser().getCode(), BEGCode, "QUE_PAYMENT_METHOD_GRP");
		}
		rules.setState("CREATED_PAYMENT_ITEM");
		rules.footer();
end
