package life.genny.rules;

import life.genny.rules.RulesUtils;
import life.genny.rules.QRules;

import life.genny.qwanda.Answer;

/* Sorry Adam if you read this */
import io.vertx.core.json.JsonArray;
import io.vertx.core.json.JsonObject;
import life.genny.qwandautils.PaymentUtils;
import life.genny.qwandautils.MergeUtil;

rule "Create new payment method - user"

	when
		rules: QRules(  !isState("CREATED_PAYMENT_METHOD") )
		$m : QEventMessage( event_type == "PAYMENT_SUBMIT" && data.code == "USER_ADD_NEW_PAYMENT_METHOD" )

	then

		rules.header();

		String paymentMethodDataString = $m.getData().getValue();

		String assemblyAuthKey = PaymentUtils.getAssemblyAuthKey();
       	String assemblyId = MergeUtil.getAttrValue(rules.getUser().getCode(), "PRI_ASSEMBLY_USER_ID", rules.getToken());

       	/* Save tokens */
       	if(assemblyId != null) {

       		RulesUtils.println("Refreshing tokens");
       		PaymentUtils.saveTokenAnswers(rules.getQwandaServiceUrl(), rules.getUser().getCode(), rules.getToken(), assemblyId, assemblyAuthKey);
       	}

		rules.println("Payment method string1 ::"+paymentMethodDataString);
		if(paymentMethodDataString != null) {
			rules.println("Payment method string2 ::"+paymentMethodDataString);
			String userCode = rules.getUser().getCode();
			RulesUtils.println(paymentMethodDataString);
			String userCurrentPaymentMethods = MergeUtil.getAttrValue(userCode, "PRI_USER_PAYMENT_METHODS", rules.getToken());
			if(userCurrentPaymentMethods != null) {

				RulesUtils.println(userCurrentPaymentMethods);

				JsonObject newPaymentMethod = new JsonObject(paymentMethodDataString);
				JsonArray currentPaymentMethods = new JsonArray(userCurrentPaymentMethods);
				currentPaymentMethods.add(newPaymentMethod);
				String finalPaymentMethods = currentPaymentMethods.toString();

				Answer paymentAnswer = new Answer(userCode, userCode, "PRI_USER_PAYMENT_METHODS", finalPaymentMethods);

	            rules.saveAnswer(paymentAnswer);

			}
			else {
				rules.println("Payment method string ::"+paymentMethodDataString);
				RulesUtils.println("Payment method string ::"+paymentMethodDataString);
				Answer paymentAnswer = new Answer(userCode, userCode, "PRI_USER_PAYMENT_METHODS", "[" + paymentMethodDataString + "]");

	            rules.saveAnswer(paymentAnswer);


			}

			 PaymentUtils.disburseAccount(assemblyId, paymentMethodDataString, assemblyAuthKey);
		}


		rules.setState("CREATED_PAYMENT_METHOD");

		rules.footer();

end
