package life.genny.rules;

import life.genny.rules.RulesUtils;
import life.genny.rules.QRules;

import life.genny.qwanda.Answer;
import life.genny.qwanda.message.QEventBtnClickMessage;

import life.genny.qwandautils.PaymentUtils;
import life.genny.qwandautils.MergeUtil;


rule "Create Payment Item"
	agenda-group "payments"
	when 
		m : QEventBtnClickMessage( event_type == "BTN_CLICK" && data.code == "BTN_CONFIRM_OFFER") 
		rules: QRules()
	then
		rules.header();
		
		rules.println("Item creation process started"); 
		
		String offerCode = m.getItemCode();
		String assemblyAuthKey = PaymentUtils.getAssemblyAuthKey();
       	String assemblyId = rules.getBaseEntityValueAsString(rules.getUser().getCode(), "PRI_ASSEMBLY_USER_ID");
       	
       	/* Save tokens */
       	if(assemblyId != null) {
       		PaymentUtils.saveTokenAnswers(rules.getQwandaServiceUrl(), rules.getUser().getCode(), rules.getToken(), assemblyId, assemblyAuthKey);
       	}
			
		/*Getting BEG code from offerCode that has been confirmed */
		String BEGCode = PaymentUtils.getBegCode(offerCode, rules.getToken());
		RulesUtils.println("BEG CODE ::"+BEGCode);
       	
       	/* Creating Payment Item */
        String itemId = PaymentUtils.createPaymentItem(offerCode, BEGCode, assemblyAuthKey, rules.getToken());
        System.out.println("AssemblyId="+assemblyId);
		
		/* Save itemId as an attribute to BEG Group */
		if(itemId != null && assemblyId != null) {
			
			System.out.println("Saving Answer");
			Answer itemIdAnswer = new Answer(BEGCode, BEGCode, "PRI_ITEM_ID", itemId);        
	        rules.saveAnswer(itemIdAnswer);	    
	        rules.askQuestions(rules.getUser().getCode(), BEGCode, "QUE_PAYMENT_METHOD_GRP"); 
		}	
		
		rules.footer();			
end 
