package life.genny.rules;

import life.genny.rules.QRules;
import life.genny.qwandautils.PaymentUtils;
import life.genny.qwandautils.MergeUtil;


rule "Create Assembly Tokens"
	agenda-group "payments"
	no-loop true
	when 
		rules: QRules(isState("IS_ASSEMBLY_USER_CREATED") && !isState("IS_ASSEMBLY_TOKEN_CREATED") ) 
	then
		RulesUtils.header(drools.getRule().getName());
		
		String assemblyAuthKey = PaymentUtils.getAssemblyAuthKey();
       	String assemblyId = MergeUtil.getAttrValue(rules.getUser().getCode(), "PRI_ASSEMBLY_USER_ID", rules.getToken());

		
		if(assemblyId != null) {
		
			/* Saving Assembly authentication tokens as user attributes */
 			PaymentUtils.saveTokenAnswers(rules.getQwandaServiceUrl(), rules.getUser().getCode(), rules.getToken(), assemblyId, assemblyAuthKey); 
     	    
		}
		
		rules.setState("IS_ASSEMBLY_TOKEN_CREATED");		
		RulesUtils.footer(drools.getRule().getName());
    	
end
 