package life.genny.rules;

import life.genny.rules.RulesUtils;
import life.genny.rules.QRules;
import life.genny.qwandautils.MergeUtil;

rule "Check if Payments User Exists"
	agenda-group "payments"
	no-loop true
    when
    	rules: QRules( isState("IS_LOGGED_IN") && (!isState("IS_ASSEMBLY_USER_CREATED"))) 
    then
     
     RulesUtils.header(drools.getRule().getName());

     
    String assemblyUserId = MergeUtil.getAttrValue(rules.getUser().getCode(), "PRI_ASSEMBLY_USER_ID", rules.getToken());
     
     if(assemblyUserId != null) {
         rules.setState("IS_ASSEMBLY_USER_CREATED");   	
     }
    
	 if(assemblyUserId == null) {
     			
     	rules.setState("NEW_ASSEMBLY_USER_CREATION");
     	drools.setFocus("payments");
     	
      }	

	  rules.footer();      		      
end