package life.genny.rules;
import life.genny.rules.QRules;
import life.genny.qwanda.message.QEventAttributeValueChangeMessage;

import java.util.List;

rule "Profile Completed Attribute Change - {{REALM}}"
     when
        m : QEventAttributeValueChangeMessage( data.code == "PRI_IS_PROFILE_COMPLETED" )
        rules: QRules(  isState("STARTED") &&
                        !isState("LOOP_PROFILE_COMPLETED") )
     then
        rules.header();

        rules.setState("LOOP_PROFILE_COMPLETED");

        String isCompleted = m.getAnswer().getValue();
        if( isCompleted.equals("TRUE") ) {
  		    rules.setState("TRIGGER_PROFILE_CHECK");
        }

		rules.footer();
end
