package life.genny.rules;

import life.genny.rules.RulesUtils;
import life.genny.rules.QRules;
import life.genny.qwanda.message.QEventMessage;
import life.genny.qwanda.message.QCmdMessage;
import life.genny.qwanda.entity.EntityEntity;
import life.genny.qwanda.Answer;
import life.genny.qwandautils.QwandaUtils;
import life.genny.qwandautils.GPSUtils;
import life.genny.rules.RulesUtils;
import life.genny.qwanda.entity.User;
import life.genny.qwanda.Link;
import life.genny.qwanda.attribute.EntityAttribute;
import life.genny.qwanda.entity.BaseEntity;
import java.util.Map;
import java.util.HashMap; 
import life.genny.qwanda.Answer;
import io.vertx.core.json.JsonObject;

import java.time.format.DateTimeFormatter;
import life.genny.qwanda.DateTimeDeserializer;

rule "Owner rate driver and confirm delivery"
    when
      $m : QEventMessage( event_type == "FORM_SUBMIT" && data.code == "QUE_USER_RATING_GRP" )
      rules: QRules()   
    then

         rules.header();  
      	
      	RulesUtils.println($m.getData().getValue());
      	
      	String dataString = $m.data.getValue();
      	String userCode = rules.getUser().getCode();
        
      	/* we grab the job code */
      	String begCode = rules.getBaseEntityValueAsString(userCode, "STT_JOB_IS_RATING");

      	 if(begCode != null) {
      		
          	/*Release payment for driver */
          	 drools.setFocus("payments");

      		/* we mark the job as marked */
          	rules.moveBaseEntity(begCode, "GRP_COMPLETED", "GRP_PAID", "LNK_CORE");
          	
          	/* redirecting user to bucket */
          	rules.sendSublayout("bucket-dashboard", "dashboard_channel40.json");
      	}
      	  	
      	rules.footer();
end