package life.genny.rules;
import life.genny.rules.QRules;

rule "Trigger Chat Worflow - Step 0"
	when
		rules: QRules(  isState("START_CHAT") &&
						!isState("LOOP_START_CHAT")) 
	then
	 	rules.header();
		
		rules.setState("LOOP_START_CHAT");

		/* variables */
		BaseEntity conversation = null;
		
		/* chat code should be sent as an itemCode */
	   	String itemCode = rules.getAsString("itemCode");
		String currentUserCode = rules.getUser().getCode();
		   
		/* if we have a user code, we check whether or not a conversation between current user */
		/* and user code already exists. */
		if(itemCode.startsWith("PER_")) {
			rules.setState("DID_SELECT_USER");
		}
		/* if itemCode is a chatCode */
		else if(itemCode.startsWith("CHT")) {
			rules.setState("DID_SELECT_CHAT");
		}

	 	rules.footer();      
end
