package life.genny.rules;

import life.genny.rules.RulesUtils;
import life.genny.rules.QRules;



import life.genny.qwanda.message.QEventMessage;



rule "Send Chat Message"
	no-loop true

	salience 9999
	ruleflow-group 'Chat'
    when
	    m : QEventMessage( event_type == "BTN_CLICK" && data.code == "BTN_SEND_MESSAGE" )
        rules: QRules( isState("SEND_CHAT") && !isState("SENT_CHAT")) 
     then
     	
     	rules.header();
     		
	    String data = m.getData().getValue();
		
  		if(data != null) {
  			
  			rules.processChat(m);
  			rules.setState("SENT_CHAT");
  		}
     	
     	rules.footer();
end
