package life.genny.rules;
import life.genny.rules.QRules;
import java.util.HashMap;

rule "Send shortlist notification to Intern"
	when
		rules: QRules(  isState("INTERN_WAS_SHORTLISTED") )
	 then
	 	rules.header();

 		//this is to grab a parameter from the previous rule
 		String internCode = rules.getAsString("internCode");

  		BaseEntity internBe = rules.getBaseEntityByCode(internCode);
 		String internBaseEntityCode = internBe.getCode();


 		String eduCode = rules.getAsString("eduCode");
 		//String urlCode = rules.getAsString("urlCode");

 		if(internCode != null) {

	 		HashMap<String, String> contextMap = new HashMap<String, String>();
	        contextMap.put("INTERN", internCode);
	        contextMap.put("HOST_COMPANY", rules.getUser().getCode());
	        contextMap.put("Edu_provider", eduCode);


 			String[] recipients = new String[1];
 			recipients[0] = internCode;
 			rules.sendMessage(null, recipients, contextMap, "MSG_INTERNMATCH_SHORTLISTED_FOR_INTERNSHIP", "EMAIL");
 		}

	 	rules.footer();
end
