package life.genny.rules;

import life.genny.rules.QRules;
import life.genny.qwanda.entity.BaseEntity;
import java.util.List;
import java.util.ArrayList;


rule "Send Intermatch BucketData To Frontend"
    salience 670
    agenda-group "SendLayoutsAndData"
    when
        rules: QRules( !isState("SEND_BUCKET_DATA")  && isState("SUBLAYOUT_CHANGE_READY"))
     then
     	rules.header();

		 /* Show loading indicator */
		 rules.showLoading("Loading your interface...");

     	 BaseEntity user = rules.getUser();

     	 List<BaseEntity> root = rules.getBaseEntitysByParentAndLinkCode("GRP_ROOT","LNK_CORE", 0, 20, false) ;
    	 	 rules.publishCmd(root,"GRP_ROOT","LNK_CORE");
 		 rules.println(root);

 		 List<BaseEntity> admin = rules.getBaseEntitysByParentAndLinkCode("GRP_ADMIN","LNK_CORE", 0, 20, false) ;
    	 	 rules.publishCmd(admin,"GRP_ADMIN","LNK_CORE");

     	 List<BaseEntity> buckets = rules.getBaseEntitysByParentAndLinkCode("GRP_DASHBOARD","LNK_CORE", 0, 20, false) ;
     	 rules.publishCmd(buckets,"GRP_DASHBOARD","LNK_CORE");
  		 rules.println(buckets);

     	/* Send messages to user if they belong to the conversation. TODO: to optimize */

      	/* rules.publishBaseEntitysByParentAndLinkCodeWithAttributes("GRP_MESSAGES","LNK_CHAT", 0, 100, true); */

      	List<BaseEntity> conversations = rules.getBaseEntitysByParentAndLinkCode("GRP_MESSAGES", "LNK_CHAT", 0, 100, true);
      	List<BaseEntity> userConversations = new ArrayList<BaseEntity>();

      	if(conversations != null) {

      		for(BaseEntity convo: conversations) {

          		List<BaseEntity> users = rules.getBaseEntitysByParentAndLinkCode(convo.getCode(), "LNK_USER", 0, 100, true);
          		if(users != null) {

          			for(BaseEntity linkedUser: users) {

              			/* if user is a stackholder of this conversation  we send it */
              			if(linkedUser.getCode().equals(rules.getUser().getCode())) {
              				userConversations.add(convo);
              			}
              		}
          		}
          	}
      	}

  		rules.publishCmd(userConversations, "GRP_MESSAGES", "LNK_CHAT");
     	rules.setState("SEND_BUCKET_DATA");

	    rules.footer();
end
