package life.genny.rules;

import life.genny.rules.QRules;
import life.genny.qwanda.message.QEventMessage;
import life.genny.qwanda.message.QCmdMessage;
import life.genny.qwanda.entity.EntityEntity;
import life.genny.qwanda.Answer;
import life.genny.qwandautils.QwandaUtils;
import life.genny.qwandautils.GPSUtils;
import life.genny.qwandautils.JsonUtils;
import life.genny.rules.RulesUtils;
import life.genny.qwanda.entity.User;
import life.genny.qwanda.Link;
import life.genny.qwanda.entity.BaseEntity;
import java.util.Arrays;


import io.vertx.core.json.JsonObject;


/* Rule handling Cancel and Submit Button click in the Create Load  */
rule "Submit Job"
    when
      $m : QEventMessage( event_type == "FORM_SUBMIT" && data.code == "QUE_JOB_DETAILS_GRP" )
      rules: QRules( !isState("NEW_JOB_SAVED") )   
    then
         rules.header();  
         rules.setState("NEW_JOB_SAVED"); 
        /* rules.showLoading("Creating your new load..."); */
                
       /*  Get data.value and decode    */
        String dataString = $m.data.getValue();
        JsonObject dataJson = new JsonObject(dataString);
        String jobCode = dataJson.getString("targetCode");
        BaseEntity job = rules.getBaseEntityByCode(jobCode);
        String actionCode = dataJson.getString("action"); 
        rules.println("The job code is   :: "+jobCode);
        
       if(actionCode.equalsIgnoreCase("submit")) {       
           
   		rules.saveJob(job);
        
         /*  Calling the rule group : BucketView     */
           drools.setFocus("SendLayoutsAndData"); 
      }
      else if(actionCode.equalsIgnoreCase("cancel")){
      
       /*  String status =  rules.removeLink("GRP_DRAFTS", jobCode, "LNK_CORE");
        rules.println("Status after removing link  :: " +status);   */
       
       /*    Calling the rule group : BucketView     */
         drools.setFocus("SendLayoutsAndData");       
      }
             
     rules.footer(); 
        
end
