package life.genny.rules;
import life.genny.rules.QRules;

/* Create BEG BaseEntity */
rule "Add BEG - Step 2"
	when
		rules: QRules(	isState("SET_ATTRIBUTES_FOR_BEG") &&
						isState("CREATED_BASE_ENTITY") &&
						isState("BEG") &&
						!isState("LOOP_SET_ATTRIBUTES_FOR_BEG") ) 
	 then
	 	rules.header();
        rules.setState("LOOP_SET_ATTRIBUTES_FOR_BEG");

		BaseEntity beg = rules.getAsBaseEntity("baseEntity");	
		if(beg != null) {
			/* we add an attribute "PRI_AUTHOR" that contains the current user code */
			rules.baseEntity.updateBaseEntityAttribute(rules.getUser().getCode(), beg.getCode(), "PRI_AUTHOR", rules.getUser().getCode());
			/* we add an attribute "PRI_CODE" that contains the current user code */
			if(rules.getUserCompany() != null){
				rules.baseEntity.updateBaseEntityAttribute(rules.getUser().getCode(), beg.getCode(), "PRI_COMPANY_CODE", rules.getUserCompany().getCode());
			}
			rules.set("begBe", beg);
			rules.setState("CHECK_PRJ_HAS_PRODUCT_TEMPLATE");
		}
		else {
			rules.setState("FAILED_CREATE_BEG");
			rules.setState("FAILED_SET_AUTHOR");
		}

		rules.setState("LINK_GRP_DRAFTS_AND_BEG");

	 	rules.footer();      
end
