package life.genny.rules;
import life.genny.rules.QRules;

/* Check If Project requires Product Template */
rule "Add BEG - Step 3.0"
	when
		rules: QRules(  isState("CHECK_PRJ_HAS_PRODUCT_TEMPLATE") &&
						!isState("LOOP_CHECK_PRJ_HAS_PRODUCT_TEMPLATE") ) 
	 then
	 	rules.header();
        rules.setState("LOOP_CHECK_PRJ_HAS_PRODUCT_TEMPLATE");

		Boolean productTemplateRequired = rules.getProject().getValue("PRI_HAS_PRODUCT_TEMPLATE", false);
        if(productTemplateRequired){
            /* prj requires product template */
            rules.setState("CREATE_PRODUCT_BASEENTITY");
            rules.setState("PRODUCT_IS_REQUIRED");
        }
       
	 	rules.footer();      
end
