package life.genny.rules;
import life.genny.rules.QRules;

/* Create BEG BaseEntity */
rule "Add BEG - Step 3.1"
	when
		rules: QRules(	isState("CREATE_PRODUCT_BASEENTITY") &&
						!isState("LOOP_CREATE_PRODUCT_BASEENTITY") ) 
	 then
	 	rules.header();
        rules.setState("LOOP_CREATE_PRODUCT_BASEENTITY");

		rules.clearState("CREATED_BASE_ENTITY");	

		BaseEntity beg = rules.getAsBaseEntity("begBe");	
		if(beg != null) {
			
			/* we grab the product code */
			String productCode = rules.getProject().getValue("PRI_PRODUCT_CODE", "PRD");

			/* we create the PRODUCT base entity */
			rules.set("beCode", rules.getUser().getCode());
			rules.set("bePrefix", productCode);
			rules.set("beName", productCode);

			rules.setState("CREATE_BASE_ENTITY");
			rules.setState("LINK_BEG_AND_PRODUCT");	
		}
		else {
			
			rules.setState("FAILED_CREATE_BEG");
			rules.setState("FAILED_CREATE_PRODUCT");
		}


	 	rules.footer();      
end
