package life.genny.rules;
import life.genny.rules.QRules;

/* LINK BEG + PRODUCT  */
rule "Add BEG - Step 3.2"
	when
		rules: QRules(  isState("LINK_BEG_AND_PRODUCT") &&
						isState("CREATED_BASE_ENTITY") &&
						!isState("LOOP_LINK_BEG_AND_PRODUCT") ) 
	 then
	 	rules.header();
        rules.setState("LOOP_LINK_BEG_AND_PRODUCT");

		BaseEntity beg = rules.getAsBaseEntity("begBe");
		/* BaseEntity product = rules.getAsBaseEntity("productBe"); */
		BaseEntity product = rules.getAsBaseEntity("baseEntity");
		
		rules.println(beg.getCode());
		rules.println(product.getCode());

		if(beg != null && product != null) {
			
			/* link BEG to PRODUCT */
			rules.set("linkSourceCode", beg.getCode());
			rules.set("linkTargetCode", product.getCode());
			rules.set("linkCode", "LNK_BEG");
			rules.set("linkValue", "PRODUCT");
			rules.set("linkWeight", 1.0);

			rules.clearState("CREATED_LINK");
			rules.setState("CREATE_LINK");
			rules.setState("SEND_BEG_QUESTION");
		}
		else {
			
			rules.setState("FAILED_CREATE_BEG");
			rules.setState("FAILED_CREATE_LINK_PRODUCT");
		}
		
	 	rules.footer();      
end
