package life.genny.rules;
import life.genny.rules.QRules;

/* LINK GRP_DRAFTS + BEG  */
rule "Add BEG - Step 4"
	when
		rules: QRules(  isState("LINK_GRP_DRAFTS_AND_BEG") &&
						isState("CREATED_BASE_ENTITY") &&
						!isState("LOOP_LINK_GRP_DRAFTS_AND_BEG") ) 
	 then
	 	rules.header();
        rules.setState("LOOP_LINK_GRP_DRAFTS_AND_BEG");

		BaseEntity product = rules.getAsBaseEntity("baseEntity");	
		if(product != null) {
			
			rules.set("productBe", product);
			BaseEntity beg = rules.getAsBaseEntity("begBe");
			if(beg != null) {
				
				/* link GRP_DRAFTS to BEG */
				rules.set("linkSourceCode", "GRP_DRAFTS");
				rules.set("linkTargetCode", beg.getCode());
				rules.set("linkCode", "LNK_CORE");
				rules.set("linkValue", "BEG");
				rules.set("linkWeight", 1.0);
				rules.setState("CREATE_LINK");

				rules.setState("SEND_BEG_QUESTION");	
			}
			else {
				rules.setState("FAILED_CREATE_BEG");
				rules.setState("FAILED_CREATE_LINK");
			}
		}
		else {
			
			rules.setState("FAILED_CREATE_BEG");
			rules.setState("FAILED_CREATE_PRODUCT");
		}

	 	rules.footer();      
end
