package life.genny.rules;
import life.genny.rules.QRules;

/* Send Question Layout */
rule "Add BEG - Step 7"
	when
        rules: QRules(  isState("SEND_ADD_BEG_QUESTION_LAYOUT") &&
                        !isState("LOOP_SEND_ADD_BEG_QUESTION_LAYOUT")  )
     then
 		rules.header();
		rules.setState("LOOP_SEND_ADD_BEG_QUESTION_LAYOUT");

		rules.set("subLayoutCode", "ADD_BEG_LAYOUT");
		rules.set("subLayoutPath", "/beg/add_beg.json");
		rules.set("subLayoutRootCode", null);
		rules.set("subLayoutIsPopup", true);

		rules.setState("SEND_SUBLAYOUT");
 		rules.footer();
end
