package life.genny.rules;
import life.genny.rules.QRules;

rule "Trigger Message"

    when
         rules: QRules( isState("TRIGGER_SEND_MESSAGE") &&
         				!isState("LOOP_TRIGGER_SEND_MESSAGE") )
     then
     	rules.header();
        rules.setState("LOOP_TRIGGER_SEND_MESSAGE");
        
        rules.setState("SEND_SMS");
        rules.setState("SEND_EMAIL");
        rules.setState("SEND_TOAST");
    
	    rules.footer();      		      
end
