package life.genny.rules;
import life.genny.rules.QRules;

import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.ArrayList;

rule "Trigger Send SMS"
    when
         rules: QRules( isState("SEND_SMS") &&
         				!isState("LOOP_TRIGGER_SEND_MESSAGE") )
     then
     	rules.header();
        rules.setState("LOOP_TRIGGER_SEND_MESSAGE");
        
        HashMap<String, String> contextMap = rules.getAsHashMap("contextMap");
        String[] smsRecipient = rules.getAsArray("smsRecipient");
        String templateCode = rules.getAsString("templateCode");

        if( contextMap == null){
            rules.println("SEND SMS   ::   contextMap is null");
        }else if( smsRecipient == null){
            rules.println("SEND SMS   ::   smsRecipient is null");
        }else if( templateCode == null){
            rules.println("SEND SMS   ::   templateCode is null");
        }else{
            rules.sendMessage("", smsRecipient, contextMap, templateCode, "SMS");        
            rules.setState("SENT_SMS");
        }     
	    rules.footer();      		      
end

