package life.genny.rules;
import life.genny.rules.QRules;

import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.ArrayList;

rule "Trigger Send Email"
    when
         rules: QRules( isState("SEND_EMAIL") &&
         				!isState("LOOP_TRIGGER_SEND_EMAIL") )
     then
     	rules.header();
        rules.setState("LOOP_TRIGGER_SEND_EMAIL");
        
        HashMap<String, String> contextMap = rules.getAsHashMap("contextMap");
        String[] emailRecipient = rules.getAsArray("emailRecipient");
        String templateCode = rules.getAsString("templateCode");
        
        if( contextMap == null){
            rules.println("SEND EMAIL   ::   contextMap is null");
        }else if( contextMap == null){
            rules.println("SEND EMAIL   ::   emailRecipient is null");
        }else if( contextMap == null){
            rules.println("SEND EMAIL   ::   templateCode is null");
        }else{
    		rules.sendMessage("", emailRecipient, contextMap, templateCode, "EMAIL");        
            rules.setState("SENT_EMAIL");
        }   
	    rules.footer();      		      
end

