package life.genny.rules;


import life.genny.rules.QRules;



import life.genny.qwanda.Answer;
import life.genny.qwanda.message.QDataAnswerMessage;
import life.genny.qwanda.message.QEventAttributeValueChangeMessage;


rule "Listen Attribute Change"
ruleflow-group 'AttributeChange'
    when
        $m: QEventAttributeValueChangeMessage(  )
        rules : QRules()
     then    
      	rules.header();
 
       /* rules.publishData(new QDataAnswerMessage($m.getAnswer()));  */
     	rules.publishBE($m.getBe());
   	    rules.footer();
  
end