package life.genny.rules;


import life.genny.rules.QRules;



import life.genny.qwanda.Answer;
import life.genny.qwanda.message.QDataAnswerMessage;
import life.genny.qwanda.message.QEventAttributeValueChangeMessage;


rule "Listen Attribute Change"
ruleflow-group 'AttributeChange'
    when
        $m: QEventAttributeValueChangeMessage(  )
        rules : QRules( isState("STARTED")  && (!isState("ATTRIBUTE_CHANGE")))
     then    
      	rules.header();
 
       /* rules.publishData(new QDataAnswerMessage($m.getAnswer()));  */
        String[] recipientCodes = rules.getRecipientCodes($m);
     	rules.publishBE($m.getBe(),recipientCodes);
     	 rules.setState("ATTRIBUTE_CHANGE");
   	    rules.footer();
  
end