package life.genny.rules;


import life.genny.rules.QRules;



import life.genny.qwanda.Answer;
import life.genny.qwanda.message.QDataAnswerMessage;
import life.genny.qwanda.message.QEventAttributeValueChangeMessage;


rule "Listen Attribute Change"
ruleflow-group 'AttributeChange'
    when
        $m: QEventAttributeValueChangeMessage(   )
     rules : QRules( isState("STARTED")  && (!isState("ATTRIBUTE_CHANGE2")))
     then    
      	rules.header();
      	
 		rules.listenAttributeChange($m);
   	    rules.footer();
  
end