package life.genny.rules;


import life.genny.rules.QRules;
import life.genny.qwanda.Link;

import life.genny.qwandautils.QwandaUtils;

import life.genny.qwanda.Answer;
import life.genny.qwanda.message.QDataAnswerMessage;
import life.genny.qwanda.message.QEventSystemMessage;
import life.genny.qwanda.message.QEventLinkChangeMessage;


rule "Focus Rule Group"
no-loop true
    ruleflow-group 'SystemEvent'
    when
        $m: QEventSystemMessage( event_type == "EVT_SYSTEM"  && data.code == "FOCUS_RULE_GROUP")
        rules : QRules( !isState("FOCUS_RULE_GROUP") && (hasRole("dev") == true) )
     then    
      	rules.header();
 		/* user must be dev */
 		rules.setState("FOCUS_RULE_GROUP");
 		rules.println("Focus Rule");
		String ruleGroup = $m.getData().getValue();
		drools.setFocus(ruleGroup);
   	    rules.footer();
  
end