package life.genny.rules;


import life.genny.rules.QRules;
import life.genny.qwanda.Link;

import life.genny.qwandautils.QwandaUtils;

import life.genny.qwanda.Answer;
import life.genny.qwanda.message.QDataAnswerMessage;
import life.genny.qwanda.message.QEventLinkChangeMessage;


rule "Listen Link Change"
ruleflow-group 'LinkChange'
    when
        $m: QEventLinkChangeMessage( event_type == "EVT_LINK_CHANGE" && link != null )
        rules : QRules( isState("STARTED") && (!isState("LINK_CHANGE")) )
     then
      	rules.header();
 		rules.setState("LINK_CHANGE");

 		Link link = $m.getLink();
 		String[] recipientCodes = rules.getRecipientCodes($m);
		rules.println(Arrays.toString(recipientCodes));
 		rules.println("Link "+link);

 
		rules.publishData($m,recipientCodes);

   	    rules.footer();

end
