package life.genny.rules;


import life.genny.rules.QRules;
import life.genny.qwanda.Link;

import life.genny.qwandautils.QwandaUtils;

import life.genny.qwanda.Answer;
import life.genny.qwanda.message.QDataAnswerMessage;
import life.genny.qwanda.message.QEventSystemMessage;
import life.genny.qwanda.message.QEventLinkChangeMessage;


rule "System Event Listener"
    when
        $m: QEventSystemMessage( event_type == "EVT_SYSTEM" )
        rules : QRules()
     then    
      	rules.header();
      	System.out.println("🚚🚚🚚🚚🚚🚚🚚🚚🚚🚚🚚🚚🚚🚚🚚🚚🚚🚚🚚🚚🚚🚚🚚🚚🚚🚚🚚🚚🚚🚚🚚🚚🚚🚚🚚🚚🚚🚚🚚🚚🚚🚚🚚🚚🚚🚚🚚🚚🚚🚚🚚🚚");
 
 		rules.println("System Event:"+$m.getData().getCode());
 		
 		QwandaUtils.apiGetBasicAuth(System.getenv("JENKINS_URL")+"?WEB_URL="+System.getenv("WEB_URL"), System.getenv("JENKINS_USER"), System.getenv("JENKINS_PASS") );
   	    rules.footer();
  
end