package life.genny.rules;


import life.genny.rules.QRules;
import life.genny.qwanda.Link;

import life.genny.qwandautils.QwandaUtils;

import life.genny.qwanda.Answer;
import life.genny.qwanda.message.QDataAnswerMessage;
import life.genny.qwanda.message.QEventSystemMessage;
import life.genny.qwanda.message.QEventLinkChangeMessage;


rule "System Event Listener"
    when
        $m: QEventSystemMessage( event_type == "EVT_SYSTEM" )
        rules : QRules()
     then    
      	rules.header();
 
 		rules.println("System Event:"+$m.getData().getCode());
 		QwandaUtils.apiGet("https://jenkins.outcome-hub.com/generic-webhook-trigger/invoke?token="+System.getenv("JENKINS_CODE"),null);
 	   	generateNewItemsCache()
   	    rules.footer();
  
end