package life.genny.rules;

import life.genny.rules.QRules;

import life.genny.qwanda.message.QEventMessage;
import life.genny.qwanda.message.QCmdMessage;



rule "User Logout"
    when
        m : QEventMessage( event_type == "LOGOUT" && data.code == "LOGOUT" )
 		rules: QRules() 
    then
        rules.header();
        
        rules.publishCmd(new QCmdMessage("CMD_LOGOUT","LOGOUT"));
        
		rules.footer();      
end