package life.genny.rules;

import life.genny.rules.QRules;
import life.genny.qwanda.entity.BaseEntity;
import java.util.List;
import java.util.ArrayList;
import java.util.Optional;
import life.genny.utils.VertxUtils;

rule "Trigger channel40 homepage"
    when
        rules: QRules( isState("TRIGGER_HOMEPAGE") && !isState("LOOP_HOMEPAGE") )
     then
     	rules.header();

     	rules.setState("LOOP_HOMEPAGE");
		rules.setState("SEND_BUCKET_LAYOUT");

	    rules.footer();
end
