package life.genny.rules;

import life.genny.rules.QRules;
import life.genny.qwanda.entity.BaseEntity;
import java.util.List;
import java.util.ArrayList;
import java.util.Optional;
import life.genny.utils.VertxUtils;

rule "Send Ch40 BucketData To Frontend"
    when
        rules: QRules( isState("BUCKET_DATA_CHANNEL40") && !isState("SENT_BUCKET_DATA_CH40") )
     then
     	rules.header();

     	rules.setState("SENT_BUCKET_DATA_CH40");

		  rules.sendLayoutsAndData();

	    rules.footer();
end
