package life.genny.rules;
import life.genny.rules.QRules;
import life.genny.qwanda.message.QEventMessage;

rule "View Intern Profile"
    when
        m : QEventMessage(  event_type == "PROFILE" && 
                            data.code == "PROFILE")
                            
	    rules: QRules(  isState("ROLE_FOUND") &&
                        isState("PRI_IS_INTERN") &&	
                        !isState("LOOP_VIEW_INTERN_PROFILE")) 	
     then
        rules.header();    
        rules.setState("LOOP_VIEW_INTERN_PROFILE");

        rules.sendSelections("GRP_UNI_SELECTION", "LNK_CORE", 10);
     	rules.sendSelections("GRP_DEGREE_SELECTION", "LNK_CORE", 10);
     	rules.sendSelections("GRP_GENDERS", "LNK_CORE", 10);
     	rules.sendSelections("GRP_RESIDENTIAL_STATUS", "LNK_CORE", 10);

        rules.set("questionSourceCode", rules.getUser().getCode());
		rules.set("questionTargetCode", rules.getUser().getCode());
		rules.set("questionGroupCode", "QUE_INTERN_GRP");
		rules.set("questionIsPopup", false);

        rules.setState("ASK_QUESTION");
        rules.footer();     		      
end
