package life.genny.rules;

import life.genny.rules.QRules;

rule "Pre Init User Logout"
    when
  		m : QEventMessage( event_type == "LOGOUT" && data.code == "LOGOUT" )
        rules: QRules(isState("PRE_INIT_READY") && !isState("STARTED")) 
     then    
        rules.setDrools(drools);
        rules.header();
        rules.println("RULE INIT USER_LOGOUT: "+m);
 
        rules.setState("EVENT_USER_LOGOUT");
        rules.setState("STARTED");

        drools.setFocus("UserLogout");
        rules.footer();
end
