package life.genny.rules;

import org.apache.commons.lang3.StringUtils;

import life.genny.rules.QRules;


rule "Pre Init Answer"
    when
        m : QDataAnswerMessage( QDataAnswerMessage.getData_type().equals(Answer.class.getSimpleName()) )
        rules: QRules( isState("PRE_INIT_READY") && !isState("STARTED") && !isState("PREINIT_ANSWER_LOOP"))
     then
        rules.setDrools(drools);
        rules.header();
        rules.println("RULE INIT ANSWER: "+ m + " - " + m.getItems());

		rules.setState("PREINIT_ANSWER_LOOP");
		
		/* we grab the data associated to the answers */
		 Answer[] answers = m.getItems();
		 if(answers.length > 0) {
		 	
		 	/* TODO: update to handle multiple answers */
		 	Answer firstAnswer = answers[0];
		 	String sourceCode = firstAnswer.getSourceCode();
		 	String targetCode = firstAnswer.getTargetCode();
		 	String attributeCode = firstAnswer.getAttributeCode();
		 	String value = firstAnswer.getValue();
		 	
		 	if(sourceCode != null && targetCode != null && attributeCode != null && value != null ){
		 	    rules.set("sourceCode", sourceCode);
		 		rules.set("targetCode", targetCode);
		 	    rules.set("attributeCode", attributeCode);
		 	    rules.set("value", value);
		 	    
		 	    rules.setState(attributeCode);
		 	    rules.set(attributeCode, firstAnswer);
		 	}	 	
		 }
	
        rules.setState("STARTED");
        rules.setState("EVENT_ANSWER"); /* other rules listening for thos state */
        rules.setState("DATA_ANSWER");
        rules.setState("ANSWER");
        
        if (StringUtils.isBlank(m.getAliasCode())) {
            drools.setFocus("Answer");
        } 
        rules.processAnswers(answers);
        rules.footer();
end
