package life.genny.rules;
import life.genny.rules.QRules;

rule "Pre Init Search"
    when
      m : QEventMessage( event_type == "SEARCH" )
      rules: QRules(!isState("LOOP_PREINIT_SEARCH"))
     
    then
        rules.setDrools(drools);
        rules.header();
        rules.println("RULE INIT SEARCH: " + m);

        rules.setState("LOOP_PREINIT_SEARCH");

        String searchCode = m.getData().getCode();
        rules.setState(searchCode);

        String dataString = m.getData().getValue();
        
        try {
           
          JsonObject dataJson = new JsonObject(dataString);
          String searchValue = dataJson.getString("value");
          String attributeCode = dataJson.getString("attributeCode");

          if(searchValue != null) {
            rules.set("searchValue", searchValue);
            rules.setState(searchValue);
          }

          if(attributeCode != null) {
            rules.set("searchCode", attributeCode);
          }
        }
        catch(Exception e) {
            rules.println("Select event   ::   " +  m.getData());
        }
        
        rules.setState("EVENT_SEARCH");
        rules.footer();
 end