package life.genny.rules;

import life.genny.rules.QRules;

rule "Pre Init Menu Profile"
    when
          m : QEventMessage( event_type == "PROFILE" && 
                            data.code == "PROFILE" )
          rules: QRules(isState("PRE_INIT_READY") && !isState("STARTED")) 
     then    
        rules.setDrools(drools);
        rules.header();
        rules.println("RULE INIT MENU_PROFILE: "+m);
        rules.setState("STARTED");
 
        rules.setState("EVENT_MENU_PROFILE");
        rules.footer();
end
