package life.genny.rules;
import life.genny.rules.QRules;
import life.genny.qwanda.message.QEventMessage;

rule "Pre Init - Auth Init"
    when
        m : QEventMessage( data.code == "AUTH_INIT")
        rules: QRules(  isState("PRE_INIT_READY") && 
                        !isState("STARTED") &&
                        !isState("LOOP_AUTH_INIT_EVT") )
     then
        rules.setDrools(drools);
     	rules.header();
        rules.setState("LOOP_AUTH_INIT_EVT");
        rules.setState("STARTED");

        rules.setState("TRIGGER_AUTH_INIT");
        
	    rules.footer();
end
