package life.genny.rules;

import life.genny.rules.QRules;
import life.genny.qwanda.message.QEventMessage;
import io.vertx.core.json.JsonObject;

rule "Pre Init Redirect Event"
    when
		m : QEventMessage( event_type == "REDIRECT_EVENT" )
		rules: QRules(isState("PRE_INIT_READY") && !isState("STARTED")) 
     then   
        rules.setDrools(drools);
        rules.header();
        rules.setState("STARTED");

        rules.println("RULE INIT REDIRECT_EVT: "+m);
        rules.setState("REDIRECT_EVENT");

        String dataCode = m.getData().getCode();
        String valueCode = m.getData().getValue();
        rules.println("redirect datacode ::"+dataCode);
        rules.println("redirect valueCode :: "+valueCode);

		if(dataCode != null) {
 	 		rules.setState(dataCode);
		}
		if(valueCode != null) {
			rules.set("dataCode", dataCode);
			rules.set("valueCode", valueCode);
		}
		rules.footer();
end
