package life.genny.rules;

import life.genny.rules.QRules;
import life.genny.qwanda.message.QEventLinkChangeMessage;

rule "Pre Init Link Change"
    when
         m: QEventLinkChangeMessage( event_type == "EVT_LINK_CHANGE" )
          rules: QRules(isState("PRE_INIT_READY") && !isState("STARTED")) 
     then    
        rules.setDrools(drools);
        rules.header();
       rules.println("RULE INIT EVT_LINK_CHANGE: "+m);
        rules.setState("STARTED");
    
        rules.setState("EVENT_LINK_CHANGE");
		
        drools.setFocus("LinkChange");
        rules.footer();
end
