package life.genny.rules;

import life.genny.rules.QRules;


rule "Pre Init Focus Rule Group"
    when
          m : QEventMessage( event_type == "FOCUS_RULE_GROUP" )
          $rules: QRules(isState("PRE_INIT_READY") && !isState("FOCUS_RULE_GROUP") ) 
          eval( $rules.hasRole("dev") ) 
     then    
        $rules.setDrools(drools);
        $rules.header();
        $rules.println("RULE INIT FOCUS RULE GROUP: "+m);
 
        $rules.setState("FOCUS_RULE_GROUP");

		
       String ruleGroup = m.getData().getCode();
		drools.setFocus(ruleGroup);
		$rules.footer();
       		      
end