package life.genny.rules;
import life.genny.rules.QRules;

rule "Pre Init Select Event"
    when
      m : QEventMessage( event_type == "BTN_CLICK" && 
                        getData() != null && 
                        getData().getCode().equals("SELECT_EVENT") )
      rules: QRules(!isState("LOOP_PREINIT_SELECT_EVENT"))
     
    then
        rules.setDrools(drools);
        rules.header();
        rules.println("RULE INIT SELECT_EVENT: "+m);

        rules.setState("LOOP_PREINIT_SELECT_EVENT");

        
        String dataString = m.getData().getValue();
        
        try {
           
          JsonObject dataJson = new JsonObject(dataString);

          String itemCode = dataJson.getString("itemCode");
		      String hintCode = dataJson.getString("hint"); 

          if(itemCode != null || hintCode != null) {
            rules.set("itemCode", itemCode);
            rules.set("hintCode", hintCode);
            rules.setState(itemCode.substring(0, 3));

          }
          
        }
        catch( Exception e) {
            rules.println("Select event   ::   " +  m.getData());
        }
        
        rules.setState("EVENT_SELECT");
        rules.footer();
 end