package life.genny.rules;

import life.genny.rules.QRules;
import life.genny.qwanda.message.QEventCronMessage;
import io.vertx.core.json.JsonObject;

rule "Pre Init Cron Event"
    when
      m : QEventMessage( event_type == "CRON_EVENT")
  		rules: QRules(isState("PRE_INIT_READY") && !isState("STARTED"))
     then
        rules.setDrools(drools);
        rules.header();
        rules.println("RULE INIT CRON_EVT: "+m);
        rules.setState("STARTED");
        rules.setState("CRON_EVENT");

        String dataCode = m.getData().getCode();
    		if(dataCode != null) {
     	 		rules.setState(dataCode);
    		}
    		rules.footer();
end
