package life.genny.rules;
import life.genny.rules.QRules;

rule "Pre Init De-Select Event"
    when
      m : QEventMessage(  event_type == "BTN_CLICK" && 
                          getData() != null && 
                          getData().getCode().equals("DESELECT_EVENT") )
      rules: QRules(!isState("LOOP_PREINIT_DESELECT_EVENT"))
    
    then
      rules.setDrools(drools);
      rules.header();
      rules.println("RULE INIT DESELECT_EVENT: "+m);

      rules.setState("LOOP_PREINIT_DESELECT_EVENT");


      String dataString = m.getData().getValue();
      
      try {
            
        JsonObject dataJson = new JsonObject(dataString);

        String itemCode = dataJson.getString("itemCode");
        String hintCode = dataJson.getString("hint"); 

        if(itemCode != null || hintCode != null) {
          rules.set("itemCode", itemCode);
          rules.set("hintCode", hintCode);
          rules.setState(itemCode.substring(0, 3));

        }
        
      }
      catch( Exception e) {
          rules.println("Deselect event   ::   " +  m.getData());
      }

      rules.setState("EVENT_DESELECT");
      rules.footer();
  end