package life.genny.rules;
import life.genny.rules.QRules;
import life.genny.qwanda.message.QEventMessage;

rule "Pre Init EVT_TV_SELECT"
    when
        m : QEventMessage( event_type == "TV_SELECT")
        rules: QRules(isState("PRE_INIT_READY") && !isState("STARTED"))
     then
        rules.setDrools(drools);
        rules.header();
        rules.println("RULE INIT TV_SELECT: "+m);

        rules.setState("STARTED");

        rules.setState("EVENT_TV_SELECT");

        String tvSelectCode = m.getData().getCode();
        String tvSelectValue = m.getData().getValue();
        
        if(tvSelectCode != null){
          rules.set("tvSelectCode", tvSelectCode);
          rules.setState("PARENT_" +tvSelectCode);
        }

        if(tvSelectValue != null){
          rules.set("tvSelectValue", tvSelectValue);
          rules.setState(tvSelectValue);
        }

        drools.setFocus("TV_SELECT"); /* Set focus to group of rules handling TreeView item selections */
        rules.footer();
end
