package life.genny.rules;

import life.genny.rules.QRules;

rule "Pre Init Attribute Change"
    when
        m : QEventAttributeValueChangeMessage()
        rules: QRules(isState("PRE_INIT_READY") && !isState("STARTED") && !isState("LOOP_ATTRIBUTE_CHANGE")) 
     then    
        rules.setDrools(drools);
        rules.header();
        rules.println("RULE INIT ATTRIBUTE_CHANGE: "+m);

        rules.setState("LOOP_ATTRIBUTE_CHANGE");

        String sourceCode = m.getAnswer().getSourceCode();
        rules.println("sourceCode   ::   " + sourceCode);

        String targetCode = m.getAnswer().getTargetCode();
        rules.println("targetCode   ::   " + targetCode);

        String attributeCode = m.getAnswer().getAttributeCode();
        rules.println("attributeCode   ::   " + attributeCode);

        String value = m.getAnswer().getValue();
        rules.println("value   ::   " + value);

        if(sourceCode != null) {
            rules.set("sourceCode", sourceCode);
		}
        if(targetCode != null) {
            rules.set("targetCode", targetCode);
		}
		if(attributeCode != null) {
			rules.set("attributeCode", attributeCode);
			rules.setState(attributeCode);
		}
		if(value != null) {
			rules.set("value", value);
		}

        rules.setState("STARTED");
        rules.setState("EVT_ATTRIBUTE_VALUE_CHANGE");
        drools.setFocus("AttributeChange");
        rules.footer();
end