package life.genny.rules;

import life.genny.rules.QRules;


rule "Pre Init System Event"
    when
          m : QEventMessage( event_type == "EVT_SYSTEM" )
          rules: QRules(isState("PRE_INIT_READY") && !isState("STARTED")) 
     then    
        rules.setDrools(drools);
        rules.header();
        rules.println("RULE INIT SYSTEM_EVENT: "+m);
        rules.setState("STARTED");
 
        rules.setState("EVT_SYSTEM");
		
        	drools.setFocus("SystemEvent");
        	rules.footer();
       		      
end