package life.genny.rules;
import life.genny.rules.QRules;

rule "Pre Init De-Select Event"
    when
      m : QEventMessage(  event_type == "BTN_CLICK" && 
                          getData() != null && 
                          getData().getCode().equals("DESELECT_EVENT") )
      rules: QRules(!isState("STARTED"))
    
    then
      rules.setDrools(drools);
      rules.println("RULE INIT BTN_CLICK: "+m);

      String dataString = m.getData().getValue();
      
      try {
            
        JsonObject dataJson = new JsonObject(dataString);

        String itemCode = dataJson.getString("itemCode");
        String hintCode = dataJson.getString("hintCode"); 

        if(itemCode != null || hintCode != null) {
          rules.set("itemCode", itemCode);
          rules.set("hintCode", hintCode);
          rules.setState(itemCode.substring(0, 3));

        }
        
      }
      catch( Exception e) {
          rules.println("Deselect event   ::   " +  m.getData());
      }

      rules.setState("STARTED");
      rules.setState("EVENT_DESELECT");
  end