package life.genny.rules;

import life.genny.rules.QRules;

rule "Application is ready - channel40"
    when
        rules: QRules( isState("TRIGGER_APPLICATION") && isState("APPLICATION_READY") && 
                    !isState("LOOP_APPLICATION_READY_CHANNEL40") )
    then
        rules.header();
        
		rules.setState("LOOP_APPLICATION_READY_CHANNEL40");
		rules.setState("TRIGGER_HOMEPAGE");
		
        rules.footer();
end
