package life.genny.rules;
import life.genny.rules.QRules;

/* LINK BEG + INT || INTERNSHIP */
rule "Add Self Sourced Internship - Step 3"
	when
	    rules: QRules( 	isState("LINK_BEG_TO_SS_INT") && 
						isState("CREATED_BASE_ENTITY") &&
						isState("INT") &&
						isState("CREATED_INT") &&
						!isState("LOOP_ADD_SS_INTERNSHIP_STEP3") ) 
	 then
	 	rules.header();
        rules.setState("LOOP_ADD_SS_INTERNSHIP_STEP3");

		/* GET BEG BaseEntity from state map */
		BaseEntity beg = rules.getAsBaseEntity("begBe");	
		
		/* GET newly created INT BaseEntity */
		BaseEntity internship = rules.getAsBaseEntity("baseEntity");	
		
		/* SET INT BaseEntity to state */
		rules.set("internshipBe", internship);	

		/* link BEG to INT */
		rules.set("linkSourceCode", beg.getCode());
		rules.set("linkTargetCode", internship.getCode());
		rules.set("linkCode", "LNK_BEG");
		rules.set("linkValue", "INTERNSHIP");
		rules.set("linkWeight", 1.0);
		rules.setState("CREATE_LINK");

		rules.setState("LINKED_BEG_TO_SS_INT");
		rules.setState("LINK_DRAFTS_TO_SS_BEG");
	 	rules.footer();      
end
