package life.genny.rules;
import life.genny.rules.QRules;

/* Create Internship BaseEntity */
rule "Add Self Sourced Internship - Step 4"
	when
	    rules: QRules( 	isState("LINK_DRAFTS_TO_SS_BEG") && 
						isState("CREATED_LINK") &&
						isState("INTERNSHIP") &&
						isState("LINKED_BEG_TO_SS_INT") &&
						!isState("LOOP_ADD_SS_INTERNSHIP_STEP4")) 
	 then
	 	
	 	rules.header();
		rules.setState("LOOP_ADD_SS_INTERNSHIP_STEP4");
		rules.setState("CREATED_SS_HOST_COMPANY");
		rules.setState("TRIGGER_CREATE_HOST_COMPANY");
	    rules.footer();     		      
end