package life.genny.rules;
import life.genny.rules.QRules;

/* LINK GRP_DRAFTS + INT || INTERNSHIP */
rule "Add Self Sourced Internship - Step 6"
	when
	    rules: QRules( 	isState("LINKED_SS_HC_TO_BEG") && 
						isState("CREATED_LINK") &&
						!isState("LOOP_ADD_SS_INTERNSHIP_STEP6")) 
	 then
	 	rules.header();
        rules.setState("LOOP_ADD_SS_INTERNSHIP_STEP6");

		BaseEntity beg = rules.getAsBaseEntity("begBe");	

		/* link GRP_DRAFTS to BEG */
		rules.set("linkSourceCode", "GRP_DRAFTS");
		rules.set("linkTargetCode", beg.getCode());
		rules.set("linkCode", "LNK_CORE");
		rules.set("linkValue", "BEG");
		rules.set("linkWeight", 1.0);
		rules.setState("CREATE_LINK");

		rules.setState("LINKED_DRAFTS_TO_BEG");
		rules.setState("ASK_SELF_SOURCED_QUESTIONS");
	 	rules.footer();      
end
