package life.genny.rules;
import life.genny.rules.QRules;

/* Show Offer Document - Intern */
rule "Show Offer Document - Intern"
	when
		rules: QRules( 	isState("REDIRECT_EVENT") && 
						isState("REDIRECT_SHOW_OFFER") && 
						isState("PRI_IS_INTERN") && 
						isState("EXIT_HOME_PAGE") &&
						!isState("LOOP_SHOW_OFFER_DOCUMENT_INTERN") ) 
	 then
	 	rules.header();
        rules.setState("LOOP_SHOW_OFFER_DOCUMENT_INTERN");

		String begCode = rules.getAsString("valueCode");

        if(begCode != null){
		   	String questionSourceCode = rules.getUser().getCode();
			String questionTargetCode = begCode;
			String questionGroupCode = "QUE_INTERN_AGREEMENT_GRP";
			Boolean questionIsPopup = false;

			rules.set("questionSourceCode", questionSourceCode);
			rules.set("questionTargetCode", questionTargetCode);
			rules.set("questionGroupCode", questionGroupCode);
			rules.set("questionIsPopup", questionIsPopup);
			rules.setState("ASK_QUESTION");

			rules.setState("SHOWN_OFFER_DOCUMENT_INTERN");

        }else{
			rules.println("begCode is null");
		}
	 	rules.footer();      
end
