// package life.genny.rules;
// import life.genny.rules.QRules;

// /* Set BEG \ APP \ INTERN To Map */
// rule "Decline Intern - Step 0"
// 	when
// 		rules: QRules( 	isState("BTN_DECLINE_INTERN") && 
// 						isState("EVENT_BTN_CLICK") && 
// 						!isState("LOOP_DECLINE_INTERN_STEP0") ) 
// 	 then
// 	 	rules.header();
//         rules.setState("LOOP_DECLINE_INTERN_STEP0");

// 		String applicationCode = rules.getAsString("itemCode");
// 		String begCode = rules.getAsString("hintCode");

// 		if(applicationCode == null){
//             rules.println("applicationCode is null");
//         }else if(begCode == null){
//             rules.println("begCode is null");
//         }else{
// 			BaseEntity beg = rules.getBaseEntityByCode(begCode);
// 			rules.set("begBe", beg);
			
// 			BaseEntity application = rules.getBaseEntityByCode(applicationCode);
// 			rules.set("applicationBe", application);

// 			BaseEntity creator = rules.getChildren(beg.getCode(), "LNK_BEG", "CREATOR");
// 			BaseEntity hostCompany = rules.getChildren(beg.getCode(), "LNK_BEG", "HOSTCOMPANY");
// 			BaseEntity internship = rules.getChildren(beg.getCode(), "LNK_BEG", "INTERNSHIP");
// 			BaseEntity intern = rules.getChildren(application.getCode(), "LNK_APP", "APPLICANT");

// 			if (creator == null) {
//             	rules.println("Creator of oldBeg is null");
// 				return;
// 			} 
// 			if (hostCompany == null) {
//             	rules.println("Host Company of oldBeg is null");
// 				return;
// 			} 
// 			if (internship == null) {
//             	rules.println("Internship is null");
// 				return;
// 			} 
// 			if (intern == null) {
//             	rules.println("Intern is null");
// 				return;
// 			} 

//             rules.println("beg   ::   " + beg);
//             rules.println("application   ::   " + application);
//             rules.println("creator   ::   " + creator);
//             rules.println("hostCompany   ::   " + hostCompany);
//             rules.println("internship   ::   " + internship);
//             rules.println("intern   ::   " + intern);
			
// 			rules.set("creatorBe", creator);
// 			rules.set("companyBe", hostCompany);
// 			rules.set("internshipBe", internship);
// 			rules.set("internBe", intern );
			
// 			rules.setState("DECLINE_INTERN_READY");            
// 			rules.setState("MOVE_BEG_TO_DECLINE");
//         }
// 	 	rules.footer();      
// end
