// package life.genny.rules;
// import life.genny.rules.QRules;

// /* Move BEG from GRP_SHORTLISTED >>> GRP_DECLINE  */
// rule "Decline Intern - Step 1"
// 	when
// 		rules: QRules( 	isState("MOVE_BEG_TO_DECLINE") && 
// 						isState("DECLINE_INTERN_READY") && 
// 						isState("BTN_DECLINE_INTERN") && 
// 						isState("EVENT_BTN_CLICK") && 
// 						!isState("LOOP_DECLINE_INTERN_STEP1")) 
// 	 then
// 	 	rules.header();
//         rules.setState("LOOP_DECLINE_INTERN_STEP1");

// 		BaseEntity beg = rules.getAsBaseEntity("begBe");
//         if(beg != null){
//         	rules.moveBaseEntity(beg.getCode(), "GRP_PLACED", "GRP_DECLINE", "LNK_CORE");
//         	rules.setState("MOVED_BEG_TO_DECLINE");

// 		}else{
// 			rules.println("beg is null");
// 		}
// 	 	rules.footer();      
// end
