package life.genny.rules;
import life.genny.rules.QRules;

/* Intern Accepts Offer */
rule "Accept Offer - Intern"
	when
		rules: QRules( 	isState("BTN_ACCEPT_OFFER") && 
						isState("EVENT_BTN_CLICK") && 
						isState("PRI_IS_INTERN") && 
						isState("QUE_INTERN_AGREEMENT_GRP") && 
						isState("SUBMIT") && 
						!isState("LOOP_INTERN_ACCEPT_OFFER") ) 
	 then
	 	rules.header();
        rules.setState("LOOP_INTERN_ACCEPT_OFFER");
		
		String begCode = rules.getAsString("quesTargetCode");

        if(begCode != null){
		    rules.updateBaseEntityAttribute(rules.getUser().getCode(), begCode, "PRI_INTERN_ACCEPTED", "TRUE");
            rules.setState("INTERN_ACCEPTED_OFFER");

            rules.setState("CHECK_OFFER_ACCEPTED");
        }
	 	rules.footer();      
end
