package life.genny.rules;
import life.genny.rules.QRules;

/* Intern Accepts Offer */
rule "Accept Offer - Intern"
	when
		rules: QRules( 	isState("EVENT_FORM_SUBMIT") && 
						isState("QUE_INTERN_AGREEMENT_GRP") && 
						isState("SUBMIT") && 
						isState("PRI_IS_INTERN") && 
						!isState("LOOP_INTERN_ACCEPT_OFFER") ) 
	 then
	 	rules.header();
        rules.setState("LOOP_INTERN_ACCEPT_OFFER");
		
		String begCode = rules.getAsString("quesTargetCode");

        if(begCode != null){
		    rules.println("begCode    ::   " + begCode);
			rules.saveAnswer( new Answer(rules.getUser().getCode(), begCode, "PRI_INTERN_ACCEPTED", "TRUE") );

            rules.setState("INTERN_ACCEPTED_OFFER");
         	rules.setState("TRIGGER_INTERNMATCH_HOMEPAGE");
			
        }else{
			rules.println("begCode is null");
		}
	 	rules.footer();      
end
