package life.genny.rules;
import life.genny.rules.QRules;

/* Save begCode as an attribute of APPLICATION BE */
rule "Apply for BEG - Step 2"
	when
	    rules: QRules(  isState("SAVE_BEG_CODE_AS_ATTRIBUTE") && 
	                    isState("CREATED_BASE_ENTITY") && 
	                    isState("APP") && 
						!isState("LOOP_APPLY_BEG_STEP2")) 
	 then
	 	rules.header();
        rules.setState("LOOP_APPLY_BEG_STEP2");

        /* GET BEG || APPLICATION BE from state */
		BaseEntity application = rules.getAsBaseEntity("baseEntity");
		BaseEntity beg = rules.getAsBaseEntity("begBe");
        
        if(application == null){
            rules.println("application is null");
		}else if(beg == null){
            rules.println("beg is null");			
		}else{
			rules.saveAnswer(   new Answer(	rules.getUser().getCode(), 
											application.getCode(), 
											"PRI_BEG_CODE", 
											beg.getCode()
										)
							);

		    rules.setState("SEND_APPLY_BEG_QUESTIONS");
		}
	 	rules.footer();      
end


        
        
