package life.genny.rules;
import life.genny.rules.QRules;
import java.util.List;

/* Save additional attributes for APPLICATION */
rule "Apply for BEG - Step 2"
	when
	    rules: QRules(  isState("SAVE_BEG_CODE_AS_ATTRIBUTE") && 
	                    isState("CREATED_BASE_ENTITY") && 
	                    isState("APP") && 
						!isState("LOOP_APPLY_BEG_STEP2") ) 
	 then
	 	rules.header();
        rules.setState("LOOP_APPLY_BEG_STEP2");

        /* GET BEG || APPLICATION BE from state */
		BaseEntity application = rules.getAsBaseEntity("baseEntity");
		BaseEntity beg = rules.getAsBaseEntity("begBe");
        
        if(application == null){
            rules.println("application is null");

		}else if(beg == null){
            rules.println("beg is null");

		}else{
			
			String applicantName = rules.getFullName(rules.getUser());
			if(applicantName == null){
				rules.println("applicantName is null");
				return;
			}
			
			List<Answer> answers = new ArrayList<Answer>();

			answers.add( new Answer( rules.getUser().getCode(), application.getCode(), "PRI_BEG_CODE", beg.getCode() ) );
			answers.add( new Answer( rules.getUser().getCode(), application.getCode(), "PRI_APPLICATION_CODE", application.getCode() ) );
			answers.add( new Answer( rules.getUser().getCode(), application.getCode(), "PRI_APPLICANT_CODE", rules.getUser().getCode() ) );
			answers.add( new Answer( rules.getUser().getCode(), application.getCode(), "PRI_APPLICANT_USERNAME", rules.getUser().getName() ) );
			answers.add( new Answer( rules.getUser().getCode(), application.getCode(), "PRI_APPLICANT_FULLNAME", applicantName ) );
			rules.saveAnswers(answers);

		    rules.setState("SEND_APPLY_BEG_QUESTIONS");
		}
	 	rules.footer();      
end


        
        
