package life.genny.rules;

import life.genny.rules.QRules;
import life.genny.qwanda.entity.BaseEntity;

rule "User Logs In"
    when
         rules: QRules( isState("AUTH_INIT") && 
                        !isState("LOOP_USER_LOGGED_IN") )
     then
     	rules.header();

        rules.setState("LOOP_USER_LOGGED_IN");

        /* we send application data */
        rules.setState("SEND_INTERNMATCH_DATA");

	    rules.footer();
end
