package life.genny.rules;

import life.genny.rules.QRules;
import life.genny.qwanda.entity.BaseEntity;

rule "Send Internmatch Layout"
    when
         rules: QRules( isState("EXIT_SEND_DATA") && (!isState("LOOP_SENT_LAYOUTS")) )
     then
     	rules.header();

        rules.setState("LOOP_SENT_LAYOUTS");

        /* we send application layout */
        rules.setState("TRIGGER_SEND_LAYOUTS");

	    rules.footer();      		      
end
