package life.genny.rules;

import life.genny.rules.QRules;
import life.genny.qwanda.entity.BaseEntity;

rule "User Role was NOT found"
    when
         rules: QRules( isState("EXIT_SEND_LAYOUTS") && isState("ROLE_NOT_FOUND") && !isState("USER_ROLE_WAS_NOT_FOUND") )
     then
     	rules.header();

        rules.setState("USER_ROLE_WAS_NOT_FOUND");
        rules.clearState("DID_TRIGGER_ROLE_CHECK");
        rules.setState("TRIGGER_ROLE_CHECK");

	    rules.footer();      		      
end
