package com.sample;
 
import life.genny.qwanda.message.QEventMessage;
import life.genny.qwanda.message.QCmdMessage;
import life.genny.qwanda.message.QDataAskMessage;
import life.genny.qwanda.message.QDataAnswerMessage;

import life.genny.qwanda.Answer;
import life.genny.qwandautils.QwandaUtils;
import life.genny.qwanda.Ask;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonParseException;
import com.google.gson.JsonPrimitive;
import com.google.gson.JsonSerializationContext;
import io.vertx.core.json.JsonObject;
import life.genny.rules.QRules;

rule "Send Facebook Friend List"
    when
        $m : QEventMessage( event_type == "SEND_FB_FRIENDS")
        rules: QRules()
    then
        rules.header();
        String userCode= rules.getUser().getCode();            
        rules.publishBaseEntityByCode(userCode);

        /* Getting all Facebook Friends and their attributes */
        String result = QwandaUtils.apiGet(rules.getQwandaServiceUrl() +"/qwanda/baseentitys/"+userCode+"/linkcodes/LNK_FRIEND/attributes", rules.getToken());
        if(result != null){
            JsonObject friendList = new JsonObject(result);
            System.out.println("------------------------------------------------------------------------\n");
            System.out.println("FACEBOOK FRIEND LIST   ::   "+friendList.toString());  
            System.out.println("------------------------------------------------------------------------");
            friendList.put("token", rules.getToken());
            rules.publish("cmds", friendList);
        }
        rules.footer();
end

