package life.genny.rules;
import life.genny.rules.QRules;

/* Create Application BaseEntity */
rule "Check If Already Applied - Step 1"
	when
	    rules: QRules(  isState("BTN_APPLY_INTERNSHIP") && 
						isState("EVENT_BTN_CLICK") && 
						!isState("LOOP_CHECK_IF_USER_HAS_APPLIED_STEP0")) 
	 then
	 	rules.header();
        rules.setState("LOOP_CHECK_IF_USER_HAS_APPLIED_STEP0");
        
        String begCode = rules.getAsString("itemCode");
        if(begCode != null){
            BaseEntity beg = rules.getBaseEntityByCode(begCode);
            rules.set("begBe", beg);
            rules.setState("CHECK_IF_USER_HAS_APPLIED");
        }else{
            rules.println("begCode is null");
        }
	 	rules.footer();      
end