package life.genny.rules;
import life.genny.rules.QRules;

/* Create Application BaseEntity */
rule "Send User Has Already Applied Layout"
	when
	    rules: QRules(  isState("USER_HAS_APPLIED") && 
						!isState("LOOP_USER_HAS_APPLIED")) 
	 then
	 	rules.header();
        rules.setState("LOOP_USER_HAS_APPLIED");
        
        rules.set("subLayoutCode", "USER_HAS_APPLIED");
        rules.set("subLayoutPath", "internships/applied.json");
        rules.set("subLayoutRootCode", "APPLIED");
        rules.set("subLayoutIsPopup", true);

        rules.setState("SEND_SUBLAYOUT");
        rules.setState("SENT_USER_HAS_APPLIED_LAYOUT");

	 	rules.footer();      
end


        
        
