package life.genny.rules;

import life.genny.rules.QRules;
import life.genny.qwanda.message.QEventMessage;

rule "Host Company Registration Form Submit"
	when
	    rules: QRules( 	isState("QUE_NEW_USER_COMPANY_GRP") && 
						!isState("LOOP_HOST_COMPANY_REGISTRATION_FORM")) 
	 then
	 	rules.header();
        rules.setState("LOOP_HOST_COMPANY_REGISTRATION_FORM");

		String sourceCode = rules.getUser().getCode();
		String targetCode = rules.getUser().getCode();
		String attributeCode = "PRI_IS_PROFILE_COMPLETED";
		String value = "TRUE";

		/* rules.set("sourceCode", sourceCode);
		rules.set("targetCode", targetCode);
		rules.set("attributeCode", attributeCode);
		rules.set("value", value);
        rules.setState("UPDATE_BASEENTITY_ATTRIBUTE"); */

		rules.updateBaseEntityAttribute(sourceCode, targetCode, attributeCode, value);

	 	rules.footer();      
end
