package life.genny.rules;

import life.genny.rules.QRules;
import java.util.List;

rule "Profile Completed"
     when
        $m: QEventAttributeValueChangeMessage( QEventAttributeValueChangeMessage.getData().getCode().equals("PRI_IS_PROFILE_COMPLETED") )
        rules: QRules( isState("STARTED") && !isState("HAS_CHECK_PROFILE_COMPLETEION") ) 
     then      
        rules.header();
        
		rules.setState("HAS_CHECK_PROFILE_COMPLETEION");
		rules.setState("TRIGGER_PROFILE_CHECK");
		
		rules.footer();     		      
end
     	