package life.genny.rules;

import life.genny.rules.RulesUtils;
import life.genny.rules.QRules;

import life.genny.qwanda.message.QEventMessage;
import life.genny.qwanda.entity.BaseEntity;


rule "User-Profile"
    when
       m : QEventMessage( event_type == "PROFILE" && data.code == "PROFILE"  )
       rules: QRules( isState("STARTED") )
    then
        rules.header();
        BaseEntity user = rules.getUser();
  	    String userCode = user.getCode();

  	    drools.setFocus("ispayments");  /* NOW Set up Payments */


        rules.sendQuestions(userCode,userCode,"QUE_USER_PROFILE_GRP", false);
       /*  Get Company Code of the current user   */
        BaseEntity company = rules.getParent(userCode, "LNK_STAFF");
        if(company != null)
        {
            rules.println("Company BE is  :: "+company.toString());
            String companyCode = company.getCode();
            rules.println("The Company Code is :: "+companyCode);
           /*    Send Company asks   */
            rules.sendQuestions(userCode, companyCode, "QUE_USER_COMPANY_GRP", false);

        }

        /*  Send Bank Details asks   */
          rules.sendQuestions(userCode, userCode, "QUE_PAYMENT_METHOD_GRP", false);

        if( user.is("PRI_IS_SELLER")  || user.getValue("PRI_IS_SELLER", "FALSE").equals("TRUE")){
          /*  Send User Documents asks   */
           rules.sendQuestions(userCode, userCode, "QUE_USER_DOCUMENTS_GRP", false);

	      /* Send Driver SubLayout  */
		   rules.sendSublayout("SUB_USER_PROFILE", "user-profile-driver.json");
	    }
	   else{
	      /* Send Owner SubLayout  */
		   rules.sendSublayout("SUB_USER_PROFILE", "user-profile-owner.json");
	    }



       rules.footer();
end
