package life.genny.rules;

import life.genny.rules.QRules;
import life.genny.qwanda.message.QEventMessage;
import io.vertx.core.json.JsonObject;

rule "User-Company Info Submit"
    when
        rules: QRules( isState("EVENT_FORM_SUBMIT") && isState("QUE_USER_COMPANY_GRP") && !isState("COMPANY_INFO_UPDATED") )
    then
       rules.header();
    	    /*  Get data.value and decode   */
         /*String dataString = $m.data.getValue();
         JsonObject dataJson = new JsonObject(dataString);
         String userCode = rules.getUser().getCode();
         String companyCode = dataJson.getString("targetCode");
         String actionCode = dataJson.getString("action"); */

           rules.setState("COMPANY_INFO_UPDATED");

           //rules.setState("TRIGGER_HOMEPAGE");
           rules.redirectToHomePage();

        rules.footer();
  end
