package life.genny.rules;
import life.genny.rules.QRules;

/* Sends TreeView / Buckets / BEGs */
rule "Trigger Send Channel40 Application Data"

    when    
         rules: QRules( isState("TRIGGER_SEND_CHANNEL40_APPLICATION_DATA") && 
                        !isState("LOOP_TRIGGER_SEND_APPLICATION_DATA") )
     then
     	rules.header();
        rules.setState("LOOP_TRIGGER_SEND_APPLICATION_DATA");
    
        rules.setState("SEND_APPLICATION_DATA");
	    rules.footer();      		      
end
