package life.genny.rules;
import life.genny.rules.QRules;

/* Sends Grp / BEGS / BEG kids */
rule "Send Application Data - Channel40" 
    when    
         rules : QRules( isState("SEND_APPLICATION_DATA") && 
                        (isState("PROFILE_IS_COMPLETED") || isState("PRI_IS_PROFILE_COMPLETED")) && 
                        !isState("LOOP_SEND_APPLICATION_DATA_CHANNEL40") )
     then
     	rules.header();
       
		rules.setState("LOOP_SEND_APPLICATION_DATA_CHANNEL40");
        rules.sendLayoutsAndData();
        rules.setState("SENT_APPLICATION_DATA");
        
	    rules.footer();      		      
end