package life.genny.rules;
import life.genny.rules.QRules;

/* Sends Grp / BEGS / BEG kids */
rule "Send Application Data - HOST COMPANY" 
    when    
         rules: QRules( isState("SEND_APPLICATION_DATA") && 
                        isState("PRI_IS_HOST_COMPANY") && 
                        (isState("PROFILE_IS_COMPLETED") || isState("PRI_IS_PROFILE_COMPLETED")) && 
                        !isState("LOOP_SEND_APPLICATION_DATA_HOST_COMPANY") )
     then
     	rules.header();
        rules.setState("LOOP_SEND_APPLICATION_DATA_HOST_COMPANY");
        rules.sendHostCompanyApplicationData();

        rules.setState("SENT_APPLICATION_DATA");
	    rules.footer();      		      
end
